### ISSUE TITLE
'testing' broken?

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1008]
As reported by _Billtoo_ and _Sailor Enceladus_ there seems to be some problem at the `testing chroot` stage which may or may not be slacko specific. (http://www.murga-linux.com/puppy/viewtopic.php?p=954181#954181)

I don't know, I'm working out of `rationalise` branch and it's all pretty stable so far.. (with a heap more commits to add over the coming weekend - with my _very_ limited time).

It may also be 'user' failure to rebuild all ( or needed updated ) packages.

Anyway, I'm posting it as an issue because both had success from `rationalise` branch.

(not tagging @wdlkmpx  and @gyrog [ as you guys and @rserwin1 are the only other recent committers] as assignee's as it may well be my fault - but I am assigning this issue the 'bug' tag. )

**Comment by peabee** [comment]
I think testing is fine.....
Just done 2 builds with:
> BUILD_FROM_WOOF='testing;9957add;2017-05-10 05:29:18 +1000'
1st was with my usual build system (bit long in tooth 1607 vintage)
2nd was bang up to date - i.e. the system I had just built.

Both built fine with no chroot issues.
I suspect the build environment being used rather than testing - chroot problems are more likely to be a devx problem or something else in the build environment.

I think this can be closed as a bug on testing.....

**Comment by wdlkmpx** [comment]
Hmm i think i read about an issue with ptheme and cross builds. I don't really feel like building a pup as i have to do extra steps just to get something barely usable (a win-xp like pup). There should be 2 kind of builds. One for desktop, and for tablets (the current one).

**Comment by 01micko** [comment]
Hmmmm .. I just thought of something... 

The pinstall for shared-mime-info (slacko) does a chroot to update the mime database which will fail in an X build. I'll have to fix that. This happens before the test too.

I'll close and take a closer look. I haven't done a 32 bit build in 2 weeks so it may be specific to that.
