### ISSUE TITLE
PUPMODE 3

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#1014]
I think it was never implemented in the old init but there are several scripts referencing that pupmode.

It's a "full install in a flash drive" or something...

I wonder if anybody has something to say about it or code snippets to implement it?

**Comment by s243a** [comment]
It's a full install for sure. It would be typically on a USB drive but has ram as the top layer:

See: 
```
#Boot param PMEDIA= usbflash|usbhd|usbcd|ideflash|idehd|idecd|idezip|satahd|scsihd|scsicd
#unionfs layers:            RW            RO1             RO2              PUPMODE
#PUPSFS only:               tmpfs                         pup_xxx.sfs      5
#PDEV1 has puppy:           tmpfs         PDEV1*                           3
#PDEV1 has puppy, no tmpfs: PDEV1                                          2
#PDEV1, PUPSFS:             tmpfs         PDEV1*          pup_xxx.sfs      7
#unionfs layers:            RW            RO1             RO2              PUPMODE
#found PUPSFS, PUPSAVE:     tmpfs         pup_save.3fs*   pup_xxx.sfs      13
#PUPSAVE(multi), PUPSFS:    tmpfs         folders(tmpfs2) pup_xxx.sfs      13+64 = 77
#PUPSAVE, PUPSFS, no tmpfs: pup_save.3fs                  pup_xxx.sfs      12
```

http://webcache.googleusercontent.com/search?q=cache:http://www.puppylinux.com/development/howpuppyworks.html
 
Just set pfx=ram in a full install as the boot parameters and see what happens.

**Comment by wdlkmpx** [comment]
Thanks for that insight.

The problem is  a full install doesn't use a initramfs. 

I added the ability for a full install to use to use initrd.gz with another alternate simplified init (see /usr/sbin/puppyinstaller) because i couldn't boot with a debian kernel, it's an experiment that worked for both woofce kernels and other type of kernels and fixed an issue with the raspi stuff.

Other than that, it will take implementing the aufs stuff in the full install init to make it behave as it was intended, making it a bit complex, i don't think it's going to happen

**Comment by s243a** [comment]
> I added the ability for a full install to use to use initrd.gz with another alternate simplified init (see /usr/sbin/puppyinstaller) because i couldn't boot with a debian kernel, it's an experiment that worked for both woofce kernels and other type of kernels and fixed an issue with the raspi stuff.

Wouldn't that be like using a save folder but with "/' as the folder...granted that breaks naming conventions. The other thing that comes to mind is like an underdog but with nothing but an empty tmpfs above the underdog.

**Comment by gyrog** [comment]
@s243a,
Unfortunately the document you reference is quite ancient, and Puppy has moved on a lot since then, particularly since the rewrite of init that is now in woof-ce 'testing'.
"pfix=ram" makes no sense in a normal full install of Puppy.
Trying to have "/" as a savefolder, certainly won't work with the current Puppy code, and I doubt it would lead to a reliable aufs stack. It certainly would not be a "proper" overlayfs stack.
In general, stacks are simpler, and more likely to be reliable, if the directories that makeup the layers are "beside" each other, not "inside" each other.
You could use a full install of Puppy as an underdog, but I don't get the point.
I think that pupmode=3 is an idea that never really made it, since, from memory, even "classic" init did not actually support it.

**Comment by wdlkmpx** [comment]
So i think this issue is solved. It's not possible to implement pupmode 3.. or maybe it is but with unreliable results.
