### ISSUE TITLE
Have new "wait4usb" script for "initrd.gz", suggestions as to where I could put it?

### ISSUE THREAD

**Issue by gyrog** [puppylinux-woof-CE/woof-CE#1017]
While I've done several successfull usb boots using it, it may be a bit raw for the "testing" branch.
Since the "rationalise" branch is gone, any suggestions?

It's a re-write, mainly to remove searchs of "dmesg" output for messages that don't appear anymore.
But while I was at it, I re-coded all the usb stuff.

**Comment by gyrog** [comment]
Well it's available at [http://www.fishprogs.software/puppy/initrd/wait4usb](http://www.fishprogs.software/puppy/initrd/wait4usb)

**Comment by wdlkmpx** [comment]
The changes look fine to me, however i've seen this line in some rootfs scripts:

 #force update of /proc/partitions...
 dd if=/dev/${ONEDRV} of=/dev/null bs=512 count=1 >/dev/null 2>&1

I wonder how old that stuff is. Maybe it should go to testing anyway, the branch i created today has changes that are too radical and will take some time to analyze and fix the consequences

**Comment by gyrog** [comment]
The old wait4usb script contained those lines, but in my testing the new version worked fine without them. But then I didn't specifically check /proc/partitions, I just checked that booting off a usb device worked ok.
I'll have a look at that.
I'm still not comfortable with putting it in testing yet.

**Comment by gyrog** [comment]
Testing new wait4usb as is, without those lines:
A "cat /proc/partitions" in the "init" script immediately after the call to "wait4usb" produced output in "/initrd/tmp/bootinit.log" that contained the usb partitions, identical to the output from "cat /proc/partitions" in the subsequent running system.
It appears that the lines are not needed.

**Comment by 01micko** [comment]
I reinstated `rationalise` @gyrog so go for it

**Comment by gyrog** [comment]
@01micko, thanks I will

**Comment by gyrog** [comment]
Well it in rationalise now.
So closing this issue

**Comment by wdlkmpx** [comment]
I'll merge rationalise to testing today. I've been testing and editing the code and it has my seal of approval... A couple other issues were fixed as well.

However i think wai4usb should always be called quietly, with timeout as follows:
k4.x = 2 secs
k3.x = 3 secs
k2.x = 5 secs

if kernel param pmedia=usb*, then, add 2 seconds and remove the "quiet" flag
k4.x = 4 secs
k3.x = 5 secs
k2.x = 7 secs

If a non-woofce kernel is being used, add another 2 seconds to the above...

**Comment by gyrog** [comment]
"init" only calls wait4usb whenever a partition is specified, that doesn't "exist", the idea being that it could be on a usb device and only doesn't "exist" because the usb device is not ready yet.
Also "init" is meant to only execute wait4usb once, no matter how many times wait_for_usb is called.
So ususlly the either wait4usb is never executed, or there is a usb device and wait4usb exits as soon as it finds it, no matter how big the timeout is.
Since they are only activated in unusual circumstances, the timeouts should be set just large enough to accomadate all usb devices,

**Comment by wdlkmpx** [comment]
psave=partition:/path/to/file is a special case. if it triggers wait4usb then what if the pupsave happens to be in a usb drive.. PUPMODE 7/13 won't be set, because that's only triggered by pmedia=usbflash.

pmedia=usbflash forces PUPMODES 7/13 if a pupsave is found. it's ok for testing and for those who know what they do..

A more automatic and complementary behavior is in commit: 6e701ff05c19c40dfd90cff3ce0e1a26fce4f2d9

 PMEDIA is the boot media (boot param)
 However the PUPSAVE (savefile, savefolder, savepartition)
   might be located in another drive (ex: psave=sdb1:/customsavefile.4fs)
   we must check if it's located in a flash media storage
   in order to change the $SAVE_LAYER to /pup_ro1

---
Booting from a hard drive, but specifying a pupsave in sdb1/a.4fs.

...
PUPSAVE=sdb1,ntfs,/a.4fs
Setting PUPMODE 12
*** Pupsave is located in a flash media storage: sdb
Setting PUPMODE 13
SAVE_LAYER=/pup_ro1
--SAVEFILE-- /mnt/dev_save/a.4fs
...

This will certainly be more obvious when booting from CD and having a the pupsave in a flash drive. Haven't tested that situation but i know it will work..
