### ISSUE TITLE
Root partition is not marked in full installs

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#1032]
In a slacko-6.9.9.6-k3.16-4G-PM-ABI full install, the root partition is not marked with the little home icon, neither the green unmount arrow (correctly) when you open it with rox. 
So booting a full install in multi-disk/partition system is hard to identify your boot partition.

**Comment by wdlkmpx** [comment]
Oops the commit shouldn't have closed this.. i omitted 'for'.

I haven't tested myself, but it was easy to spot where the bug is..

**Comment by wdlkmpx** [comment]
I deleted my last comment... it was for #1031 

Well i did see that issue, but it kinda feels like an unnecessary work. Everything in all cases work fine in pcmanfm+pvm0.1.17.

However i'm booting a full install with a new init (in initrd,gz) for full installs. And i see the boot partition is properly recognized in the rox desktop.  'mount' doesn't show /dev/root  mounted on /, but the real boot partition (/dev/sda3)

This issue is already fixed, but i first need to push some significant changes,,,

**Comment by mavrothal** [comment]
> 'mount' doesn't show /dev/root mounted on /, but the real boot partition (/dev/sda3)

So does ```mount -v``` on line 320 of /usr/local/pup_event/frontend_funcs 😉 
Hopefully the full install-specific init does some more good  things.
