### ISSUE TITLE
Puppyinstaller fails on full install upgrades.

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#1041]
As the title says, the [cp -a -u command](https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/usr/sbin/puppyinstaller#L1835) exits with errors regarding symlinks in SOURCE and TARGET, and the process fails.
Tried briefly with rsync and tar but no much luck either.

**Comment by wdlkmpx** [comment]
A full install is a fragile setup, when i first tried it, it was completely broken for me. I thought about removing the upgrade button. But icp -a -u proved useful to "update" and test a full install quicker..

**Comment by wdlkmpx** [comment]
I think i'll try to fix this. But there's something important to notice

I read some days ago that someone said that only the full install with the initrd is working for him.

When i was looking into the full install stuff, i had problems creating proper generic kernel parameters as different kernel versions do not support the same info. Or maybe some kernels are properly configured and some are not.

Some would not accept root=/dev/XXXX or root=UUID=, only root=PARTUUID= and PARTUUID is only provided by the full blkid. And some would not recognize PARTUUID=

Mayhem.

This problem is solved by the full-install init, as it properly decodes whatever you specify, except root=PARTUUID=

**Comment by wdlkmpx** [comment]
In /sbin/initNEW (/sbin/init) there's code (200 lines to create a ramdisk and perform a fsck) that can be deleted if the initrd.gz is enforced in a full install...

the full-install init provides some extra facilities that can be removed.. or maybe those facilities should be removed from rc.sysinit. yes, both scripts write the same stuff to /etc/rc.d/PUPSTATE.

the puppyinstaller could create a minimal initrd.gz with the required stuff to boot into a full install...

**Comment by wdlkmpx** [comment]
This issue is fixed by `cp -a --remove-destination`.. it was probably changed 2 years ago.

https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/usr/sbin/puppyinstaller#L1085

To be able to perform a full install you must export this before running puppyinstaller:
 `export ENABLE_FULLINSTALL=1 `

I recently tested a full install, it works fine, but it's only for power users, the secret info is at the beginning of the script. There are issues with grub4dosconfig and stuff, a full install uses initrd.gz and a simple init file.
