### ISSUE TITLE
Puppy Upgrade/Update

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#1042]
It would appear that the puppy upgrade process has regressed.
Now days in can only be done manually and not always with success.
The new init will not see savefiles/folders within subfolders and as always will ignore puppies installed in PUPMODE 2, 6 and 7.
Even when it it finds a save file/folder to update, is still up to the user to update the puppy files, as this facility was not incorporated in the new init.
I may agree that is not up to the init to take care of the updates or to identify installed puppies in a system. However, if puppy is to be more than a hobby/emergency/portable/special-case distro, needs a reliable, user-foolproof, update process.
For major version updates I would think of  a script analogous to puppy installer that will run from a CD in pupmode 5, find relevant installations, including pupmode 2, 6, and 7, and replace the SFSs or upgrade in the case of full installs.
For point release updates, an update process similar to the FatDog or the PPM one, would be handy.  However would be better instead of loading the save folder/file with the updates  to extract and rebuilds the SFSs or use deltas (as un/re-squashing may be too slow on older machines).
In all cases that the SFSs are updated, care should be taken so user installed files do not clobber updated files removing files and whiteouts from the rw layer.

I know puppy is a doocracy, but still I though to try a suggestion instead. 👅

**Comment by wdlkmpx** [comment]
I saw people complain about this. i tend to agree with keeping the "mad machine" behavior for the majority of puppy users and special boot params for the power users..

**Comment by gyrog** [comment]
I understand that being able to upgrade is a nice idea, but it's a can of worms to implement.
So I would encourage anyone who thinks its quite doable, to do.

**Comment by wdlkmpx** [comment]
Lately i've been using puppy mostly through virtual box and the subdirectory search starts to make sense, as i usually change just the iso, using the same virtual machine, to test several puppies.. 

So i think i'll bring back that feature. 

But if we really want to improve puppy.. it has to be a "system rescue cd" by default.. with key tools.. that's why i have a script to compile 30+ apps to make it look more like SystemRescueCD.

When it comes gui frontends, it's really not hard to identify what apps are the most friendly and "Windows-like". i forked, updated and simplified engrampa (file-roller). and now it even compiles and works fine in slacko 5.3-ce (slk13.37)

**Comment by gyrog** [comment]
I just had reason to have a closer look at "rc.update".
1) It's very inefficient, in that you end up with a whole lot of copies of stuff in the rw layer that really don't need to be there.
I really hate to say this, but the only "efficient" way is to have "init" manipulate the rw layer directory before it gets added to the stack.
2) It's made messier because Puppy has no clear distinction between the system and the user.
e.g. MODULESCONFIG
If we use the old "SKIPLIST" we keep any changes made by the user, but we lose any improvements made to the default list as it now exists int the puppy...sfs file.
If we use the new "SKIPLIST", we lose any changes that the user had made to the list, so the user wonders "what's the point of an 'upgrade' if it discards my mods".
And we have no way of knowing if the old "SKIPLIST" has been modified by the user.
If we want to be able to do reliable and "satisfying" version upgrades, we might need to redo the way some user changes get stored.

I never "upgrade" any Puppy.
For a new version I delete everything in the existing directory, and do a fresh manual install.
It's the only way I can be absolutely sure that what I'm testing is only the Puppy I think I'm testing.

**Comment by wdlkmpx** [comment]
In /sbin/initNEW (/sbin/init) there's code (200 lines to create a ramdisk and perform a fsck) that can be deleted if the initrd.gz is enforced in a full install... 

the full-install init provides some extra facilities that can be removed.. or maybe those facilities should be removed from rc.sysinit. yes, both scripts write the same stuff to /etc/rc.d/PUPSTATE. 

the puppyinstaller could create a minimal initrd.gz with the required stuff to boot into a full install...
