### ISSUE TITLE
petget in pupmode 13 is broken

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1043]
Here is the problem:

The default for petget is to save the package directly to the save file.
This is bad and broken.
* a pinstall.sh, doinst.sh (and probably debian equivalent) is executed at '/' - which goes to the tmpfs - that makes it broken.
* it is the understanding of most users on the forum that if they install a package, it gets nuked if they don't save the session - it doesn't. That's bad.

Everything works correctly if you check the box  `install to tmpfs instead of savefile, till session saved`

IDK why we even save it directly to the savefile in the first place :confused: . IMHO that option should be removed and if not, any post install script should be executed at the place where the install happens.

**Comment by ninaholic** [comment]
@01micko I notice this as well with pets, and I think you described both issues perfectly. Seems like "install to tmpfs instead of savefile, till session saved" should be default?

**Comment by wdlkmpx** [comment]
#boot from flash: bypass tmpfs top layer, install direct to pup_save file...

That code has been there for years. I'll take a look

**Comment by jamesbond3142** [comment]
On Fri, 09 Jun 2017 14:25:26 -0700
Mick Amadio <notifications@github.com> wrote:

> 
> IDK why we even save it directly to the savefile in the first place :confused: . IMHO that option should be removed and if not, any post install script should be executed at the place where the install happens.
> 

Historical perspective: 
---
When this was devised, target machine was 128MB machine, with perhaps 64MB absolute minimum. The amount of RAM reserved as tmpfs layer was miniscule, perhaps 64MB at most or may be less. If you install directly to root ("/"), which means it gets installed to that tmpfs, installing a few large packages can easily overwhelm it. It was confusing when people created a 1GB savefile and yet installing a few large pets suddenly popped up warning that the savefile is full.

The workaround this was to install one pet at a time, and then forcing a snapmergepuppy. Another more drastic workaround is to reboot after installing large package. But this of course don't work if the size of the pet is larger than tmpfs to begin with (see below for the size requirement calculation).

Because of that, Barry conceived the idea that pet installation should go directly to savefile (because that's where we want it to end up anyway) to avoid clogging that tmpfs.

PS: The required storage for package installation isn't the size of expanded pet. It's the total size of the following:
a) size of pet itself 
b) size of expanded pet
c) Depending on how you do it, you may need another copy of (b)

So in theory the required size to install a pet is about 5x the size of the pet itself (assuming 50% gzip compression on the pet, assuming that the pet itself is downloaded to "/root").

-- 
James B

**Comment by 01micko** [comment]
Thanks for the insight James :+1: 

On further thought, I think removing the functionality is a bit drastic. Could it be fixed by doing `chroot $DIRECTSAVEPATH sh install/doinst.sh # (or sh pinstall.sh)`?

BTW, with modern machines the minimum requirement for slacko is ~1GB RAM so the default could (should?) be reversed.

Perhaps my biggest beef is the fallacy that has been spread that running in pupmode 13 with periodic saving disabled gives you the choice to save pets installed, which simply is not true (unless of course you tick the well hidden tmpfs checkbox - that should probably go in the main GUI).

**Comment by 01micko** [comment]
Of course a chroot wont work if the utilities aren't there so a simple cd will mostly work with relative paths.. (doinst.sh has these.. Debian anyone?)

It won't work with pinstall.sh that have absolute paths - will still go to tmpfs.

**Comment by mavrothal** [comment]
James gave all the background on the story.
The simplest "solution" is to revers the default.
Better yet detect the available tmpfs and act accordingly.
BTW the default required size in PPM is 2X the size of the installed pet. Is usually sufficient.

**Comment by 01micko** [comment]
@mavrothal yeah _simple_ is not always correct.

I've been experimenting and it works OK (so long as post-install has relpaths) by cd in to $DIRECTSAVEPATH and executing there. Slackware is probably the biggest problem because they don't ship symlinks so the `install/doinst.sh` **must** run or you are likely to have a broken system. 

A consequence of slackware creating symlinks on the fly is that on uninstall your system may end up with a bunch of dangling symlinks pointing to the abyss. That is another issue though.

**Comment by 01micko** [comment]
Probably best practice for PET packages is to start using relpaths in `pinstall.sh`

Anyway.. here is my patch so far if anyone wants to test/add/debug

```patch
--- /initrd/pup_ro2/usr/local/petget/installpkg.sh	2017-04-29 16:50:19.000000000 +1000
+++ /usr/local/petget/installpkg.sh	2017-06-10 15:00:38.951114300 +1000
@@ -200,7 +200,7 @@ elif [ $PUPMODE -eq 3 -o $PUPMODE -eq 7
 	   sleep 1
 	  done
 	  DIRECTSAVEPATH="/initrd${SAVE_LAYER}" #SAVE_LAYER is in /etc/rc.d/PUPSTATE.
-	  rm -f $DIRECTSAVEPATH/pet.specs $DIRECTSAVEPATH/pinstall.sh $DIRECTSAVEPATH/puninstall.sh $DIRECTSAVEPATH/install/doinst.sh
+	  #rm -f $DIRECTSAVEPATH/pet.specs $DIRECTSAVEPATH/pinstall.sh $DIRECTSAVEPATH/puninstall.sh $DIRECTSAVEPATH/install/doinst.sh
 	 fi
 	fi
 fi
@@ -475,27 +475,28 @@ ls -dl /tmp | grep -q '^drwxrwxrwt' || c
 
 #post-install script?...
 #          puppy         slackware       debian/ubuntu/etc
-for i in /pinstall.sh /install/doinst.sh /DEBIAN/postinst
+[ "$IMODE" = 'savefile' ] && EPATH=$DIRECTSAVEPATH || EPATH=''
+for i in pinstall.sh install/doinst.sh DEBIAN/postinst
 do
-	[ ! -e "$i" ] && continue
-	chmod +x ${i}
-	cd /
-	LANG=$LANG_USER nohup sh ${i} &
+	[ ! -e "$EPATH/$i" ] && continue
+	chmod +x $EPATH/${i}
+	cd $EPATH/
+	LANG=$LANG_USER nohup sh $EPATH/${i} &
 	sleep 0.2
-	rm -f ${i}
+	rm -f $EPATH/${i}
 done
 
 #130314 run arch linux pkg post-install script...
-if [ -f /.INSTALL ];then #arch post-install script.
+if [ -f $EPATH/.INSTALL ];then #arch post-install script.
  if [ -f /usr/local/petget/ArchRunDotInstalls ];then #precaution. see 3builddistro, script created by noryb009.
   #this code is taken from below...
   dlPATTERN='|'"`echo -n "$DLPKG_BASE" | sed -e 's%\\-%\\\\-%'`"'|'
   archVER="`cat /tmp/petget_missing_dbentries-Packages-* | grep "$dlPATTERN" | head -n 1 | cut -f 3 -d '|'`"
   if [ "$archVER" ];then #precaution.
-   cd /
+   cd $EPATH/
    mv -f .INSTALL .INSTALL1-${archVER}
-   cp -a /usr/local/petget/ArchRunDotInstalls /ArchRunDotInstalls
-   LANG=$LANG_USER /ArchRunDotInstalls
+   cp -a /usr/local/petget/ArchRunDotInstalls ArchRunDotInstalls
+   LANG=$LANG_USER ./ArchRunDotInstalls
    rm -f ArchRunDotInstalls
    rm -f .INSTALL*
   fi
@@ -503,22 +504,22 @@ if [ -f /.INSTALL ];then #arch post-inst
 fi
 
 #v424 .pet pkgs may have a post-uninstall script...
-if [ -f /puninstall.sh ];then
- mv -f /puninstall.sh /root/.packages/${DLPKG_NAME}.remove
+if [ -f $EPATH/puninstall.sh ];then
+ mv -f $EPATH/puninstall.sh /root/.packages/${DLPKG_NAME}.remove
 fi
 
 #w465 <pkgname>.pet.specs is in older pet pkgs, just dump it...
 #maybe a '$APKGNAME.pet.specs' file created by dir2pet script...
-rm -f /*.pet.specs 2>/dev/null
+rm -f $EPATH/*.pet.specs 2>/dev/null
 #...note, this has a setting to prevent .files and entry in user-installed-packages, so install not registered.
 
 #add entry to /root/.packages/user-installed-packages...
 #w465 a pet pkg may have /pet.specs which has a db entry...
-if [ -f /pet.specs -a -s /pet.specs ];then #w482 ignore zero-byte file.
- DB_ENTRY="`cat /pet.specs | head -n 1`"
+if [ -f $EPATH/pet.specs -a -s $EPATH/pet.specs ];then #w482 ignore zero-byte file.
+ DB_ENTRY="`cat $EPATH/pet.specs | head -n 1`"
  rm -f /pet.specs
 else
- [ -f /pet.specs ] && rm -f /pet.specs #w482 remove zero-byte file.
+ [ -f $EPATH/pet.specs ] && rm -f $EPATH/pet.specs #w482 remove zero-byte file.
  dlPATTERN='|'"`echo -n "$DLPKG_BASE" | sed -e 's%\\-%\\\\-%'`"'|'
  DB_ENTRY="`cat /tmp/petget_missing_dbentries-Packages-* | grep "$dlPATTERN" | head -n 1`"
 fi
```

..but perhaps the EPATH var should be `[ "$IMODE" = 'savefile' ] && EPATH=${DIRECTSAVEPATH}/ || EPATH=''` and remove the later used slashes to keep things relative.

**Comment by gyrog** [comment]
There is another problem with installing directly to the save layer in pupmode=13.
Sometimes libraries won't install at all, this is because links like "/usr/lib/i386-linux-gnu" do not exist in the save layer, but in the puppy...sfs, so installing to the stack (i.e. directly to the file system) works, but installing directly to the save layer fails.
I never install any pets in pupmode=13, I have an alternate pupmode=12 boot entry I use just for that.

**Comment by ninaholic** [comment]
I try to avoid installing pets after savefile/savefolder is created for the same reasons. I am attempting to build puppy with wdlkmpx version (because I understand it better :laughing: ) now https://github.com/ninaholic/woof-CE

**Comment by gyrog** [comment]
If folk don't have enough space in their tmpfs, then increase the size of, or install, a swap partition or a swap file.
The machine might run slow, but it least it should not crash and it should get the job done.

**Comment by 01micko** [comment]
Well a1b3a0f seems to work ok in slacko, xenialpup64 and @Randall-Glass ' kodipup. (in `rationalise`). It can be tweaked of course. Doesn't seem to affect uninstall.

I did notice that xenialpup ships with `tmpfs` (box checked) by default.

**Comment by ninaholic** [comment]
I think something is still not right. I install dosbox.deb to puduan, then did not save, and upon reboot Desktop entry was still there but the program wasn't. Perhaps "install to tmpfs" should be default for all puppies with old method as backup option?

**Comment by 01micko** [comment]
@ninaholic from line 546 onward in `installpkg.sh` needs work. I haven't touched it yet, including looking at the installation path. Also, `DEFICON` logic needs updating for `/usr/share/pixmaps/puppy` instead of using the old mini-icons.

**Comment by gyrog** [comment]
The idea of "install to tmpfs" is a slight concern, It could be understood as installing directly to the "tmpfs"in a similar manner to the "install directly to save layer" does.
The only reliable thing to do is simply "install", yes in pupmode=13, aufs will write all files to the tmpfs, but at least the whole directory tree is available, e.g. symbolic links for some directories, so installs have the same chance of working as in pupmode=12.
Trying to install directly to any layer means you are dealing with only a subset of the directory tree, and some vital information could be in one of the other layers and so not directly available.
Yes, we might be able to fiddle "instlling directly to xxxx layer" to work with the current directory trree, but that could change in the future and it fails again.
"instll to tmpfs" should be the default, only we should call it "install".
If the problem is not enough space in the tmpfs, then fix the real problem, provide more space to the tmpfs.

**Comment by 01micko** [comment]
@gyrog thank you for your perspective and I tend to agree. 

I don't want to be intrusive on users and don't want to 'automagically' force creation of swap. That is a choice for the user. I think I will make `tmpfs` the default but with your correct wording.

I can however detect if a machine has a small `tmpfs` and splash a warning recommending to make a swap partition or swap file. If the user refuses that then they can set 'direct to save' in PPM. How small I don't know where to cut off but I suppose if it is smaller than 500M then there could well be issues.

**Comment by gyrog** [comment]
I would not 'automagically' force creation of swap.
In a PPM environment, I would probably only provide a message advising the creation/increase of swap if an install failed due to lack of space, (or calculations predicted that it would fail due to lack of space), and they were running in an odd pupmode.

**Comment by 01micko** [comment]
The problem that I have seen when tmpfs is overloaded is a RAM crash; system just hangs up and you need a forced poweroff. I haven't seen this for a long time though because my weakest system at the moment has 1GB RAM . I just want to avoid data loss in the current session. So calculating predicted space and popping a message seems the safe way.

All ideas welcome.

**Comment by peabee** [comment]
Is this the same error being worked on here?? This is ppm before a savefolder has been created.... after reboot and savefolder creation the error goes away.... BUILD_FROM_WOOF='testing;aadd84b;2017-06-15 19:35:33 +1000'

![screenshot](https://user-images.githubusercontent.com/5926865/27252400-9fdcffc4-5355-11e7-8c9d-d66c48cd7327.png)

**Comment by gyrog** [comment]
The best insurance against a RAM crash, is significant swap.
The idea being that you will notice a significant slowdown in the machine when it starts to actually use swap, but it will survive. For this reason I have my swap partition on my HD (slower), rather than my SSD.
The nice thing about a swap partition is that every puppy just uses it, nothing to do, and they all  use the same one.
Sorry for ranting off topic a little.

I thought that PPM already did some space requirement predictions when it was sorting out dependencies.

**Comment by ninaholic** [comment]
Maybe a dialog box with two buttons could work?

[Install to RAM ] ............ [ Install directly to savefile/folder ]
(RAM space: 1.3GB ) ... (savefile space: 2.2GB)

SFS files have a similar dialog box when you click on them.

**Comment by gyrog** [comment]
@ninaholic, this suggests that the choice is between 2 equally reliablle processes and so the it depends only on space.
Wheras attempting to install directly into any single layer of the stack, is inherently prone to problems because any layer could contain only a subset of the full directory tree. e.g. the symbolic link "/usr/lib/i386-linux-gnu" does not exist in the save layer, so installing any libraries that are destined for "/usr/lib/i386-linux-gnu" will fail. On the other hand a simple "install" sees the whole stack including the necessary symbolic link that's down in the puppy...sfs layer and the libraries get installed.

**Comment by 01micko** [comment]
Ok, logic is now reversed in `rationalise` branch. Tests welcome.

**Comment by 01micko** [comment]
@mrfricks .. please note the logic is reversed and that setting `/var/local/petget/sc_category` to true now has the opposite effect.
