### ISSUE TITLE
svg icons on 1st boot can be "not ready" causing desktop to start incorrectly

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1046]
On first boot svg icons seem to take some time to become ready for use - i.e. some sort of initialisation process occurs....
On a "standard" Puppy with relatively few svg icons this "startup time" is not apparent and doesn't cause any problems.
However if an icon scheme with many svg icons (such as flat-remix in LxPup) is used then this startup time can cause problems as the desktop tries to start before the svg icons are "ready".
The startup time seems to vary between slacko and xenial based pups - with xenial being sufficiently slower to be "ready" as to cause problems.....
What I think is needed is a test for the svg initialisation process to have completed to be added to .xinitrc so that desktop initialisation does not start until svg initialisation has completed.
But I don't know where svg initialisation happens in Puppy or how to test that it has finished - any clues anybody??

**Comment by ninaholic** [comment]
In puppies boot with newer woof-CE I noticed that sometimes it takes longer for the desktop to appear (it will be black with just cursor for a few seconds longer), like newer Tahrpup 6.0.6 or Xenialpup. Maybe it is because they already wait for svg to load? What does the desktop look like if it appears before svg, are the icons generic or triangle warnings?

mplayer, firefox, and vlc is the same for me, the first time you run it it takes longer to "initialize". pmusic is the worst because it scans my entire drive for mp3s (and I have like 5000) so the playing window doesn't come up for about 30 seconds the first time. It would be nice to turn that "scan entire drive" feature off or at least have a message about what pmusic is doing while waiting @zigbert  :laughing:

**Comment by zigbert** [comment]
@ninaholic 
Regarding pMusic, will you please specify if this is equal for ubuntu-based puppies and Slacko. I have 80000 mp3's, and pMusic needs some seconds to scan the system, BUT the gui shows up rather quickly and shows a message about what's going on... With the gui up and running, you can start use pMusic while the scan is proceeding.

I am REALLY interested in knowledge about this to improve the usage.
I don't think it is the number of mp3's that makes your delay, but the amount of files in the filesystem(s). My system contains one system disc of 100Gb, and one additional archive-disc of 1 Tb.

**Comment by 01micko** [comment]
@peabee just FYI - gtk and librsvg take care of svg loading. That probably doesn't help much ..

**Comment by peabee** [comment]
I've kludged it pro-tem by putting a 5 sec sleep into .xinitrc for LxPupXenial just for the first boot....@ line#55 - not nice but seems to work....
`.......
# lxpupxenial needs time for svg generation....
if [ ! -f /opt/lxpup/lxpupxenialstartdelay ]; then
 sleep 5
 touch /opt/lxpup/lxpupxenialstartdelay
fi

#100501 if full nvidia pkg installed, it has a gui config app...
[ -f /root/.nvidia-settings-rc ] && nvidia-settings --load-config-only
.........
`

**Comment by ninaholic** [comment]
sorry @zigbert, I could not replicate the pmusic scanning for mp3s for 30 seconds (the first time I click on an mp3) problem after re-building again, so I think my post was a mistake :laughing:

**Comment by mavrothal** [comment]
does this still needs to be open?

**Comment by peabee** [comment]
I'll close until it happens again.....
