### ISSUE TITLE
rox desktop drive icons slow to refresh

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1051]
['prehistoric'](http://murga-linux.com/puppy/viewtopic.php?p=958016#958016) reported this and I have seen it on my slower machines under load. They never used to be this slow. I can't be sure if it's not a rox issue either as it is getting old.

**Comment by wdlkmpx** [comment]
i've never seen that happening. but i don't think it's a delay, that would mean the system is relaying messages too slowly or frontend_change failed to properly parse the args from pup_event_frontend. or maybe it's just rox displaying a shining new feature.

by the way pup_event_frontend and pup_event_ipc should rewritten in C.

the rox drive icons don't get updated when i mount a partition with pcmanfm. but the pvm always  shows mounted or unmounted volumes properly no matter what app mounted them..

in my tests with fido and now uzer, rox doesn't work as expected because pup_event_frontend is running as root and creating a bunch of files with root ownership, and it's never too late to realise that rox is a bad choice to be a forced system app and when it's gone the world will be a better place...

**Comment by ninaholic** [comment]
I wonder is something got messed up https://github.com/puppylinux-woof-CE/woof-CE/commit/0c19fd374e4256b4584b44f87a84acec55943d15 https://github.com/puppylinux-woof-CE/woof-CE/commit/c7598579563045ace00249ebce5f20b4379a7b9f and https://github.com/puppylinux-woof-CE/woof-CE/commit/d51e8dabe3083ea964593036d46fc8deee791ecb , or maybe https://github.com/puppylinux-woof-CE/woof-CE/pull/984/files (not sure what this actually fixed)

I think this bug has scared off @mrfricks from continuing Xenialpup  :dizzy_face:

**Comment by wdlkmpx** [comment]
it was probably radkys fix then.

i don't know how to trigger this, but i still have the rox pinboard (desktop) and all, but another default filemanager+pvm so i can do basic things such as copy and paste with the keyboard, tabs, etc..

**Comment by 01micko** [comment]
no, radky's fix didn't do anything apart from 
1) if you chose 'clear' in the gui and 
2) introduce a call to 'feh' which if non-existant caused 'feh: command not found' non-fatal error.

**Comment by wdlkmpx** [comment]
the only delay i see is when mounting fat partitions. all fat partitions. i'm not able to reproduce the bug in a new install with everything rox by default. there's an insane amount of code just for the puppypin, when in other fms, you just add or delete a .desktop file. i'll keep testing even in virtual box to see if i hit the bug

**Comment by wdlkmpx** [comment]
commit https://github.com/puppylinux-woof-CE/woof-CE/commit/ac81370a42fbc6bd606d72902f92047411f3c55e is a critical fix

the umount script was badly outdated, i saw a very weird behavoir when unmounting a ntfs partition. then looking at the script, the target umount binary can be run twice and it's busybox umount with the -d switch ... it's not supported by busybox 1.21. why was it working???

there was a convoluted logic for puppy 4, but i guess it didn't make sense in puppy5 or puppies made in 2011+

now partitions are unmounted way faster and reliably and this fixes issues probably including the one reported here..

**Comment by wdlkmpx** [comment]
no, it wasn't run twice, i knew that part was not true, but still wrote it haha..

one of them was to handle umount -a...
commit https://github.com/puppylinux-woof-CE/woof-CE/commit/ea0f0f2ba99d8ace547069c0b850bde703062a7d does the same

**Comment by 01micko** [comment]
3084fa6 by @ninaholic thanks to radky should fix this
