### ISSUE TITLE
DISTRO-PKGS-SPECS-ubuntu-xenial has wrong FALLBACKS

### ISSUE THREAD

**Issue by wiake** [puppylinux-woof-CE/woof-CE#1089]
Not sure, but my understanding thus far of support/findpkgs suggests to me that for DISTRO-PKGS-SPECS-ubuntu-xenial:

FALLBACKS_COMPAT_VERSIONS='trusty saucy raring precise'

should be:

FALLBACKS_COMPAT_VERSIONS='xenial trusty saucy raring'

**Comment by woodenshoe-wi** [comment]
My understanding of support/findpkgs is that it works either way.

The comment at line [81](https://github.com/puppylinux-woof-CE/woof-CE/blob/ca4c327c28b9d3bcc5ce06402e84e7ac42cba540/woof-code/support/findpkgs#L81) seems to suggest that DISTRO_COMPAT_VERSION is in the list of FALLBACKS_COMPAT_VERSIONS but line [185](https://github.com/puppylinux-woof-CE/woof-CE/blob/ca4c327c28b9d3bcc5ce06402e84e7ac42cba540/woof-code/support/findpkgs#L185) will add DISTRO_COMPAT_VERSION to petcompiledPTNS and line [188](https://github.com/puppylinux-woof-CE/woof-CE/blob/ca4c327c28b9d3bcc5ce06402e84e7ac42cba540/woof-code/support/findpkgs#L188) will ignore it if it was listed in FALLBACKS_COMPAT_VERSIONS.

**Comment by wdlkmpx** [comment]
That variable is meaningless. I never found Code that actually performs that operation... Or if i did i can't remember. It can be implemented, but at this point it's something meaningless.

Mrfricks haven't updated his files in months, somebody should Tell him that most of the issues he encountered are already solved and probably also Provide him a ISO file so he can just upload it to ibiblio and release a new version of the most popular puppy

**Comment by woodenshoe-wi** [comment]
petcompiledPTNS is passed to support/findpkgs-search-helper, and was used in the original search function to find the closest match for pets when DISTRO-PKGS-SPECS doesn't specify which pet repo they come from.

It's been a while since I worked on support/findpkgs-search-helper so I might not be remembering correctly but I don't think there is anything broken with it.  (Besides the usual woof issues 😀)

**Comment by woodenshoe-wi** [comment]
I guess I was wrong about that, I did some testing and FALLBACKS_COMPAT_VERSIONS gets reset to "" if DISTRO_COMPAT_VERSION is not included.

I have a fix for this if it doesn't cause any new problems.  #1090

**Comment by wdlkmpx** [comment]
Yeah that is a bugfix.. merge It.

I see the fallback versions for xenialpup should be: tahr... Yes tahr
only.. although precise can also be included.

In distro_pet_repos only tahr and precise are listed. You might want
to edit the xenialpup fallback PET repos.. i'm Not sure but it might
make findpkgs a little faster for xenialpup

We're talking here about PET repos.. if i'm Not mistaken. I remember
the script only downloads pkgs from only one compatible distro repo..
the current version.

**Comment by woodenshoe-wi** [comment]
Yes, FALLBACKS_COMPAT_VERSIONS only applies to PETs.

I don't see any technical issues with adding support for the previous version of the compat distro, it would make building from the testing distro version possible from the very beginning, but I do see practical issues.  The large distro package lists would need to be downloaded and processed, which would take twice as long to do two, and findpkgs might run half as fast with all those packages to search through.

I'm not sure if setting FALLBACKS_COMPAT_VERSIONS makes findpkgs run faster or slower, but it makes more sense to me to explicitly set FALLBACKS_COMPAT_VERSIONS="" rather than findpkgs doing it automatically whenever it doesn't like the format of FALLBACKS_COMPAT_VERSIONS.

The only difference FALLBACKS_COMPAT_VERSIONS makes is if there are multiple PETs of the same name.  If it is not specified findpkgs will pick more or less the first one it finds, otherwise it will search for one compiled in the FALLBACKS_COMPAT_VERSIONS in order of preference.

**Comment by mavrothal** [comment]
does this still needs to be open?

**Comment by woodenshoe-wi** [comment]
I don't think so, but I didn't open this issue.
