### ISSUE TITLE
ROX icon theme always Puppy Standard

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1091]
Lines 132-143 of the pinstall.sh of ptheme in rootfs-packages mean that the ROX icon theme is always "Puppy Standard"
To make the ROX icon theme the same as the Desktop theme, line 33 in
/root/.config/rox.sourceforge.net/ROX-Filer/Options
should be:
<Option name="icon_theme">ROX</Option>

**Comment by 01micko** [comment]
No. The 'desktop' icon theme has nothing to do with ROX icon theme. Only a compliant _gtk_ icon theme can be used as  `$PTHEME_ICONS_GTK` , which is defined in the theme so if you want stock ROX icons hack the theme. So far, the only other theme usable is 'puppy flat' but I am working on another loosely based on google's 'material design' principles.

The reason for using 'puppy standard' is because it is the default  _desktop_  icon theme. So, if you want consistency make or hack a gtk-icon-theme and base a desktop icon theme on that then make a `ptheme` using those as  `$PTHEME_ICONS_GTK ` and `$PTHEME_ICONS`

**Comment by peabee** [comment]
Hi Mick - great to hear from you even if it is just to tick me off ;-)
I of course bow to your superior knowledge - all I can report is that if line 33 in
/root/.config/rox.sourceforge.net/ROX-Filer/Options
says "Puppy Standard" then the Rox directory icons are always Puppy Standard
but
if the line says "ROX" then the Rox directory icons change when the Desktop Icon Set changes with no other obvious downsides
which for me is nicer and more consistent behaviour......
I'll just keep patching in my builds in 00build.conf  .... close the Issue if you want.
Cheers
peebee

**Comment by zigbert** [comment]
Hi Mick :-)

**Comment by wdlkmpx** [comment]
talking about icon themes.

we need a more or less complete lightweight icon theme to be included in all woofce pups, gtk3 apps in particular tend to use icons only found in the icon theme. i use some gtk3 apps

i have one for dpup that i've been using for a while, but it has only 48x48 png images, everything loads fast though.

another interesting fact, when you install apps, icons are installed in /usr/share/icons/hicolor, i added more iconpaths to the jwm_config, including a couple hicolor subdirs, that alone is a huge and simple fix

we should strive to follow that approach rather than creating endless custom .desktop files and unnecessary code... well only a sed command to replace the app category, it would be a hit
