### ISSUE TITLE
wifi not automatically connecting after reboot

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#1108]

**Comment by mrfricks** [comment]
Both frisbee & sns fail about 80% of the time, to automatically connect to wifi after rebooting.  Network wizard connects fine.
I'm trying to figure out if this a xenialpup issue or a woof issue, any pointers/ideas would be appreciated.

**Comment by mavrothal** [comment]
Rebooting as oppose to cold start? or as when you run with a savefile/folder? or just at the  first reboot?
I do not see issue with frisbee and xenial64 (Broadcom card) or xenial 32 (Intel card) either at reboot or cold start with a savefile
Frisbee has pretty extensive diagnostics. Anything there?

**Comment by ninaholic** [comment]
Running woof-CE build of Slacko 14.0 made this week as full install, after rebooting my wifi almost always connects, and when it does not I wait and it eventually connects (when the signal gets strong enough again I think). This seems more reliable than when I did the same as frugal install, where it doesn't connect automatically most of the time as well, and I had right-click on the taskbar icon to connect manually, so maybe the problem is frugal only?

**Comment by ninaholic** [comment]
Running woof-CE build of Slacko 14.0 made this week as full install, after rebooting my wifi almost always connects, and when it does not I wait and it eventually connects (when the signal gets strong enough again I think). This seems more reliable than when I did the same as frugal install with savefolder, where it doesn't connect automatically most reboots and I had right-click on the taskbar icon to connect manually, so maybe the problem is frugal only? (perhaps a timing issue?)

**Comment by mrfricks** [comment]
It happens both restarting and on a cold boot and only with xenialpup64. I've managed to test on some more laptops and it seems it's only a problem on this low end netbook so is probably a timing issue as ninaholic says.

frisbee & sns could wait a bit after connection has supposed to of occurred, check if /var/db/dhcpcd-*.lease exists & if not restart the dhcpcd process. 

anyway, i'm really happy it's not an issue for everyone ..... panic over!! :)

**Comment by ninaholic** [comment]
> frisbee & sns could wait a bit after connection has supposed to of occurred, check if /var/db/dhcpcd-*.lease exists & if not restart the dhcpcd process.

@mrfricks this sounds like a great idea if possible! If something like this can fix the issue on your old netbook it might help on my old 2005 laptop booting frugal too, and maybe other edge cases too :smiley:
