### ISSUE TITLE
raspberry pi 3 issues - built from latest testing

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1147]
I built a stretch raspbian based distro and transferred the resulting files to a 2GB SD card partitioned with FAT and ext4 (no journal). Proceeded to boot in RPI 3

*issues*
1. During build `shared-mime-info` was missing. Changed the `PKGS_SPECS_TABLE` to accept the raspbian deb instead of the non-existent pet. (solved)
2. Wouldn't boot. The reason was that busybox in initrd.gz was broken. Replaced with one from June last year. (solved - but probably needs tweaking). Booted to desktop and connected.
3. Rebooted and saved on ext4 but save folder wasn't seen - needed `psave=$(my-ext4-part-UUID)` (or perhaps` mmcblk0p2` would have done - took the safe route) in `cmdline.txt` file on the FAT boot partition. (solved). Subsequent reboot found the save dir and all settings were saved.
4. No sound. Files were missing from /usr/share/alsa. This is because, for some reason, `alsa-base` is a dummy deb package. The real package, with all the same files as expected in alsa-base is `libasound2-data`. (solved). Installed, and after a reboot sound works. 
N.B-1. I believe that the HDMI sound doesn't work because we don't let udev choose the drivers needed in xorg.conf. Maybe RPI should be one of those udev cases in `/etc/rc.d/rc.sysinit`.
NB-2. I also added `dtparam=audio=on`, not sure if it helped or not - too lazy to test.
5. In setting up JWM in `3builddistro-Z` it affected the running system (broke the menu in my slacko64 - easily fixed with `fixmenus; jwm -reload`). No detrimental effects in the target system. Note that this is with the external `jwm-config` package (default in the specs), not the `rootfs-packages/jwm_config`.

*good stuff*

Congrats @woodenshoe-wi and @wdlkmpx on your good work. With a little arm/rpi experience I was able to solve most of the issues with a minimum of fuss.
The system is very responsive running from RAM and it is a bit of fun. Midori is a good browser for this. :+1:

**Comment by wdlkmpx** [comment]
Regarding jwm_config, there's only one way to deal with this... blacklist jwmconfig3 in 3builddistro-Z.. https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/3builddistro-Z#L373

and move jwm_config to rootfs-skeleton.

Some apps have been rewritten or heavily modified for woofce, so there must be a way to enforce them.. and there is.

The 1st time i tested the wce jwm_config i was building a precise pup with jwm 2.3.6.. and it was buggy including ptheme. So i thought.. there are like 1000 bugs to fix everywhere in the system, maybe i can fix this in the distant future.. and decided to use jwmconfig3. which is overridfen by my config when i install my zz pet package haha (i'm going to delete that config).

Unfortunately it would seem that jwm itself hasn't received enough fixes, so the only reasonable approach is compile the latest jwm version every few months. The same history with the abandonware called rox, from the jun7 repo, although it doesn't seem compatible with older pups.

Now that i'm using mostly openbox, i see jwm is more lighweight and better, more appealing. Now i also appreciate the rox desktop a bit more, just because i added a crapload of enhancements and behaves a little better than the p-v-m. But i still thinks it's unneeded and hipster stuff, i certainly wouldn't be able to contribute much using rox as the filemanager, so it's a matter of practicality, even in windows or using thunar i miss pcmanfm.

**Comment by woodenshoe-wi** [comment]
Glad to see someone doing a build! 👍

Issue 1, - I think peabee deleted the noarch shared-mime-info... the last posting in #925 proposed deleting it.  I'll see if I can make a noarch petbuild for it.

Issue 2, - I haven't done a build with the latest set of initrd_progs, the compilers were changed recently.

Issue 3, - I have been using a save file on a SD card with a single fat partition, so I didn't catch that.  Should the save dialogue modify cmdline.txt or is the problem with the init script?

Issue 4, - I guess I haven't been testing the sound... I'll have to look into that.

Issue 5, - That is why I try to use run_woof, some random pet with a bad pinstall script can try to make the changes to the build Puppy instead of the one being woofed.  Maybe we need to repackage that pet with a fixed pinstall.

**Comment by woodenshoe-wi** [comment]
I was going to try to make a new noarch shared-mime-info pet, but after getting the petbuild to run in the new location I discovered that update-mime-database is a binary.

**Comment by 01micko** [comment]
>I was going to try to make a new noarch shared-mime-info pet, but after getting the petbuild to run in the new location I discovered that update-mime-database is a binary.

Indeed. I think the raspbian version is ok committed in 0edd24f

As for issue 3 I think it is a general deficiency in the shutdown routine in woof. For example, if a user boots on sda5 and saves session on sda6, no matter the distro or arch,  the new init will not find it. It does only what it is told and that is by design.

**Comment by woodenshoe-wi** [comment]
Well, if wdlkmpx or gyrog have a fix for issue 3 I'll gladly test it, but I wouldn't be comfortable modifying init without their input.

It would be nice if save files could be on USB sticks, and if copied to a different stick the UUID would not be the same... so searching for save files and giving a list to choose from would be the most flexible... but some people don't want init searching for things because it slows it down.

It might be possible to have a separate init for the raspup builds...

**Comment by wdlkmpx** [comment]
Assuming the savefolder is not in a subdirectory then pmedia=cd does
the trick. or so i think.

Maybe a quick fix can be: set pmedia=cd for arm* arches

if [ -z "$pmedia" ] ; then
case $(uname -m) in arm*) PMEDIA=cd ;; esac
fi

I deleted all the aboriginal linux stuff.

I compiled static toolchains with musl-cross-make (ggc 6.3, musl
1.1.16), the current arm cc is arm-linux-musleabihf. There is also
arm-linux-musleabi.. should i use that one for the next release?

**Comment by 01micko** [comment]
About busybox.. it was only 300k - so I dunno what went wrong there. I'm gathering that aboriginal as is to musl was the difference between june and the last compile. I never tried musl to cross compile but have used aboriginal (a looong time ago) with success. Note that @woodenshoe-wi 's pi distro supports armv6 as well (pi 1, which I do have but haven't tested yet).

As for finding save files.. maybe pmedia=cd would work, but it still has to be written to the `cmdline.txt` in the FAT part of the pi, which I suppose could be added at woof level. I'll brb while I test `pmedia=cd` out.

**Comment by 01micko** [comment]
Just tested `psave=mmcblk0p2` in `cmdline.txt` and it works fine.

Righto.. this should be _reasonably_ safe somewhere in shutdown-config

```shell
if [ "$DISTRO_BINARY_COMPAT" == 'raspbian' ];then  # raspi can only boot off first vFAT partition
  dev1=/dev/mmcblk0p1
  tmpmnt1=/mnt/mmcblk0p1
  mkdir -p $tmpmnt1
  mount -t vfat "$dev1" "$tmpmnt1" -o utf8
  if [ -e "${tmpmnt1}/cmdline.txt" ];then
    xline=`head -n1 "${tmpmnt1}/cmdline.txt"`
    newline= "$xline psave=${SAVEPART}"  #eg mmcblk0p2
    echo "$newline" > "${tmpmnt1}/cmdline.txt" # overwrite
  else
    echo "psave=${SAVEPART}" > "${tmpmnt1}/cmdline.txt" # create
  fi
  sync
  umount ${tmpmnt1}
fi
```

**Comment by wdlkmpx** [comment]
It should work with pmedia=cd, i'd like to see the init script

**Comment by 01micko** [comment]
>It should work with pmedia=cd, i'd like to see the init script

init is stock standard woof.

**Comment by 01micko** [comment]
`pmedia=usbflash` should work too but it does not. The pi is a different beast. `psave=` seems to be the best answer, and that can't be done from woof, unless making gross assumptions.

**Comment by wdlkmpx** [comment]
Have you tried running the current static binaries in a running
arm-based pup? What errors do you see? In a raspi1-2-3.

Something like: ./busybox ./cryptsetup

http://landley.net/aboriginal/ ... it's dead

AL used only ancient GPL2 software. When I switched to musl-cross-make
binaries suddenly were easier to compile with less hacks.

But when i was using AL i noticed that i was able to cross-compile for
arm using a i686 pup. And that was what i was doing: compile i686 and
arm static initrd progs in a i686 pup.

The one mistake i probably made was compiling a x86_64 static cross
compiler for arm.. that is what comes to mind. I have never attempted
to build a raspbian pup.

But the advantage of musl-cross-make, use the latest musl and gcc to
cross-compile the latest version of the selected initrd-progs

And that fits what i do: compile the latest version of the
initrd-progs. It might seem too edgy but it really isn't.. each
release = better performance even the oldest in supported compat
distro. It's a big plus.

So, i'd like to see the errors. I'll update the initrd progs for a new
release and compile a new arm cross-compiler if the current one is
broken.. one of these weeks.

**Comment by woodenshoe-wi** [comment]
I've been working on a init-bootmenu add on, so I haven't tried a new raspup build because I want to add the bootmenu stuff.

If you have recompiled binaries that you want me to test just give me the link.

**Comment by woodenshoe-wi** [comment]
Hmm, I tested the current version apps, (initrd_progs-20170706-2-static.tar.xz), and busybox is the only one that segfaults...

**Comment by wdlkmpx** [comment]
I haven't recompiled but the arm static binaries in
http://01micko.com/wdlkmpx/woof-CE/initrd_progs-20170706-2-static.tar.xz
are broken (apparently)

There's also aarch64 static binaries.. something that would have never
been possible with aboriginal linux.

**Comment by woodenshoe-wi** [comment]
`file busybox` gives
```
busybox: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), 
statically linked, missing section headers 
```
It is the only app with 'missing section headers'... and the only app that segfaults...

**Comment by wdlkmpx** [comment]
It has the same files found in
http://01micko.com/wdlkmpx/woof-CE/initrd_progs-20170706-static.tar.xz

00_arm/bin/busybox

except busybox.. i don't know what happened but the file in -2-
tarball is corrupted. i only added i686 static binaries to the tarball
and removed 00_armv5 and 00_i486

Hmm not sure what to do, create revision -3-, or just add 00_i686 to
the original tarball. Or maybe a new release.. one of these weeks..

**Comment by wdlkmpx** [comment]
I know what i'll do. I'll just update versions and configs. And
woodenshoe-wi will compile the next release (running './build.sh
tarball' in a x86_64 pup) that happen today! As dpup i686 is the only
iso i have atm. But ntfs-3g 2018.xx.xx has been released yet. Hmm

**Comment by gyrog** [comment]
Comment on 01micko's issue 3, "init" not finding the savefolder:
It's a "telling init where it is" issue, not an "init not finding it" issue.
The problem begins with "shutdownconfig" giving a false impression that you can select a location for your savefolder and now Puppy knows where it is.
The reality is that "rc.shutdown" is told where to save stuff, but "init" is not told where it has been saved. So you have to add a boot parameter to tell "init" where it has been saved.
That's why "overlay_init" uses a "bootspecs" file as a way for the running system to pass information to "init". And the "saveconfig" utility not only tells "rc.shutdown" where to save, but also tells "init" the partition, subdirectory, and save mode used.

Note on specifying a partition:
I recommend using unique labels on your partitions, and specifying those.
In 01micko's case, you should also be able to specify "psavemark=2".

PS. I could waffle on at length as to why "searching" in "init" is not a preferred solution, but I'll spare you at this time.

**Comment by wdlkmpx** [comment]
After https://github.com/puppylinux-woof-CE/woof-CE/commit/9d0d4e7866b3287f4f3dddf890be8979f6574a6a
initrd-progs is ready for a new release. I tested the resulting
initrd.gz in virtual box (dpup) and it works fine. now w-wi can
'./build.sh tarball' and post the tarball here, hopefully it will also
work fine in a raspi

**Comment by woodenshoe-wi** [comment]
I got my init-bootmenu add-on working 725c3d2

I also compiled the arm initrd programs and tested them on my Pi 1 and Pi 2, so the current cross compiler is fine, something must have happened to the busybox binary.

I submitted some changes to initrd-progs/build.sh that allow separate tarballs for the different arch binaries, if/when they would be merged it should fix the initrd problem.  (initrd_progs-arm-... is already uploaded to gitlab)

**Comment by 01micko** [comment]
@gyrog wrote

>The reality is that "rc.shutdown" is told where to save stuff, but "init" is not told where it has been saved. So you have to add a boot parameter to tell "init" where it has been saved.

I wrote

>As for issue 3 I think it is a general deficiency in the shutdown routine in woof. For example, if a user boots on sda5 and saves session on sda6, no matter the distro or arch, the new init will not find it. It does only what it is told and that is by design.

@gyrog wrote

>That's why "overlay_init" uses a "bootspecs" file as a way for the running system to pass information to "init". 

Perhaps a bootspecs file would be a good idea for this init?

**Comment by woodenshoe-wi** [comment]
I got to the bottom of issue 5...

It's not jwmconfig3 (I think this is used in the xenial builds too), it is the jwmxdgmenu pet that I compiled from the sources located at http://distro.ibiblio.org/puppylinux/sources/x/xdg_puppy-0.7.6-9.tar.bz2

If you look in the jwm-xdgmenu directory you will find the offending pinstall.sh script.  
At the bottom...
```
cp ~/.jwmrc ~/.jwmrc.$$
cp /tmp/jwmrc ~/.jwmrc
```

Do the sources at ibiblio need fixing, or should I just delete the pinstall.sh script from the pet and ask peabee to re upload it?

**Comment by peabee** [comment]
http://distro.ibiblio.org/puppylinux/pet_packages-common/xdg_puppy_jwm-0.7.6-16-i486.pet
does not have a pinstall....used in "slackware" builds....

**Comment by woodenshoe-wi** [comment]
Ok, I just deleted the pinstall.sh and repackaged the pet.

https://www.dropbox.com/s/340bqhgcd9ee07e/jwmxdgmenu-0.7.6-1.pet?dl=1

It should replace the one in arm/pet_packages-jessie.

Because I only repackaged it, I just added a '-1' to the name so the new pet will be downloaded.

Packages-puppy-jessie-official will still need to be updated.

**Comment by peabee** [comment]
Done.

**Comment by woodenshoe-wi** [comment]
Thanks.

**Comment by gyrog** [comment]
@01micko wrote
"Perhaps a bootspecs file would be a good idea for this init?"

Yes, well, definitely a well defined back channel, if not exactly the bootspecs code.
This is just one of the "deficiencies" I perceive in the current init that "overlay_init" attempts to "solve".
Some of them could easily be ported, some of them would be difficult.
When I've "finished" development of "overlay_init" I would like to have a discussion, about what to do with the technologies contained in it. I have only 1 more version planned, before reaching this milestone.

**Comment by woodenshoe-wi** [comment]
I found a rather serious bug in init that is easily triggered by init-bootmenu.

If the DISTRO_SPECS file in the initrd is not updated to match the version of the puppy main sfs file specified by the bootmenu.txt entry selected, a version upgrade is triggered even though the savefile matches the version of the main sfs.  At this point it is only a minor misconfiguration and no harm has been done.

load_ext_file() has mounted the save file on $SAVE_LAYER (/pup_rw) and the user, realizing that the upgrade was triggered by a mistake in the bootmenu.txt entry selected, cancels the upgrade.

umount_unneeded() will only un-mount real partitions, not loop devices, so the savefile remains mounted on /pup_rw

/pup_rw  is moved to /pup_new/initrd/pup_rw, and

https://github.com/puppylinux-woof-CE/woof-CE/blob/1302768627962cd38258bed5597588bd12567545/initrd-progs/0initrd/init#L1451-L1453 checks if /pup_new/initrd/mnt/tmpfs/pup_rw is a directory, I'm assuming it is because the upgrade was canceled and the choice was to run in ram, and proceeds to `rm -rf /pup_new/initrd/pup_rw` and make a link to /initrd/mnt/tmpfs/pup_rw which sits in my now empty savefile.

Fortunately I had copied backup savefiles to test init-bootmenu, so no files were lost in this misadventure, but I wouldn't encourage anyone to use init-bootmenu without making backups of all savefiles before making any changes to bootmenu.txt or installing a new initrd.gz.

**Comment by wdlkmpx** [comment]
./ffprobe <any media file>

**Comment by woodenshoe-wi** [comment]
It depends on if you want to support the Pi1 / Pi zero.  They do have hardware floating point, but are ARMv6 chips.

The armel version works on my Pi1, but the armhf version gives `Illegal instruction`.

On my Pi3 both work.

Pi1
```
# uname -m
armv6l
```

Pi3
```
# uname -m
armv7l
```

If it is a problem, I am set up to compile things natively on my Pi1 using a "Network Block Device" connection to a partition on my PC.  I also set up swap space the same way, so I have basically unlimited hard disk space and enough swap space to compile anything.  But it may take all day on that little chip...

**Comment by wdlkmpx** [comment]
It's my understanding that the Pi1 is incredibly slow that we have
look back in time to find something as slow... maybe a pentium II
processor. That's what i read.

I also read that the pi3 might be the first pi with a decent
performance for a desktop user.

But i wanted to know what happens if you run ./ffprobe file.mp3 etc ..
it should crash

The history behind that request is that the static x86  ffmpeg and
ffprobe crash when given an input file.. because the static libx265
tries to dlopen() the system's libx265.so !

https://github.com/videolan/x265/blob/master/source/encoder/api.cpp#L736

I sent JVS a patch to fix this issue and he just notified that the
issue is fixed. Hopefully he will produce new static binaries for
x86*, armel, armhf and aarch64 .. thats great because if you think
about it, a universal SFS ffmpeg package can be produced with all
those static apps + wrapper scripts that use $(uname -m), now i have
one, but the static ffmpeg was crashing

It has come to my attention that i'm producing static initrd-progs for
armhf ..  arm-linux-musleabihf

https://github.com/richfelker/musl-cross-make/issues/34#issuecomment-330987634

Does this run in the raspi1?
http://distro.ibiblio.org/puppylinux/arm/pet_packages-armv6/cryptsetup-1.7.5-musl_static_armhf.pet

I also have some palemoon builds that you might want to test..

**Comment by woodenshoe-wi** [comment]
I ran `./ffprobe` with an absolute path to a mp4 video file.  According to ffprobe the video in my test file is using h264 encoding.

I installed the cryptsetup pet with the SD card in my Pi1.  I don't normally use cryptsetup but it seems to work.
```
# cryptsetup --version
cryptsetup 1.7.5
```

The special thing for me about the Pi1 is that it has the same CPU and RAM as the Pi zero plus wired ethernet, so if something runs on a Pi1 it should also run on a Pi zero and I can reliably connect it to my PC when compiling things.

For "desktop" use I would definitely not recommend a Pi zero, it is more appropriate for "Internet of Things" type projects...  It still has hardware accelerated video and is supposed to handle full HD video but IoT projects usually connect with ssh (maybe adding the `screen` program would be useful?).

According to the torrent files for the latest version of Raspbian, the full version is 1364 MB and the "lite" (no X) version is 351 MB.  Raspup can pack a full graphical desktop into a zip file the size of the command line only version of Raspbian, and can run "frugally" from the SD card without reformatting it which means that "Windows only" users can easily backup their save file without any special programs.  Also "Puppy" users wouldn't have to learn the "Debian" way of doing things.

Although there are a couple of ARM versions of the Puppy related distros, I don't think any of them support the Pi zero.  Actually, a small "no X" build might be more appropriate, I'm sure it would be possible to make something much smaller than Raspbian "lite"...  I'll bet it could even run in RAM.

**Comment by wdlkmpx** [comment]
There is a fatal flaw that has not been addressed.. profiles to
produce a minimal build (core), desktop edition, and kitchen sink
edition (gui apps). This must be done manually of course, and i guess
probably only one or two pups will implement it

It's possible to create more than one
DISTRO_PKGS_SPECS-raspbian-stretch and use one of them for a specific
build. But it will probably make a bit more difficult to maintain.

I want to add alpine linux as a compat distro, but i've been busy.
https://alpinelinux.org/downloads/

This distro looks interesting: https://github.com/michaelforney/oasis

Overall, i see the big distros provide stable systems for everyday
use, even with those it's a bit hard to provide proper support for
many things, but there's room for true minimalism.. but it takes time

palemoon
http://01micko.com/wdlkmpx/palemoon-25.8.1.en-US.linux-gnueabi-armv6.tar.gz
http://01micko.com/wdlkmpx/palemoon-26.1.1.en-US.linux-gnueabi-armv7l-VFPv4.tar.gz
http://01micko.com/wdlkmpx/palemoon-27.9.1-armv7-VFPv3-cortex-A8.tar.gz

I guess palemoon-27.9.1-armv7-VFPv3-cortex-A8.tar.gz can be added to a
"universal" palemoon sfs

I think i'll buy a pi3 model b+ one of these months so i want to have
sfs's that i can use in all my machines

But of course i expect to have a frugal install in the pi3, i wonder
if that's possible

**Comment by woodenshoe-wi** [comment]
palemoon-27.9.1-armv7-VFPv3-cortex-A8 gives me a "Couldn't load XPCOM." error.

The other two work on my Pi2 and Pi3, but all three give `Illegal instruction` on my Pi1.

Although the Pi3 is much better for GUI desktop use than the Pi1 / Pi zero, I don't know if it can be considered a replacement for a "normal" PC.  It works with lightweight browsers on websites that are not too "heavy", but flash is not available for ARM and I think the mainstream browsers need at least 2GB of RAM to work properly.  (When I browse the Internet on a PC with 1GB RAM some websites use it all up and start using swap)

After working on speeding up findpkgs, I wanted to try re-writing it.  Change the format used for the package specs, add dependency handling, aliases for different package names in different distros and blacklists for packages that should never be included.  I was working on it last winter, but got too confused.  I want to try again but need to draw a flow-chart first and figure out how it has to work.

I got tired of updating the package specs, first to jessie and then to stretch.  I thought it would be much easier if I could also specify meta-packages in the package specs but that requires dependency handling.  If aliases can be supported, it might be possible to share package specs between distros.  All this is theoretical at this point, I got too confused trying to work it out.
