### ISSUE TITLE
Desktop Drive Icon Manager is buggy.

### ISSUE THREAD

**Issue by Randall-Glass** [puppylinux-woof-CE/woof-CE#1153]
I am trying to create a 64 bit xenialpup. 

The drive icons don't line up evenly.

Take the average y position, and some are higher than y position, some are lower than the y position.

Looks very unprofessional. 

A very good example of this is the latest official release of Slacko-32.

It has the very same bugs in it.

I do not like the new "Desktop Drive Icon Manager" at all. 

The old one had just the right amount of options in it.

**Comment by wdlkmpx** [comment]
The drv icon maths acrobatics have not been touched, but that issue happens when you enable the showing of partition labels, which is always enabled now.

This can be fixed by disabling it.  But i removed that option, because who wouldn't want to see partition labels?

But i see i have to bring that option back. How i hate the rox and the rox desktop and the terminal disease it has spread in the P community..

**Comment by wdlkmpx** [comment]
I added a hack to fix the alignment in the drv icons with labels (a 2nd line below the drv name).

That fixed the issue for my font size, i changed the font size in the rox options dlg and the bug appeared again...

What is this? A rox bug. The program itself is a bug.

ROX does not respect the specified XY position for the icons...  how to fix this?

**Comment by wdlkmpx** [comment]
I'll see if the latest jun7's rox source has fixed this..

Meanwhile you might want to read this:
https://github.com/puppylinux-woof-CE/woof-CE/issues/893

Hmm that's the first time i used the phrase: "Working through pain". it's only good short from Batman Gotham Knight...
https://www.youtube.com/watch?v=asEQeCfaEgE

**Comment by wdlkmpx** [comment]
rox will not show drv labels until i reimplement that option..

i can't even compile the app. perl erros and what not. eveything else compiles fine.

rox is the worst possible choice for a default file manager. the one single app that ruins a whole family of pdistros. but dpup will be free..

**Comment by mavrothal** [comment]
> How i hate the rox and the rox desktop and the terminal disease it has spread in the P community.

Pretty strong feelings... 
Hopefully they'll leave  some room for those that may still like ROX and want to use it without being forced to go through whatever you are going through now, to bypass it.
ROX/JWM are woven in Puppy almost since its inception and would be nice to remain available without a lot of hassle.

And just to avoid misunderstandings, I do think that better compatibility with other D/W managers is improving Puppylinux.

**Comment by wdlkmpx** [comment]
I'm not removing rox support, just making it less invasive and
hardcoded. It's the greatest service this project is receiving. At the
expense of own sanity.. i could just remove the whole thing without
going through all of this, and it's quite easy for me to do that.

In fact only dpup is showing all my work, and as a side effect in some
cases lxpup too, and i'm ok with that. And anybody can replicate it by
reusing the EXTRA_COMMANDS.. It's just that i have so  many code
snippets and stuff that i wrote while trying to improve the os for
myself that i had to dump some of them somewhere..

The old EM gui had options to:
- show only 1 drive: just disable hotplug support
- auto play CD/DVD: just enable the auto handler
- show labels - always showing them now.. but not anymore.......

In fact no one else has contributed so many fixes and enhancements to
the rox desktop than me. At the expense of own sanity..

And i did it because i don't want to start a new fork even though
that's the most reasonable thing to do with a project like this.. it's
not fixable without forking it completely and getting rid of the
brand.

**Comment by mavrothal** [comment]
Again, I'm not criticising or discouraging your excellent work.
I just try to make sure that your dismay for what has become Puppylinux in the course of 10+ years out of the  patchwork of 50+ people, will not drive you to totally unroot it.

Sanity is important however! So if you want to fork, strip and rebuild I'm sure you'll find many welcoming puppians, or as you would say "Pians" 😃
