### ISSUE TITLE
pmount is called when a device/media is attached

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#1163]
When a drive/usb stick is attached or a disk is inserted pmount runs and prompts the user to mount the media/device.
Not sure it it is intentional or slipped through recent pup_event/eventmanager -related changes.
I think it should be removed unless there is some reasoning that I miss.

**Comment by wdlkmpx** [comment]
That happens when HOTPLUGNOISY is enabled (auto-launch 'handler' when media plugged in).

I think it wasn't working properly before i fixed it, the autoplay cd/dvd equivalent was never implemented as an independent function.. ticking that checkbox did nothing.

Things you realise when you look at the code..

**Comment by mavrothal** [comment]
At a time was annoying because clicking on a CD/DVD the media player was coming up even for data CDs. Then was inactivated or broken. 
I admit that I find the current implementation with pmount both annoying and not doing the job, because even if indeed autoplays audio/video disks (I did not test), it comes up with any disk and other devices too. 
Which commit re-introduced the autoplay functionality?

**Comment by wdlkmpx** [comment]
This is not enabled by default, it must be peebee's default settings.

If you have ever used any other distro than puppy, you'll see that the
current behavior is basically what you get from other distros (though
it's a complex thing to setup) and Windows when the auto-handler is
enabled, a dialog appears with possible actions to take. At least
that's what i see in my brother's debian or arch install

I can make it behave as it was probably originally intended though,
But the fact that i can do it.. doesn't necessarily mean i will

hmm  back in 2014 the year i began learning bash scripting, i wrote
how broken some stuff is...
http://www.murga-linux.com/puppy/viewtopic.php?t=96347

**Comment by wdlkmpx** [comment]
Hmm reading the link i provided there's something important to say
about cddetect.

cddetect is badly broken .. and it shouldn't be used at all.

probably a new and simpler cd detect is required, just to detect audio
cds.. or maybe cdrecord has this functionality?? -prcap -inq or
something? .. but cdrecord is a cdrtools app, which is a slightly big
pkg, but it's an essential pkg that needs to be recognized as such.

hmm simple replacement app can be created with just a few lines and
using the ioctl() syscall to determine whether the inserted disc is an
cd audio.. this is what pup-volume-monitor does...

**Comment by mavrothal** [comment]
I rarely use puppy or windows extensively, but this is beyond the point.
If you want to autoplay/automount/auto-open/auto-anything should just do it. If not just show it on desktop/filemanager and let user open/mount it at will. Popping up pmount or any other app and asking  "are you sure you want to do this?" when the option is auto-something, is very vista-like 😄 
Anyway, if you could point to the relevant commit and save me some searching would be nice (in case you do not have the time/desire to take another look)

**Comment by wdlkmpx** [comment]
Then peabee will complain that usb drives are automounted when
inserted, it's not expected behavior, etc. There has to be consensus.

That option should be always disabled by default. i think @peabee has
something to say about this

**Comment by wdlkmpx** [comment]
Knowing that the rox desktop shows drive icons on the desktop itself,
this discussion is more about paradigms.

The auto-handler with dialogs doesn't look good in the rox desktop
because you can see the drives and can click on drive icons.

But this is not the case with all the others desktops, unless you have
the file manager open. That dialog may be even welcomed..

Now that i see missing icons in the jwm menu, i changed the theme  to
standardsvg  (converts .svg to png), but then i see drive icons
missing in the rox desktop. Laughable how many things are broken, but
that doesn't bother me.

Yesterday while thinking about this, i decided to read about rox, i
read this interview to the author

http://www.drobe.co.uk/article.php?id=2002&nc=29

"One of the comments that people mention about ROX is that, even
though the desktop and its applications follow the design principals
set by yourself, all the other system software follows a different
design. Is there any way that this might change at all, or will
applications need to be rewritten in order to follow the ROX design
and employ features such as drag and drop? "

**Comment by mavrothal** [comment]
All Desktop managers have the option to show drive icons on the desktop or not (as puppy) so this should not be a concern.

Regarding mounting, for me the logic is simple. 
If automount/play is selected by the user then the media just automount/autoplay regardless of their appearance on the desktop (and I fully agree that the default should be OFF *).
If  automount/play is off, then if the drives appear on the desktop, nothing happens and wait for user input. If they do not appear on the desktop, then pmount runs. ie pmount depends on the appearance of the drives on the desktop rather than autoplay setting.  (And if you want to be picky, even without desktop drive icons if your file manager supports drive mounting and has an open window at the time, pmount should stay put.)

Maybe @zigbert the resident UI-expert could have some input too.

Should I assume that you do not remember in which commit(s) this functionality was introduced and I actually will have to search for it? 😭 

\* I could see a case if we could **reliably detect original** music and video CD/DVDs, to have them auto-mounted and played in the default media player, as originally attempted.

**Comment by wdlkmpx** [comment]
There is code in drive_all to reliably detect cd/dvd disc type, i
spent many hours with cddetect dvdrw+...tool with cd drives and dvd
drives and 1 bd (briefly) using blank discs (cds/dvds/, video dvds[9],
audio cds

I briefly tested a bd, the script didn't mishaved and that was enough for me.

i added 100+ lines to drive_all to fix the cddetect stuff. It's the
same code i wrote in 2014/2015.

But i see cdrecord might provide a shorter way. We're talking about
schily's cdrecord, debian's fork is "defective"

I can do it, but peebee will complain... and davids will go nuts when
he sees all of his 40 partitions are being mounted..

This probably requires a couple changes to drive_all again

@peebee your silence means consent

**Comment by peabee** [comment]
My "silence" means that:
I'm happy with the current situation and am not looking for a change (I can live with occasional activation of pmount in exchange for autoplay of cd's and dvd's)
If a change arises and there are configuration options then I will set defaults as I think best in my builds (maybe not the defaults provided by woof-ce) - as long as users can set their desired behaviour then I see no problem.
I don't want to lose autoplay of cd's / dvd's and I certainly don't want automount of partitions unless set as now in pmount.

**Comment by woodenshoe-wi** [comment]
If peabee wants cdrecord in the common32/64 repos I can compile it.  The compiling logs don't show any errors, but I have not tested if the pets actually work properly.

**Comment by wdlkmpx** [comment]
The current code does not autoplay or automounts anything. It shows a
dialog asking you if want to play a video dvd or audio cd.

It follows what drive_all currently does, except that instead of
automounting partitions, it shows pmount.

Years ago, there was true autoplay when you clicked on the cd/dvd
icon.. and it sometimes opened the media player trying to play a data
dvd, there was no way to avoid that, now even though the code is 200%
more reliable, it shows a dialog asking if you want to play an audio
cd, video dvd, or burn something into a blank disc.

So two options make sense..
- Autoplay CD/DVD .. the same as the dialogs when you click on a cd icon
- Automount partitions .. mount all known partitions

But peebee didn't want automount of partitions to affect optical drives.

Some usb drives might have too many partitions and will cause a bit of
a shock when all of them are automounted.

When too many partitions are automounted, then it will take some time
to unmount then all, this leads to a new feature.

- Autounmount partitions

So, maybe there should be two radioboxes:
* Automount partitions
* Show drive handler/wizard/pmount

pmount has an option to automount certain drives.. but i haven't
tested it. i assume it's broken

**Comment by peabee** [comment]
Dialog is fine - no need for true autoplay
pmount automount is not broken - works fine

**Comment by wdlkmpx** [comment]
- The setting is disabled by default, enabled in peebee's builds.
- Can be easily disabled. Untick "Auto-launch handler when media plugged in"
- It's probably disabled in all default woofce builds.
