### ISSUE TITLE
Recognizing media devices .. optical input" takes too long during boot

### ISSUE THREAD

**Issue by aarf** [puppylinux-woof-CE/woof-CE#1170]
i have been using xenialpup64-7.5 mostly since it came out this is the one thing that i see as needing a look :
 "Recognizing media devices .. optical input" takes too long during boot, recent quirkys easy09 etc get past this much faster.
dont have a cd on my netbook

**Comment by aarf** [comment]
long pause in recognizing optical devices during boot that is in xenialpup isnt in upupbionic18.05 so hopefully that woofce fix has happened

**Comment by wdlkmpx** [comment]
This commit probably fixed issues: https://github.com/puppylinux-woof-CE/woof-CE/commit/dead7cc327099eadcc236780cec8ee1b0e1ddf1f#diff-6a2146b3065318a4df3931711887df79

But xenialpup 7.5 was released later. Maybe that change wasn't included. 

There have been many changes and fixes since then, so hopefully someone releases a new official version soon..
