### ISSUE TITLE
Use github package db's instead of ibiblio

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1178]
Package db's are currently held as text files on ibiblio and other versions held in woof-ce / woof-distro.
Keeping the 2 versions equivalent and consistent is causing great problems.
A possible solution for 0setup is to change /support/fix-puppy-dbs to fetch package db's from github - e.g.
`wget https://raw.githubusercontent.com/puppylinux-woof-CE/woof-CE/testing/woof-distro/x86/slackware/14.2/Packages-puppy-slacko14.2-official`
to get the slacko14.2 package db
PPM would also need changing to use github instead of ibiblio......
To form the above url you would need to extract which github branch was being used from DISTRO_SPECS and there would need to be a mapping of the github structure to the ibiblio repos.

**Comment by ninaholic** [comment]
I like the idea of not using the ibiblio list too, mainly because only active person who can update it is peebee :laughing: The "removing puppy-common" from woof-CE seemed like a nice idea, at least for Slacko 14.2 32-bit where there was only about 3 entries. I still have the slacko_updates_no_common.zip made by wdlkmpx if it's of use, I guess that is up to 01micko though.

**Comment by mavrothal** [comment]
The problem is that woof is building puppies that never made it to ibiblio even if they have the "official" stamp.
Developers that keep their puppies and pets on other servers should have PKG_DOCS_PET_REPOS and other files in woof-distro point to those servers and not ibiblio and its mirrors. 
There is no good reason to keep Packages-puppy-* in github I think

**Comment by peabee** [comment]
System builders can of course use whatever server they want for both the repos and the package-db's.....but as a minimum the package-db's for the "official" pups need to be stored on a common server accessible by a number of developers. ibiblio has proven to be not 100% suitable - github/woof-ce should be more suitable.

**Comment by mavrothal** [comment]
> System builders can of course use whatever server they want for both the repos and the package-db's

Actually this is the case for no other distro but puppy, as "other" server can come and go so an "offical" version  can simply disappear, but I guess that's what makes puppy unique. 
Anyway, the issue is that github has no mirrors so everything depends on single server. When down there are no alternatives. So if Packages-puppy-* end up in github would be wise to be regularly uploaded to ibiblio and keep ibiblio and its mirrors  as the source.

**Comment by peabee** [comment]
Also.....
I don't think fetching package db's uses the ibiblio mirroring as there is a direct url to ibiblio in DISTRO_PET_REPOS - only downloads of .pets from the repos use mirrors....so ibiblio and github are equivalent in this regard?

Using mirrors for backup purposes is a different matter - but I feel pretty sure that github is well backed up.....but a small script to copy files from github to some form of backup in the cloud (ibiblio or smokey01 or sourceforge or....) should be easy to make.... so long as you have write permission for the backup system.
