### ISSUE TITLE
microsoft buys git hub

### ISSUE THREAD

**Issue by aarf** [puppylinux-woof-CE/woof-CE#1213]
my take on the situation and links to news items
http://puppylinux.info/topic/4-men-and-11-sheep-found-in-small-car-yes-it-was-new-zealand/page/6#post-8333
any forward outlooks from vested puppy interests?

**Comment by Butterfly** [comment]
I'm a newly vested interest although I did once play around with Puppy Linux several years ago (can't remember how long ago now). I'm not sure what to think, although I do lean toward the "wait-n-see" side of the fence. I *JUST* started finally using my Github account after having it for something like getting close to 10 years. :smile:

Some links from my inbox in last couple days:

- ProgrammableWeb 2018.06.05: [The Developer Community Reacts to Microsoft's GitHub Acquisition](https://www.programmableweb.com/news/​-developer-community-reacts-to-microsofts-github-acquisition/analysis/2018/06/05)

- SlashDot 2018.06.03: [Microsoft is Said to Have Agreed to Acquire Coding Site GitHub](https://developers.slashdot.org/story/18/06/03/2042255/microsoft-is-said-to-have-agreed-to-acquire-coding-site-github)

- SlashDot 2018.06.04: [Microsoft's Interest In Buying GitHub Draws Backlash From Developers](https://developers.slashdot.org/story/18/06/04/0935200/microsofts-interest-in-buying-github-draws-backlash-from-developers)

- SlashDot 2018.06.04: [Microsoft Acquires GitHub For $7.5B](https://developers.slashdot.org/story/18/06/04/1314247/microsoft-acquires-github-for-75b); Satya Nadella says, "GitHub will remain open and independent."

- Reddit 2018.06.02: [I think it's time I publicly shared about how Microsoft...](https://www.reddit.com/r/linux/comments/8nztqi/i_think_its_time_i_publicly_shared_about_how/); DISCLAIMER: Author is not a happy camper, but there were a number of suggestions that might be useful for later.

Those were shared because there were several bookmarkable suggestions scattered throughout highly varied opinions.

This last related piece stands out to me:

- SlashDot 2018.06.03: [Microsoft Sticks With Controversial 'GVFS' Name Despite Backlash](https://tech.slashdot.org/story/18/06/03/0626246/microsoft-sticks-with-controversial-gvfs-name-despite-backlash)

That's not very... neighborly. Amicable (harmonious) types pick an idea then search the Net to see if it pops at all. If it *does* pop, how is it being used? By a competitor for almost the very same thing? Team player types go back to the chalkboard and keep scribbling away until they find something that is uniquely their own.

I've seen something like that done a few times to the Disability Self-Advocacy movement. I've seen their catch phrases that have been in prominent use for years.. become confiscated by entities that sometimes could even be seen as their opponents. \*seriously not amused\* :smile:

**Comment by aarf** [comment]
http://bkhome.org/news/201806/microsoft-buys-github.html

murga forum thread http://murga-linux.com/puppy/viewtopic.php?t=113552

**Comment by 01micko** [comment]
Trouble is we are far too invested here now. The pupplinux.com website for a start. IDK if any other (apart from sourceforge - that went proprietary awhile ago now) can host pages where anyone can edit and submit a pull request. Self hosting? By whom?

I'm NOT sticking up for github/microsoft. Hell I'd be outa here like a shot but what is the _real_ alternative? 

Let the dust settle and it may become clear.

**Comment by aarf** [comment]
perhaps you can test what you want to do  at at this mirror  https://notabug.org/aarf/woof-CE
me i dont know what needs to be able to be done

**Comment by MJLHThomassen** [comment]
Why is this an issue?

**Comment by wdlkmpx** [comment]
So this issue is resolved. We're not moving, besides github gives you probably the best  and easiest git experience.

Puppy risks being embraced, extended and extinguished
