### ISSUE TITLE
JWM theme change broken

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1222]
Between
BUILD_FROM_WOOF='master;1873fb09;2018-06-08 22:06:23 +0800' and
BUILD_FROM_WOOF='master;ec80b41b;2018-06-23 11:36:40 +0800'
something has changed to break JWM theme changing.....
![screenshot](https://user-images.githubusercontent.com/5926865/42126207-36a86268-7c7c-11e8-87e5-fc787b6bfbef.png)
see upupbb-18.05+6.iso

**Comment by ninaholic** [comment]
@peabee: Do you know which jwm version upupbb is using? I had an issue with jwm-2.3.2 https://github.com/puppylinux-woof-CE/woof-CE/pull/1211 and some of the newer themes and using jwm-2.3.6 instead fixed it

**Comment by wdlkmpx** [comment]
The error is in /root/.jwmrc 

i see this:

```
<Program label="System Update" icon="/usr/share/pixmaps/puppy/install.svg">sh -c "xmessage -title Updates_Warning -bg firebrick1 -fg white 'Updates can only be applied to
the original upupbb-18.05.iso
with md5=55e20c3e53339cf6ddbc5bc3c0c0bad1

Reverse_updates are available to generate
the original .iso from one of the updates' & defaultbrowser https://sourceforge.net/projects/zestypup/files/Upup-Bionic/updates/"</Program>
 <Separator/> 
```

I fixed the issue by editing:

/usr/share/applications/sys-update.desktop

Change this:

```
Exec=sh -c "xmessage -title Updates_Warning -bg firebrick1 -fg white 'Updates can only be applied to\nthe original upupbb-18.05.iso\nwith md5=55e20c3e53339cf6ddbc5bc3c0c0bad1\n\nReverse_updates are available to generate\nthe original .iso from one of the updates' & defaultbrowser https://sourceforge.net/projects/zestypup/files/Upup-Bionic/updates/"
```

To this:
```
Exec=sh -c "defaultbrowser https://sourceforge.net/projects/zestypup/files/Upup-Bionic/updates/"
```

then run ```fixmenus``` .. and ptheme works again...

**Comment by peabee** [comment]
Thank you - my bad - not woof-ce
upupbb has jwm-2.3.7

**Comment by wdlkmpx** [comment]
I also noticed an lxrandr bug in upupbb.. the same bug i see in dpup...

Here is my current collection of lxrandr patches:
[lxrandr-patches.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/2152225/lxrandr-patches.zip)

The one that fixes the most obvious lxrandr bug in upupbb and dpup is:
[PATCH]_lxrandr-Wait-2-seconds-before-showing-confirmation-dialog.patch

I might post that patch in the lxde sourceforge page, but it doesn't look like something they would merge, they also take months and even years to review the few patches they receive, i see 2 critical patches are still waiting to be reviewed and approved, they apply cleanly and seem to work..

**Comment by peabee** [comment]
Hi @wdlkmpx 
Do you have any plans to produce a puppy specific patched version of lxrandr?
Do the bugs also affect the slackware builds?
I'm using:
http://ponce.cc/slackware/slackware-current/packages/lxrandr-0.3.1-i486-1ponce.txz
in LxPupSc

**Comment by wdlkmpx** [comment]
I forgot to reply to this

> Hi @wdlkmpx
> Do you have any plans to produce a puppy specific patched version of lxrandr?
> Do the bugs also affect the slackware builds?
> I'm using:
> http://ponce.cc/slackware/slackware-current/packages/lxrandr-0.3.1-i486-1ponce.txz
> in LxPupSc

A couple of bugs affect all distributions & desktops, the one that needs fixing in upupbb and other pups ASAP is a severe bug that is probably caused by jwm or something, it didn't happen in an arch linux install when i asked someone to test lxrandr in front of me.. months ago. 

JWM seems to misbehave in some situations, apparently joewing doesn't use a linux distro..

So it probably doesn't happen in lxpups.. i will confirm this sometime in the future..

Well lxrandr is a barebones app with some advanced features, there are patches to make it better and more appealing... lxrandr only depends on gtk2, it can be completely rewritten as a bash/gtkdialog app, in fact i could do that, but time waits for nobody..

Excluding pcmanfm/lxpanel, all lxde apps are generic barebones apps, the fact that they are part of a desktop env. is good and bad at the same time. Good = draws attention. Bad = people think those apps are not generic and barebones....  leafpad, galculator are part of lxde, but they were not written for lxde. deadbeef was once part of lxde. I once suggested they should fork (simplify) gnome-mplayer and offered help... but you know FOSS is all about wrong decisions and huge egos everywhere (including woofce ahahaha)..

I'm kind of lazy to create an lxrandr pkg, i'm more inclined to create a pkg of the whole of lxde including my up to date gtk2 fork of engrampa (file-roller), gmrun (this app launcher creates a menu if you hit the tab key), and pup-volume-monitor .. and maybe some other gtk app

What do i mean by saying this?. an lxde pkg that should be part of all wce pups, offering a choice of DE... this probably adds about 3MB to isos (a few more if a icon theme is added), so it's a not a big deal.

Most of the big changes that happened in the last 2 years were meant to make woofce more compatible by default with the compat distro and with other DEs, specially with LXDE, there are still many things to do. 

What i want to do is make xkbconfig(manager) produce the same results as the xkb lxpanel applet,  i don't know how the lxpanel applet works and i already wasted so much time doing something else with xkbconfigmanager
