### ISSUE TITLE
pup_event_backend and /lib/modules/all-firmware

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#1226]
This looks like superfluous stuff as /lib/modules/all-firmware was "deprecated" sometime ago.

I think all the firmware pet packages have firmware in /lib/modules/all-firmware, there is code to handle this in pup_event_backend scripts, rc.sysint. etc. In other words all those pet packages are "deprecated", probably.

The pup_event_backend stuff seems to crash or something as /var/log/messages reveal..

There also many scripts that deal with 'modems' or something:

/etc/udev/rules.d/60-dialup-modem.rules
/usr/bin/wvdialshell
/usr/sbin/gen_modem_init_string
/usr/sbin/get_bluetooth_connection
/usr/sbin/get_modem_alternate_device
/usr/sbin/modemprobe
/usr/sbin/modemprobe_erase
/usr/sbin/modemtest
/usr/sbin/pmodemdiag
/usr/sbin/pupdial
/usr/sbin/pupdial_init_hotpluggable
/usr/sbin/usb_modem_special_status
/usr/sbin/usb_modeswitch_status

How many of those scripts are actually important nowadays? I see @rserwin1 was involved in the development or testing of all those scripts..

There is also the pgprs  pkg... this is small script that seems to be enough to connect, does this replace scripts in rootfs-skeleton?

**Comment by wdlkmpx** [comment]
The question is.. what happens if the /sbin/pup_event_backend_* scripts are deleted?

**Comment by rserwin1** [comment]
I would like to look into the modem issues.  I understand that analog 
dialup modems are no longer supported in linux kernel beyond 3.2.  I 
found an interesting article at:
http://www.portlandiacloudservices.com/dialup-modems-under-windows-7/

The pgprs scripts and frisbee's "telephone networks" tab support only 
mobile wireless systems.  But there are many USB wire-line modems 
available and supported by the built-in cdc-acm driver for those who 
need wire-line connectivity.  So, I would keep that support, which 
includes pupdial and most of the files with "modem" in their names.

Please hold off any modem-related deletions until I complete my 
assessment of the situation.
Thanks for alerting me to this issue.
rserwin1




wdlkmpx wrote:

**Comment by wdlkmpx** [comment]
I'm not familiar with the code so i don't know what to delete, but i did use pupdial (i think) with a usb modem to connect to a prepaid mobile broadband server  or something years ago, it worked.. I don't know the current status of the code

I was aware about the big modem firmwares in the Wary days, i never used those old 56k dialup modems.. when i got internet at home it was already ADSL. I think 56k dialup just disappears completely in many places. 

Indeed, 56k is still being used in some places, this article shows the knowledge to configure 56k dialup modems is getting lost...
https://www.digitaltrends.com/cool-tech/aol-dial-up-a-relic-of-the-past/

In many places of the world companies just turn off dialup internet
https://www.bbc.co.uk/news/technology-23877364

I read dialup internet is slow as hell, not even possible to navigate with it, so i think it will be completely replaced by 3G, 4G, 5G... and wimax?

https://www.tutorialspoint.com/wimax/what_is_wimax.htm

# CONFIG_WIMAX is not set

I'm mostly ignorant in this subject, what else can i say. Today was a really sad day for football

**Comment by wdlkmpx** [comment]
I think i have one of those old modems, it's a CNR card. Years ago i was given a bunch of old pc parts in exchange for some old coins. I still use the hard drives, ethernet cards and mainboards.

I also have  some ISA audio cards. Stuff that i never got to use.... I get that some people in remote rural areas are forced to use dialup, but what i don't understand is why someone would want to use a floppy drive/disk nowadays, aside from technicians that want to revive some old mainboard with a (partially) damaged bios of course.

I'm sure even the poorest of people avoid floppy disks nowadays. Cd drives, old hard drives,  old usb drives... they are all reliable to some extent.

This takes back in time when i used to use floppy disks to store some pages i downloaded.  The problem with floppy disks is that data gets corrupted in a matter of days... even in their day floppy disks were utterly useless... the worst product of capitalism, garbage in all senses of the word. I read even zip drives were very "temperamental". A failed technology.

**Comment by Butterfly** [comment]
> Indeed, 56k is still being used in some places

Talking Rock, Pickens County, North Georgia, by a very abject poverty level individual. I had a connection issue a while back. While talking to the provider's tech folks, my impression was that the server serving my dialup Internet was lost, gathering dust in a *forgotten* corner somewhere. They admitted they forget to check it to make sure it's still operating properly.

> I get that some people in remote rural areas are forced to use dialup, but what i don't understand is why someone would want to use a floppy drive/disk nowadays, aside from technicians that want to revive some old mainboard with a (partially) damaged bios of course.

Real World usage case: Couple months ago, I bought a book, "Introduction to Programming Concepts and Methods With Ada (Mcgraw-Hill Series in Computer Science)". They lured me in with a promise of both "a book AND a disk". *score!*

Year of copyright went straight over my head. Book got here a few days later. I open it up....

And laughed and laughed. Copyright date was 1990's so it was a *floppy drive disk* that was included. Brought back fond memories of storing computer class assignments from about that same time period. :smile:

To put this on topic... I'm trying to get a Puppy instance running here so I can lurk along with. My recently purchased disk is failing for some reason already. If I can get that operational, I *am* on 56k dialup... (54.6 if I keep shutting it off and redialing 'til it gets that *high*)... for whatever that might be worth... :smile: !

**Comment by wdlkmpx** [comment]
What OS and version are you using to connect to the internet?

I think wary5 and retro precise puppy were the last versions to
include drivers and firmware for old analog dialup modems. You might
want to try wary5 and retro precise puppy 5.7.1. Although those old
puppies are the reason i had to edit everything to fix stuff for me

It might be possible to support those 'analog dialup modems' in woofce
puppies. Analog is the key, as rerwin said.

With slacko 14.0 + k3.2.xxx, but i think patches are needed and stuff
only rerwin knows about

And configuring those modems, that knowledge is getting lost in the
abyss of distant memory, which also reminds of geocities
http://www.oocities.org/ghikar/Introduction/vpm_page4.html

**Comment by rserwin1** [comment]
The other last puppies to support analog modems are precise-retro and 
super lucid 2.  I do not know whether the drivers were recompiled for 
any of slacko's kernels.  Such support seems to have stopped after 
kernel 3.2.x.

I advocate dropping the firmware packages for the analog modems.

In my testing with xenial, bionic and stretch puppies, I found that 
stretch is missing the modem-stats-1.0.1 package, which should be in the 
standard woofCE configuration, to support pupdial and possibly pgprs.

The pet packages pmodemdiag and 60-dialup-modem.rules can be deleted 
from the repos.

**Comment by wdlkmpx** [comment]
It was my fault, i am the one to blame. But i see this code in frisbee:

```
 elif [ "$(which microcom 2>/dev/null)" ];then
  [ -f "/var/lock/LCK..${1##*/}" ] \
   &&rm -f "/var/lock/LCK..${1##*/}"
  echo -e "ATZ\n" | microcom -t 200 $1 > $ANSWERFILE 2>/dev/null
 fi
```

dpup has busybox microcom, that's the solution, theoretically. 

Well, it's technically possible to support the old stuff again, everything can be in an sfs. Recently the 3.2 kernel config was deleted, it can be restored. Although someone already compiled the kernel, i hope it was in slacko 14.0... only the kernel sources sfs is missing.

A new slacko14.0 iso + devx + k3.2.xxx sources. Then rerwin patches and compiles kernel
modules, adds firmware, etc... everything needed to support analog modems goes to a specialized SFS, but that probably won't happen. There's no need to add anything to the git repo.

I will delete pmodemdiag and 60-dialup...rules.

But there's still a problem.. what is the logic behind /lib/modules/all-firmware ? 

In the past there were many firmware files in the git repo, they still are in the git history, adding many megabytes to the overall size of the repo. There was an effort to move out all the firmware files as pet pkgs.

I think all firmware pet packages (most are not added to the default builds) install firmware to /lib/modules/all-firmware. There are scripts that process stuff in /lib/modules/all-firmware

Why not /lib/firmware ?

**Comment by rserwin1** [comment]
All-firmware was intended for loading firmware and other files only when 
an installation needs them.  That included initialization scripts for 
dialup modems and consisted of tarballs containing those files.  Later, 
the files were placed in directories because they ended up in squash 
files, so did not need to be compressed.

Now that we provide the real firmware in a separate tarball or house 
them in the fdrv SFS file, the all-firmware copies are no longer 
needed.  But there was one case where the all-firmware tarball/directory 
was needed -- to install the (wifi) b43-legacy real firmware only if 
needed, because having both in /lib/firmware caused 'legacy' to prevent 
the b43 firmware from being found.  If we decommit from b43-legacy, the 
issue goes away.  Or it can be provided as a pet package.

BTW, if you keep analog modem support in an SFS file, 60-dialup...rules 
needs to be included.  Which 3.2.x kernels are you considering for 
including analog modem support?

**Comment by peabee** [comment]
Hi Richard @rserwin1 

> The pet packages pmodemdiag and 60-dialup-modem.rules can be deleted
> from the repos.

I'm unable to locate these .pets - any clues as to where you think they are??

**Comment by rserwin1** [comment]
I think they were never put into official pets, just always part of the skeleton.  So they can be deleted from the woofCE rootfs/skeleton directories.

**Comment by wdlkmpx** [comment]
There's no objections. The golden rule here is silence means consent..

I've been busy but i'll build a new slacko 14.0 (5.8) iso + devx + k3.2.102 sources sfs soon, or maybe someone else can do it...

A few days ago i edited all the rootfs scripts that call modem-stats, i added microcom as a fallback... i just pushed the changes to testing
 woof-code/rootfs-skeleton/usr/sbin/gen_modem_init_string
 woof-code/rootfs-skeleton/usr/sbin/modemtest
 woof-code/rootfs-skeleton/usr/sbin/pupdial_init_hotpluggable

commit https://github.com/puppylinux-woof-CE/woof-CE/commit/8bc461a5c12fafb2c5db2e2d278adf25f7e1ca52

Now that you're moving scripts, you can discard those changes if you wish. I recommend pushing all the changes in a single commit, that's way less work. I can also lend a helping hand, people can send me up-to-date files or patches  and instruct me what to do..

There's still the /lib/modules/all-firmware issue. All firmware should be in /lib/firmware, but in /lib/modules/all-firmware i see config files, etc..

So there should be a way to keep all firmware in /lib/firmware, and hacks and stuff somewhere else ... that means that all firmware pet packages should be sent to the darkness and new firmware pet packages and stuff should be created.. erase the past to learn from the future... is this reasonable?

**Comment by ninaholic** [comment]
> I've been busy but i'll build a new slacko 14.0 (5.8) iso + devx + k3.2.102 sources sfs soon, or maybe someone else can do it...

Hi wdlkmpx,

When I try to build slacko 14.0/5.8 with testing branch it gets stuck on "boost" in ./2createpackages. I'll try again with master branch in a bit.

![screenshot](https://user-images.githubusercontent.com/5408521/43091748-f2477064-8e78-11e8-9825-7bc01e8490fb.png)

**Comment by wdlkmpx** [comment]
@ninaholic the issue is fixed in https://github.com/puppylinux-woof-CE/woof-CE/commit/595058075f34a036e1e56526cb7ec92534e98741

**Comment by Butterfly** [comment]
Hi! I'm still here. #Life keeps happening and takes focus. :smile:

Early on, I saw the Wary (?) reference above so I downloaded that, *too*. You all are my first ISO burnt to mini-disk. I had *no* idea that's what goes on there.

It booted, AND it recognized "a" dialup modem. I have two, a USB and a PCI slot. Connect had a bunch of chatter that said something about AGP which I don't ever remember messing with in all these years. That's as far as I got because I didn't have phone number to test it at that second.

I've got some chores then I'll be back to test that AND catch up to what you all are saying here. I, as one user, understand that older hardware is getting phased out starting at the top/base with the Linux kernel.

BUT... If I'm able to dial out straight out of the box later, I'll do what I can to help make sure that knowledge of Puppy Wary 5.5's existence doesn't stop at my keyboard. #ThankYou all for the work you're doing! I'm just glad I'm not you when you have to make those tough calls about what stays and goes each time k/t limited Human Developer resources. :smile:

**Comment by rserwin1** [comment]
I am working on "pupdial 2.0", which fixes some misbehavior and polishes 
the windows and splash messages.  Note that it supports both analog and 
mobile dialup modems, so should be a woofCE package.  Putting everything 
else in a separate SFS file seems like a good idea.

Note that the "all firmware" related to analog modems is not real 
firmware, but is startup scripts and module.d config files.  I think 
Barry eliminated the need for them with his rewrite in the precise era.

I am waiting for the new (k3.2.102?) ISO so that I can try building 
drivers for it.  If that turns out to be possible, I plan on collecting 
the rest of things related to dialup modems, to keep what is usable.  
And to work around the absence of the all-firmware modem 
packages/directories.

I am willing to see how far we can get with the analog modems, but 
mainly want to be sure dialup support is healthy.

BTW, the driver sources I have may not be what Barry used for the 
Precise drivers.  Does anyone know where the source files are that Barry 
used for Precise and kernel 3.2.48.?  They may contain updates for the 
3.x kernels.

**Comment by wdlkmpx** [comment]
I think those files are gone.. but i can attempt to patch the drivers
to make them compile with k3.2.102

Kernel 3.2.102 was released on jun 1, 2018... the last release for the
LTS kernel 3.2.

What is needed that should be provided as download links to get things started:
1) iso + 3.2.102 sources sfs
2) driver sources
3) patch the sources
4) add stuff

I think @ninaholic already compiled k3.2.102 and might want to provide
1) .. or i'll have to do that next week.

Rerwin provides 2) and can probably attempt 3) .. i can also attempt 3)
Rerwin does 4)

This can lead to patched driver/kernel sources (kernel patches go to
the kernel-kit). This may end in failure ..

Then a new iso will have to be created to continue

**Comment by ninaholic** [comment]
> I think @ninaholic already compiled k3.2.102 and might want to provide 1) .. or i'll have to do that next week.

Hi wdlkmpx,

Yes I have made 3.2.102 twice in slacko 5.8 but it never connects to wireless, maybe something related to wireless is missing in the config? Might be better to try to build 3.2.102 on your machine and I can test if yours instead if it works for you, or I can try to debug it later. 

I found a few issues with 5.8CE:
- the slackware gparted is missing a library for libparted so it doesn't execute
- grub4dos 0.9.3 has 3 menu entries and missing icons on the menu.lst dialog (fixed in 0.9.2.2)
- when I move my cursor out of the inkscapelite window the icons disappear
- kernel_headers is now in the main iso instead of the devx? is that right? :D 
- maybe something else but I forgot...

If legacy modem/phone support and this all ends up being too much work I have no issue with dropping slackware 14.0 and 14.1 from "testing" branch again to make it easier 💣 😄

**Comment by peabee** [comment]
The version in noarch for woof-ce should have a different name....
Shinobar's changes should be applied to the woof-ce version??

**Comment by wdlkmpx** [comment]
I compiled kernel 3.2.87 twice. I thought i was compiling the correct
version but i wan't. @rserwin1 i'll try to patch the drivers for this
kernel version first... where can i find the drivers sources?

**Comment by rserwin1** [comment]
I reviewed the "insert" build instructions and found them to me mostly obsolete, referring to the all-firmware tarballs.  The firmware_linux_module pets should handle the "user land" stuff.  And the Intel parts assume an older version than we are using -- Barry did not include them in precise.  So disregard them, for now.

**Comment by wdlkmpx** [comment]
Ok this is for @rserwin1 so he can continue with his work.

Here is a slacko ISO with kernel 3.2.102 + devx + kernel sources sfs
The firmware in the zdrv is from firmware-140621-cut.tar.bz2 ..

http://01micko.com/wdlkmpx/slacko_retro/slacko-5.8.1-g4dos.iso
md5: 0716faca353d9460364ad120f9a986fd

http://01micko.com/wdlkmpx/slacko_retro/devx_slacko_5.8.1.sfs
md5: 566e7be297af39187b5e076ac9e2d837

http://01micko.com/wdlkmpx/slacko_retro/kernel_sources-3.2.102-slacko.sfs
md5: 20029a7abc5767da210e55f692a27ea0

Bonus:
http://01micko.com/wdlkmpx/slacko_retro/kernel_headers-3.2.102-slacko-i686.pet

I forgot to add a -test suffix, but the files are already uploaded.

I don't know if something is missing but everything can be compiled i guess..

The included firefox doesn't connect to github and other sites..

There may be some issues here and there. This kind of stuff should
probably be discussed in a forum thread or something.. it's all dead..

**Comment by wdlkmpx** [comment]
rerwin do you know the current status of pdiag?

I'm thinking of moving /tmp/sns* files to /tmp/apps/sns/ and i see
that some other apps use some of the SNS files.. pmodemdiag, pdiag...
this is not in rootfs-skeleton, it should be integrated asap.. i can
do that, but i figured out   someone else can do that too

modem-stats... this can be a script that emulates the basic
functionality... just for retro compat... just in case someone wants
to use an old script relying on that old app.

A recent example:
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-skeleton/sbin/cddetect

That way more and more binaries are some noarch pkgs are removed from
the wce pkg databases.. there are gtk apps (ssh-gui, gtklp,
lxrandr,etc) that can be easily replaced by gtkdialog scripts that can
do exactly the same , and so on, it just takes some time to write a
suitable replacement, and time waits for nobody

**Comment by wdlkmpx** [comment]
There is a problem, the iso i uploaded doesn't have the kernel i
compiled, i actually have ninaholic's kernel with the same name in
local-repositories/huge_kernels and forgot it was there... when i
built the iso, it didn't download the kernel.

The kernel i compiled is i486.. the kernel in the iso is i686.

Or maybe the kernel should be i686, i decided to make it i486 for some reason

the kernel-kit needs more work.. i want to add a -revision suffix for
the tarball without changing the kernel release name (uname -r)

I'll update a few things and produce a new iso with the correct
kernel, or maybe ninaholic will be willing the build and upload the
iso? Only the iso...

The included firefox is too old, i can't use gmail, and it doesn't
connect to many sites..  i wonder why. I'm planning to use this
browser instead:
ftp://contrib:get@ftp.palemoon.org/SSE-Linux/

I don't know what to do..

**Comment by wdlkmpx** [comment]
@rserwin1 i forgot that you can swap kernels

This is the correct kernel
http://01micko.com/wdlkmpx/slacko_retro/huge-3.2.102-slacko.tar.bz2

Until a new iso is produced with important updates for slacko retro..

This is the pdiag pet pkg that must be integrated directly into rootfs-skeleton
http://distro.ibiblio.org/puppylinux/pet_packages-noarch/pdiag-20130207.pet

I'll delete pmodemdiag ..

Yes i'm reorganizing apps, some apps just dump everything in /tmp,
but i wonder if the right place should be $HOME/tmp

But then some apps like pclock and ptiming write to disk too many times,
redirecting apps' tmp files to a tmpfs mountpoint is the right thing to do

I also want to make it easier to use non-root users and move spot to
/home/spot..
that certainly requires almost a dictatorial control over the whole of
woofce and many puppy pkgs and fortunately many of them are already in
rootfs-packages

**Comment by rserwin1** [comment]
I will try swapping kernels.

The pdiag package you mention is obsolete.  I have a version dated 
20170325 that I never submitted for upload.  I don't have a forum thread 
for it, so probably should start one.  Anyway, I have updated that 
package to 20171205, which has the changes for my revised networking 
done last year.

What to do with it.  It could be its own package in woofCE, or simply be 
uploaded to the noarch repo, maybe without a thread.  Or both.  What do 
you think?

BTW, I got the pctel modem driver to build, but may not be able to build 
it for tahrpup.

**Comment by rserwin1** [comment]
I need help with swapping to the correct kernel.  I have never done 
that.  When I try the change_kernels command, the following message pops up:

Error message:
Unfortunately this does not work with older puppy installs.

I have the downloaded expanded to the vmlinuz and kernel_modules_sfs... 
files, but do not know what to do with them. The vmlinuz seems obvious 
-- just substitute -- but the other is not.  Now what?

**Comment by wdlkmpx** [comment]
I think it's good to create a topic for it, i personally don't read
the forum as much as i should... but i reckon there's some info i must
gather, but it's good to maintain a package as a woofce rootfs-package
and as an independent package.

I don't know, but the pet repos lack a maintainer. and that maintainer
has to keep an eye on the forum, an eye of the tiger, you must fight
just to keep the pets alive

So the git repo is becoming the place to store scripts and stuff.. i
forked some apps, now they're in rootfs-skeleton, i'm just too lazy to
create more rootfs-packages, and some of the apps i added have become
too woofce-specific..

There is danger in adding a package to rootfs-packages.. pdiag will be
edited by me to change some paths.. a git repo is different than a pet
repo.

Now.. change_kernels needs some fixing... in the future..

huge-3.2.102-slacko.tar.bz2

vmlinuz-3.2.102-slacko -> vmlinuz
kernel-modules.sfs-3.2.102-slacko -> zdrv_slacko_5.8.1.sfs

When you want to replace a kernel, just replace 'vmlinuz' and the
'zdrv_*' ... it's the kernel modules sfs.

**Comment by rserwin1** [comment]
Re pdiag:
I think it has outlived its usefulness because it is for troubleshooting 
user problems, which seem to have diminished.  The most useful logs are 
now captured by sys-info.  So, pdiag should be kept in the repo for PPM 
but not be part of woofCE.  I will handle update as needed, although I 
depend on you or peebee to upload them to ibiblio.  I will start a 
thread for it.

Re modems and slacko-5.8.1:
I have built hsfmodem, so seem to have the major analog modems covered.  
However, I have encountered 2 showstoppers in 5.8.1!

I run in an ext4 save file.  When copying some files into it, they abort 
claiming no space left on device, but there is no indication of which 
device.  The tray shows 151MB free in a 512 MB savefile. Rebooting 
fails, also claiming "no space".

To recover, I created a new save file (pfix=ram), copied my development 
folder from the "dead" savefile into the new one and saved the new file 
as I rebooted.  After selecting the new savefile during boot-up, the 
desktop show the windows seen on a pfix=ram boot-up, although the 
/etc/rc.d/PUPSTATE file lists the intended save file!  I saw this 
behavior on A xenialpup installation a while ago but rebooted out of it, 
which wiped out the content of the original pupsave!  Now I know not to 
do that, so immediately held down the power switch, to preserve. the 
savefile.

I feel that both of these bugs pertain to woofCE.  The failure to load 
the pupsave is probably an initialization bug, but the "no space" issue 
could be ext4 or slacko related, I suspect.

How should I go about reporting this officially?  In the Bugs sub-forum 
or as an "issue" in woofCE github?

**Comment by rserwin1** [comment]
Re save file issue:
I see now that the new save file actually does not have the copied 
development folder, meaning the added content never got saved or that 
the empty environment overwrote the save folder despite my shutdown.  I 
suspect that the new folder never got written to the save file.

**Comment by woodenshoe-wi** [comment]
> I run in an ext4 save file. When copying some files into it, they abort claiming no space left on device, but there is no indication of which device. The tray shows 151MB free in a 512 MB savefile. Rebooting fails, also claiming "no space". 

Could you be running out of inodes?  Source code often has lots of small files that don't take up much space but each one uses up one inode.

**Comment by wdlkmpx** [comment]
https://www.ctrl.blog/entry/how-to-all-out-of-inodes

Maybe you'll find the answer if you look in /initrd/tmp/bootinit.log
or /var/log/messages.. or dmesg.. when a bad filesystem is mounted the
kernel probably writes something to the syslog

What happens if you add pfix=fsck to the kernel params ?

But now i'm aware of the problem, i'm using savefolders lately though.. hmm

In woofce it's easier to troubleshoot stuff, in theory. There are more
verbose logs and some hidden stuff: 'reboot debug  shell' 'reboot
shell' .. many scripts have debug code at the beginning (commented
out), so it's easier to debug

You're raising the most important issue.. the pet repos.... well,
communication is somewhat broken and i don't have much to say about
it... but you can always say something here and it will be heard and
an action will be taken..

Something happened a few months ago, in order to continue development,
the woofce pkgs dbs are now maintained in the git repo, so that a
massive cleanup could happen, right now the pet pkgs docs (or dbs) are
not the same as the ones found on ibiblio.

Right now the focus is in adding some changes that were planned 5
years ago but that could not happen, because puppy is puppy you
know...

My vision is this: there's a temporary lead dev that does most of the
heavy work to update and fix the whole system, there's other devs who
help fixing stuff and adapt their stuff to the latest changes, there's
builders that provide isos so that testing is continuous... this is
not how things work in the forum, where basically everyone expects
stuff to just work, the changes i make are not simple changes, i make
structural changes, but that in fact are small changes just to get
some basic stuff to work.. and as a side effect the system becomes
faster and faster

Once the lead dev gets tired or needs money and has to withdraw from
the competition to do important stuff, that's when a new era begins...

So yes, you can create a topic for pdiag, i'll be checking it every
once in a while and @peabee will upload the updated pet pkgs, but i
want to say something but i think i should  not say it again because i
already said it many times ... but i somehow feel the need to say it
again, and i

**Comment by wdlkmpx** [comment]
@rserwin1 i think i have an answer for the issue you reported...

It's because the savefile filesystem ran out of inodes..

I created a small savefile.. 256MB and ran this code:

# mkdir exploit
# cd exploit
# for ((i=0; i<100000; i++)) ; do echo -n > file${i} ; done
bash: file65245: No space left on device
bash: file65246: No space left on device
..
bash: file99954: No space left on device
bash: file99955: No space left on device

It was unable to create 34712+ files

So i think savefiles are not good for compiling.. you should never
compile in /root, /opt or any other directory that is being count as
part of the current 'session'.

I guess this solves the mystery, however you're right, there's still
240MB free..

The personal storage can be.. the pdrv (PDEV1, boot drive) -
savefolders/savepartitions, the savefile or ram (first boot, pfix=ram)

In pupmode 13 (pmedia=xxxflash) there's a complication, ram is the top
layer but the personal storage is either the pdrv (pdev1) or the
savefile

This 'personal storage' is where everything is being written in the
current session (unless you're working in a directory where a drive
was mounted or /tmp)

The tray icon doesn't tell you what is currently the 'personal
storage', but i guess that's easy to fix, it's a compiled app...

In this case it's the savefile, you can create a very limited number
of files before the FS becomes unusable..

After rebooting, i see everything's fine, there are no errors mounting
the savefile but:

(in /root dir)
# touch b
# touch c
touch: cannot touch 'c': No space left on device
#

I created a file, then i tried to create another one and there was no
space left on device (savefile), even though it's not full according
to the tray icon, it's just unusable..

**Comment by woodenshoe-wi** [comment]
If repartitioning/reformatting is not an option to make a "working area" for compiling, I have been able to compile a lot of things in the past using a 4GiB (minus a little bit so it wouldn't hit the FAT file size limit) ext2 image file that I would open to do my compiling inside and then unmount when I was done.

It was not a "savefile", I used a much smaller savefile, it just had the stuff I was compiling in it.  The only things that I found were too big were xorg and woof builds.

Maybe it would be helpful if the code that checks for running out of space in the savefile would also check for running out of inodes.

**Comment by rserwin1** [comment]
wdlkmpx wrote:
> @rserwin1 i think i have an answer for the issue you reported...
>
> It's because the savefile filesystem ran out of inodes..
>
Thanks for checking that out.  Two of the linuxant (HSF, HCF) firmware 
packages contain a /etc/h*fmodem/nvm directory that has a ton of small 
files.  Using 'ls -R firmware... | wc -l', I find the ...hsfmodem 
package has 2156 files (inodes?) and the the hcfpcimodem one has 4522!  
I have several copies of each in the pupsave file. The total number of 
files in the root directory of the pupsave I cannot boot into is 39532!  
The new pupsave where I copied some of the content is at 22900.

**Comment by rserwin1** [comment]
Regarding analog modem drivers and related "all-firmware", I have built 
drivers for 4 analog modem types: ESS PCTel, Lucent/Agere/LSI MARS and 
Conexant HSF modems.  I avoid the need for any "all-firmware" 
directories by including all supporting scripts, udev rules and an 
executable in a .pet package I call 'pupdial_softmodem'.  It supports 
all of those modems.

As luck would have it, I found updates for the Lucent driver for up to 
kernel 3.16 and built that driver for the TharPup (32) kernel, 3.14.56.  
For that, only the existing martian_modem firmware package is needed.

The driver packages and updated source tarballs are here:

http://www.mediafire.com/folder/7d84to4v89krx/Driver_Modules_-_Kernel_3.x

I named the supporting package as I did because it applies almost-only 
to pupdial, but can be installed without pupdial to support faxing 
(which I have not tried).

Also, I updated pupdial (2.0.1) to improve performance with the Lucent 
driver and will post it to the forum and submt a pull request soon.

Can the slacko-5.8.1 kernel (3.2.102) be used in other puppies?
What is the latest upup that could use that kernel or the tahrpup kernel?

**Comment by wdlkmpx** [comment]
The 3.2.102 kernel can be compiled in tahrpup, i think newer wce pups will not compile it... the slacko k3.2.102 might be usable in tahrpup though, but not in newer upups/dpups... as far as i can tell

The tahrpup kernel can be used in newer pups i think. The last 3.14 revision is 3.14.79

I liked EOL'd kernels, the hype is gone and one can focus on adding support for many things that require compiling kernel modules, specially network modules, i noticed my 2 old pci wireless adapters require some proprietary driver or a win xp driver (ndiswrapper), looking at the vendor page i see sources for kernel modules are provided (for newer models).

A proper handling of manually compiled modules has not been devised yet, but they can be added in a single sfs that is found at boot... adrv_slacko_5.8.1.sfs or ydrv_slacko_5.8.1.sfs or fdrv_slacko_5.8.1.sfs (the kernel-kit can generate the fdrv..)

Remasterization can also happen in the adrv or ydrv .. without touching the main sfs

I'll provide a new slacko14 iso soon..

**Comment by wdlkmpx** [comment]
This issue is (mostly) fixed, stuff was deleted and simplified. What to do next may be discussed in a new issue..
