### ISSUE TITLE
audio cd autoplay problem

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1228]
Autoplay of audio cds seems to have disappeared somewhere between:

BUILD_FROM_WOOF='master;ec80b41b;2018-06-23 11:36:40 +0800'
and
BUILD_FROM_WOOF='master;dbbc710f;2018-06-17 12:47:13 +0800'

Autoplay of video dvds continues to work as expected.
Manual play of audio cds via pmusic from the menu also works.

**Comment by wdlkmpx** [comment]
ISO file?

**Comment by peabee** [comment]
https://my.pcloud.com/publink/show?code=XZPWg27ZrG0azUYODgR44bK2GWrlSV5cgQYX

md5=645317330e18232e12c017019893141d  LxPupSc-18.06+1M-k64.iso

**Comment by wdlkmpx** [comment]
does this fix the the issue? 
[adrv_LxPupSc_18.06.sfs_fake.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/2224783/adrv_LxPupSc_18.06.sfs_fake.zip)

**Comment by peabee** [comment]
Yes - thanks - that reinstates autoplay of audio cds.....

**Comment by peabee** [comment]
@wdlkmpx 
I need some more help please - this time with a 64-bit build - lxpupsc64-18.06+2
https://my.pcloud.com/publink/show?code=XZAUa27Zxr1vpwAy485IfODquP9btbV4WoHy
I must be doing something very wrong in the build as both cds and dvds do not appear at all in pcmanfm when inserted and only appear on the jwm desktop after I run blkid in a terminal.....
I suspect something is wrong in my build in providing the 64-bit versions of the pup_event binaries but I've no idea what it can be.
HELP! please....thanks
p.s. build has the fix provided above.

**Comment by wdlkmpx** [comment]
I haven't downloaded the iso yet, but this is what i think

0) There are no pup_event binaries, only scripts. the p-v-m is not part of pup_event.

1) pcmanfm: pup-volume-monitor probably needs recompiling or there may be a conflict between pup-volume-monitor and the gvfs volume monitor daemon.. gio stuff

2) rox: udev is not reporting uevents for optical discs... a uevent is triggered by blkid's activity.. which you ran manually from the console.

This sfs should fix 2)
[adrv.sfs_fake.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/2234505/adrv.sfs_fake.zip)

The compat distro eudev/udev is not fully compatible with puppy, but it somehow works with a little help from pup_event_frontend_d

You might want to attach a zip containing /tmp/xerrs.log, /tmp/bootsysinit.log, /var/log /messages.. i'll check it once i wake up or when i have time

**Comment by peabee** [comment]
@wdlkmpx 
Thanks - adrv.sfs contents certainly help - with it both cds and dvds are detected and play...
pdiag output uploaded-
https://my.pcloud.com/publink/show?code=XZF7v27Ztvd9LCAOmMbuHEO5ErW9o8n5zYpX

p-v-m in the 64-bit build is older than the 32-bit:
pup-volume-monitor-0.1.15-1-x86_64-slacko6.pet
pup-volume-monitor-0.1.17-1-i686-sc.pet

so looks like a rebuild is indeed needed....neither cd nor dvd appear in the pcmanfm device list with the old p-v-m so they can't be ejected under LXDE - they can under JWM.

Many thanks for your help. Cheers peebee.

**Comment by peabee** [comment]
@wdlkmpx 
I have made a new 64-bit pet version of p-v-m-0.1.17...
https://my.pcloud.com/publink/show?code=XZi2v27ZCVWd6zUSW5mJGdDFw5SezRaWnR6k
however
this causes pcmanfm to crash completely (produces no errors when run in terminal or in dmesg)
and in bootsysinit.log I see:
(pup-volume-monitor:6199): GLib-GObject-WARNING **: 10:12:56.960: specified instance size for type 'PupServerMonitor' is smaller than the parent type's 'PupVMMonitor' instance size
(pup-volume-monitor:6199): GLib-CRITICAL **: 10:12:56.961: g_once_init_leave: assertion 'result != 0' failed

Any ideas?? Thanks!

**Comment by wdlkmpx** [comment]
So commit 6cfc25c3bb7412eaca4c881e2a3d9733309f9d27 (in master) was meant to close this, but instead it closed #1128

There seems to be a problem with pvm, but i'll look into it later.

A few days ago i was testing stuff to fix the issue you reported and i realized there was an issue with the rox desktop when a blank cd was inserted, and i ended up adding many changes

Many new changes to the core scripts are now in testing. Yesterday i spent the whole day coding and testing, building a few isos and realizing that some changes were not there, adding missing changes, reverting a few changes that seemed to be ok at first glance, etc.

So today i think i'll build 2 more isos and see if something is missing or broken.

My advice is that you build isos from testing and privately share them with your users or something until testing is merged to master, what else can i say, testing is now too much ahead of master and i'm having trouble maintaing serveral branches and i'll probably have to stop contributing until 2019, but i'll be listening nonetheless

One of my ideas was to rewrite pvm, using all the kwnoledge i gained by editing the pup_event_frontend stuff.. make a generic app that doesn't depend on udev and with a tiny portion using glib.. the volume monitor plugin or something, i hate glib and the time i have to spend polluting my already damaged mind learning how to fix glib stuff in apps... however i enjoyed writing my own C irc bot that compiled fine on my android tablet (to download a lot of files from xdcc bots from rizon.. that was months ago)

**Comment by peabee** [comment]
I've raised an issue on the p-v-m github repository for 64-bit builds....
I don't know of any mechanism to "share with my users privately"!!!
Please advise when you think "testing" is in a fit state to do reliable builds and I'll switch back to "testing" for LxPupSc and LxPupSc64.
UpupBB will stay on "Master" for the foreseeable.
I feel that a big divergence between master and testing may cause confusion....I want to make reliable builds which also can also act as test vehicles for new initiatives....

**Comment by wdlkmpx** [comment]
The divergence in code is huge, they called it "under the hood" or
something like that.  Leprechaun in the hood

Well, what's been happening for a long time now is basically a rewrite
of everything

It only requires that people use the default stuff, if you use custom
base scripts, you will find unpleasant surprises.. that's why i said
that if people want to merge stuff, do it or adapt to the changes

Not exactly divergence, what i do is mostly replace old puppy apps
with scripts (some of them are broken), etc. Fix broken stuff (e.g.:
full install ramdisk to fsck), basically rewriting whole scripts. No
one should notice those "under the hood" changes. In fact if someone
says that nothing has changed in over a year.. it just means i'm doing
a good job hiding what i do. Or that people never look at the code

I try to keep the same behavior, but in the end what i do will make it
really easy to add a new compat distro with a different architecture
or libc... it will also let me use the woofce base in other distros
without adding binaries.. e.g. cddetect calls /lib/udev/cdrom_id

I also added a number of divergent changes but no one will notice them
because i usually add a hack to avoid breaking old stuff, adding a bit
of complexity but that's the price to pay.

Right now, if someone is using fido or have somehow edited the
inittab... an upgrade will break the shutdown process, but i'll add
code to /sbin/poweroff to 'handle variations in /etc/inittab'.. about
50 lines.

Having said that, i have many ideas and dont know if i'll be able to
apply them this year, i want to add 'plogin' and use an unprivileged
user, i mean a human, abstract or feline user, not a dog
