### ISSUE TITLE
Grub4DOS Error 13, wee 13> due to 64-bit Ext4 

### ISSUE THREAD

**Issue by bigpup1** [puppylinux-woof-CE/woof-CE#1263]
When trying to use Grub4DOS with newer systems, with 64-bit Ext4 partitions, typically created when another newer Linux distro is installed.
Grub4dos boot loader can not boot the other Linux operating system.
Here is a way to fix this that needs to get into Puppy.
This topic in the Puppy forum gives info on how to correct this.
http://murga-linux.com/puppy/viewtopic.php?t=111376

**Comment by wdlkmpx** [comment]
woofce builds are fixed since https://github.com/puppylinux-woof-CE/woof-CE/commit/2fb37fe07e819e91dbf505648bb38ac5969f5145#diff-2d682c7a36dcb206592bb85534365518

But grub4dosconfig and other similar apps should check the fs, warn the user about 'incompatibility issues' and abort before installing wee and other wee mbrs. this is something that shinobar should fix, i usually end up forking or rewrting all of his apps .. when i want to fix something

syslinux doesn't support the ext4  64-bit feature as far as i know

**Comment by bigpup1** [comment]
shinobar recently did an update to Grub4dos Config on 18 sept.
So, he seems to be back working on it.
I posted to the Grub4dos Config topic to tell him about this issue.
Will see if he gives response. 
http://www.murga-linux.com/puppy/viewtopic.php?t=51697
