### ISSUE TITLE
compat-distro repos oddities

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#1303]
hi wdlkmpx ,
The Packages-ubuntu-bionic-main, Packages-ubuntu-bionic-multiverse & Packages-ubuntu-bionic-universe files produced by woofce when building and included in the finished iso are altered somehow  causing the PPM not to find all dependencies. Using the PPM or PKG to update the database fixes it.

an example is xfce 
before updating the PPM  Packages (with deps): 18 - Required space to install: 14mb
this results in a non working partial install
after updating the PPM Packages (with deps): 38 - Required space to install: 30mb
this results in a working install

note that this isn't  because the database of packages have changed , it's because woof changes the files somehow, the files are different sizes, and although they look the same when viewed in geany, trying to diff them doesn't work properly, the diff program (xdiff,meld,kdiff) shows every single thing as different (when it obviously isn't)

**Comment by wdlkmpx** [comment]
In dpup i see 36 deps without updating the DB's, But i won't install anything. I don't know if the oddities only happen in bionicpup64, but it indeed is a bug, i think i don't have time this month to look into this issue. I don't use the ppm and lately i don't have time to use and test puppy, maybe next month i'll try to see what's wrong in bionicpup  someone should confirm if the issue happens in other pups

**Comment by mrfricks** [comment]
i've just done a xenial build and all deps were found for xfce.  i have noticed this issue before though, when the original xenials were being built., although never looked into the reason.
For now i'll just copy the ok files into the build

cheers

**Comment by wdlkmpx** [comment]
Well, xenialpup and tahrpup were heavily edited, i mean, a cleanup operation happened. I think it's relatively safe to release new versions of xenialpup and tahrpup, hmm that can also happen after 'get rid of the multiarch symlink' is merged

I don't know much about bionicpup64, i don;t know if the issue also happens in upup bb. or any other ubuntu pup.

But `woof-distro/x86_64/ubuntu/bionic64/PKGS_HOMEPAGES `

This file is automatically created every time you run 0setup, So that file is also affected right?

I don't know if somebody else builds bionicpup64 isos, but someone might want to give you a hand by opening pull requests with fixes or comment about how to fix issues.

I briefly read the bionicpup64 and pbackup needs to go, all references to pbackup should be deleted (woof-distro/).

**Comment by wdlkmpx** [comment]
I also read people are having issues with pmount or something (in bionicpup64), filesizes are wrong.

That doesn't happen in dpup, but i'm seeing it now.. 0.0G everywhere... after compiling busybox 1.30.0

The new busybox dc behaves like gnu dc, this breaks many puppy scripts, inside and outside woofce.

I remember sending a patch to the busybox mailing list. That patch made dc compatible with gnu dc while keeping the old busybox dc behavior

http://lists.busybox.net/pipermail/busybox/2018-April/086358.html

In busybox 1.30.0 the timeout applet (alternative to waitmax) has changed
      timeout: fix arguments to match coreutils

**Comment by mrfricks** [comment]
hi wdlkmpx
bionicpup uses the static busybox from http://distro.ibiblio.org/puppylinux/pet_packages-common64/
l0wt3ch has also mentioned that replacing /usr/local/bin/drive_all fixed some mounting issues.

**Comment by wdlkmpx** [comment]
I still haven't tested bionicpup64, but the drive_all issue looks like an upgrade issue, There is also the fact that are 2 jwmconfigs and environments that are supported, or the project is being forced to support.

There is a massive problem in the handling of upgrades. The DISTRO_VERSION doesn't say much about the woof version. Changes in woof break stuff, it's not like adding another trivial package. momanager and extensions are also known to cause upgrade issues. People edit scripts and then wonder why stuff is broken after an upgrade, because they have custom versions of woof scripts,. that's why.

A proper versioning scheme is missing. One day a "dramatic" change happens (i.e. get rid of the multiarch symlink) and ..., If woof version is 7, after that change it must be 8. Simple changes can be so dramatic. Then version 9, 10, 11, 12, 13, 14.

Then init should refuse to perform the update process if the woof version differs.

**Comment by wdlkmpx** [comment]
This is an example of how to perform a minor cleanup in bionicpup64
https://pastebin.com/KVnRbPi1

This file contains several custom woof scripts:
zz_bionicfix64.pet

**Comment by mrfricks** [comment]
hi wdlkmpx,

i've issued a pull request for the clean up but it does cause some issues https://github.com/puppylinux-woof-CE/woof-CE/issues/1321
as for the custom scripts in zz_bionicfix64.pet.

dir2sfs ...  just opens a terminal window to show progress (i prefer this, could be added to woof)

sfs_load ... this runs ldconfig when the 32bit compatibility sfs is loaded. would be good to add to woof but my implementation would need fixing so that it wouldn't cause problems in 32bit pups (running ldconfig when not needed), and also to support slacko etc.

fixmenus ... some time ago puppy menus seemed to default to size 24, rather than 16. on top of that the setting for size 16 as default seemed to be broken. it may be fixed now, if so i can remove this script

change kernels ...  has a link to kernels on ibiblio, i'll issue a pull request

sfsget  ....  still using the old one as couldn't figure out the new one :)

connectwizard & connectwizard_2nd ... opens the window in the centre of screen rather than top left which is annoying on a 4k screen.

**Comment by mrfricks** [comment]
Packages-ubuntu-bionic-main, Packages-ubuntu-bionic-multiverse & Packages-ubuntu-bionic-universe files that are built into the iso end with ||
```
GNOME solitaire card game collection|ubuntu|bionic||
```
when updating the repos through the PPM they end with |
```
GNOME solitaire card game collection|ubuntu|bionic|
```
this is explains the differences i was seeing with the files, but would this affect the resolving of dependencies when installing applications from the PPM? (before the package database is updated)

**Comment by mrfricks** [comment]
yes it definitely does affect the resolving of dependencies.
i tested swapping the woof versions & PPM update versions in and out of /var/packages and
with xfce again
woof versions (with deps): 18 - Required space to install: 14mb
PPM versions (with deps): 38 - Required space to install: 30mb

**Comment by sc0ttj** [comment]
We should count the number of pipes per line (a random selection of lines) to validate the repo files .. every line checked should have the same number of pipes...
