### ISSUE TITLE
encrypted savefile password entry

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#1310]
on the bionicpup thread 'rek769' has raised an issue about encrypted savefiles. i'll just post the entire quote here

***
Greetings all, 
I use Bionicpup with an encrypted savefile which requires password entry at boot time. 

In previous versions of Puppy that I've used, an incorrect password entry resulted in being presented with another opportunity to enter the password. 

With Bionicpup, if the password is entered incorrectly I get a screen showing a dump of the last lines of bootinit.log (saying that mounting the save file has failed). The system then pauses for 60 seconds and boots without savefile. 

Is there any way to revert to the old behavior of having the opportunity to re-enter the password if entered incorrectly?
***
maybe having a second chance would suffice, but i think it shouldn't allow more than that

**Comment by gyrog** [comment]
This is not a Bionicpup thing, it's an "init" thing.

I think that "init" has not provided another go at the password since the re-write done with the original "rationalise" project in early 2017.
So the "previous puppies" must be a bit ancient.
I notice that  this doesn't seem to have worried anyone else between then and now.

I just had a look at a version of "clasical" "init" from February 2015, and indeed the "password" stuff is in an endless loop until the mount succeeds, (not ideal).

To change this behaviour would need a patch to current "init".

I guess this is not a good time to suggest to 'rek769' that they should change their ways; stop using an encrypted savefile and use an encrypted directory instead.
(There have been utilities in the forum to support encrypted directories.)

**Comment by wdlkmpx** [comment]
I implemented the requested feature. It's an example of how to use `dialog` in the initrd.

I also removed cryptoloop support from rc.shutdown and shutdownconfig.

Currently shutdownconfig detects if there is proper dm-crypt support and only then an encrypted savefile can be created,

The same logic can be applied to gyro's stuff, but i haven't tested it, so i have no idea what needs to be done.
