### ISSUE TITLE
savefile massacre 

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#1335]
hi wdlkmpx ,
there's quite a big issue with the new savefile update (or not) mechanism.
RedQuine on the forum booted the new 8.0 iso (i've taken this down for now) and got the new warning about updating the savefile. so he chose not to update and booted into ram, and then rebooted to create a new 8.0 savefile.
upon reboot he clicked on his old savefile to copy some stuff across and everything inside it was gone apart from a symlink to pup_rw.

i've confirmed this in a VM and it seems to just affect savefiles not folders
![snapshot-2019-02-23-14-57-11](https://user-images.githubusercontent.com/1454550/53288009-5b133000-377b-11e9-8cdd-5a50e2796e82.png)

**Comment by mavrothal** [comment]
I tried it on real iron booting from a USB in pupmode 13 and it did not happen.
However, it did load  the old savefile  at /initrd/pup_ro1 with "rw" were it is actually normally loaded. But in pupmode 13 both shutting down without creating a new savefile or making a new one. Did not affect the old one
In any case the savefile should be mounted when you pull out of the update

**Comment by wdlkmpx** [comment]
In woofce people are supposed to produce reproducible builds.

There is something very wrong in bionicpup, xenialpup, tahrpup.

The zz_xxxfix.pet is updated but never renamed, so what if i want to test the latest bionicpup
and i don't manually delete zz_xxxfix.pet or other pet packages so that updated versions
get downloaded? I have to increase my psychic powers

When i mean the latest bionicpup, i mean the latest git revision

I have only opened bionicfix and i still see sfsget and sfs_load, peabee reported issues with those scripts and the issues have been fixed

As far as i can tell, sfsget has a fix that was applied to the git repo weeks ago.

I'll add the i386-xxz--xzx change in sfs_load to git.

You better delete those scripts and rename bionicfix to bionicfix-1  bionicfix-2 bionicfix-3

It's really a pity, because woofce is, in a poetic sense, somewhat rolling release, the
infrastructure and core apps are updated but all the pups are still properly supported and can be released again, but not as things stand. This of course has only one mastermind behind.

I wish i could say that i will identify all the faulty pet packages, delete dangerous stuff, rename, reupload, but i guess i need some donations and cash first..

**Comment by mavrothal** [comment]
> I wish i could say that i will identify all the faulty pet packages, delete dangerous stuff, rename, reupload, but i guess i need some donations and cash first..

This would not be a bad idea though you should be a bit more "visible" for people to donate to you... 
BK, Peebee and jamesbond (and maybe others) have "donate buttons" check how are they doing.

**Comment by mrfricks** [comment]
first off thanks for fixing the bug and updating sfs_load, i'll remove it from bionicfix.
so that i can remove sfsget could you please just give me a working sfsget.conf that either lists all .sfs in both 
http://distro.ibiblio.org/puppylinux/pet_packages-bionic64/  &
http://distro.ibiblio.org/puppylinux/puppy-bionic/
or just reads http://distro.ibiblio.org/puppylinux/pet_packages-bionic64/sfsget.lst
either way is fine but i can't figure it out (hence why the old sfsget is in bionicfix).

i'll remove fixmenus from bionicfix but will be putting that version in the build, as i don't want the root menu size 24, and if i try setting it to 16 in /root/.jwm/menuheights it breaks. 

change_kernels & the connect wizards will also be removed and i'll issue pull requests.
and once bionicpup is done, i'll go back and revisit tahrs & xenials fixes.

**Comment by jamesbond3142** [comment]
> BK, Peebee and jamesbond (and maybe others) have "donate buttons" check how are they doing.

Barry does have a donate button. I'm not sure about peebee. As for me (or anyone from the Fatdog team) - we don't have donate button. We're doing it only for the betterment of humanity :rofl: 

But seriously, if a donate button helps to motivate you, then go for it.

**Comment by mavrothal** [comment]
> Barry does have a donate button. I'm not sure about peebee. As for me (or anyone from the Fatdog team) - we don't have donate button

[BK](http://bkhome.org/contact/) and [peebee](http://distro.ibiblio.org/puppylinux/puppy-upupbb/ISO-upupbb-18.05.htm) (actually in all the download links of upupbb abd upupcc) do have it. Regarding you, I confused yours with [Mick's site](http://01micko.com/). Hopefully, you are not in the Red Hat payroll 👅

**Comment by jamesbond3142** [comment]
> Hopefully, you are not in the Red Hat payroll :tongue: 

:rofl: I wish :rofl:
Anyway, there is no more Red Hat, there is only IBM :smiley_cat:

**Comment by wdlkmpx** [comment]
Well, my income doesn't come from programming and i do have a million things to do, even my room looks like a war zone, my free time can be better spent certainly. But this donation stuff is so alien to me, and being the foe number 1 that constantly breaks stuff that has worked well for years, the thought of it even seems crazy.

 fixmenus: i think peebee also uses 16 instead of 22, it seds a file or something. I see both use the same style for splashes, which is not the default.. those different settings will become the default ones..

Back to bionicpup, I read people say /usr/lib64 is a symlink, but in my build, which is the default build i see

puppy_bionicpup64_7.9.8.sfs/usr/lib64: directory

I fixed it days ago,  that's why i closed the issue about /usr/lib64

I don't know what to do or what to expect.

**Comment by mavrothal** [comment]
Is a good idea NOT to treat puppy as a rolling release. Never was and shouldn't be (I think).
The common practice is that when a build reaches beta or RC only bug fixes are allowed. Not new features. Not in the build branch.
Because of that (and the overall puppy culture), builders may keep an old woof and cherry pick fixes through z_hack or not at all.
Maybe is a good idea builders to keep their own branch and merge/cherry pick changes in testing as they see fit, instead of expecting you to both know how they build and what may be the build-specific bugs.
Another idea (that I "offer" as a friendly advice) now that you thoroughly know puppy, is to decide first what you want to change overall and then start working on the big picture from the start. I say that because I see that woof has 100.000 lines of code and your commits sum up to almost a million lines! I'm sure is fun but you are burning yourself up I'm afraid. 
Oh..., and do not feed the trolls...

**Comment by wdlkmpx** [comment]
Well, i used precise puppy until 2016 and i adapted it to woofce and
was contributing from it, it was a remaster that morphed into a woofce
puppy.

It's my style to keep using the same pup while it changes
dramatically. Of course that shouldn't be applied to woof, but that's
what i did.

With ubuntu xenial woofce reached a point where it became too buggy to
keep going and phil couldn't produce a working xenial. xorg evdev,
packages-templates, 2createpackages, ppm.

As you can see sfs_load has partially implemented features and broken
stuff, you can't really ask shinobar to fix it, it's the product of
trying to support several puppy generations in an independent app..
after many cleanups there are only 2400 lines. The script has very
well delimited code blocks and it's waaaaaaaaay more readable, of
course it's very long.

The same can be said of other core apps following the puppy tradition,
but that is fixed when the most important apps are integrated into
woof, it's a pity because i think remasterx looks quite good, simple
and intuitive gui, very complex code, and currently mostly broken for
woofce pups. Basically all shinobar apps should have been
automatically integrated into woofce after forking woof2.

Well i do know the system, probably better than anyone else, what
should i do,, start a blog, well it's the git log, not always
commented but it's a long blog. Anyone reading it can translate it
into a real blog, just by reading the changes anyone can get a picture
of what's happening. I could talk about my plans, but most of the
things i do are just cleanups and bugfixes, the problem is that simple
changes are actually big changes.

Coordination, well, here is the problem, but i think it's just the
puppy tradition, that's why those who can, fork a project completely
and create what want they in their own style, woofce is a bit
different, it's the painful result of forced improvements..

Communication, a project like this actually requires a very fluid and
constant communication but it's been proven that there's no adequate
avenue for that.

Releases, well, i think this 8.0 should be released after my pr is
merged, that will be the first deb-based puppy to not severely
conflict with the compat distro, but it's not going to happen.

And git was probably a mistake, you can see many other distros filled
with git repos with many people contributing, it's incredible how many
people can create patches and stuff and submit them  through different
means, can manage local and remote git repos, but puppy does not work
that way, it's probably the tradition.

Having said that, i hope phil gets to release 8.0 soon.. i won't get
in the way ..
