### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#1339]
you've done a hell of a job speeding up the whole woofce build process. what used to take somewhere around 3-4 hours, now takes 30-40 mins.

my request is to be able to stipulate the 'background' 'jwm-theme' 'gtk-theme' 'icon-them' & 'openbox-theme' in _00build.conf so that the process can be automatic if desired.

cheers

**Comment by wdlkmpx** [comment]
That is already implemented in ptheme, except openbox-theme. 

But ptheme requires jwm_config (not jwmconfig3). ptheme was somewhat or quite buggy, i guess that's why you didn't want to use it, but it's usable now. I used to hate it, until i fixed it a bit.

The problem is that jwm themes must be adapted to jwm_config. I adapted 6 or 7, but i have like 30-40 that i wanted to adapt, but xzxzmnxn,,

You can create a ptheme, which is a config file.

I guess documentation is needed, i usually don't need it 'cause i end up reading the scripts themselves but peebee can teach you how to use ptheme and how to create new pthemes. 

in _00build.conf:
PTHEME="Dark_Blue"

![screenshot 1](https://user-images.githubusercontent.com/10052849/53533949-e0aa2d80-3b37-11e9-9cac-228cfeee74aa.png)

**Comment by wdlkmpx** [comment]
I can't ignore the fact that some puppies don't include ptheme, and that the `choose_themes` dialog pops up when i'm not paying attention.

Commit https://github.com/puppylinux-woof-CE/woof-CE/commit/cebc7adb36bc5300aef14b328cc7418f8dae4a34 implements this request

The dialog has been deleted, the script force some automatic defaults if they're not specified in _00build.conf. This newly added code doesn't make noises when building a cli-only pup.
