### ISSUE TITLE
 update needed on the Puppy Universal Installer!!!!  It has no support for UEFI bios

### ISSUE THREAD

**Issue by bigpup1** [puppylinux-woof-CE/woof-CE#1352]
Is anyone still watching this program for errors, problems, needed code changes, etc.....?
I ask, because I am not sure this Universal Installer works with the new computers using UEFI bios.
Recently, someone posted they tried to do an install, to the internal hard drive, using the Universal Installer.
It refused to do the install. A message said it is not able to do installs to a computer with UEFI bios.

**Comment by wdlkmpx** [comment]
The universal puppy installer does not support uefi, It shows an error when puppy is running in uefi mode. And the option to perform full installs should be a hidden feature or something, only for power users.

Bootflash can perform a uefi frugal install, using uefi-usb-installer or by dd'ing a uefi iso to a usb stick.

There is also frugalpup by gyro and maybe some other apps posted on the forum.

The universal puppy installer is easier to fix and edit now, 2500 lines -> 1770.. but i think it should be simplified to use only wee+grub4dos and grub2. The boot menus:
/usr/share/boot-dialog
/usr/share/g4dos

It's not one of my priorities

**Comment by bigpup1** [comment]
I agree.
Grub2 needs to be a bootloader offered by the Universal Installer.
It seems to be needed in Puppy for true UEFI normal booting.
All that USB installing is OK.
But I have a computer with UEFI bios, that will not even see a USB drive as a boot device, if secure boot is enabled.
It will not boot a Puppy install on the internal drive, unless secure boot is enabled and the internal drive has Grub2 boot loader on it.

**Comment by karthussss** [comment]
Hello,

Just wanna pitch in my experience with universal installer. Im trying to install puppy linux on SD card but universal installer cannot detect the laptops internal sd card reader. I was able to install Puppy linux using universal installer opting on Internal IDE/SATA flash drive but boot is broken. No matter what settings I make at BIOS e.g. secure boot disabled, legacy enabled, reorganizing boot order, it still wont boot. Tried installing Grub4DOS but it too failed because it wants to format? the drive and the process fails leaving me with an 'unknown' file system according to gparted. I was able to successfully install Puppy by inserting my SD card into my USB SD card reader adapter then plugged to USB port and universal installer worked flawlessly. Im able to boot as long as the SD card is plugged inside my USB sd card reader adapter and plugged to USB port. It wont boot if I try to plug the  working SD card Puppy install directly into my laptops internal SD card reader. 

Im using BionicPup64 8.0 frugal install in a 32GB SD card fat32 format. Would be nice if Universal installer can recognize SD card reader so I dont have to boot from an external sd card adapter that may get yanked out by accident.

FAQ: 
yes i have internal hard drive.  
No i dont want to install Puppy to hard drive because the laptop will be used as surveillance camera server. Puppy (or any OS) on flash yields faster IO and zoneminder or shinobi client will be doing a lot of CPU work due to motion detection, encoding, decoding and frame buffering from 4 IP cameras at its optimal setting. 
The hd will be dedicated as media storage.

Thnx
