### ISSUE TITLE
input-wizard issue

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#1356]
westwest had reported in the bionicpup thread that 

> In the Mouse Wizard, changing any setting then clicking OK disables the touchpad, seemingly irremediably. This was not so with earlier BionicPups. 

the error is 
```
modprobe: FATAL Module mousedev is builtin
```

**Comment by mavrothal** [comment]
mousedev is builtin few years now.
The real error is in X ```SynPS/2 Synaptics Touchpad: Read error 19```
Is happening if you try to change the "type of mouse" but not "mouse sensitivity" or "touchpad"
Does to affect a Physical mouse. 
Restarting X does not fix it. Rebooting Does.
It maybe a kernel/uevent/X config issue. 
Also the Input-wizard had a rewrite about a month ago, so something might be there.

**Comment by mrfricks** [comment]
yes, just tried and the old input-wizard doesn't disable the touchpad

**Comment by wdlkmpx** [comment]
The script is essentially the same, i only removed some old code and references to kernel 2.6. simplified some stuff and relocated some lines. that's the problem. i think.

But i don't have that issue. Does removing the modprobe -r lines fix the issue?
[input-wizard.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/2966666/input-wizard.zip)

Also, i think i read the serial mouse stuff doesn't work if using the evdev driver... some additional steps are required with some extra app(s). 

I have never used a serial mouse in my life, the first PC i ever touched was a pentium Ii when i was a kid, And it came with a PS/2 mouse, i remember.

I wanted to comment about this, but i don't know. A serial mouse is a mechanical mouse, Just like ancient PS/2 mice. PS/2 mice exist since the late 80s i think, optical mice started to become mainstream in 1998.

So removing serial mouse stuff is the right thing to do. I'm being selfish.

http://www.computinghistory.org.uk/det/613/the-history-of-the-computer-mouse/

**Comment by mrfricks** [comment]
yes your attached input-wizard.zip fixes the issue with the touchpad
