### ISSUE TITLE
bionic64 DISTRO_PKGS_SPECS rox_config should be 'yes'?

### ISSUE THREAD

**Issue by wiake** [puppylinux-woof-CE/woof-CE#1360]
My understanding, though I'm not sure, is that in DISTRO_PKGS_SPECS-ubuntu-bionic
rox_config is required and should thus be yes|roxconfig rather than existing:

no|rox_config||exe,dev,doc,nls[/code]

As it stands, the pop-up chooser seems to be required (which defaults it seems to yes for all packages in support/rootfs-packages) else rootfs-packages.conf-backup needs renamed to rootfs-packages.conf with correct selections in it. I find this painful.

**Comment by wdlkmpx** [comment]
I don't know what you're trying to do, but if you follow the steps you'll get the correct results, although it is my understanding that upup builds are not reproducible, i.e. my bionicpup64 build differs from the official release. There are packages that are updated but there's no revision number, there's no way to tell if something has been updated, i guess you have to delete all the pet packages from the local repository.

If you're trying to bypass the dialog and automate things you'll find problems with builds using something other than jwm_config/ptheme (i.e. jwmconfig3/jwmdesk or something, upups, slacko 14.0)

The upups need a special rootfs-packages.conf, there's an example in -/woof-distro/x86_64/ubuntu/xenial64/rootfs-packages.conf

I guess the rootfs-packages should be moved to another repo (noarch-sources) and become regular pet packages (noarch). And rootfs-packages should be extra packages that are always added to the build .. no need for a dialog.

Editing stuff and creating pet packages is a hassle, well at least for me, since i tend to edit many things at the same time.

This certainly requires a high level of communication and a lot of work, i'm not sure if that's possible.

It's difficult and there's nothing to worry about, life is short.

**Comment by wdlkmpx** [comment]
To resolve this little conflict and include a generic rootfs-packages.conf in woof-code/ so that 3builddistro becomes more automated by default, the following rootfs-packages must be removed:

- jwm_config
- pt_buntoo
- pt_faux_xfwm
- ptheme
- pmusic (phil usually disables this)

Converted to pet packages and uploaded to the noarch repo

The following pups are affected (PKGS_SPECS):
- upupbb
- peebee's pups
- slacko 14.1
- slacko 14.2
- dpup

Other unknown pups and builders are affected as well.

After that, the pkgs specs must have:
yes|jwm_config||exe,dev,doc,nls
yes|pt_buntoo||exe,dev,doc,nls
yes|pt_faux_xfwm||exe,dev,doc,nls
yes|ptheme||exe,dev,doc,nls
yes|pmusic||exe,dev,doc,nls

**Comment by wiake** [comment]
I am not asking you to fix or contribute to makepup. My issue was with DISTRO_PKGS_SPECS containing no|rox_config which, I remarked, the pop-up chooser, for reasons of your own (or whoever wrote that code) appears to ignore. However, main thing I wanted was for DISTRO_PKGS_SPECS for bionicpup64 to be amended to yes|rox_config. If you are happy with the pop-up code overwriting no|pkgname entries in DISTRO_PKGS_SPECS, then that is up to those looking after woof-CE scripts then.

**Comment by wdlkmpx** [comment]
PKGS_SPECS define a package in the pet repos, a package that may be
completely different from the same package in rootfs-packages.

I don't use makepup and am not sure what it's changing and i also
don't build upups, so i have to guess what happens.

If you define yes|rox_config the package must exist in the pet repos
otherwise the package "will not be found and  will be ignored in the
build process" and it doesn't matter if it's not a rootfs-package.

rox_config is a rootfs-package, but phil tried to override with his
pet pkg with the same name.

The code that "finds" all the packages to be included in the build has
nothing to do with rootfs-packages, roofs-packages is processed only
in 3builddistro.

Woofce keeps changing and i see this is something that will change, if
time allows of course, but every change has always dramatic and
cinematic effects as there is people building their stuff and i have
to fix it for them. That's why many changes are stalled.

But yeah, it should be yes|rox_config ..

1) 1download. the script detects and downloads rox_config , a pet
package uploaded by phil to override rox_config (rootfs-package)

2) 2createpackages detects that rox_config is also a rootfs-packlage
.. and uses the rootfs-package instead of the extracted pet pkg.

3) at this stage it doesn't matter what happens in the dialog to
select extra packages or the the automatic stuff created by makepup

4) conflict between jwm_config/jwmconfig3 may arise if jwmconfig3 is
defined in the PKGS_SPECS and jwm_config rootfs-package is included in
the build.. unexpected results

5) old fixed and modified scripts in zzfix bionic, zzfixxenial .. etc
introduce bugs in the build process , you have to delete all zz....pet
packages first, so they are download again. Unexpected results.

**Comment by wiake** [comment]
Only one issue was raised. A correct request that BionicPup64 DISTRO_PKGS_SPECS no|rox_config should be changed to yes|rox_config. All these other claims about all these tons of mods that the respondent says would be additionally required are not required or requested by me despite the implication. I just want a woof-CE configuration file which is wrong, corrected. Nothing to do with makepup per se. Please correct.

**Comment by wdlkmpx** [comment]
I'm only trying to explain what happens as you have no idea what
you're doing or what is happening.
