### ISSUE TITLE
# don't overwrite user chosen specs in builddistro-Z function?

### ISSUE THREAD

**Issue by wiake** [puppylinux-woof-CE/woof-CE#1361]
I'm not sure but DISTRO_PKGS_SPECS code actually seems to be overwritten by the builddistro-Z current code (around line 146). In particular, if DISTRO_PKGS_SPECS has a 'no' entry, the pop-up seems to show it as a 'yes'. Is that not the erroneous effect of the code below?:

			*)
				if grep "yes|${d}|" DISTRO_PKGS_SPECS-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION} ;then
					state=false # don't overwrite user chosen specs
				else
					def=true
				fi

**Comment by wiake** [comment]
I posted more details about the issue here and in a few posts above that:

http://murga-linux.com/puppy/viewtopic.php?p=1022512#1022512

**Comment by wdlkmpx** [comment]
I see what you're trying to do, i know that rootfs-packages is confusing, there is PKGS_SPECS and there is rootfs-packages, a conflict between the two  arose since stuff is fixed in the git repo and some apps were added to rootfs-skeleton. It's a long story, but rootfs-packages do override PKGS_SPECS ... in 2createpackages.

I also see you need some serious help, it's not hard for me to fix  makepup and integrate it better with the build system, but i'm not sure if it's a good idea to post it on the murga forum, i only find it reasonable for contributors to test and help debug stuff and their own additions to the system by building their own isos. I'm not against people's creativity and their right to release their own derivatives, it's just that woofce is a not stable thing. In fact i never released anything, but i do build my own isos for my own purposes. I'm being selfish.

**Comment by wiake** [comment]
I'm not sure you are talking about the same issue as me actually, but maybe you are. I do wonder, from your comment, how the distro recipe builder then would have control as to which packages to include in rootfs-packages (via the no|pkg_name and yes|pkg_name format, which as I understood things was being over-ridden in 3builddistro-Z for the no|case).

**Comment by wiake** [comment]
And no where in my raised issues have I asked for help in developing my own program makepup or in making it work. I considered the issue a fault in woof-CE scripts themselves - your opinion differs, that is fine but I guess up to others to decide too.

**Comment by wiake** [comment]
I have asked for someone still interested in Puppy woof-CE developments to take over makepup for me, but that is nothing to do with here; that's on the forum, and that will be done.

**Comment by wiake** [comment]
It is illogical to overwrite DISTRO_PKGS_SPECS 'no' entries automatically by the 3builddistro-Z pop-up gui for rootfs-packages. Then the user, has to go through the gui checkboxes manually putting them back to 'no' as the distro builder wanted (per the DISTRO_PKGS_SPECS) they created. The code for that pop-up is wrong whether one woof-CE maintainer thinks so or not.

**Comment by wdlkmpx** [comment]
Here is the explanation.

			if grep "yes|${d}|"
DISTRO_PKGS_SPECS-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION}
;then
				state=false # don't overwrite user chosen specs

If a pet/deb/txz/etc pkg is selected then the rootfs-package cannot be
selected, because it will overwrite it.

But by reading 3builddistro one knows that the rootfs-packages are
added to rootfs-complete before the extracted pet packages/deb
packages/ etc, so they will never overwrite the pet/deb/txz/etc pkgs.

It's not about respecting PKGS_SPECS, it's about not overwriting the
selected pet pkg, which never happens (in 3builddistro). no|package| =
rootfs-package can be selected in the gui.

rootfs-packages was added years ago, maybe right after forking woof2.
Pet packages vs  Git repo. I was not around. It has been discussed
several times, rants were heard. It takes action and a bold move for
something to change.

woofce is the result of conflicting views and development, that's not
a secret. Most of the development process involves undoing, removing
or rewriting somebody's code.

There is a song that comes to mind, it's called Code and other bruises

Code and other bruises makes us all good losers
Code and other bruises didn't to have choose us
But it did and i'm alive and i'm trying to survive

I hope this helps.

**Comment by mavrothal** [comment]
Indeed rootfs-packages was/is an effort to include and maintain all the puppy-noarch and even puppy-commonXX packages, in github, so would be readily visible, easier to maintain and collectively develop and give open credit to the people that developed the code.
As this is not still the case for most noarch packages and actually many exist in both places, is  currently up to the builder to chose if it is going to come from the pet or a *-packages folder,  and that is where the confusion arrises.
Given that rootfs-packages is evolving (grows) with time, having _another_ SPECS files for these packages to allow flag-based configuration maybe harder to maintain, but pull requests are always welcome and discussed and most of the time accepted. 
So let's "let the code do the talking"
