### ISSUE TITLE
Packages-puppy-noarch-official should not have been moved

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1362]
Please move it back

**Comment by wdlkmpx** [comment]
I restored the file, but the pet_repos point to another file.

**Comment by peabee** [comment]
I don't think it matters if the database is in a different branch/repo to the pets....thats how its been with github and ibiblio for some time.
It is important that changes do not break existing systems - for instance when we moved the database from ibiblio to github we didn't delete the ibiblio versions although they do of course become out of date over time.
There should only be one version of the database - so the pet_repos should be reverted to point at the previous location.

**Comment by wdlkmpx** [comment]
I really doubt people would want to update 2 repos when it can be done with
only 1. The noarch repo.

**Comment by peabee** [comment]
Defo only 1 repo and 1 database - but leave the database where it was for compatibility with existing systems.....

**Comment by wdlkmpx** [comment]
Existing systems:

PKG DB: woof-CE/woof-distro/Packages-puppy-noarch-official
PET REPO: ibiblio.org [closed to contributors]

Current stuff

PKG DB: woof-CE-noarch
PET REPO: woof-CE-noarch

Is this what you want?

PKG DB: woof-CE/woof-distro/Packages-puppy-noarch-official
PET REPO: woof-CE-noarch

or do you want me to revert the whole thing?

PKG DB: woof-CE/woof-distro/Packages-puppy-noarch-official
PET REPO: ibiblio.org [closed to contributors]

Because when people using existing system update
Packages-puppy-noarch-official, they will find that some packages
don't exist in the repo (ibiblio.org)

Please read the above carefully and try to process it

**Comment by peabee** [comment]
PKG DB: woof-CE/woof-distro/Packages-puppy-noarch-official
PET REPO: woof-CE-noarch

**Comment by wdlkmpx** [comment]
When someone updates one of the woof-CE-apps, they will update version
in the pet.specs, then run ./make_pet.sh app, then

They will upload the pkg to woof-CE-noarch

They will edit woof-CE/....packages-noarch

3 repos to edit when someone updates one of woof-CE-apps (currently
called rootfs-packages].

2 repos to edit when someone adds a new version/pkg that is not a woof-CE-app

1 person was watching the wheels go round and round

0 07 is the key
