### ISSUE TITLE
save to cd broken

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#1365]
tallboy on the forum mentioned that save to cd wasn't working, so i fished out an old CDRW to give it a go and it failed.
looking into the save folder on the cd shows all text files as unreadable binaries
![Screenshot](https://user-images.githubusercontent.com/1454550/55620738-7ec29080-5793-11e9-8b2b-be2259fe2a72.png)

**Comment by wdlkmpx** [comment]
I see It's working but it's broken, i don't have CDs, only a few blank DVDs. I certainly don't have any CD-RW or DVD-RW discs, only a few blank DVD-R discs.

He also said that it works fine in dpup stretch 7.5,rc4.. so it maybe because debian is more puppy-friendly, or the cdrecord binary is performing better for some reason. Who knows.

For dvds it calls growisofs (a frontend for cdrecord), and for cds it directly uses cdrecord with different params.

So i can only test with a DVD-R disc.. one of these days.

**Comment by mrfricks** [comment]
thanks for the pointers ... updating cdrecord has fixed it
