### ISSUE TITLE
Ready-made sfs's for the adrv/ydrv (3builddistro)?

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#1388]
01micko added clever code to create adrv/ydrv/fdrv in 3buildistro. And firmware stuff,

I believe there's another way to achieve that: ready made sfs's with the browser of your choice or other apps. I.g. palemoon (works in all woofce pups), firefox (works in all woofce), etc.

How about this:
ADRV=....../path/to/peebeesbrowser.sfs
FDRV=.../path/to/peebees/fdrv.sfs

So there's no need for Packages-extra-........

**Comment by wdlkmpx** [comment]
Soo, basically the build configs should specify one of peebee's browser sfs. I just hope he deleted the palemoon-updater from the palemoon sfs, that script no longer works.

Or maybe a combination of portable sfs's that will become a single sfs. ADRV or YDRV

Sooo, as we can see stuff can be simple and a few more hundred lines of code lines can be deleted, making the build scripts really tiny.

**Comment by wdlkmpx** [comment]
This could apply to kernels and extra compiled modules, it all becomes the ZDRV. Eh?

**Comment by s243a** [comment]
You can already specify the path of these drives via the boot parameters passed to initrd. 

BTW what is wrong with "extra sfs" concept?

Although with your trick perhaps there needs to be code in "extra sfs" to detect if the sfs is already loaded.

**Comment by s243a** [comment]
Another alternative my be a boot parameter that let's you change the file "or directory" which specifies which extra sfs files to include. BTW as ([mikeslr notes](http://murga-linux.com/puppy/viewtopic.php?t=115397)) notes if you load the files via some (X)drv then the files are loaded into ram. If you use the extra sfs they are not loaded into ram. People might put the applications into an extra sfs pricisely because they don't want to load the application into ram at boot.

**Comment by wdlkmpx** [comment]
I'm not talking about the running system, it's about 3builddistro and how to simplify the logic and at the same fix other issues. By using read-mady sfs's the builder can just update sfs file and no need to update pet packages and son.

**Comment by mavrothal** [comment]
>How about this:
ADRV=....../path/to/peebeesbrowser.sfs
FDRV=.../path/to/peebees/fdrv.sfs
...
Soo, basically the build configs should specify one of peebee's browser sfs. I just hope he deleted the palemoon-updater from the palemoon sfs, that script no longer works.


If this option is added is fine, otherwise it just limits the scope of "X"RDVs and makes them a blackbox of binaries where the source and configs are hard to trace. 
What about taking the XDRV code out of builddistro and just give the option for ready SFS or build from source, in build.config?

**Comment by wdlkmpx** [comment]
It looks like stuff that shouldn't be in a helper script, just like the rootfs-packages stuff.

The way i see it, that everything should be installed to rootfs-complete, and then

move out ADRV, YDRV, FDRV, ZDRV ..
move out DEV, DOC, NLS

But for that happen there are changes structural that might be considered controversial.. it's not hard for me to do that.  And the package lists will not be as accurate, i mean if compat distro post-intall scripts are executed.

If you look in packages.slackware.com, you'll notice missing files that are listed in puppy's /var/packages/builtin_files/pkg

Talking about the frv, ydrv, zdrv, i guess we must use a huge kernel that already has everything ready, no need to load kernel modules, well i guess all static apps in the initrd should be in main.sfs (except busybox of course), and init should just symlink them to /bin (in the initrd).

The build system is starting to show true consistency, all scripts use status/findpkgs_FINAL_PKGS to determine stuff, i remember the days when all the scripts used their own logic.. see the legacy branch and really old stuff, around 2015.

Now it's easy to add code to create _DOC.sfs and NLS_sfs

**Comment by mavrothal** [comment]
> It looks like stuff that shouldn't be in a helper script, just like the rootfs-packages stuff.
The way i see it is that everything should be installed to rootfs-complete, and then

That what was done originally and was heavily criticised because is mixing up apps, system scripts, info files and everything else in a very "un-linux" way. Harder to maintain too (assuming more than one person involved...).   

> Talking about the frv, ydrv, zdrv, i guess we must use a huge kernel that already has everything ready, no need to load kernel modules, well i guess all static apps in the initrd should be in main.sfs (except busybox of course), and init should just symlink them to /bin (in the initrd).

Not sure if you mean that, but a kernel with all modules built in is a huge waist and burden. 90%+ of the modules are never used by any specific system.
Also static initrd apps make sense for a consistent booting across different puppy flavours/compat distros. The opposite can be a problem as compat distro apps may have different options and behaviour.

**Comment by wdlkmpx** [comment]
huge kernel = woofce kernel, custom vmlinuz.

With a huge_kernel, you don't need to load modules to access drives
and stuff, it either works or it doesn't. The old code used to load ..
modules to access disk drives, that doesn't apply to woofce kernels.

So i guess a standard main.sfs build could come with standard static
apps. These apps could be added to woof-arch.. which will become a
tarball, and then what happens, these apps override stuff, because
they're 1) part of the system, 2) always up-to-date and even 3) init
calls them.

Sounds like a good idea.

For rc.cleanup, the poweroff could copy the needed binaries to the
initrd mountpoint  .. i'm yet to test the rc,cleanup stuff in a raspi,
if it doesn't work... i.e. recovering journal, i'll delete it.

**Comment by wdlkmpx** [comment]
Well, gentlemen, it's a clean shutdown in a raspi with a savefile in a
fat32 partition.. with and without rc.cleanup. There's an issue with
the arm init-bootmenu code that overrides pup boot params in
cmdline.txt with empty values (i fixed it locally).

So i guess, when something works, it works, and when it doesn't not
even rc.cleanup will fix it. So rc.cleanup will get the axe..

**Comment by woodenshoe-wi** [comment]
> There's an issue with
the arm init-bootmenu code that overrides pup boot params in
cmdline.txt with empty values (i fixed it locally).

Go ahead and put the fixes in woof-CE, I was expecting that boot params would be specified in bootmenu.txt and didn’t test specifying them in cmdline.txt.

**Comment by wdlkmpx** [comment]
https://github.com/puppylinux-woof-CE/woof-CE/commit/1469bcf7b68812316fe326f4e14102fd0440fa6c

This is what i think i know:

[ $variable ] && ...

true if variable exists, true even if variable is empty

[ "$variable" ] &&

true if variable is not empty

so if you export a variable with an empty value ... [ $variable ] &&
VAR=$variable .. $VAR will be empty.

Reading the init script i noticed that some small changes i made in
the past are not there.. git works in mysterious ways when you
maintain several branches and rebase often.

**Comment by wdlkmpx** [comment]
I wasn't sure how to create a bootmenu.txt.. i might need a sample
bootmenu.txt to test the code.. a new file can be added,
bootmenu.txt.sample .. in
woof-distro/arm/raspbian/stretch/rootfs-skeleton/boot
