### ISSUE TITLE
swap file on sd card wont mount during boot

### ISSUE THREAD

**Issue by karthussss** [puppylinux-woof-CE/woof-CE#1456]
Im running BionicPup64 8.0 on an external SD card reader plugged to USB. I created a swap file on another SD card inserted into my laptops internal sd card reader but Puppy cant 'swapon' the swap file on the SD card during boot. According to the pupsysinfo bootsysinit log, the only recognized media are:

RECOGNISE MEDIA DEVICES
'/dev/cdrom' -> '/dev/sr0'
'/dev/dvd' -> '/dev/sr0'
'/dev/mouse' -> 'input/mice'

Over these past few days I've been reading the boot scripts and logs to learn how it works. For now, I found a temporary solution by directly having bootup and shutdown script swapon/swapoff the file via its PATH. 

Modifications:
	Insert in line 16, 17 of /etc/rc.d/rc.local #this is personal script section during bootup;

	swapon /mnt/mmcblk1p1/pupswap.swp 
	chmod 600 -v -c /mnt/mmcblk1p1/pupswap.swp

Insert in line 270 of /etc/rc.d/rc.shutdown;

	swapoff /mnt/mmcblk1p1/pupswap.swp 

Attached is a pupsysinfo generated log.

[pdiag-20190605.tar.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/3255192/pdiag-20190605.tar.gz)

**Comment by wdlkmpx** [comment]
pupswap.swp is supposed to be in the boot device/partition/pupsave partition.. and most of the time it's the same device.

It doesn't mount all partitions looking for pupswap.swp, it only checks for pupswap.swp in only partition and it must be already mounted, and that's usually the case unless you're booting with pfix=ram

Is pupswap.swp located in the boot device/partition/pupsave partition?

**Comment by karthussss** [comment]
No, pupswap.swp is located on a seperate sd card. Another sd card serves as a boot device and no matter what choice i pick at grub4dos menu, it default to pup mode 5 during boot. Upon checking pupsysinfo>sys-files>pupstate, it says im on pupmode 13 and that pupsysinfo>sys-files>pupsaves are empty. So yes, im always but not by choice booting with pfix=ram. I need to post a new bug dedicated for this because that is also my concern. Despite having bionicpup64save.4fs located at /mnt/home symlink to /initrd/mnt/dev_save it seems to mount but rc.update always says Empty pupsave? Simulating PUPMODE=5...This is probably my 12th restart and all turns into PUPMODE=5. This could probably be the reason why htop settings not being persistent after reboots in which i posted as a bug. 

Anyway back to original issue, I get that bootup wont mount all partitions. But during the creation of pupswap, its an option to choose where to save the pupswap file. I chose another device=SDcard. My rationality is, the file pupswap will have better efficiency ie. access times, read, write, if its on a different device rather than on the same device where the OS is located because it works as a pagefile and I/O operations of swapfile will be queued up together with the OS. Yes, puppy linux is so efficient that it only requires very minimal cpu and ram usage which would make my desire to have swap file on another device to increase efficiency a moot point. But the rig im creating is going to run a surveillance client hooked to 4 IP cameras running at optimal resolution and one of which is 4MP. Encoding, decoding, pre buffer frames, motion sensing algorithm, saving files will require lots of CPU and ram. And that is why i prefer the swap file not in the same boot device/partition. If the sdcard hosting the swap file goes kapoot, i can just replace it and create a new swap file rather than shortening the life cycle of the sd card boot device. This is basically the same reasoning behind windows xp/vista ReadyBoost feature, that is, to use a faster external media such as USB drive as cache/pagefile syste to augment the RAM and increase speed and efficiency. 

Sry if i rambled on too much, its 5am and i cant sleep bcus of insomnia.

I dont mind Puppy not configured to mount and search all devices for pupsave since I can just change the scripts to tailor my needs. So this bug thread can be considered closed.

 Instead, Id like to make a feature request to have bionicPuppy64 remember the user defined file PATH used when a swap file was created.

**Comment by wdlkmpx** [comment]
pfix=ram (boot param) = force copying sfs's to ram + don't mount any partitions = don't load pupsave  .... 

PUPMODE 12/13: a pupsave is found, default logic applies. but in PUIPMODE 13 the system writes to ram instead of the pupsave, that's when periodic or manual saves are needed using snapmergepuppy = merge snapshot (i think).

Hmm i think a new boot param is missing: pfix=nopsave, follow default logic but just ignore pupsave.

I added the pupswap dialog (BootManager), and i added it so that you can create pupswap.swp that can be used in the running pup using the default dir, or one that can be run in other pups (other partitions).

It's worth noting that in rc.sysinit, pupswap.swp is loaded only if no swap partitions are found. And there's some code that validates the pupswap.swp and the drive it's in.. code i'll delete. 

There's some logic in the startup and shutdown scripts to trigger the pupswap dialog, i regret having added that, i just wanted to be popular and show my skills

So much can be written about this, i'll think about the feature request and i think i'll implement it.

But you're doing the right thing, using rc.local to fix issues. It's the right thing to do.

I don't know if a new update of bionicpup64 will be ever released, but there's an unofficial 64bit pup that is often updated, and changes and fixes in the system become available there.

It's called LxPupSc64, although it tends to be unstable, it uses slackware current, the equivalent of debian sid.

**Comment by karthussss** [comment]
thank you, as an aspiring coder its an honor to be praised by a dev. 

This is my first time spending so much effort to learn linux distro. Ive tried several times specially with Ubuntu and some other distros in the past but the amount of reading and learning to grasp how to make it work use the OS puts me off. But right now I truly need a non bloated stable distro with efficient use of resources for a home surveillance project of mine so Ill pass on LxPupSc64. Ive understood a small part of the scripts in Puppy64 already and can grasp the usage of a few commands and other utils so i might use this distro to learn linux and maybe go on to bigger things like remaster it purely for surveillance use.

**Comment by peabee** [comment]
> It's called LxPupSc64, although it tends to be unstable, it uses slackware current, the equivalent of debian sid.

Hmmm - don't think "unstable" is quite the right word...........

There is also ScPup64 if you don't want the LXDE desktop...........

**Comment by gyrog** [comment]
Use a swap partition not a swap file.
The code in rc.sysinit, should find and use all swap partitions in the system, no matter where they are.
