### ISSUE TITLE
CD do not show on Desktop?

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#1468]
Tried briefly a [slacko 14.2 build](https://www.mediafire.com/folder/o2hpqpbhd2ohi/14.2) that reports it was build from the, (now disappeared ie does not show in a github search) d9f0b441 commit, of the  (now deleted ) experimental branch, on a VM.
"Insertion" of a new CD does not show on the desktop nor the pmount list. If you restart X or refresh pmount you can see it. 
I remember having seen some pup_event changes relying now on kernel for detection, but given the history mixup I am not sure how it relates to the above commit. In any case if it is not a VM-specific bug, (anybody sees that a physical machine?) may need some looking into it.

**Comment by mavrothal** [comment]
> was build from the, (now disappeared ie does not show in a github search) d9f0b44 commit ...... "Insertion" of a new CD does not show on the desktop nor the pmount list

Actually d9f0b44 is now da44abb1  (!) and the commit I was thinking is c5fd425bc.
```/sys/module/block/parameters/events_dfl_poll_msecs``` is as directed and ```blkid``` does see the CD correctly. But not the pup_event and pmount
<img width="465" alt="CDmount" src="https://user-images.githubusercontent.com/1014999/59823315-80353b00-9336-11e9-92d0-935c1762b3b9.png">

**Comment by ninaholic** [comment]
Hi,

I am only able to test it with usb sticks on my netbook, but I tried two of them and at least those showed up on desktop (in PUPMODE=5) for me. I was hoping it didn't so I could help debug, oh well. Next time gadget, next time :octocat:

**Comment by wdlkmpx** [comment]
- Rebasing a branch = different commits.
- Most commits were cherry-picked = different commits.
- Merging commits = same commits.

I tested in a physical machine with dpup (k4.1) and slacko140 (k3.2). 

It's probably a timing issue where "kernel polling" doesn't seem to start.

Will test in another machine and in a virtual machine later.

**Comment by mavrothal** [comment]
Sorry for not mentioning it in the original post, but indeed USB has no issues.
Couldn't see anything on a fast check either.
So I hope is a quirk of the VM that somehow this pup can not handle (is OK with other puppies)

**Comment by wdlkmpx** [comment]
I tested that slacko142 ISO in a core i7 pc with a bluray burner drive. I didn't burn the iso, i just put something there to see if it's recognized when X starts... it works fine.

Linux + qemu:
![Screenshot_qemu](https://user-images.githubusercontent.com/10052849/59885497-095b7900-93ee-11e9-9262-93a6947e03a4.png)

Windows 10 + virtual box
![screenshot_vb](https://user-images.githubusercontent.com/10052849/59885510-1a0bef00-93ee-11e9-91ad-78180a2e6ebd.png)

It's probably the pc emulator... in macOS? Probably needs a newer version. But i noticed something, the iso has kernel 3.16. It's not using the default kernel in _00build2.conf. Slacko Kernel 4.4.. the sfs is a little big. Which reminds me that there must a new option in the bootloader's boot menu: 'don't copy sfs's to RAM'.

I think PTHEME Buntoo is also specified in _00build2.conf. But look at the full moon in the Original Pup ptheme

This is also a good wallpaper: https://media.front.xoedge.com/images/4b276e08-67d0-40d4-a174-a015f775f15d~rs_1080.h

**Comment by ninaholic** [comment]
Yes, the blue full moon is good :large_blue_circle:  I recall bigpup complained about Buntoo theme having no desktop icons in slacko64 which might confuse new users and I like the full set as default too, and musher0 mentioned that kernel 4.4 is slower than older ones, but still firefox 60+ is too slow even in 3.16 and palemoon 28 needs sse2 now so maybe there is no hope for fast 14.2 on my netbooks any more so back to slacko14.0 for me I think :laughing:

**Comment by wdlkmpx** [comment]
Changing xorg version might help. In dpup stretch there is an alternate xorg.. xorg 1.11.4. But that old xorg depends on libudev.so.0, so autoadding of devices will not work.

I think i first tested that alternate xorg in slacko 142 and it worked fine, the behavior on first boot changes, xorgwizard is triggered with an extra option.

I'll probably add the alternate old xorg to slacko 142*32. I think the minimun kernel version for slacko 142 might be 4.1.

With an alternate xorg, i guess there's no need for older compat distro versions, unless you compile the nvidia/(old ati/amd) driver or some deprecated kernel drivers. Some ndiswrapper stuff apparently only works with some old kernels.

In Precise puppy/Slacko 140, xorg uses a different acceleration, "XAA", it was removed in xorg 1.13 maybe

In slacko 141/tahrpup+, xorg uses "EXA" or something.
https://en.wikipedia.org/wiki/EXA

**Comment by mavrothal** [comment]
> It's probably the pc emulator... in macOS? Probably needs a newer version. But i noticed something, the iso has kernel 3.16. It's not using the default kernel in _00build2.conf. 

I never use qemu. Is(was?) too slow. Usually Paralles, WMware or VirtualBox virtual machines.
But is likely the kernel. On an oldish samsung laptop (with dual GPUs) the build hangs after failing to start X and have to hard-interapt console to start X again. Also fails to shut down.
Replacing with the 4.9.30, 64bit kernel from Mick's 6.9.9.9 that happened to be in that machine, everything looks fine (regarding X, shutdown and CD/DVD showing on the desktop)

**Comment by ninaholic** [comment]
There is a similar report from foxpup about kernels recently built with kernel-kit:
http://www.murga-linux.com/puppy/viewtopic.php?p=1006853#1006853

But the ones by 01micko worked fine. Could it be a changed config setting maybe? I wonder. :thinking:

**Comment by wdlkmpx** [comment]
Qemu is incredibly slow, but with qemu_gui using kvm_intel/amd it can
be really fast. I'll push the updates soon. Hardware virtualization
must also be enabled in BIOS (Intel Virtualization Technology =
enabled).

I read someone reported issues with slacko 141 (6.3) and virtual box
(or qemu), years ago, so i guess older kernels (and distros) tend to
be buggy with virtual machines.

But there might be some stuff that shouldn't be enabled for older
processors, you can see it works in my tests.

Some builtin modules also produce a heavier system with processes
running, xfsalloc/xfs_mru_cache should not be running.

CONFIG_XFS_FS=y -> CONFIG_XFS_FS=m
CONFIG_BTRFS_FS=y -> CONFIG_BTRFS_FS=m

I agree that kernel 4.9 is too buggy, it will be edited using micko's
4.9 configs as the base. Have to download old isos. Sheesh

But let's not forget that inconsistencies might be introduced with
updates, and aufs might cause (serious) issues, because it's not LTS.
That's the problem.

This definitely needs someone who compiles regularly, edits kconfigs
and tests kernels, i'm not the one. And a new repo for the kernel-kit.

**Comment by wdlkmpx** [comment]
The only difference between the kernel-kit's k4.9 dot config and
micko's k4.9 .config is:

micko's config disabled this:
CONFIG_TMPFS_XATTR
CONFIG_OVERLAY_FS

Otherwise it's identical.

CONFIG_TMPFS_XATTR might be the problem..

- CONFIG_TMPFS_XATTR=y
configs_x86/DOTconfig-3.2.102-i486-4g
configs_x86/DOTconfig-3.14.79-i686-4g
configs_x86/DOTconfig-3.16.43-i686-4g
configs_x86/DOTconfig-4.1.39-i686-pae
configs_x86/DOTconfig-4.4.70-i686-pae
configs_x86/DOTconfig-4.9.22-i686-pae
configs_x86_64/DOTconfig-3.14.79-x86_64
configs_x86_64/DOTconfig-3.16.43-x86_64
configs_x86_64/DOTconfig-4.1.39-x86_64
configs_x86_64/DOTconfig-4.4.70-x86_64
configs_x86_64/DOTconfig-4.9.30-x86_64

- CONFIG_TMPFS_XATTR is not set
configs_x86/DOTconfig-3.18.105-i686-4g
configs_x86_64/DOTconfig-3.18.105-x86_64
configs_x86_64/DOTconfig-4.14.20-Atom-cherrytrail

**Comment by ninaholic** [comment]
Thanks wdlkmpx. For now I can try compiling
1. 4.9.178 with CONFIG_TMPFS_XATTR=y
2. 4.9.178 without
3. 4.9.22 with CONFIG_TMPFS_XATTR=y
4. 4.9.22 without

And send them to foxpup just to see what they say. It might be that, or aufs/kernel change like you said. Be back in like a day maybe when this is all finished compiling on my Atom netbook :laughing:

**Comment by wdlkmpx** [comment]
My advice is that you don't. You might want to run an irc server or
something in your netbook.

A few weeks ago i bought an atom netbook, Dell Inspiron Mini 910...
$24 without the hard drive. Intel atom N270, a 32bit cpu. Almost same
specs as my toshiba NB100.  Cheap.

I still haven't tested it properly.

There is someone who is willing to compile kernels in his powerful
machine. It's norgo, but he said he's lazy and needs automated stuff.
He sent me an email.

In a really powerful machine (core i7) it takes a few minutes to
compile the kernel. I guess norgo also has a very fast internet
connection, so the stuff might be ready in a couple of hours.

In kernel-kit/build.conf there is the auto AUTO variable

## -- AUTO --
## Enforce automation of the process. Also triggered by: ./build.sh auto
## Every error is fatal, so you must specify all the needed stuff in
build.conf first..
#AUTO=yes

You might want to contact norgo privately and tell him that wdlkmpx is
asking some favors and that he must comply. Using slacko 142.

You might want to produce 4 kermel-kit tarballs with an auto
build.conf, and ask norgo to just run ./build.sh and upload the
resulting tarball to somewhere. Then you can just provide links to
pupfox

I have some plans but i've been coughing all day, i mean i've been
barking all day, and i play FreeCell in my tablet.
https://play.google.com/store/apps/details?id=net.runserver.freecell_free

**Comment by mavrothal** [comment]
Just to point out that the kernel in nanaholic's build is 3.16 and I replaced it with 4.9 64bit. 
Regarding configs XATTR is for extended attributes (metadata and the likes) and is required if you want to implement access control (ACL) but tmpfs does not need that and should not affect the tmpfs function unless  access limitations have been set for tmpfs.
Regarding compiling you can just compile the module for your kernel and ```insmod``` it at sysinit or rc.local
or try to blacklist it (even if builtin) and see if it makes any difference.

**Comment by ninaholic** [comment]
Sorry for bailing for this thread, I found the 14.2 build with Firefox 60+ freezing and pausing too much on my Atom N270 CPU no matter what kernel I used with it, and that slacko 14.0 build was much more reliable. Maybe it is because of the xorg version or using too much RAM as wdlkmpx said. I made a 14.1 build instead + devx with latest woof-ce that is working better, feel free to test it if you like:

https://transfernow.net/679mf4z56l8e
md5sum: ed18a38a572e5213d5d06657dedd8939

I learned to use default kernel and ptheme now for better results with aufs (though I think the ndiswrapper in 14.1 was made for kernel 3.14.55). I am making a 3.18.140 nopae kernel for it too for nopae and more meltdown+spectre mitigation, will upload it as a separate download when it's finished. I do not mind making kernels with kernel-kit as usually I am busy during the day and sleeping during the night anyway. :smile_cat:
