### ISSUE TITLE
Experimental has gone...........

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1477]
https://github.com/puppylinux-woof-CE/woof-CE/wiki/Building-using-the-'experimental'-branch

**Comment by Butterfly** [comment]
Hi, @peabee.. I just tried it and found the same. In instances like this, I always "back up" the URL until I hit something that fits what I had originally wanted. For this, that meant [puppylinux-woof-CE repositories](https://github.com/puppylinux-woof-CE). It's not appearing there, either, at least not publicly.

That `--depth 1` is a *HUGE* help for me on dialup. I found it buried out on the Internet last year. This is what I do:

```
git clone https://github.com/puppylinux-woof-CE/woof-CE.git --depth 1
git fetch --unshallow
```

Prior to finding that last year, *EVERY* attempt to clone *ANYTHING* from Github failed. That two-step deal seems to help keep Github happy. I wonder if it quickly downloads the more "volatile", frequently changing entries that I think are why clone attempts fail *CONSTANTLY* on dialup. After that, `fetch` can take its sweet time downloading the rest... successfully *EVERY TIME*. :tada: 

Am saying all that because I tweaked that experimental entry a couple ways, including with the simpler command I use, to see if Experimental might still pull up. It didn't show up.

Github/`git clone` DID do something odd, though. It asked me for my Github username and password. That was *NEW*. There was no password prompt when I first tried the command on that [building how-to page](https://github.com/puppylinux-woof-CE/woof-CE/wiki/Building-using-the-'experimental'-branch) you shared.

After trying it a few ways, I decided....

* Maybe Experimental was taken private for some reason? That would explain why I was asked for the password. When I gave that information, it wouldn't match any [puppylinux-woofCE](https://github.com/puppylinux-woof-CE/) "owners" which would explain `git` then failing to find. This is probably my best top guess.
* Maybe Experimental moved to another location?
* Maybe the Development structure was streamlined to help rope things in. There's sure a lot of work and not many people with the tech talent to help out... :broken_heart:

**Comment by ghost** [comment]
I notice there is a "Edit Page" and "Delete Page" button on it. I wonder if wdlkmpx would get mad is someone pressed the Delete Page button on that article. Then, only 43 'issues' to go :astonished: :laughing:

**Comment by mavrothal** [comment]
``git clone``` works fine here. 
```git checkout experimental``` revives the branch.
Experimental "disappeared" from github during the rebase and merge with testing.
You can browse the files of experimental from the tree of its [last experimental-specific commit](https://github.com/puppylinux-woof-CE/woof-CE/tree/e7a830414962b18ddd66b4838473e5d748b5b487) 
(The e7a83041 commit in experimental  is now 0336ac9e in testing)
Anyway, the wiki page is deleted now
