### ISSUE TITLE
Pi 4 kernel and raspi save part

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1501]
I've compiled a pi 4 kernel (armv7l) and new kernels for armv6 and armv7 (both tested - I'm unable to test the 7l kernel as yet). I uploaded them to ibiblio (with huge kernels - but they can easy be moved), but looking at the code in `support/kit_kernel.sh` maybe we need a git repo for kernels.

Also, ability to add 3 kernels would be good.

Digressing slightly, while saving to a folder works fine, we need to add the save partition to `cmdline.txt`

eg:

```
psave=mmcblk0p1
```

**Comment by woodenshoe-wi** [comment]
> ... looking at the code in support/kit_kernel.sh maybe we need a git repo for kernels.

I used a git repo because I don’t have access to ibiblio, and I didn’t want to ask peabee to upload some rather large files that might not be used by anyone else and just take up space on ibiblio.  The kernel source sfs files are pretty large, and at the time I was probably the only person doing Raspup builds.

I guess I also wanted to show how an individual with a Github or Gitlab account can maintain their own publicly accessible repos and interface them into the woof scripts.  If the Raspup build is now officially supported, I don’t see why using ibiblio would be a disadvantage.

> Digressing slightly, while saving to a folder works fine, we need to add the save partition to cmdline.txt

If you use the bootmenu.txt file instead of cmdline.txt, you can have entries for multiple save files.  They can also be on a USB  stick, so psave might not always be mmcblk0p1.  https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-distro/arm/raspbian/stretch/rootfs-skeleton/boot/bootmenu.txt

Maybe when the save dialogue lets you choose where to put the savefile/directory it could add an entry to bootmenu.txt?

**Comment by 01micko** [comment]
> If you use the bootmenu.txt file instead of cmdline.txt, you can have entries for multiple save files.

That is true anyway because init handles that case. I was booting the same card on the 0 and the 3 without issue.

> Maybe when the save dialogue lets you choose where to put the savefile/directory it could add an entry to bootmenu.txt?

Yes, that is the correct way to handle it. I plan on getting a dedicated usb3 hdd when my pi4 arrives and the save can go there. Surely then pi will be much faster!

I'll dig into `shutdownconfig` and make appropriate changes.

**Comment by woodenshoe-wi** [comment]
Although you can’t choose between different versions of the kernel or initrd like you can with a real boot loader menu, you can keep multiple versions of the main sfs / devx in their own folders, which is nice when you want to test out a new build but don’t want to delete the old one and are running out of SD cards. 😄

I know init will let you choose between multiple save files when they are all in the same place, but using bootmenu.txt they can be anywhere, and you can set a default and timeout.

Another issue with the Pis is that you can’t edit the boot options while booting like grub and syslinux can.  If you want to occasionally boot pfix=ram you can add an entry so that you don’t have to edit a text file every time.

With PCs there is really no good way to automatically add boot menu entries, but since bootmenu.txt is part of raspup and can be copied to any ARM builds that could use it, it should be easier to automatically add boot menu entries for ARM builds.

**Comment by 01micko** [comment]
Ok, I like the `bootmenu.txt` idea but it needs improvement in `shutdownconfig`. Instead of testing the software we need to test the hardware. I already have an alpha for raspi [based on devuan ascii](http://www.murga-linux.com/puppy/viewtopic.php?t=116529) and intend releasing a version based on slackware-arm. 

I have already made improvements to `raspi-version` such that it now works. Perhaps it needs an exit status such that if the tests are successful in the script then the program exits with `0` else it exits with `1`. Then modding `shutdownconfig` would be very easy.

I'll do some tests.

**Comment by 01micko** [comment]
There are a few of bugs in the shut down routine regarding `bootmenu.txt`

1. On initial save the entry to `bootmenu.txt` should be 'raspup saved session' or words to that effect

2. When you shutdown without saving (and this predates your efforts @woodenshoe-wi  ) a new half empty entry is created. I don't know why yet.

3. The saved session should be the 'default' entry IMHO

**Comment by 01micko** [comment]
Commit 12111462e2598049680a1a1714e52ec7ebf62b80 addresses the kernel issue _hopefully_ without breaking the gitlab/github code.

I'll check out the `bootmenu.txt` issues when I get around to releasing a raspup version
