### ISSUE TITLE
Missing 'strings' applet in busybox-1.31.0

### ISSUE THREAD

**Issue by radky2** [puppylinux-woof-CE/woof-CE#1516]
In Puppy, it seems the 'strings' applet is present in busybox-1.30.1 but missing in the updated busybox-1.31.0.

For example, /usr/sbin/getflash calls 'busybox strings' and this fails with busybox-1.31.0.

Thanks

**Comment by 01micko** [comment]
Hi Roger,

It's here in 64 bit

```
# busybox strings --help
BusyBox v1.30.1 (2019-04-24 21:50:47 +08) multi-call binary.

Usage: strings [-fo] [-t o/d/x] [-n LEN] [FILE]...

Display printable strings in a binary file

	-f		Precede strings with filenames
	-o		Precede strings with octal offsets
	-t o/d/x	Precede strings with offsets in base 8/10/16
	-n LEN		At least LEN characters form a string (default 4)
```

**Comment by wdlkmpx** [comment]
strings is part of binutils (devx), a hack was removed and I disabled the applets that replace devx apps (ar, strings, and probably some other applet)

I guess the applet should be enabled again, a new package should be uploaded, and the hack should be restored. zwn needs the hack as well.

**Comment by 01micko** [comment]
Also concerning busybox... the _coreutils_ 'stat' is at `/usr/bin/stat` and at least in zwn gets clobbered by busybox `/bin/stat`. That error is somewhat fatal in pupmode 13 because then we get an error in `save2flash` because busybox stat can't handle the mountpoint (%m) directive (IRRC - sorry late on a work night so description may not be 100% accurate)

**Comment by wdlkmpx** [comment]
It's because zwn uses a very simple logic to create symlinks... it must be more robust because woofce requires it.

I compiled 4 cross compilers with significant updates

I guess it's always good to have a busybox as complete as possible, but some symlinks should not be created even if the full app is missing. I found that the busybox taskset breaks winetricks..

I'll create support/busybox_symlinks that will be called by both build systems, 3 build systems in fact

**Comment by wdlkmpx** [comment]
This issue should be fixed now. I enabled more applets including
adduser, addgroup, etc, this may introduce some other issue, but it's
easy to prevent some symlinks from being created, in
support/busybox_symlinks.sh there is an 'exception list'.

The zwn issue should be fixed as well
(https://github.com/puppylinux-woof-CE/woof-CE/commit/88a8d06362acff46f88d0a5c850ba94b2a228ace),
but i see the zwn slacko is broken (no busybox, no uefi), i'll take
care of that later.

**Comment by s243a** [comment]
If we are considering making a fuller version of busybox, then consider adding the -p (i.e. passthrough) option to the busybox version of cpio.

**Comment by wdlkmpx** [comment]
In busybox 1.31.0 cpio supports -p, but the busybox cpio symlink is
not created because the full app is present.

The symlinks are created "dynamically" depending on what apps are
missing, but some symlinks are not created even when the full apps are
missing.

In some cases a more consistent behavior can be achieved by calling
busybox app rather than expecting that a busybox applet will be there.

It's always good to have many busybox applets even when many of them
are not used, to see how busybox evolves and how much busybox applets
differ from the full apps.

That's why scripts are expanded or created, to deal with this situation.

**Comment by wdlkmpx** [comment]
As we can see, there is a reason to use the latest woofce, with fixes
and updates being applied, supporting a distro as old as slackware
14.0, some updates apply to all pups. If no release isos/zips/tars are
found, it only takes one command to build a iso from start to finish:
./build.sh (zwn: ./build-sfs.sh + ./build-iso.sh).

busybox is the rolling release part, i will compile some generic and
static apps to update the older compat distro p.u.p.s.

Even when i'm no longer actively contributing code, i will still
compile apps, as a rescue distro requires updated apps you know.

**Comment by radky2** [comment]
@wdlkmpx wrote,

> This issue should be fixed now. I enabled more applets including adduser, addgroup, etc, this may introduce some other issue, but it's easy to prevent some symlinks from being created, in support/busybox_symlinks.sh there is an 'exception  list'.

> 

Thanks for the updated 'static busybox-1.31.0 rev 2'
