### ISSUE TITLE
Roxfiler window no longer shows /mnt/home in title

### ISSUE THREAD

**Issue by rserwin1** [puppylinux-woof-CE/woof-CE#1519]
In the Dpup stretch forum thread, WiZard asked:
"Is there a way to change rox's behavior ... to identify the home partition as: /mnt/home?"

Rox/roxfiler has shown the home partition as /mnt/home until recently.

Release notes from version 2.0.x include the change:
"- Mounting a directory that was accessed through a symlinked directory
used the symbolic path, confusing the mount command (Thomas Leonard;
reported by Anthony DiSante)."

In implementing that change, the title on windows apparently shows the target directory instead of the directory/symlink originally specified on the roxfiler command.

I find that adding option "-d" (roxfiler -d /mnt/home) results in "mnt/home" appearing in the window title. But that might be an oversight; it simply indicates the argument is a directory. Without the option and assuming roxfiler determines that the argument is a directory, the behavior seems inconsistent. Adding that option to drive_all or defaultfilemanager_x would seem to be a workaround.

Perhaps a better solution is for woodenshoe-wi to fix the source code to use the original argument in the title without disrupting the fix for the "confusing" issue. Or maybe re-code the fix another way to avoid impacting the window title.

Possibly related question:
Does anyone know why defaultfilemanager_x does this?:
if grep -q roxfiler /usr/local/bin/defaultfilemanager ; then
exec defaultfilemanager -x "$@" "$@"
else
exec defaultfilemanager "$@"
fi

With the workaround,
defaultfilemanager -x -d /mnt/home -d /mnt/home
results in two windows being shown, one with /mnt/home and the other with /initrd/mnt/devsave. Why the second '"$@"'?

Now that "rox" is a symlink to "roxfiler", why distinguish between them in defaultfilemanager_x?

Defaultfilemanager_x is used in drive_all, filemnt, fontmanager, pmount and pupcamera (in bionicpup64).

**Comment by wdlkmpx** [comment]
rox is not a symlink to roxfiler, it's a symlink to defaultfilemanager.

Defaultfilemanager_x is a hack, instead of keeping the same hack in several scripts i moved it, The -x param "re-examines" the file or dir. this is something that rox users seem to need, i don't need it.

Now rox users can press F5 and the (rox) directory contents are updated.. i can remove the hack, but i may need the approval of some sort of authority.

I find that in pcmanfm sometimes i need to press F5 to refresh,, some changes are not recorded.

I guess scripts had the -d param but it was removed, What does that mean?

Maybe another script: defaultfilemanager_d . what else can i say.

**Comment by wdlkmpx** [comment]
Commit https://github.com/puppylinux-woof-CE/woof-CE/commit/a7591a5acdc1d4267d9f01d1320b94e7dc8fd571 fixes the issue for me.. i click on the "home" partition icon and i see /mnt/home in the title

I guess the fix is enough .. the fix applies to several key scripts, and people should -d param in their scripts or create a wrapper like defaultfilemanager_x

**Comment by 01micko** [comment]
Just did an old slacko build and `/mnt/home` works. Also works in recent `raspup`.

Closing
