### ISSUE TITLE
woof needs an easy, automated way to turn off services

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1522]
Building raspup buster I now have it booting, x running, sound and connecting on pi 4 :beer: 

However, the system services in `/etc/init.d/` spam the the early boot console with rubbish that I don't need or want to know. For the most part they should be turned off, except for essentials like sound and such. As a side note, and the topic of another issue I guess, their messages should be suppressed.

Perhaps a simple loop in in `3builddistro-Z` (btw, when we dropping the `-Z` ? , can be symlinked back for legacy) after the rootfs is fully populated could be added? A simple config file in `support`? 

I'm open to ideas.

**Comment by 01micko** [comment]
Ok, stopped the messages spamming console, their was a missing dep :fearful: 

Still, the main issue remains...

**Comment by wdlkmpx** [comment]
In my modest build i only see one service that looks out of the place:
- cupsd

I have never printed in puppy so i don't know what happens if that service is disabled by default. Of course more services are added when you install some packages.

Both build systems actually need to disable or delete some services that conflict with puppy apps. The packages templates (aka the pile of hacks) is being decimated and the code moved to support/rootfs-hacks* so that there's no need to write new hacks for zwn. Just adapt what's already available in the build scripts (3builddistro) and the packages-templates.

Both build systems share more and more code, but i can certainly morph the current stuff into an hybrid zwn, but there are obstacles, we have to support external stuff and builders. We have to please everyone. We have to renounce to our own goals and principles.

In the packages-templates it's to easy to identify what packages conflict with puppy, and then a more universal fix can be achieved by looking in the packages contents (slackware/debian/devuan/ubuntu) and only deleting specific files.

Talking about services, some puppy stuff only works with busybox applets. Perhaps this should integrated into rootfs-skeleton:
http://distro.ibiblio.org/puppylinux/pet_packages-noarch/acpid-busibox-4.pet ..

**Comment by wdlkmpx** [comment]
Actually a better solution would be to add something like this to basesfs

%pet http://distro.ibiblio.org/puppylinux/pet_packages-noarch/acpid-busibox-4.pet

Or convert the .pet to .deb witht the debiandog pet2deb or .txz with fatdog's pet2txz
[pet2txz.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/3517824/pet2txz.gz)

**Comment by 01micko** [comment]
I worked around this in my pi release in a z-hack pet. Still, it would be nice to be a woof configured option in the conf file.

**Comment by 01micko** [comment]
I suppose it can be done in the build conf. closing
