### ISSUE TITLE
possible udev issue

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#1524]
on the forum boolean1 has posted this
```
i dont think udevd is initialised properly in /etc/rc.d/rc.sysinit 
there are no /dev/disk/by-id/ symlinks , despite the fact that there is a rule 
/lib/udev/rules.d/60-persistent-storage.rules to create it, i also checked by 
putting my own .rules file in /etc/udev/rules.d and it fail to do anything for 
some reason on boot, you can fix this by doing a

udevadm trigger

after doing this all the missing symlnks and nodes in /dev/ appear , 
this leads me to believe that the udevd deamon is not initialised properly 
in /etc/rc.d/rc.sysinit?
```

**Comment by wdlkmpx** [comment]
`udevadm trigger --action=add ....` is called up to 3 times in rc.sysinit (with specific params)

I remember that years ago there was a `udevadm trigger` that was called unconditionally (a change i made) and some people reported hangs, it was not that simple then, it may not that simple now.

There is also a lot of code that is not that relevant when using huge kernels.

This kind of changes requires testing in a lot of machines and compat distro versions.

**Comment by peabee** [comment]
What build was this problem seen on?
On Slackware based pups I don't have /dev/disk at all.....but everything seems to work fine??

**Comment by 01micko** [comment]
Newer kernel >>> newer udev.

I had problems with raspi kernel 4.19 until I upgraded eudev.. (hint: compile it!)

```
./configure --prefix=/ \
			--bindir=/bin \
			--sbindir=/sbin \
			--libdir=/lib \
			--includedir=/usr/include \
			--localstatedir=/var \
			--sysconfdir=/etc \
			--mandir=/usr/share/man \
			--disable-selinux
```

latest ver : 3.2.8

**Comment by drscavngr** [comment]
I am boolean1 on murga-linux , i didnt report it here because i thought this might be specific to Bionicpup ,

i encounter it when i added : /etc/udev/rules.d/60-ioschedulers.rules
```
# set scheduler for NVMe
ACTION=="add|change", KERNEL=="nvme[0-9]*", ATTR{queue/scheduler}="none"
# set scheduler for SSD and eMMC
ACTION=="add|change", KERNEL=="sd[a-z]|mmcblk[0-9]*", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="mq-deadline"
# set scheduler for rotating disks
ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"
```
and then the cat /sys/block/sda/queue/scheduler  is none , and the modules bfq and mq-deadline are not loaded , compiling eudev-3.2.8 from scratch would not fix it 

only adding  udevadm trigger in rc.sysinit
 would fix it

**Comment by wdlkmpx** [comment]
I guess there is duplicate code in rc.sysinit, the old methods & the udev method. And, what else i was going to say

I guess it's not simple, and unexpected behavior may happen in some machines if the full udev stuff is triggered. But i guess we can try some changes, i think ninaholic has some old netbooks where bugs are easily triggered. I also have a couple of netbooks,  made in 2007/2008, not that old.

I guess some kernel versions also are a bit buggy and will probably hang in some cases... after kernel polling (triggered by rc.sysinit) was introduced, mavrothal had issues with k3.16 x32 in a virtual machine, but the issue was fixed for him with a newer 64bit kernel. I had no issues with any kernel in qemu and virtual box.. so, as we can see, things are not simple, different behavior happens with different hardware and kernel.

So we have to test and see if some sacrifices are needed to get udev to work properly.

Some people have keyboard issues with xorg+auto adding of devices, they have better luck with, kbd_drv.so, mouse_drv.so, and synaptics_drv.so.

I never used any other distro for more than a few hours, so i guess we're missing something, but what can it be.

**Comment by wdlkmpx** [comment]
There are 2 approaches to fixing bugs:
- delay the change for a year (get rid of the multiarch symlink)
- make it happen now and force everyone to test it - neat!

Commit https://github.com/puppylinux-woof-CE/woof-CE/commit/6b8fe17701d2563c696cadcec829f1e3564e1a4a tries to address this issue, it seems to work fine in 2 machines using a few compat distro versions.

But the boot process takes a bit longer.

This is the file:
https://raw.githubusercontent.com/puppylinux-woof-CE/woof-CE/testing/woof-code/rootfs-skeleton/etc/rc.d/rc.sysinit

just copy and paste into your current rc.sysinit.

**Comment by peabee** [comment]
Thread started:
http://www.murga-linux.com/puppy/viewtopic.php?p=1035024

**Comment by 01micko** [comment]
Changes seem ok in rpi4 and rpi0 using latest

**Comment by peabee** [comment]
From BarryK.........
http://www.murga-linux.com/puppy/viewtopic.php?p=1035191
other posts are also all positive........

**Comment by rizalmart** [comment]
udevadm settle -t 20 tooks 20 seconds too complete. But on Tazpuppy udevadm settle --timeout=120 tooks 1-3 seconds to complete.

however when 1-3 second timeout of udevadm it seems udev was started propely. Please try to check it to your respective machines using 1-3 second timeout on udevadm settle

**Comment by wdlkmpx** [comment]
udevadm settle --timeout=120 = 9 seconds
udevadm settle -t 20                 = 9 seconds

Running a pentium 4 pc, kernel 4.1.48

Maybe 30 seconds is a good timeout?

I use xz with no extreme compression methods, with 512k dict i expect 25 seconds. with 1024k dict i expect 40 or maybe 50 seconds.

There is a timer after that... before starting the network service.. 5 seconds, due to issues identified years ago.. and still present today, some network modules take too long to load/initialize, i wonder if it's ok to delete it now.

SNS and other apps probably need a revision..

The thing should work ok in a wide range of machines, old and new.

**Comment by drscavngr** [comment]
I dont think Udev speed is related to how fast specs are, all that it does is query metadata about devices, so it can be slow when it tries to query devices with buggy drivers, anyway it is almost standard Linux now, so i am glad we got rid of the previous hacky shortcuts

About networking,  i think there should be no netwoking done in rc.sysinit  beside assigning ip address to lo interface,  this should be done entirely in init.d or after x start and be easily removable, i had to track down a lot of scripts to stop wpa_supplicant from firing up on boot, as  i like to have a main tmux window with pans populated with wpa_supplicant, dhcpcd, named, tor,,,etc to be able to observe any problem in one window

I had to comment out ###network_default_connect --sysinit
And added
/etc/rc.d/rc.network_basic

**Comment by wdlkmpx** [comment]
Perhaps rserwin1 has some ideas 

So far i don't see new errors in /var/log/messages, but by reading rc.sysinit, people have tested it in a MAC, the uefi stuff also includes grubia32.efi, so it should boot on some old macs.. and that's when this change might break stuff if it was working properly, 'cause i read mac .support is buggy in linux. I'm just theorizing.

**Comment by 01micko** [comment]
Is this issue resolved? (for me it is)
