### ISSUE TITLE
Long file names mess up Recently Used display in JWM menu

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1532]
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-packages/jwm_config/usr/local/jwm_config/menu_build_recent_docs

if a filename is too long then display switches from right of menu to left of menu and is truncated to very few characters

![Screenshot](https://user-images.githubusercontent.com/5926865/64905761-debf4a80-d6d4-11e9-80fe-539ccff84f8a.png)

@zigbert

**Comment by 01micko** [comment]
Couple of questions..
1. Did a program create that file? If so file a bug report to it's maintainer.
2. If you created it yourself, why?

Incidentally, if it is much deeper in directory hierarchy it would exceed `PATH_MAX` defined in `<limits.h>` (in C, C++ etc) and possibly break poorly written programs.

**Comment by peabee** [comment]
@01micko 
File was specially created just to test a problem report by B.K. Johnson: see
http://murga-linux.com/puppy/viewtopic.php?p=1035833#1035833

the long filename can result from a long path as well as the filename itself

**Comment by 01micko** [comment]
TBH, any filename that long is ridiculous. Sure it might be a problem but it will go away with access to the next 20 files. I'm not prepared to slow down the script that accesses `/root/.local/share/recently-used.xbel` just to appease a stupid file name. Think about what is involved..

1. screen size
2. font size
3. character size (eg: cjk widechars)
4. the time to calculate _all_ that 

Perhaps @joewing might be able to fix it in JWM so that ridiculous menu entries either fail to appear or are truncated. I doubt @zigbert (he's not likely to be around until the Northern winter bites anyway) will want to fix it either so I'm closing this issue.

**Comment by 01micko** [comment]
BTW, kinda confuses rox when deleting it too :-1:

**Comment by peabee** [comment]
I will report to the original problem reporter ......... B.K. Johnson
http://murga-linux.com/puppy/viewtopic.php?p=1034317#1034317

**Comment by peabee** [comment]
See:
https://github.com/puppylinux-woof-CE/woof-CE/pull/1602
