### ISSUE TITLE
Check dependencies installed pkg has disappeared

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1557]
Check dependencies installed pkg
was a useful function that has been deleted for no particular reason?
However rootfs-skeleton/usr/local/petget/check_deps.sh
still exists but with different functionality - in particular no gui - 
and this confuses PupControl which puts an item into its Software menu
that doesn't work.
Probably commit: https://github.com/puppylinux-woof-CE/woof-CE/commit/b61c8dfcd2a0363edd31cc1e34fec29bc0a1b4b7
is to blame by @wdlkmpx 
It would be nice if the "Check dependencies installed pkg" could be reinstated into the menu?

**Comment by wdlkmpx** [comment]
I'll see if I can restore it. But as I said many times, people don't listen to those who read the code, when the say the ppm is so badly designed that is unreadable and unmaintainable, something that should have been deleted and replaced by something else. Just because it looks good it doesn't mean it's a good package manager.

**Comment by peabee** [comment]
Can somebody test:
http://www.smokey01.com/peebee/downloads/test/check_deps_ppm-2001.pet
if it works correctly then I'll put it back into Woof-CE
For me - it does show missing libraries OK - but not sure if its detecting missing packages?

**Comment by peabee** [comment]
was a fundamental problem with .debs..... LSB PIE executables ........
https://github.com/puppylinux-woof-CE/woof-CE/commit/dbe87e31c369409c9ea44c2c17ad7622fee9ea4e
.pet reuploaded

**Comment by peabee** [comment]
Closed by #1736
