### ISSUE TITLE
./0setup slacko 14.0/14.1 warnings

### ISSUE THREAD

**Issue by ghost** [puppylinux-woof-CE/woof-CE#1600]
Hello,

When building these four distros I got these warnings at the end of 0setup:

```
slacko 14.1 64-bit -

WARNING: npapi-sdk pkg was not found!
WARNING: xcur2png pkg was not found!

slacko 14.1 -

WARNING: npapi-sdk pkg was not found!
WARNING: pure_ftpd pkg was not found!

slacko 14.0 64-bit -

WARNING: xcur2png pkg was not found!

slacko 14.0 -

WARNING: libatomic pkg was not found!
```

I'm guessing the solution is to delete these entries from the related PKGS-SPECS file now, but wanted to make sure :cat2:

**Comment by wdlkmpx** [comment]
Commit https://github.com/puppylinux-woof-CE/woof-CE/commit/0aad632251377d1daa9a0e70306aa5ae791682c4 should fix most warnings 

According to
https://github.com/puppylinux-woof-CE/woof-CE/wiki/Scripts-and-dependencies

pcur requires xcur2png.. I tried to create a generic build, but the resulting binary requires a specific libpng version and won't run with anything else (specific symbols).

I'm yet to compile xcur2png for slacko64-14 and slacko64-14.1

Other bugs I found in slacko 14 and/or 14.1:
- issues with xarchiver (fixed by https://github.com/puppylinux-woof-CE/petbuilds/commit/a3fe3afad9a533a6ebc98e7f7717336fb6bea051 .. I'm yet to upload new xarchive packages).
- mplayer doesn't like OSS audio output.. video playback stalls. Should default to alsa, but somehow it doesn't. I'll compile mplayer 1.4 with very few dependencies and video/audio output drivers
