### ISSUE TITLE
arm arch : we need an image creator script

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1667]
The script in `support/arm_sd_image.sh` is archaic and it is designed for a FULL install. It won't work for current raspup (or anything else that runs in RAM) so should be deleted. It also installs the file onto an sdcard, not needed.

I think the current method of making an installable zip file is good but an image zip file would be much more friendly to windows users. I don't think it needs to be xz compressed. `zip -9` produces a zipped image file which is only 2 meg bigger than the installable zip file.

I'm in the process of writing this new script after successfully creating an image of 2GB. It has an ext4 no journal third partition of ~800M (and a swap partition sandwiched between the first vfat partition) all created on the commandline. I intend to make the swap partition optional. 

One problem I ran into is that we have the loop module as a builtin in the kernel so I had to reboot with `loop.max_part=31` on the kernel commandline. More on that later.

I  dd'd the image to a 16GB micro-sdcard and then resized the partition in gparted (on my main box) but this should be doable on the pi at bootup with `parted` .. perhaps as an option in `quicksetup`.

Boots, swap is recognised, everything runs as normal.

**Comment by wdlkmpx** [comment]
Yeah it can be deleted. I used that script to learn how to mount a hdd img with 2 partitions.

Then I wrote a script using the same base to programmatically create a hdd img. create partition table and partitions (vfat+ext4(nojournal or vfat+f2fs), mount the partitions and install something.

Also a new option in bootflash to write .img[.gz/xz] to flash drive.

But I was moving out some code to a cli app, which includes a command to write a .img.gz/xz to a usb drv and automatically resize the last partition (ext4 or f2fs). 

I'll push the changes one of these weeks or months

**Comment by wdlkmpx** [comment]
I had a commit in a branch where I applied very interesting changes to arm_sd_image.sh, the changes I made to create and test the new bootflash option to write a .img file to a usb flash drv.

I also had another big commit that changed the live cd stuff to use cdboot-XXXXXX.tar.xz, both changes and probably some other changes are gone.

Yes I deleted the commits before adding commits to fix full installs and hide the option to perform full installs.

**Comment by wdlkmpx** [comment]
Commit https://github.com/puppylinux-woof-CE/woof-CE/commit/241dfe9d744848293f3161b076b1448367e45626 makes arm_sd_image.sh create .. the sd image.

It's just an example, but is already complete, the only thing to change is what to include in each partition. I tried to recreate the lost commit and didn't test the code with the build system.

But two weeks ago I did test that code snippet in a separate script and the resulting .img worked in a usb stick, I mean I saw and opened the files I copied to the hd img partitions.

**Comment by wdlkmpx** [comment]
Actually it wasn't a complete example, I forgot to copy & paste the code to format partitions.. fixed by https://github.com/puppylinux-woof-CE/woof-CE/commit/f8d50effb82136e2f09c1a44354e9f79611ea05e

Well that's my method, the code to identify the offset to mount the partitions with mount/losetup is the key.

It's the experience gained by rewriting bootflash several times what made the difference, because I couldn't find good examples. I wonder if there's a simpler way to do this.

**Comment by jamesbond3142** [comment]
> One problem I ran into is that we have the loop module as a builtin in the kernel so I had to reboot with `loop.max_part=31` on the kernel commandline. More on that later.
> 

Assuming you have a kernel with the device-mapper configuration enabled. All you need is a tool called [kpartx](https://www.linux.org/docs/man8/kpartx.html). It works very similarly like losetup but it uses the device-mapper instead of the loop-module; and it can access access partitions on the fly: no reboot required. The binary comes from the "multipath-tools" source package; it is easy to build: a recipe is available [here](http://distro.ibiblio.org/fatdog/source/800/recipes/kpartx-0.7.8-x86_64-1.tar.gz).

You can create the image using dd as usual, partition it using fdisk or sfdisk, map it via kpartx, mount the partition as usual, copy files as usual, unmount, unmap, and done. No reboot required.

**Comment by 01micko** [comment]
Thanks @jamesbond3142 but I've done it without kpartx (did read bout it beforehand) and boots successfully with choice of image size (default 2GB - needs work), choice of vfat size (default is 512M), choice of storage partition type, ext2,3,4, ext4 no-journal, f2fs (default ext4 no-journal) and swap y/n (default y). Swap is second partition if chosen for ease of growing the linux partition to fill the media.

My approach was to build the zip anyway - I plan to offer both zipped files ready to copy to vfat partition and the image ready to 'flash' (don't like the term but seems to be popular) to sd/micro-sd card. My method and @wdlkmpx can co-exist but I think the best idea is to cherry pick the best of each and merge the code.

code follows

```sh
#!/bin/sh

# designed to be called from 3builddistro

# see https://unix.stackexchange.com/questions/87183/how-to-create-a-formatted-partition-image-file-from-scratch
if cat /sys/module/loop/parameters/max_part | grep -q '0' ; then
	echo "Please add -"
	if lsmod | grep -q 'loop' ; then
		echo "options loop max_part=31
to /etc/modprobe.d/loop.conf"
	else
		echo "loop.max_part=31
to your kernel commandline"
	fi
	exit 1
fi

v=0.1
CWD=`pwd`
[ -e "$CWD/tmp" ] || mkdir -p $CWD/tmp
TMP=$CWD/tmp

TSIZE=${TSIZE:-2000}
FMT=${FMT:-ext4nj}
SWAP=${SWAP:-y}
fatSIZE=${fatSIZE:-538}
LOOPDEV=''
case $SWAP in
	y)PNUM=3;;
	*)PNUM=2;;
esac

# -------------------- functions ---------------------------------------
_help() {
	echo "${0##*/} v $v"
	echo
	echo 'usage:'
	echo "${0##*/} [OS]"
	echo "where OS is the zipped file from recently built woof process"
}

_mk_img() {
	echo "making $1"
	dd bs=1M count=${TSIZE} if=/dev/zero of=$1 && sync
}

_parted_img() {
	IMG=$1
	echo "partitioning $IMG"
	echo "$fatSIZE ."
	# make partition table
	parted -s "$IMG" mklabel msdos || return 1
	# make vfat partition 
	parted -s "$IMG" mkpart primary fat32 2048s $fatSIZE || return 1
	sync
	# make swap partition 
	if [ "$SWAP" = 'y' ] ; then  
		parted -s "$IMG" mkpart primary linux-swap $((1 + $fatSIZE)) $((2 * $fatSIZE)) || return 1
		sync
	fi
	# make the other partition
	parted -s "$IMG" mkpart primary ext2 $((2 * $fatSIZE)) -- -1 || return 1
	sync
	return 0
}

_format() {
	echo "Formatting $IMG"
	LOOPDEV=`losetup -f --show $IMG`
	# vfat
	mkfs.vfat -F 32 "${LOOPDEV}p1" || return 1
	sync
	# swap
	if [ "$SWAP" = 'y' ] ; then
		mkswap "${LOOPDEV}p2" || return 1
		sync
	fi
	# linux
	case $FMT in
		ext2) mkfs.ext2 -F "${LOOPDEV}p${PNUM}" || return 2;;
		ext3) mkfs.ext3 -F "${LOOPDEV}p${PNUM}" || return 3;;
		ext4) mkfs.ext4 -F "${LOOPDEV}p${PNUM}" || return 4;;
		ext4nj)FS=ext4; mkfs.ext4 -F -O ^has_journal "${LOOPDEV}p${PNUM}" || return 4;;
		f2fs) mkfs.f2fs "${LOOPDEV}p${PNUM}" || return 5;;
		*)return 10 ;;
	esac
	sync
	mkdir -p ${TMP}/vfat # mountpoint
	mount -t vfat ${LOOPDEV}p1 ${TMP}/vfat || return 10
	return 0
}

_copy_to_vfat() {
	unzip $1 -d ${TMP}/vfat >/dev/null 2>&1 || return 1
	sleep 2
	sync
	umount ${TMP}/vfat >/dev/null 2>&1
	sync
	losetup -a | grep -q "${LOOPDEV}" && losetup -d "${LOOPDEV}" >/dev/null 2>&1
	return 0
}

#-----------------------------------------------------------------------

[ ! $1 ] && _help
OS=${1##*/}
OS=${OS%\.*}
echo
echo "Now converting $OS to a flashable image file."
echo "params: size - $TSIZE; swap - $SWAP; filesystem - $FMT;"
echo
newTSIZE=$(($TSIZE / 1000))
IMG=${TMP}/${OS}-${newTSIZE}gigabyte.img || exit $?
_mk_img $IMG || exit $?
_parted_img $IMG || exit $?
_format $IMG || exit $?
_copy_to_vfat $1 || exit $?
echo "back to 3builddistro"
echo
# hand back to 3builddistro
```
the 3builddistro  changes

```diff
--- ../woof-CE/woof-code/3builddistro	2019-11-16 20:03:09.412899701 +1000
+++ 3builddistro	2019-11-17 06:18:24.476756837 +1000
@@ -961,6 +961,18 @@ if [ "$SDFLAG" = "zip" ];then
 			( cd ../${WOOF_OUTPUT} ; md5sum ${DEVXSFS} > ${DEVXSFS}.md5.txt )
 		fi
 	fi
+	if [ "$MKIMGFLAG" ];then
+		FMT=$FMT TSIZE=$TSIZE SWAP=$SWAP ../support/mk_arm_img.sh ../${WOOF_OUTPUT}/${ZIPNAME}
+		# we're in sandbox3
+		TGTIMG=''
+		cd tmp # can't run in subshell
+		SRCIMG=`find . -type f -name "${DISTRO_FILE_PREFIX}*img"` 
+		TGTIMG=${SRCIMG##*/}
+		zip -9 ../../${WOOF_OUTPUT}/${TGTIMG}.zip ${SRCIMG}
+		cd - >/dev/null 2>&1
+		( cd ../${WOOF_OUTPUT} ; md5sum ${TGTIMG}.zip > ${TGTIMG}.zip.md5.txt )
+		rm -rf tmp/ # we're still in sandbox3
+	fi
 
 elif [ "$SDFLAG" ]; then #120506 sd image
 
``` 

The vars are set in _00build.conf

```sh
BUILD_ZIP=yes
MKIMGFLAG=yes
#FMT ext2,3,4, ext4nj (no journal - default), f2fs
FMT=f2fs
#TSIZE is total size of image - default 2000
TSIZE=4000
#SWAP y/n (default y)
SWAP=no
ADD_GIT_HASH_TO_FILENAME=yes

```

`MKIMGFLAG` must be set as well as `BUILD_ZIP`. Others are optional.

Produces a zipped bootable image in `$OUTPUT`.

**Comment by 01micko** [comment]
Ok, kpartx now seems to have been swallowed up by [multi-path-tools](https://git.opensvc.com/gitweb.cgi?p=multipath-tools%2F.git) 

I might try and build it - I have libdevmapper so *should* build.

**Comment by 01micko** [comment]
Builds ok, needed an older version from a 14.2 slackbuild. Also needed to install
liburcu-0.9.2
libaio-0.3.109
json-c-0.12

**Comment by 01micko** [comment]
@wdlkmpx just going through the code from 241dfe9 and f8d50ef it seems it doesn't suit the design of @woodenshoe-wi 's original raspup-stretch which I carried over to buster. The fat partition needs to be somewhat greater than ~300MB to allow some wiggle room as all the files are copied there and the linux partition is used purely for the savefile/folder and extra sfs and whatever else.

**Comment by wdlkmpx** [comment]
I was just showing a proof of concept, which requires special boot params.. arm_sd_image can be deleted or rewritten. Whatever works.

Changing some values my work:
- mkpart primary fat32 4MiB 80MiB -> 500MiB
- mkpart primary ext2 100MiB 100%  -> 520MiB 100%

But ext2 = ext4nj

Since commit https://github.com/puppylinux-woof-CE/woof-CE/commit/a775631bdf4f7824a96b64d2afcb30da77266137 bootflash can handle a .img file and will automatically resize the 2nd partition (ext4, f2fs)  if a 3rd partition is not found. Some functions were moved to /usr/sbin/pdsk, which will be a big cli script.

![Screenshot(16)](https://user-images.githubusercontent.com/10052849/69000072-ebdefc80-0904-11ea-9d38-8a491eb234b7.png)

**Comment by 01micko** [comment]
re `arm_sd_image` I suppose the way I handle vars that can be changed in my above script would work well - eg:
```
/bin/sh
# script .sh does something
VAR=${VAR:-1234}
echo $VAR
```
Then they can be stored in `_00build.conf` and passed to the script. - eg:
```
VAR=5678
VAR=$VAR  /path/to/script.sh
```

As for `/usr/sbin/pdsk`, can the resizepart stuff be cut and put into a standalone script? That way, when `PUPMODE=5` and a removable drive is detected as not full then something can be run from `/etc/rc.d/rc.update` to resize the last partition, so long as it is of type linux.

This is the only way to support most windows users who write the image to card/usb with some windows GUI app.

**Comment by woodenshoe-wi** [comment]
If resizing the last partition of an SD card on first boot would be acceptable, maybe there would be something useful from this pet?  http://distro.ibiblio.org/puppylinux/arm/pet_packages-armv6/sd-resize-0.1-armv6.pet

I haven’t tested it since I switched to using zip files, so it might not work with the new changes.

**Comment by wdlkmpx** [comment]
Rufus is the tool to write iso / img / img.gz files to usb stick/sd card in Windows.
https://rufus.ie/

This is a code snippet to resize the 2nd partition to fill the drive (from pdsk):

```shell
	fs=$(busybox blkid "$part2" | grep -o ' TYPE=".*' | cut -d '"' -f 2)
	case $fs in
		ext*)
			if ! type resize2fs >/dev/null ; then
				return 0 # not possible
			fi
			RESIZE_CMD="resize2fs -pf ${part2}"
			;;
		f2fs)
			if ! type resize.f2fs >/dev/null ; then
				return 0 # not possible
			fi
			RESIZE_CMD="resize.f2fs ${part2}"
			;;
		*)
			return 0 # unknown img
			;;
	esac
	#-
	echo -e "\nResizing $fs partition to fill the drive\n"
	if [ "`parted --help 2>&1 | grep resizepart`" ] ; then # 3.2+
		resizepart='resizepart'
	else
		resizepart='resize'
	fi
	echo "# parted --script -- ${xdev} ${resizepart} 2 100%"
	parted --script -- ${xdev} ${resizepart} 2 100%
	sync
	sleep 1
	echo "# $RESIZE_CMD"
	${RESIZE_CMD} || return 8
	sync
	sleep 1
	echo 'change' > /sys/block/${xdevname}/uevent
	sleep 1.5
```

I think it's a dangerous operation.

There should be a flag file that is written by the build system in the first partition or something: resizeme.flg -> 2 (number of partition to resize)

The file is read and deleted, the partition is unmounted and resized... but if this is done in the initrd, it can't use `parted` / `f2fs.resize`.. only `fdisk` / `resize2fs`

The zip file seems to be the `most friendly` approach.. unzip to the sd card and that's all.

I downloaded a few .img files and all of them contained full installs. The good thing about puppy is that it supports installation to a fat32 partition in a usb stick/sd card.

I'm not a fan of swap partitions or files in a sd card. That's why I tend to use hard drives if I'm using a machine with very limited ram// if that's not the case, I just try to avoid doing many things. flash drvs make sense when there is plenty of ram. 2gb+

**Comment by 01micko** [comment]
> flash drvs make sense when there is plenty of ram. 2gb+

That is when a problem arises with less powerful raspberry pi.

zero has 512 (less graphics)

pi 1 has 256 - 512 (less graphics)

zero has only 1 usb port, and in my case that is occupied by the wireless kb/mouse dongle.

Fan or not, swap is a requirement on those devices, unless the OS is tiny.

**Comment by 01micko** [comment]
@woodenshoe-wi the logic seems fine in the pet. Just no resize.f2fs. 

However I think a flag in `/DISTRO_SPECS` would be a better way. It is sourced very early in `init`. That way, boot doesn't need to get past `/etc/rc.d/rc.update` or actually mount the first partition under the right conditions. Of course the main fs is mounted to reach rc.update so all tools are available without bloating the initramfs, so, running in RAM, it _should_ be safe to resize any partition of the boot device, or even create partitions such as swap or ext... more thought is needed.

**Comment by woodenshoe-wi** [comment]
At the time, it was a full install.  The first partition had the boot loader and kernels, and the last partition had what would be the content of the main sfs.

If the main sfs is now in the first partition, it might be possible to resize the last partition with your method even if the main sfs is not loaded in RAM (pi zero).

The pet shouldn’t be used as a pet anymore.  Even if you did want to resize the last partition in the initrd, you only want it in the image file and not the zip file.  Pet package lists don’t give that kind of control, to include something based on what output file format you are using.

**Comment by 01micko** [comment]
@woodenshoe-wi 
I'm doing some experiments now with a 4GB vfat/swap/ext4nj image flashed to a 16GB micro sd on pi3 using your fdisk method in initrd using pfix=rdsh. Looks promising and there _should_ be no need to reboot.

**Comment by woodenshoe-wi** [comment]
If I remember right, the reboot was to switch initrd files.  The initrd in the pet only knew how to rename the original initrd that had been renamed by the pinstall script, and try to resize the last partition.

I wanted to keep it “modular”, a separate add on for Raspup builds but not touch the original init script.

Since I dropped image file builds as soon as I got Raspup to run as a “frugal” install with a main sfs, I hadn’t thought about the possibility of resizing what now amounts to the “save” partition after mounting the main sfs.

I brought up the pet in case you wanted to look at some tested and working (as of my last image file build which was awhile ago) code to do it in the initrd.  But if you can get the last partition resized while the boot partition and main sfs are mounted, your own method might be the easiest way to support f2fs.

**Comment by wdlkmpx** [comment]
fsck.f2fs 1.13.0 + resize.f2fs (symlink) + defrag.f2fs (symlink)
[f2fs_static_arm.tar.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/3865862/f2fs_static_arm.tar.gz)
[f2fs_static_x86.tar.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/3865864/f2fs_static_x86.tar.gz)

See https://github.com/puppylinux-woof-CE/initrd_progs/commit/580e53a51f598a6d24775705481aa66a62fc8d14

Adds 130kb to the initrd. Now it's possible to properly support f2fs savefiles, f2fs full installs and resize f2fs partitions from the initrd (.img)

I'll produce a new edgy initrd release tarball after some tests. I'll probably compile 4 new cross compilers with musl 1.1.24
