### ISSUE TITLE
Multisession CD/DVD support should be removed

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#1675]

**Comment by 01micko** [comment]
If it's removed Flash will have spasms; that may or may not be a bad thing. 

It should be made known that remastering the iso will be the alternative.

**Comment by wdlkmpx** [comment]
All I know is that he refuses to use `Flash` drives or hard drives.
It's not out of necessity but inability to use anything else than a
DVD.

It's said a multisession cd provides a high level of security

Well, with recent builds, you can get a similar level of security... by default.

It's quite easy to create a bootable usb stick with bootflash, many
possible options. Wow.

- Insert flash drive, make changes
- Create pupsave, reboot
- It should boot in pupmode 13 - boot to ram
- remove usb stick
- do many things
- want to save.. reinsert usb stick

It's probably the best option.

**Comment by wdlkmpx** [comment]
I see that what I described is currently... not implemented. Once the
pupsave is added to the aufs stack it's not possible to unmount the
partition.

The solution is to follow a similar logic as the multisession cd. You
can only unmount a multisession cd when everything has been copied to
ram.

I guess it's not hard to implement a similar special behavior for
pupsaves, but it would be a different pupmode

And init should record the pupsave partition UUID and snapmergepuppy
should be able to find the correct partition and mount it in case it's
unmounted.

Everything is possible but the only limitation is time, it's not infinite.

**Comment by CollaboratorGCM** [comment]
There is nothing wrong with your direction. But, some of us continue to use CD/DVDs. In fact I have probably 200 blanks from CDroms to CD-RWs to DVDs to DVD-RWs to DVD+RWs to etc. I have "heard" people say they are buggy and other such. BUT, I have never had ANY problems with my use over the past 2 decades. (well, once I had a power outage while burning, but the results is to be expected...same has happen with hard drive and a USB from time to time).

I have been a **_user of persistence_** with them since the days of Knoppix.

Usually once burned, I leave them in the PC's magazine. And, I know to "pfix" on Puppy Linux boots should I move to another PC.

My current problem which I am sure EVERYONE agrees is that all of my 30 or so USB sticks and drives have completely differing performance behavior and most often they are no better than what I get in booting DVDs. In fact in few instances my DVD performance exceeds several USB sticks I have.

But, I do understand that there are those who prefer USBs. 

For me, there is one downside to USB use that DVD disc have the advantage: I can externally write on them "their mission". I CANNOT do this on USB (in spite of what Barry says. 

Today, I needed to burn an image to a USB and ran into the same problem I always have; namely ALL 30+ USBs have data of one sort or another on them. So I spend hours inserting looking for space to erase or copy or move or ... until I find a USB candidate for the testing I needed to do. With DVDs, this search for a candidate NEVER happens. I just grab an empty and go to work. 

I do understand what you cover in this thread. **So use what you developers feel is best as you go forward.**

This post is just to give my personal use of persistence and DVDs over the many years. I probably have a DVD/CD for just about EVERY PUP ever produced that I have tested. We are talking hundreds. I am sure I will hate PC life if I have to ultimately manage hundreds of USB sticks for which I have no clue what I had put on them....even if I put a masking-tape tag on them. Yes, DVD drives are disappearing, but USB are now a nightmare for me with with the 30+ I have.

**P.S.** You mention something I consider a strong point for persistence: namely if the PC has a HDD/SSD/eMMC these are excellent candidates for persistence files. I have been doing this for the past 2+ years on each machine I boot DVDs on. USBs are often too horribly variable in speed for EITHER persistence on boots or page-files or swap-files.

Couple years ago, I ran tests and separated my 20 USBs into slow, medium, and fast stacks. But they are all jumble up again in a single pile with the additions. Its a nightmare again when I need one for blanking.

**Comment by bigpup1** [comment]
As long as computers have a CD/DVD burner drive.
Multi-session CD/DVD Puppy installs is a feature of Puppy Linux.
Not time to remove it, yet!

I would bet. The biggest problem people make for themselves, burning Puppy to a CD/DVD, is burning at to high a speed.
Not using the burning program, correctly, to make a still open disk, so it can be used as multi-session.

**Comment by wdlkmpx** [comment]
Well there's no need to remove it actually. but I already removed it somewhere else.. as part of the most massive cleanup so far that will result in a simple OS easier to maintain where users other than root can work properly and some other features that are not possible to implement with the current codebase.

**Comment by CollaboratorGCM** [comment]
Please consider these comments ===> https://github.com/puppylinux-woof-CE/woof-CE/issues/1618#issuecomment-570725091
