### ISSUE TITLE
Where is woof-CE forum?

### ISSUE THREAD

**Issue by cayoenrique** [puppylinux-woof-CE/woof-CE#1677]
At the moment I do not have identify relevant Issues related to woof-CE git.

But I love to find a forum where I can read and learn about it,  And that I can ask simple questions.
I been in http://murga-linux.com/puppy/ nice place.  But I can not find help there on woof-CE.

Can you help me?  Thanks in advance.

**Comment by rizalmart** [comment]
Here is the thread that you are looking for:
http://www.murga-linux.com/puppy/viewtopic.php?t=101174

**Comment by cayoenrique** [comment]
Thanks for the reply.  I have seen that thread.  But at first glance looks like a discussion with emphasis on github.  I am more interested in Help regards woof-CE it self.  For example like how to set some configurations.  Or even how can I used a deb/pet that I have build and is at my own PC not in a repo.

Well to be honest I will be reading those 94 pages just in case I am wrong.   In any case if there are more threads or forums please let me know.

PD: with my limited time I had for today, I re-read 1rst 15 of 94.  Except for a nice link to a original Woof tutorial, the rest of the post that I read are just a soap opera of personal reports/status.  They seems most likely experts than newbies.   Did not found yet the How / Questioning / propose solutions, ask by a new guy.  May be on the following 79 pages.

**Comment by wdlkmpx** [comment]
That is the forum thread. 

I read a few of your comments and I fear we cannot help you because documentation is scattered everywhere. In wiki pages, readme pages, forum threads, etc. This is where code changes happen, and structural changes happen quite often, not exactly the place to help people build their own distro, but to keep improving the default stuff. Default stuff.

If you want to waste your time, you may persevere in this endeavor. But if you're not a hardcore masochist I recommend using this build system:

BusterDog + build system
http://murga-linux.com/puppy/viewtopic.php?t=117255

It offers the best of 2 or 3 worlds, woof-ce cannot offer such greatness, not yet.. it will take a few years.

**Comment by wdlkmpx** [comment]
The question is what if you want to create a bionicpup64 with lxde as the desktop?. The are 2 problems:

- Currently bionicpup64 is probably quite buggy and the build will end up with different packages than what you'd expect. i.e: A PKG DB is downloaded from ibiblio and replaces the wce pkg db.
- If that's not enough, if you have added local packages to the bionicpup64 package database, it will also be overwritten, because a pkg db is always downloaded, enraging you to no end.

BusterDog provides options to build with several desktop environments. Its code is quite simple, it builds everything using only the package manager from debian, applying dependency resolution.. yes it only takes one command to install a desktop environment.

It has full compatibility with debian, I think it uses a kernel from debian, everything from debian, because it's Debian.

This information will save you a lot of time, and I'm writing this out of compassion.

**Comment by cayoenrique** [comment]
Interesting.... Hum!  To be honest I was already giving a thought in to old bootstrap articles in murga.  But you just pointed-out how to build latest.  Nice. I will be placing this on my next build.  So quick answer thanks for this gift of knowledge.

My point, I did use Ubuntu because you can get 90% of answers to questions on the web.  For the rest there is always a Personal Package Archive (PPA).  I am feed up with Windows with this constant updates.  Canonical Ubuntu is quickly reaching that level of un-comfortability too.  So I thought in Puppy simplistic approach.  I know security updates are a big issue for some people.  But for a everyday Laptop to be use for fun we do not need that seriousness. 

Debian... Well I know Ubuntu is base on it.  And I have installed Debian via bootstrap that I latter run chroot inside my Android phone.  Nice protect.  But I lack of experience on Devian.

I know you just gave me http://murga-linux.com/puppy/viewtopic.php?t=117255.   So next question to you wdlkmpx.  Can you suggest me the best forum for BusterDog + build system for a newbee like me.

What are the 3 words? in "It offers the best of 2 or 3 worlds"

And THANKSSSS for your suggestion.  I be looking into it.

**Comment by cayoenrique** [comment]
HEHEHE.  Seems there is a Bug in github...  Saw ONLY 1 post of you, reads 5 hours ago.  I answer, then did edit small thing.  Just to find out you posted a second 4 hours ago....  Why it did not show the 1rst time!!!!  Wonder 

Thanks for you compassion.  It gave me a good Idea/project.  Listen.  I did build my Puppy 64bit base  on Ubuntu 18.04 and LXDE.  MOST if not ALL thanks to peebee.  Nice guy.  I am in no hurry for a solution now.  I got what I need.  But was looking in to learning more on Puppy.    But now Thanks to You I ave to start all over again....  HEHEHEHE  Not upset just in case.  I love to learn.  And I truly believe in what you are saying.  That is why I will give it a try.

**Comment by cayoenrique** [comment]
Almost a week pass.  I guess I should close this issue.  In general I was trying to find out why I could not get repeatability using woofCE.  Builds withing days will create different issues.  Nothing important in fact latest where related to abiword problems that where simply corrected just by uninstalling the one I had and installing the latest.  So if you are looking to use woof-CE.  Please just ignore this.  woof-CE works, will build your puppy distro.

So origially I was looking to build a LXDE x86_64bits Ubuntu 18.04 LTS.  But I will be in debt the rest of my life to wdlkmpx.  Thanks to hes suggestion.    I found a frugal puppy like build system that can build my desire LXDE x86_64bits.  It pass my repeatability test:  every build I did came out good, no new issues.  It is not Ubuntu but I can live with Debian.   Do not get me wrong, it has its thighs too no-systemd cause failures installing new packages.  Thanks to all.  See you around in murga forrum.
