### ISSUE TITLE
Compat distro package types

### ISSUE THREAD

**Issue by sc0ttj** [puppylinux-woof-CE/woof-CE#1683]
In DISTRO_SPECS

```
DISTRO_BINARY_COMPAT='debian'
```

Means we need code like:

```
  case $DISTRO_BINARY_COMPAT in ubuntu|trisquel|debian|devuan)
```

and

```
    case $DISTRO_BINARY_COMPAT in
      ubuntu|trisquel|debian|devuan)
        separator='_'
        ;;
      *)
        separator='-'
        ;;
    esac
```

Can we have a `COMPAT_DISTRO_PACKAGE_TYPE=deb|txz|tar.xz|foo` ?

So all `.deb` based Puppies can be grouped together, and we have a canonical package extension to work with... Might make for cleaner code down the line.

**Comment by wdlkmpx** [comment]
I actually thought about this several times.

It's easy to do, but this also requires new builds, it has to happen in merge2out probably, because manually adding that variable to the current stuff would break stuff for people with custom configs.

In fact I've been having many ideas, such as.. slowly integrate the build system with pkg. Which means probably breakage for everyone. I've always had many ideas, but it's not possible to apply them when there is people to please by not changing structures, designs.

I guess I'm the only one who understands the whole thing and able to integrate everything, but the only problem is that we're trying to fix a design that is not fixable. Unfixable by design.

It's been 4 years changing and rewriting stuff and trying to keep builders happy, but I'm just too tired and having a fever. I need lots of cash, I've already wasted the last 15 years of my life, and at 30 I'm beginning to become fat, need exercise and a job that doesn't involve computers. It's time for new blood and ideas.

**Comment by s243a** [comment]
Can't we just check if COMPAT_DISTRO_PACKAGE_TYPE is set and if not set it based on other information such as the distro name?

**Comment by CollaboratorGCM** [comment]
@wdlkmpx, A person of your talent(s) should have work flowing your way which generates revenue. Its an all important need everyone has like fresh water and food.

**If anyone know of job opportunity** that you think @wdlkmpx is interested in, throw a shoutout his way.

BTW: Which continent are you located?

**Comment by sc0ttj** [comment]
@wdlkmpx  yeah, PM a few of us on the forums .. Let us know where you are, happy to have a look around, recommend you..

---

> it has to happen in merge2out probably, 

OK (I wouldn't know)..

>  manually adding that variable to the current stuff would break stuff for people with custom configs.

I don't think this needs to be a "breaking change" .. 

The COMPAT_DISTRO_PACKAGE_TYPE var would be an extra var available for us, _if_ devs wanted to use it.. We don't have to remove or rename anything else in DISTRO_SPECS, so everything would work as normal.

There is no reason to determine these things at "run-time", they can be determined and set once, at build time... Certainly not multiple times, scattered around in Pkg, PPM, etc, ..  

But maybe for backwards compatibility (new PETs working on old Pups), we also need some a fall back (see next point from s243a)
 
> Can't we just check if COMPAT_DISTRO_PACKAGE_TYPE is set and if not set it based on other information such as the distro name?

I agree with this.. We could add that snippet into Puppy somewhere (initrd script?)

...

Anyway, this change is not super important, just a thought about helping write cleaner and more robust code in future.. 

...not having the same code scattered around in different scripts multiple times, that needs to determine package type by relying on hard-coded lists of distro names, which might change..

**Comment by sc0ttj** [comment]
Something like this

From: https://github.com/puppylinux-woof-CE/woof-CE/blob/975e04630db1f07cdb1b603b6da9d1e649d0bdd2/woof-code/_00func#L52-L59
