### ISSUE TITLE
Feature request: .files in online repos

### ISSUE THREAD

**Issue by sc0ttj** [puppylinux-woof-CE/woof-CE#1725]
Can we host the `<pkgname>.files` in the puppy repos we build?

Can we include `*.files` of each package in the devx, in the devx? 

...It's not super important, but if we did, then we could do stuff like:

```
pkg contents <pkgname>
```

And even if the `<pkgname>` isn't installed, we can use `wget` to download `${PKG_URL//.$pkg_ext$/.files}` and print the package contents...

(Currently, `pkg contents <pkgname>` only works in `<pkgname>` is a builtin, or a user installed package...) 

Slackware repos (sometimes? often? always?) has `<pkgname>.lst` files in its repos, listing package contents.. We could pilfer one for each package in the default system repos...

I've no idea if something similar exists for Ubuntu/Debian, etc..

**Comment by 01micko** [comment]
This would be a VERY tedious task.

Every single package on ibiblio (and also githhub/woof-ce-noarch) would need to be downloaded and processed. Sure a script could do it but still.. _bandwidth_.

I'm not sure if `apt` supports listing full package contents but I do know that the web based debian package search does.

**Comment by sc0ttj** [comment]
Hmmm ... ok, maybe I wil try to write some code for Pkg that srcapes the online sites ... But yes, may be tedious!

**Comment by s243a** [comment]
One could just scrape it for the newer packages first and do it slowly over time so that it doesn't use too much bandwidth.

**Comment by Butterfly** [comment]
[Debian's apt-file package](https://packages.debian.org/buster/apt-file) came to mind as I read this so I checked its `man apt-file`:

> apt-file is a command line tool for searching files in packages for the APT package management system. Some actions are required to run the search:
> 
>        * find: Alias for search.
> 
>        * list: List the contents of a package. This action is very close to the dpkg -L command except the package does not need to be installed or fetched. By default, the list action interprets its pattern as if --fixed-string was specified.
> 
>        * search: Search in which package a file is included. A list of all packages containing the pattern pattern is returned. Since Contents files does not contain directories, the pattern must match (part of a) file name. By default, the search action interprets its pattern as if --substring-match was specified.

They reference `dpkg -l` there in case that's helpful/fruitful, too...

I just test drove `apt-file list pysycache-dblclick-butterfly` because I don't have the package installed. It sat a second or so then ran off a list of files.

One thing that comes to mind about it is that Debian *does* provide their own repository in addition to all the ones around the World. It's possible that `apt-file` is querying their in-house database and that it might not work or otherwise might not go over well with volunteer repositories' owners.

I've been debootstrap'ing my Debian copies for a few years now. That `apt-file` is one of the first packages I add in every time. I've only used it a couple times, but I see the value in having it on-hand just in case the need arises. That part about not having to download a package to inspect its contents is a HUGE win on dialup :phone:  Internet access. :smile:

PS It's been a long time since I've been on the actual Github website. The quote part above did that on its own. I don't remember ever seeing that before. I guess it's useful for having quotes/rehashed words not take up so much computer screen landscape. :smiley:
