### ISSUE TITLE
f2fs could be treated as PUPMODE=12 on flash media.

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#1750]
A long time ago I wrote a USB installer that modified the `init` script (in `initrd.gz`) to treat f2fs as _fast medium_ . It was a pure hack that simply replaced all instances (not many of them) of '13' with '12'. This made Puppy think that it was installed on a _hdd_ or _ssd_ so no periodic saving would occur. Saving occurred directly as it does on a normal frugal install to hdd/ssd. 

Now that _f2fs_ has matured somewhat, and the tools too, I believe it is time to treat an `f2fs` formatted partition as a normal partition like on a fast media (hdd/ssd).

**Comment by bigpup1** [comment]
The whole idea of running in pupmode 13 was to limit the number of writes to a USB flash drive.
This is suppose to help make it last longer.
Reading from a flash drive has no limit.
But, writes are suppose to have a specific number of times limit, before the drive starts to show errors.
f2fs does have a lot of good features, but it still writes data, to the drive, when a write command is executed.

**Comment by bigpup1** [comment]
You always can run a Puppy in pupmode 12, by simply using the pmedia=atahd command, in the boot menu entry, that is booting Puppy.
Use pmedia=usbflash or ataflash to make Puppy run in pupmode 13
I personally, would like to make the choice.
Most of the time I run Puppy, installed to any type drive (HDD,SSD,USB), in pupmode 13, by using this pmedia=usbflash command.
Save icon on desktop.
Set to no auto timed save.
Ask to save or not at shutdown.

**Comment by 01micko** [comment]
The operative word in the title is **could**.

It _could_ also be a boot parameter.

It _could_ also be **sdcard** and **micro-sdcard** specific and _only_ for `f2fs`.

I'm not trying to _force_ my ideas @bigpup1 but open a discussion which ~~might~~ will improve Puppy Linux.

**Comment by gyrog** [comment]
When pupmode=13 was implemented, usb sticks were small, expensive and precious.
I would argue that these days usb storage devices are none of these.
For my 2 cents, pupmode=13 is an obsolete Puppy feature.
So, for me the question is;
Is it worth the effort of removing pupmode=13?

Note: The only "kindness" I do for my usb sticks and SD cards, is to format them with f2fs rather than ext4.

**Comment by mavrothal** [comment]
PUPMODE 13 is handy when you want to experiment without risking your savefile integrity.
It would be nice if it remains as an option

**Comment by s243a** [comment]
If the puppy is running in ram it is much faster, especially when the save file/folder is on a device with slow IO speed. Also the ability to write directly to the save layer without changes taking immediate effect is useful if one wanted to do a live update of glibc. Finally there are security advantages of running in ram which have been taken advantage of by Puli.

**Comment by bigpup1** [comment]
> The operative word in the title is **could**.
> 
> It _could_ also be a boot parameter.
> 
> It _could_ also be **sdcard** and **micro-sdcard** specific and _only_ for `f2fs`.
> 
> I'm not trying to _force_ my ideas @bigpup1 but open a discussion which ~might~ will improve Puppy Linux.

I have had the most problems, with saves, when they are directly written to.
If something is a bad install, makes some really bad changes, replaced critical 
stuff, etc....
About all that will really fix the save is replace it with a good backup save.

If Puppy is always run using a save ramdisk (pupmode 13), everything new is in the save ramdisk until save icon is selected, timed auto save, or save at shutdown.
To the running Puppy, the save ramdisk and the actual save are one save.
If something in the save ramdisk, is messing up, and you have not caused it to go into the actual save.
 Simply do not save.
Reboot and you are back to original good save.

Maybe make this change to Puppy operation.
Maybe part of the initial setup for making a save.
I would like to see an option that would allow you to select how the save is handled. No matter what device it is installed on.
Do you want to have the save:
Directly save?
Save at a specific time?
Save when you select to save?
Save at shutdown?
Be asked to save or not at shutdown?

Simply running in pupmode 13 gives you all these options.

However, it is not a simple selection menu to choose from.
It is how you have the Puppy Event Manager->Save Session setup if you are running in pupmode 13.
Also, you need to understand how the options are now making the save work.

The save ramdisk was a problem with maybe using too much ram.
But, most people have computers with 1, 2, 3 ,4 GB ram or more.
Anyway, ram low warnings, would go off, if ram gets too low.
**Note:**
I am not sure if the save ramdisk, still clears out and writes to the save, when the ram gets too low or the amount of ram, the save ramdisk is using, is full.

**Comment by rizalmart** [comment]
PUPMODE 13 and PUPMODE 7 has one big problem. Its in the ram, if there is an important data on the ramdisk and accidentally cuts power, the important data was lost. Thats why I modified the init script of TazPuppy initrd to activate PUPMODE 7/13 if the computer has battery and it was in good health otherwise it revert back to PUPMODE 6/12

**Comment by 01micko** [comment]
I'm thinking a different way. Some _want_ to run RAM only, regardless of the risk. I suppose it ultimately boils down to user choice.

I'm going to do some experiments with the `pmedia=usbhd`. The `pmedia=atahd` has the potential to skip `wait4usb` and may not find the USB device.

**Comment by s243a** [comment]
> I'm thinking a different way. Some _want_ to run RAM only, regardless of the risk. I suppose it ultimately boils down to user choice.
> 
> I'm going to do some experiments with the `pmedia=usbhd`. The `pmedia=atahd` has the potential to skip `wait4usb` and may not find the USB device.

If there are boot options to specify the exact pup mode we want, then if someone doesn't specify an exact pupmode something like rizalmart could be implemented under the right conditions (e.g. f2fs + poor battery health + usb 3.0). 

The important thing is to give people choice and if they don't specify then we can try to select the best option for them.

**Comment by jamesbond3142** [comment]
This is why long time ago I decided to rationalise these options for Fatdog.

Basically there were 3 possible save modes:
- to a savefile
- to a savedir
- multisession
Saving to a "partition" is the same as "savedir" with a path of "/"

And there were two different kind of devices:
- direct mounted devices (harddisk, sdcard, mmc, etc)
- special devices (there is only one: optical disc)

And there are two access modes:
- direct access
- using buffered RAM layer

And then whether or not the savefile is encrypted.

Rather than spread over many different parameters, all these can be specified in one single parameter: "savefile". 

https://distro.ibiblio.org/fatdog/web/faqs/boot-options.html#savefile

All of these are manually controlled. I'm not trying to guess that the user wants - because some users want to use the RAM layer even with harddisk devices (because they only want to "persist" then they want to), and some want to have direct access with usb flash drive because the machine only have a limited amount of RAM; so the user has to specify them. (Of course I have a sane default is the parameter is __not__ specified, but once you specified it then you'd need to explicitly say that you want).

This may have to change when new possibilities of saving exists, but it has been 8 years since we adopted this approach, and so far we don't need to change. 

Of course, the downside is, people keep saying that "Fatdog behaves differently, Puppy's boot parameter doesn't work on it, etc, etc" - but it was the kind of flak I decided worth taking, to improve for the future.

My suggestion for Puppy going forward is to have a simplified parameter that can do all that, but add a "compatibility" function that breaks it down to the usual meaning of pmedia, pupmode, pdev1, etc so that existing scripts that depends on the existence of the old parameter will continue to work - while of course advocating new scripts to understand the new parameter.

cheers!

On Sat, 22 Feb 2020 19:39:09 -0800
s243a <notifications@github.com> wrote:

> > I'm thinking a different way. Some _want_ to run RAM only, regardless of the risk. I suppose it ultimately boils down to user choice.
> > 
> > I'm going to do some experiments with the `pmedia=usbhd`. The `pmedia=atahd` has the potential to skip `wait4usb` and may not find the USB device.
> 
> If there are boot options to specify the exact pup mode we want, then if someone doesn't specify an exact pupmode something like rizalmart could be implemented under the right conditions (e.g. f2fs + poor battery health + usb 3.0). 
> 
> The important thing is to give people choice and if they don't specify then we can try to select the best option for them. 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/puppylinux-woof-CE/woof-CE/issues/1750#issuecomment-590022908


-- 
James B

**Comment by CollaboratorGCM** [comment]
Good idea @jamesbond3142. 

Human nature is that EVERYTIME there is a strategy change, people react ... even for good strategy. 

Hope we can move forward without too much resistance.

**Comment by bigpup1** [comment]
This seems to be a fix for a problem that does not need fixing.
What is the problem with how it now works?
How Puppy operates in each different pupmode.
If anything should maybe be done, it is easily select what pupmode to run in.

**Comment by 01micko** [comment]
> This seems to be a fix for a problem that does not need fixing.
> What is the problem with how it now works?
> How Puppy operates in each different pupmode.
> If anything should maybe be done, it is easily select what pupmode to run in.

Are you sure? When pupmode 13 was designed flash media was rather flakey and cheapo media still is today. However, micro sd-cards were barely a thing and f2fs was 7 or 8 years from being invented.

Consider the case that raspbian (for raspberry pi) ships an image file with _ext4_ as a _full_ install, designed to be flashed to an sd-card or micro sd-card.

Sure the defaults can stay as is for anything but _f2fs_, but power to the user I say, so user can change as they see fit.

**Comment by gyrog** [comment]
Actually this can be done by patching any Puppy installer.
If the fstype of the partition containing the install directory is 'f2fs',
then it should write 'pmedia=usbhd' instead of 'pmedia=usbflash' to the boot entry.

I'll implement this in the next version of "FrugalPup"
