### ISSUE TITLE
PPM is broken?

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#1756]
Tried Peebee's [Arch32pup](http://www.murga-linux.com/puppy/viewtopic.php?p=1049512#1049512) that is using the latest PPM in woof, with the exception of 0setup, and it appears badly broken.
In "Auto" mode gives no indication of what is going to be installed and how the installation progresses. Also You need to restart PPM to update the list of installed or removed packages. In step by step mode is even worse!. It fails when the package to be installed has dependencies met with a gtkdialog error! Also when you pick download only it goes ahead and installs the packages!
I'm assuming a lot of it is the result of b61c8df and related changes but the bottom line is that as Pkg GUI is also in bad shape, Puppy has not any acceptable  GUI for the provided package managers.

BTW 0setup can support Arch packages with the attached patch that is based on a9ccd299 with minor modifications by peebee and me.

[0setup.diff.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/4239392/0setup.diff.gz)

**Comment by mavrothal** [comment]
Hmm I guess I have trouble attaching the file.
Here it is then
```
--- a/0setup	2020-02-22 11:51:42.000000000 +0200
+++ b/0setup	2020-02-22 13:30:59.920151623 +0200
@@ -266,6 +266,82 @@
    #get the category...
    ${FIND_CAT} /tmp/${ONE_PKGLISTS_COMPAT}temp > $ONE_PKGLISTS_COMPAT #130126
   ;;
+  arch)
+      #130126 arch code rewritten by noryb009: call find_cat afterward...
+      #130306 BK: sub() funtion to fix version relation operators...
+      #130306 BK: filtered out bad chars from description (note tortuous way to escape ' char)...
+      LANG=${LANGORG} echo "Processing ${ONE_PKGLISTS_COMPAT} please wait..."
+      xDLFILE=${ONE_PKGLISTS_COMPAT}pre #actually it's a tarball: core.db.tar.gz, extra.db.tar.gz, community.db.tar.gz
+      rm -rf sandbox0 2>/dev/null
+      mkdir sandbox0
+      cd sandbox0
+      tar xf "../$xDLFILE"
+      RETSTAT=$?
+      cd ..
+      if [ $RETSTAT -eq 0 ];then
+       rm -f "$xDLFILE"  
+       xxDLFILE=${ONE_PKGLISTS_COMPAT##P*-}  #this will be core, extra, community  130306
+       for i in sandbox0/*; do
+        cat "$i/desc" #"$i/depends"
+       done | awk -v pkgpath="$xxDLFILE" '
+        function output() {
+         if(filename == "") return;
+         
+         printf("%s-%s|%s|%s|%s||%0.fK|pentium4/%s|%s|%s|%s||||\n", pkgname, pkgverarr[1], pkgname, pkgverarr[1], pkgverarr[2], pkgsize, pkgpath, filename, pkgdeps, pkgdesc)
+         pkgname=""; pkgverarr[1]=""; pkgverarr[2]=""; pkgsize=""; filename=""; pkgdeps=""; inDeps=0; pkgdesc="";
+        }
+        BEGIN{
+         inDeps=0
+        }
+        {
+         if($1 == ""){
+          #do nothing
+         }else if($1 == "%FILENAME%"){
+          inDeps=0
+          output()
+          getline filename
+         }else if($1 == "%NAME%"){
+          inDeps=0
+          getline pkgname
+         }else if($1 == "%VERSION%"){
+          inDeps=0
+          getline pkgver; split(pkgver, pkgverarr, "-")
+         }else if($1 == "%DESC%"){
+          inDeps=0
+          getline pkgdesc
+          gsub(/</, " ", pkgdesc)
+          gsub(/>/, " ", pkgdesc)
+          gsub(/\|/, " ", pkgdesc)
+          gsub(/'\''/, " ", pkgdesc)
+          gsub(/\"/, " ", pkgdesc)
+          gsub(/\(/, " ", pkgdesc)
+          gsub(/\)/, " ", pkgdesc)
+         }else if($1 == "%ISIZE%"){
+          inDeps=0
+          getline pkgsize; pkgsize = pkgsize / 1024
+         }else if($1 == "%DEPENDS%"){
+          inDeps=1
+         }else if($1 ~ /^%/){
+          inDeps=0
+         }else if(inDeps == 1){ # dependency
+          if(pkgdeps != "") pkgdeps=pkgdeps","
+          pkgdeps=pkgdeps"+"
+          sub(/>=/, "\\&ge", $0)
+          sub(/<=/, "\\&le", $0)
+          sub(/>/, "\\&gt", $0)
+          sub(/</, "\\&lt", $0)
+          sub(/=/, "\\&eq", $0)
+          pkgdeps=pkgdeps$0
+         }
+        }
+        END{
+         output();
+        }
+       '  > /tmp/${PKGLISTFILE}temp #130306
+      ${FIND_CAT} /tmp/${PKGLISTFILE}temp > $ONE_PKGLISTS_COMPAT #130126 130306
+      fi
+      rm -rf sandbox0 2>/dev/null
+     ;;
   puppy)
    echo "...it's already in the Puppy standard format."
   ;;
```

**Comment by 01micko** [comment]
Reverting to e443e98 and moving forward from there might be the best solution.

**Comment by s243a** [comment]
> Reverting to [e443e98](https://github.com/puppylinux-woof-CE/woof-CE/commit/e443e98238f85a08c5e3e48452b53d636f119e0a) and moving forward from there might be the best solution.

Is there any list of improvements made vs features lost since said commit? I see that the commit says, "Remove Classic Mode". I thought the step-by-step install was the classic mode but it's been a while.

**Comment by s243a** [comment]
> BTW 0setup can support Arch packages with the attached patch that is based on [a9ccd29](https://github.com/puppylinux-woof-CE/woof-CE/commit/a9ccd299cd035a233efb8a2d0503e58fc47277ee) with minor modifications by peebee and me.
> 
> [0setup.diff.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/4239392/0setup.diff.gz)

Regardless of whether we roll back or not can we include this patch to add arch support? Troubleshooting the ppm via arch32pup is more interesting to me because it is a new system with new challenges. To me the obsession with trying to simplify things so that the code is easier to maintain misses the fact that historically puppy users loved to tinker with the system. Once the forum was a hot bed of puppy development in recent time users have felt more excluded from the development processes. Hopefully this perception has been changing so that users feel more involved. .  

I'm not saying their isn't a place for a more elegant looking system but not at the expense of making the system less unique and interesting. 

Making the system more general to support more binary compatible versions of linux adds new testing vectors to help improve the code.

**Comment by mavrothal** [comment]
> Reverting to e443e98 and moving forward from there might be the best solution

I wish was that simple.
PPM has seen a number of changes some associated with changes in other puppy frameworks, with out a clear final goal and any serious testing.
So it does need  work. 
Reverting just one commit may break it more.
Maybe easier to give a decent  GUI to Pkg and drop PPM altogether.
The problem I see is that none of the 2 has any decent testing from "everyday" users.

> Regardless of whether we roll back or not can we include this patch to add arch support? 

I would think not.  Adding/changing features to a broken system just breaks it more. 
That's one of the reason that PPM is not simple to "fix" right now. 
Besides  the code is there to use. 
0setup does not affect the other functions of PPM as long as it makes a sane package database.

**Comment by mavrothal** [comment]
Of course the above should not stop anybody from working with PPM!
I just do not have the time nor feel inclined to.

**Comment by s243a** [comment]
I just thought I would put some notes about the download button. The download button sets the parmater:
EXIT=BUTTON_PKGS_DOWNLOADONLY
here
```
<action type="exit">BUTTON_PKGS_DOWNLOADONLY</action>
```
https://github.com/puppylinux-woof-CE/woof-CE/blob/7f7cb910b5b9565bea3dce24c7237a0032aa0f4b/woof-code/rootfs-skeleton/usr/local/petget/installpreview.sh#L164

This value is first assigned to RETPARAMS on line [#171](https://github.com/puppylinux-woof-CE/woof-CE/blob/7f7cb910b5b9565bea3dce24c7237a0032aa0f4b/woof-code/rootfs-skeleton/usr/local/petget/installpreview.sh#L171) and then the eval statment is used to assign it to the current workspace on line [#185](https://github.com/puppylinux-woof-CE/woof-CE/blob/7f7cb910b5b9565bea3dce24c7237a0032aa0f4b/woof-code/rootfs-skeleton/usr/local/petget/installpreview.sh#L185) 

Now some more digging

**Comment by s243a** [comment]
Okay, I think this is the issue with the download button. Here is the legacy code:
```
#now do the actual install...
PASSEDPRM=""
[ "`echo "$RETPARAMS" | grep '^EXIT' | grep 'BUTTON_PKGS_DOWNLOADONLY'`" != "" ] && PASSEDPRM="DOWNLOADONLY" && touch /tmp/manual_pkg_download
/usr/local/petget/downloadpkgs.sh $PASSEDPRM
if [ $? -ne 0 ];then
 [ -f /tmp/petget/current-repo-triad.previous ] && mv -f /tmp/petget/current-repo-triad.previous /tmp/petget/current-repo-triad #120504
 exit 1
fi
[ "$PASSEDPRM" = "DOWNLOADONLY" ] && exit
```
[rootfs-skeleton/usr/local/petget/installpreview.sh#L419](https://github.com/puppylinux-woof-CE/woof-CE/blob/445ab4f5c9fb363334a8e02710d494ccec1aa4a2/woof-code/rootfs-skeleton/usr/local/petget/installpreview.sh#L419)

Notice that if [ EXIT = BUTTON_PKGS_DOWNLOADONLY ] then it sets the flag: /tmp/manual_pkg_download. Then it downloads the packages and finally exists rather then executing the rest of the install script. 

The newer code is: 
```
#now do the actual install...
PASSEDPRM=""
if [ -f /tmp/petget_proc/download_only_pet_quietly ]; then
  PASSEDPRM="DOWNLOADONLY"
  touch /tmp/petget_proc/manual_pkg_download
fi
/usr/local/petget/downloadpkgs.sh $PASSEDPRM
```
[rootfs-skeleton/usr/local/petget/installpreview.sh#L386](https://github.com/puppylinux-woof-CE/woof-CE/blob/7f7cb910b5b9565bea3dce24c7237a0032aa0f4b/woof-code/rootfs-skeleton/usr/local/petget/installpreview.sh#L386)

In the newer code the manual_pkg_download flag is not set unless, the dropdown menu item is selected in the main gui, and it also won't exit if this dropdown item is not set. So the newer code ignores the download only button.

**Comment by 01micko** [comment]
PPM is flogging a dead horse _IMHO_. The more we patch it the more we waste our _very_ __*limited*__ developer resources. 

`pkg`,  while good, is immature and had very little testing, however, as a 'pure' 'puppy' alternative _might_ be the way to go if, as @mavrothal stated, we can concoct a decent **GUI**. Also, another limitation is @sc0ttj 's choice of GitLab as the main repo, which makes issuing pull requests ('merge requests' in GitLab speak) more challenging for casual `git` users.

`zwn` is another option which started development as `woof-next` by @jamesbond3142 and I _somewhat_ successfully released a [devuan based raspberry pi version](http://murga-linux.com/puppy/viewtopic.php?t=116529) (alpha) for pi 2 and 3 boards. However this may or may not be a bit alien to the average joe puppy user.

I'd be interested in other people's thoughts.

**Comment by s243a** [comment]
> PPM is flogging a dead horse _IMHO_. The more we patch it the more we waste our _very_ **_limited_** developer resources.
> 
> `pkg`, while good, is immature and had very little testing, however, as a 'pure' 'puppy' alternative _might_ be the way to go if, as @mavrothal stated, we can concoct a decent **GUI**. Also, another limitation is @sc0ttj 's choice of GitLab as the main repo, which makes issuing pull requests ('merge requests' in GitLab speak) more challenging for casual `git` users.
> 
> `zwn` is another option which started development as `woof-next` by @jamesbond3142 and I _somewhat_ successfully released a [devuan based raspberry pi version](http://murga-linux.com/puppy/viewtopic.php?t=116529) (alpha) for pi 2 and 3 boards. However this may or may not be a bit alien to the average joe puppy user.
> 
> I'd be interested in other people's thoughts.

I'm a strong believer in doaucracy as well as giving developers and users choice. For banding purposes we need guidelines of what must be included in puppy for it to be official. In that regards, puppy will have to include ppm for now untill their is a better GUI for pkg, then in my opinion developers should be able to include either pkg or ppm and still have it be an official puppy.

I think the broken downloaded button is easy to fix. I think I know how ([see previous post](https://github.com/puppylinux-woof-CE/woof-CE/issues/1756#issuecomment-590087808)). I don't find that fact that the ppm doesn't immediatly update which packages that its shows as installed as critical but but it should be fixed. An issue, which was not mentioned by mavrothal is the console output it getting to noisy on the ppm. Perhaps there is a `set -x` statement that someone forgot to comment out. This should also be fixed because it slows down installation. 

In my mind it really comes down to what people want to fix. If someone wants to make a good gui for pkg, then developers should have the choice of not including the ppm and still having it be an official puppy if they include pkg instead. Personally I like using pkg without a GUI but puppy probably should have a good gui for it's pkg manager for wider appeal. 

Regarding zwm, it is good for building puppies but using the native package manager isn't always better. For instance, 
1. dpkg can be broken and become unusable if some of the metatadata gets corrupted (e.g. the status file) and this has happened to me before. 
2. dpkg doesn't have support for installing .pet files
3. dpkg doesn't let you install certain packages at the same time. For instance you can't install openssh and dropbear at the same time --- at least not very easily with dpkg. 

Regarding 3. if you do force dpkg to install openssh and dropbear at the same time it will automatically uninstall one of them perhaps against your wishes if you do certain commands. 

It is possible to have both one of the two official package manager for puppy with a foreign package manager like dpkg/apt by syncing the foreign/native package manager  with one of the two official puppy package managers. However, the foreign package manager may do unwanted things on us like install packages that we want to block or removing packages that it thinks of as "alternatives" but which we want to coexist.

**Comment by sc0ttj** [comment]
> the bottom line is that as Pkg GUI is also in bad shape, Puppy has not any acceptable GUI for the provided package managers.

Pkg has 3 GUIs... And the CLI.. My personal fave is the CLI, then the Xdialog GUI, then the ncurses one, and lastly the Gtkdialog one.. Each to their own, I guess.

I did previously mention the GUIs are simple, small, almost demos ... 

The amount of code in the 3 different GUIs that Pkg already has is small ... Very small compared to the PPM. 

Fixing up the Gtkdialog GUI (Gpkgdialog) shouldn't be too much work.. But it's not for me to decide what people want.. I, for example, don't care about icons next to packages in the GUI, they are merely a "nice to have"..   Maybe some PRs on the GUIs?

Side note: There is always the option of creating a web-based GUI - this could even double as an online packages website, similar to https://packages.debian.org/stable/ (etc) .. Running off a cgi-bin on localhost.. 

The main issue with Pkg is the slow dependency resolution... Replacing the Pkg funcs `list_deps()` and `find_deps()` with AWK alternatives should help a lot, and make Pkg quite nice.. 

> Pkg, while good, is immature and had very little testing, however, as a 'pure' 'puppy' alternative might be the way to go if, as @mavrothal stated, we can concoct a decent GUI. 

It's only had so little testing, as many puppy devs choose not to test it .. I've been using it exclusively for about 2 years or more..  I almost never use the PPM except on rare occasions.. And I use only Puppy at home.

Pkg only has 1 serious/complex bug at the moment - installing 3rd party Debian repos which have a stream of "main" _sometimes_ overwrites one of the system repos..  Myself and @s243a have been having a go, but there's not yet been a simple fix..

And, very occasionally Pkg seems to fail to unpack certain packages IIRC .. 

Most other limitations Pkg has mainly relate to stuff the PPM can't even do - convert build .deb packages, for example. So not "system critical" in puppy terms. 

Most recently I did a plugin system for Pkg, so it's behaviour can be extended easily, and also gave examples of how it can be used in place of the "FIXUP HACK" stuff .. 

I can only do so much - it's up to others to _want_ to test it by using Pkg in place of PPM.

> Another limitation is @sc0ttj 's choice of GitLab as the main repo, which makes issuing pull requests ('merge requests' in GitLab speak) more challenging for casual git users.

PRs can be made on the Github fork and I'll merge them in if they're good .. Then I'll port the work over to Gitlab.. Or people can contribute on the forum, as it ever was.. 


Another note: whether its petbuild, buildpet, sbopkg or some new one based on src2pkg (with a stuff borrowed from petbuild/buildpet), Pkg is well-placed to provide a decent ports-like system too - for compiling programs, packaging them up, and even adding them to user-contributed repos, etc.

Given all the things Pkg can do that the PPM cannot, and could do, I say PPM is looking long in the tooth by now.. Even if the Pkg GUIs need a few fixes .. 

Just my 2 cents.

**Comment by mavrothal** [comment]
I think that the Package manager issue is debated through out the puppy years to a great extend because people have different ideas about Puppy itself.
So you have arguments that if a PM can not upgrade downgrade packages and distros is not a PM, to that a PM should be able to install any package from any distro or source.

However, I think that all these are related to tinkerers, hackers and builders rather that normal users (ie, single user surfing, mail, documents, videos, pictures, maybe personal book keeping and the likes). 
Puppy suppose to be a complete OS that runs from an immutable source (SFSs), that you do not need to use the terminal (as with other linux at the time) and keep working as you did with Windows (XP) systems.

So upgrading downgrading etc does not make a lot of sense for an OS that runs from an immutable core.  Installing well vetted compatible packages is all the PM has to do and this should be done in the original puppy way, ie through a GUI, informing the user for every step of the way, and providing alternative options. 
All the features that need anything more than a search box and clicking might appeal to the seasoned linux user, but not to the “Windows refugee”. A CLI-based-30-50 options PM may also alienate the novice and even put them in danger since “well vetted packages” is the one thing that Puppy does not have... Specially if we start installing from any distro or source.
Granted, a CLI-bases PM avoids the hassle of developing a user friendly comprehensive UI but all distros have one (or more) striving for friendliness and functionality.
PPM had (not any more) a  user friendly GUI and functionality but it would appear to be restrictive or for the tinkerers..
Pkg has a very nice infrastructure/CLI but is suffering from GUI.
As I said, my money is on Pkg with a “ziggy treated” GUI. But  puppy is a (n uncontrolled?  😸 ) doocracy 

A valid argument against the “good GUI” and “carefully crafted and vetted packages” is that in the era of tablets and smart phones the “novices” have better options, the group of retiree-puppy-user is decreasing  and seasoned users, tinkerers and enthusiasts all it’s left for (puppy)linux. 
Of course the question becomes then why puppy and not any other distro? Main or compact spinoff? ... But this is not a PM issue I guess.

Regarding the  puppy PM though, I think that one feature would be really useful and in sync with the above puppy idea (a complete OS that runs from an immutable source). Install packages in a pdrv layer so your system files are always immutable while the user installed packages are easily separated and you can run pristine but with all your personal configuration data in place. This may require changes in the init and of course the package manager(s) but I think would be a worthy addition if implemented. 

Anyway, enough talking! (you can) Code as you see fit!

**Comment by sc0ttj** [comment]
@01micko @s243a @jamesbond3142 @mavrothal  (and others obviously) ...

If you have time, I'd love to get your thoughts on these options for a new petbuild/buildpet thingy: https://github.com/puppylinux-woof-CE/Pkg/issues/27

**Comment by s243a** [comment]
> @01micko @s243a @jamesbond3142 @mavrothal (and others obviously) ...
> 
> If you have time, I'd love to get your thoughts on these options for a new petbuild/buildpet thingy: [puppylinux-woof-CE/Pkg#27](https://github.com/puppylinux-woof-CE/Pkg/issues/27)

I don't know anything about either the new or old system. Are there any tutorials or examples available. Are there any detailed comparisons between these systems and other systems like slackbuild, dir2pet, sandbox2pet or source2pkg?

**Comment by s243a** [comment]
@sc0ttj :
> Pkg has 3 GUIs... And the CLI.. My personal fave is the CLI, then the Xdialog GUI, then the ncurses one, and lastly the Gtkdialog one.. Each to their own, I guess.
>
> I did previously mention the GUIs are simple, small, almost demos ...
>
> The amount of code in the 3 different GUIs that Pkg already has is small ... Very small compared to the PPM.

I'm pretty weak when it comes to GUIs but I recently looked a bit at the ppm GUI since it's more mature and I didn't think the issues in the original post would be that hard to fix. 

I may or may not take a look at PKGs gui's in the near term. If pkg coexists with puppy then the gtk gui isn't needed. We can modify the .desktop file to hide the pkg gtk gui when the puppy ppm is installed, until the pkg gtk gui becomes more mature. If pkg is installed without puppies ppm then we will of course want the pkg gtk gui as a menu option. 

I do like the idea of a web based gui for a package manager. Tazpup has one, which is based on the busybox httpd server. This might be easy to modify to work with pkg. 

One advantage of a web based gui is it can be faster when bandwidth is limited (e.g. an ssh connection). On my local network I can just X11 forward without going through the ssh tunnel but generally this isn't a very secure method of networking and I wouldn't even think about doing it over the public internet without some extensive study of X11 security.

**Comment by s243a** [comment]
I just want to say I think there are still some good things that we can learn from the ppm by trying to fix the errors in it but some of the code is quite confusing. For instance:

The following code implies that the file pkgs_to_install has four fileds:
```
pkg_info() {
	# Exit if called spuriously
	[ "$TREE1" = "" ] && exit 0
	NEWPACKAGE="$(grep ^$TREE1 /tmp/petget_proc/petget/filterpkgs.results.post)"
	IFS="|" read PKG_NAME PKG_CAT PKG_DESC PKG_REPO <<< "$NEWPACKAGE"
	(
		echo "Name    : $PKG_NAME"
		echo "Category: $PKG_CAT"
		echo "Desc    : $PKG_DESC"
		echo "Repo    : $PKG_REPO"
	) > /tmp/petget_proc/petget/pgk_info
	echo "$NEWPACKAGE" > /tmp/petget_proc/pkgs_to_install
}
```
[/rootfs-skeleton/usr/local/petget/pkg_chooser.sh#L120](https://github.com/puppylinux-woof-CE/woof-CE/blob/60d94862a3343bf0a062a0fcd0dd73475d6985ba/woof-code/rootfs-skeleton/usr/local/petget/pkg_chooser.sh#L120)

but at other times this file has two fields:
```
cut -d"|" -f1,4 /tmp/petget_proc/pkgs_to_install > /tmp/petget_proc/pkgs_to_install_tmp
	mv -f /tmp/petget_proc/pkgs_to_install_tmp /tmp/petget_proc/pkgs_to_install
```
[/rootfs-skeleton/usr/local/petget/pkg_chooser.sh#L159](https://github.com/puppylinux-woof-CE/woof-CE/blob/60d94862a3343bf0a062a0fcd0dd73475d6985ba/woof-code/rootfs-skeleton/usr/local/petget/pkg_chooser.sh#L159)

The code would be much more readable if a different file name was chosen when the number of fields changed. 

In this section of code pkgs_to_install is now a space delimited file rather than a new line delimited file!
```
install_package () {
 #set -x
 [ "$(cat /tmp/petget_proc/pkgs_to_install)" = "" ] && exit 0
 cat /tmp/petget_proc/pkgs_to_install | tr ' ' '\n' > /tmp/petget_proc/pkgs_left_to_install
```
[/rootfs-skeleton/usr/local/petget/installmodes.sh#L406](https://github.com/puppylinux-woof-CE/woof-CE/blob/60d94862a3343bf0a062a0fcd0dd73475d6985ba/woof-code/rootfs-skeleton/usr/local/petget/installmodes.sh#L406)

If you're wondering why I'm looking at this, I was trying to write a function to install the missing packages based on the missing libs in arch32pup. So far not much luck:
https://pastebin.com/a0NsT7Mv
See also: http://www.murga-linux.com/puppy/viewtopic.php?p=1051756#1051756

**Comment by s243a** [comment]
@mavrothal writes:
>  In step by step mode is even worse!. It fails when the package to be installed has dependencies met with a gtkdialog error! 

To fix this only two lines of code need to be changed. See:
https://github.com/puppylinux-woof-CE/woof-CE/pull/1772/files

What probably happened is someone changed double quotes to single quotes and forgot to remove the escaping of the double quotes from within the (now) single quotes.

**Comment by wdlkmpx** [comment]
I figured out a fix, delete the whole PPM, pup_event and many other things, and for some reason things just work, including non-root users
