### ISSUE TITLE
Using static busybox only for puppy

### ISSUE THREAD

**Issue by rizalmart** [puppylinux-woof-CE/woof-CE#1787]
I suggest that statically stripped busybox must be used on every Puppy. The advantage of using static busybox was the ease of recreating new minimal filesystem. Minimal root filesystem was useful especially for clean shutdown of layered root fs by creating a minimal filesystem on ramdisk then pivot_root to unmount the layered root filesystem and unmount the mountpoints used for layered root filesystem.

**Comment by s243a** [comment]
I don't think a static busybox is necessarily more minimal but it would make it easier to do things like update glibc. I say, leave things like this up to the distro builders.

**Comment by rizalmart** [comment]
Much better if static compiled was a default build for busybox in future puppies. It was extremely useful in some situations

**Comment by s243a** [comment]
I suppose it doesn't matter to me whether or not a static version of busybox is the default  or not. So I decline to vote. Anyone else want to vote?

**Comment by 01micko** [comment]
@rizalmart the idea _does_ have merit, however I do **not** think is appropriate for a main stream puppy.

In saying that, the default `busybox` should have a simple mechanism to be overridden with the puppy builders choice.

Now I digress..

A lot of people have asked _"how do I include my custom packages in my woof build?"_ . The answer has always been convoluted; create your own repo, add a 'spec' file and add it to the pet order. That is frankly stupid and unintuitve. A dir should be created in the root of the woof tree at the time of `merge2out` and builders can place whatever pet packages they want in there where _generic_ names take priority, a specs  file (say `Packages-puppy-${DISTRO_FILE_PREFIX}-custom`  or something similar) is generated automatically. If that dir is determined not to be empty or the spec file is non-zero bytes then packages in there will take automatic priority, overriding the defaults in other `Packages-*` files or added if added to the `PKGS_SPECS_TABLE` variable

Make sense in the context of the topic?

**Comment by jamesbond3142** [comment]
static busybox has problems. Not becase of its "static-ness", but because the libc that is compiled with. A dynamic busybox uses glibc, so the semantic uses glibc semantics. I have never heard of anyone building a static busybox using glibc (although it is not impossible); usually static busybox is built using uclibc (older ones) or musl libc (newer ones) or even dietlibc (for the very small ones). In this case, the semantics of static busybox operations will depend on uclibc, musl, or dietlibc (and sometimes, by busybox itself - busybox is well-known for "re-implementing" certain features itself if the libc it uses is "not capable" of doing things it needs).

An easy example is the TZ environment variable. A dynamic busybox linked with glibc will use glibc's semantic for TZ, for example, setting it to TZ=:/etc/localtime means "use the timezone in /etc/localtime". AFAIK it doesn't work like that on uclibc, musl, dietlibc. So you will have timezone problem, unless you make sure that your TZ is set in the way that works consistently for all the libc that you use.

But it doesn't mean static busybox is useless. It does help to perform clean un-mount. So perhaps to get the best of both worlds, let's have puppy by default carry the static busybox somewhere that is accessible, but don't make it the default (perhaps in /usr/share/static-bb/busybox). At time of shutdown, you can add PATH to make this accessible and used. Or perhaps copied over to the temporary ramdisk, etc. 

A static busybox compiled with almost all features is less than 1MB on 64-bit system, maybe less than that in 32-bit system. In the past I wouldn't even suggest this due to size, but today's puppy carries various libraries whose size puts 1MB to shame ...

**Comment by s243a** [comment]
If we have both a static version of busybox and a dynamically linked version then we can write a script that calls the appropriate one. The following code writes such a script:
```
echo "#!/bin/sh
script=\${0##*/}
script2=\$1
if [ \"\$script\" = \"busybox\" ]; then
  script=\$script2 ; shift
fi
exec \"$BB_UTIL_DIR/\$script\" \"\$@\"" > "/$BB_DIR/busybox"
chmod +x "/$BB_DIR/busybox"
```
https://github.com/s243a/woof-next/blob/e6590c1044adc0a182a9b299129ed707b7bd95d2/woof-code/rootfs-packages/tinycore9_bb_wrapper/usr/bin/mk_busybox_utils#L62 

It works as follows. There is a folder (called /bin/busybox) that has each command symlinked to the appropriate version of busybox. The script looks up which version of busybox to use by calling the appropriate symlink as if it was it's own utility. It is actually the symlink that does the logic and not the script. 

I did this because tinycore separated busybox into two parts, one part for commands that required busybox to have the suid set, and a separate binary for commands which didn't require the suid set. The security advantage is that sometimes the suid can be used for privilege escalation. A more restricted user might not have execute privlages for the busybox version that has the suid set. 

In our case we would link as many utilities to the static version of busybox that we can except for those in which the function of busybox static was impaired for some reason.
