### ISSUE TITLE
Revert 8eb6e1e 6-dec-2019?

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#1834]
Should:
https://github.com/puppylinux-woof-CE/woof-CE/commit/8eb6e1eb9333de396e2a76ccbee745ce73f08d0b#diff-99b62595b998dbfd92d3d1dbe2b327a6
init: improve test for boot drive from 6-dec-2019
be reverted?
It apparently causes kernel panic on some systems (HP? SD card?  emmc drive?)
Long thread chasing down cause from:
http://www.murga-linux.com/puppy/viewtopic.php?p=1059721#1059721
with result at:
http://www.murga-linux.com/puppy/viewtopic.php?p=1060387#1060387

**Comment by gyrog** [comment]
The evidence we do have, suggests that reverting this commit will avoid the issue, so it will go away, for now.
But, I do not believe that this is a "solution", we don't know what the problem really is.

How can "grep"ing a text file cause a kernel panic??
Unless the said text file was complete garbage, because "probepart" actually crashed, (just guessing here).

By all means revert the commit if you must.
But I don't see how "01micko" could even start to "fix" the code.

**Comment by 01micko** [comment]
I suppose yet _another_ boot param can be added, _presize_. That way the code can only run if that is set.

This would make it easier for resizing images on USBFLASH drives too so I can expand the code for that, regardless of the apparent bug.

**Comment by 01micko** [comment]
I _think_ I've solved @bigpup1 's issue because his boot drive is GPT, just waiting for a report. `fdisk` as we know doesn't support GTP so my suspicion is that the algorithm i'm using to calculate free space is causing an error and init stops. So I've put in a check to see if `/dev/mmcblk0` is GPT using `fdisk`. Here is the diff: 

```diff
--- init	2020-05-31 11:46:29.210999690 +1000
+++ /root/spot/init	2020-06-13 07:22:03.702212647 +1000
@@ -667,6 +667,7 @@ umount_unneeded() {
 
 check_resize_part() { #must be fast, no partitions can be mounted, can't work out pupmode at this stage
  DEVICE=/dev/mmcblk0 # sd card only for now
+ fdisk -l $DEVICE | grep -qm1 "using GPT" && return
  grep "$DEVICE" /tmp/probedisk.log | grep -q 'card' || return
  FS=`grep "$DEVICE" /tmp/probepart.log | tail -n1 | cut -f 2 -d '|'`
  case $FS in
```

If bigpup reports success then I'll commit this but I still can't fathom 'mash' 's issue which seems unrelated.

**Comment by 01micko** [comment]
This should be fixed now.

**Comment by CollaboratorGCM** [comment]
This is NOT a request. Instead, it is just food for thought. Would PARTED be a better/robust utility for use with drive accesses?

I, too, in the past, have run into issues where newer GPTs have had problems with utilities using fdisk and the confusion that ensued. 

Again, this problem is solved, but, going forward into PUP's future, maybe a better way is other services in PUPPY vs using fdisk.

**Comment by 01micko** [comment]
@CollaboratorGCM it would but we need small static binaries in the initrd. I do have to find something capable of manipulating GPT disks in the initrd. There will be something out there.
