### ISSUE TITLE
Menu Manager Removal request

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#2123]
The Menu Manager found in Menu>Setup>Menu manager has no apparent useful function.

If it intends to be helpful for Menu edit, it should allow a Menu item's desktop entry to be edit/updated/changed/moved vs a visible or invisible effort that the manager, itself, does NOT make apparent.

**Request** for it to be expanded or removed. And, for a replacement "setup/edit" Menu entry for "editing" the desktop entry that the manager list in the menus for which an entry refers to.

**Comment by zigbert** [comment]
Doesn't sound like you are using the latest menu manager?
- Click on menuitem to show/hide in menu
- edit and save *.desktop file

![Screenshot(1)](https://user-images.githubusercontent.com/5928708/111448750-04387480-870f-11eb-8ab4-3dd0ab81a730.png)

**Comment by rizalmart** [comment]
> Doesn't sound like you are using the latest menu manager?
> 
> * Click on menuitem to show/hide in menu
> * edit and save *.desktop file
> 
> ![Screenshot(1)](https://user-images.githubusercontent.c

**Comment by rizalmart** [comment]
@zigbert 

Hello sorry for off-topic today. Can you port Stardust theme to GTK+3?

**Comment by dimkr** [comment]
I tried to port it but the result was horrible. I tried to replace the background images used for bottons, etc' with CSS, but couldn't get the border width, the background gradient, etc' right.

**Comment by rizalmart** [comment]
@dimkr 

> I tried to port it but the result was horrible. I tried to replace the background images used for bottons, etc' with CSS, but couldn't get the border width, the background gradient, etc' right.

What if you just respect the gtkrc and just port the gtkrc to gtk.css 1:1 translation

**Comment by dimkr** [comment]
Sadly, you can't do a 1:1 port.

GTK+ 3 themes work differently - you'd have to use two images, one for the border and another for the widget "body", add padding, etc'. It's easy to do with mostly square themes - Polished-Blue and Flat-grey-rounded are very uniform, all widgets are square and some have slightly rounded corners. But Stardust is different, because the background of widgets consists of multiple gradients and the way the background image of widgets is stretched is different between the GTK+ 2 pixmap engine and GTK+ 3 CSS.

Yes, GTK+ 3 themes are not fun.
