### ISSUE TITLE
nlsx is not loaded automatically when inside the Puppy ISO

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2227]
The user must understand English well enough to configure Puppy to load this SFS 🤔 

Maybe it should become an "ndrv" and get loaded by the init script.

**Comment by 01micko** [comment]
`ydrv` ? That will do.

**Comment by dimkr** [comment]
Technically yes, but this use of ydrv is not exactly what's described in https://github.com/puppylinux-woof-CE/initrd_progs/blob/master/0initrd/README.txt#L38.

EDIT: and, renaming nlsx to ydrv would conflict with the YDRV_INC mechanism.

**Comment by 01micko** [comment]
Ok, I don't see a PR for a0de935 yet.

**Comment by dimkr** [comment]
Yes, needs testing. I'll take care of that today or tomorrow probably.

**Comment by 01micko** [comment]
NLSX and DEVX should really be treated as special cases. If they reside on the iso/install media then they should be automatically be loaded.

**Comment by gyrog** [comment]
I don't have a problem with the idea that if you place  an appropriate devx...sfs file in the install directory, then it automatically gets loaded at the next boot.
But, it must be at the very bottom of the stack.

Maybe it's been cleaned-up since then, but a few years ago when I first started playing  with loading extra sfs files above the Puppy system sfs files, I tried the devx. That was a big mistake, there were lots of very old versions of stuff in there which very nicely downgraded my Puppy.
Ever since then, I've always made a point of loading the devx...sfs last.

**Comment by gyrog** [comment]
@dimkr,
Could you please move the block of code in 'init' that actually does the deed, so that it is after the zdrv, and before the ydrv, the diff would then read "@@ -961,6" instead of "@@ -969,6"
or
Remove the "p" parameter from the end  of the "setup_onepupdrv" command.

I don't think that the very top of the stack is the appropriate place for the ndrv.

**Comment by dimkr** [comment]
@gyrog I believe "ndrv" is not the way to solve this issue. Instead, I think {dev,doc,nls}x should be loaded automatically. The layer position doesn't matter much because these three and the main SFS are 4 parts of one whole, and therefore shouldn't provide different files at identical paths.

**Comment by dimkr** [comment]
This is fixed by #2679, when `BUILD_ISO=no FRUGALIFY=yes`. I don't care about ISO images anymore, so I'm closing this.
