### ISSUE TITLE
Support for running JWM over Cage+Xwayland

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2252]
https://source.mnt.re/reform/reform-system-image/-/blob/mmdebstrap/reform2-imx8mq/template-skel/bin/reform-windowmaker

It's a very neat trick!

I've built a dpup bullseye with wlroots and all the required Wayland bits, then built Cage and used it to run a fullscreen Geany or ROX-Filer.

I couldn't run a non-rootless Xwayland, though, because there's no elogind and Cage doesn't like running as root. I'm trying to add PAM, PAM support in busybox login and elogind, to see if now it's possible to run the normal Puppy desktop inside a full screen Xwayland.

In addition to the cool factor, JWM over Xwayland would provide tear-free rendering, and allow us to remove many packages needed by Xorg (i.e. stuff like xserver-xorg-video-*). In some ways, despite of this "translation layer", JWM over Wayland could be more elegant than a proper Xorg desktop, and I wouldn't be surprised if it's smaller in terms of ISO size.

**Comment by dimkr** [comment]
Got the Puppy desktop running over Xwayland and cage. Had to build Xwayland, seatd, wlroots (with a patch that allows it to build against Wayland 1.18.0) and cage (with a patch that allows it to run as root).

The keyboard wizard doesn't do anything because Xwayland doesn't read Xorg.conf.

Applications seem to work just fine and everything is rendered without tearing, on an old x86_64 laptop. Haven't tried 3D games yet, and haven't tested this setup on ARM.

**Comment by dimkr** [comment]
Look ma, no Xorg!

![xwayland](https://user-images.githubusercontent.com/1471149/118363444-0e56e200-b59d-11eb-8bb5-de34bf82b8ee.png)

**Comment by CollaboratorGCM** [comment]
+1!

**Comment by CollaboratorGCM** [comment]
I have 3 configurations for testing an ISO when one is available that will interest you in your wayland progress.
1. Touchscreen AIO AMD 2018 desk
2. TV-HDMI-nVidia Intel 64bit desktop
3. 2008 HP touchscreen Intel 64bit Laptop

**Comment by dimkr** [comment]
Published https://github.com/dimkr/woof-CE/releases/tag/cagepup64-8.0-prepreprealpha1, for early testing.

The keybouard/mouse wizard should work, but there's no way to configure the resolution and I'm sure there are more issues.

Tested on a Dell Latitude E7250 (x86_64) and an Asus C201 (ARM) so far.

I could connect the Dell laptop to a second monitor and it works, but there's no way to configure the monitor placement, and I couldn't run Tux Racer when connected to two monitors.

In both laptops, rendering is silky smooth and everything (especially browsing and scrolling) feels much faster.

**Comment by CollaboratorGCM** [comment]
1st attempt at boot: No GRUB2 loopback.cfg, could not boot the ISO directly via SG2D. Would be nice if I could to avoid having to go to any media to test operations.

Created a CD and booted on a 2 thread-2 core Intel desktop via VGA monitor.

Yes, there are issues when at desktop, but this, understandably, is an early precursor.

At shutdown, the normal PUP operations are working with options presented as expected.

Looking forward...

**Comment by dimkr** [comment]
> Yes, there are issues when at desktop, but this, understandably, is an early precursor.

The only issues relevant here are related to graphics and input peripherals. What issues do you see?

**Comment by CollaboratorGCM** [comment]
Firstly, Of the 3 mentioned platforms I offered for test, I have only been able to boot ONLY one: The old HP touchscreen laptop. It is a BIOS based PC, but the CD boots fine. The touch screen works but tapping is hit-miss requiring several taps sometimes to launch the desktop icons.
distro
Several of the Menu items are not responding to either touch or mousepad taps.

Next, My AMD system will NOT boot the CD (or a DVD that I also created from the ISO). It is not recognizing the disc in the drive at PC start for boot device select. This is NOT a distro problem, I see it as an hardware issue that needs more investigation. This unit is a Windows based PC that I SG2D boot ISOs on for the past year+half.

Thirdly, I will take my main system, the TV, down tonight and try the CD boot on it.

Current status on the original Wayland release.

**Comment by dimkr** [comment]
@CollaboratorGCM Is that with https://github.com/dimkr/woof-CE/releases/tag/cagepup64-8.0-prepreprealpha1 or https://github.com/dimkr/woof-CE/releases/tag/cagepup64-8.0-prepreprealpha3?

**Comment by CollaboratorGCM** [comment]
I have cagepup64-8.0.iso is the ISO with a filedate of 17 May at 294MB.

I will swap out for the prepreprealpha3 and retest. Hoping for the ISO with the loopback.cfg for SG2D use as it makes faster mode to get to testing PUP-DOG desktops on all of my PCs; BIOS/UEFI.

Edit: Just downloaded and will have to write ISO to media before testing. I sure you will rectify this via WoofCE in the future.

**Comment by CollaboratorGCM** [comment]
I've downloaded 3 of the preprealpha (PPA) versions. All test, today, have been run on a  2x Pentium Dual. (BIOS desktop)

- The PPA1 version boots all the way to desktop
- The PPA2 version boots to a prompt only...no desktop
- The PPA3 version boots to the "starting x..." message ... no desktop (**[this boot has a video log, here](https://photos.app.goo.gl/BxohfgjA5JkNerEq8)** where you can see the boot-time messages fly by.)
- The PPA4 version boots to the same message as PPA3; namely "Starting X, specs in /etc/X11/xorg.conf..." where the system locks.

**P.S. _Unrelated:_** Your Focal64 ISO boots via SG2D and operates smoothly in initial testing. SAMBA, QEMU, others working without issues.

**Comment by CollaboratorGCM** [comment]
@dimkr ... I hope this is helpful for this distro. I used @01micko & @peabee loopback.cfg as a guide. I extracted this "find_iso=${iso_path}" and added it to each linux line in your grub.cfg file creating a new file in the /boot directory named loopback.cfg. I use isomaster to add the loopback appropriately, creating new ISO for testing.

Hope this is met with favor in an attempt to help, as it allows download to SG2D USB and booting the ISO file directly without the need to create media in order to test. "loopback" is Attached:
[loopback.cfg.fake.gz](https://github.com/puppylinux-woof-CE/woof-CE/files/6521806/loopback.cfg.fake.gz)

BTW: The boot results are the same as reported earlier for each of the PPA1-4

**Comment by 01micko** [comment]
#2265 is merged.

**Comment by CollaboratorGCM** [comment]
No GRUB2 "Loopback.cfg" from this WoofCE build. 

Is this manually removed after ISO build by its developer or just not a part of WoofCE builds anymore?

Is this a problem or does this cause problems? Why is it not included? Makes for more work to do boot testings and desktop testings.

**Comment by gyrog** [comment]
@CollaboratorGCM,
I don't think it ever did have a "Loopback.cfg".
Current woof-ce Puppy has a script called 'isoboot' in 'initrd.gz' that gets executed by the 'init' script to handle direct .iso booting.

**Comment by CollaboratorGCM** [comment]
ISOBOOT app does not work the same. And SG2D does not require the setup for ISOBOOT use you refer.

I could go into the differences, but that may not be what you want. Short answer: For past 20 months is WoofCE PUPs have included EFI, GRUB2 and loopback to facilitate PUP startups with little to no effort on the part of the developers/users when it was introduced in the WoofCE cycle. It takes literally 2 minutes from download to desktop via the WoofCE PUPs. This cannot be done with Frugals or ISOboot and certainly not full installation on BIOS + UEFI PCs.

Loopback.cfg allows to quickly grab and boot to report/observe test results via SG2D. 

PUP developers have made this a simple process for awhile now.

So my question is raised because there may be some good reasoning for removing that ability. I am not objecting versus trying to understand why it has been removed?
