### ISSUE TITLE
PIGZ - compress data faster

### ISSUE THREAD

**Issue by CollaboratorGCM** [puppylinux-woof-CE/woof-CE#2384]
**[Potential to shorten wait time](https://zlib.net/pigz/)**, significantly.

If useful, I'm sure it will show up in future PUPs and used by developers, here.

**Comment by dimkr** [comment]
dpup uses pigz instead of gzip since ae638d4e7e7435244e528f66b8b3ecd827208cb4.

Does it "shorten wait time"? No, only if you're compressing or decompressing something with pigz, and it's probably a small file anyway, and gzip is not as popular as it was before xz and zstd.

I'm closing this, I don't think it's a real issue.
