### ISSUE TITLE
gcc_dev_FIXUPHACK does not create cc and gcc links with Ubuntu gcc-10

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2402]
In Ubuntu builds with gcc-10
/packages-templates/gcc_dev_FIXUPHACK
does not create the necessary cc and gcc links......

**Comment by peabee** [comment]
Lots of other links also not created..........
![Screenshot](https://user-images.githubusercontent.com/5926865/126767924-7d2a8fbb-3401-4926-ad37-45b52bfd6806.png)

**Comment by dimkr** [comment]
If it's focal, then the `gcc` package depends gcc 9.x, not 10.x. If you use the `gcc` package, which symlinks `/usr/bin/gcc` to `gcc-9`, you'll have to replace the symlink. Technically, you're not supposed to change the default GCC version to something different than the version used to build packages in focal, because you might run into some incompatibility.

And if you're not sure if this is caused by missing dependencies, you can do this:
```
yes|gcc_dev|gcc-10|exe>dev,dev,doc,nls||deps:yes
```

**Comment by peabee** [comment]
gcc_dev_FIXUPHACK should create the correct symlinks.......

DISTRO_PKGS_SPECS-ubuntu-focal has:
yes|gcc_dev|gcc-10-base,gcc,gcc-10,g++,g++-10,cpp,cpp-10|exe>dev,dev,doc,nls

Packages-ubuntu-focal-main has:
gcc-10-base_10.3.0|gcc-10-base|10.3.0|1ubuntu1|BuildingBlock|265K|pool/main/g/gcc-10|gcc-10-base_10.3.0-1ubuntu1~20.04_i386.deb||GCC the GNU Compiler Collection base package|ubuntu|focal|

so gcc-10 is a valid focal option............

**Comment by peabee** [comment]
OK - 2 problems.........
My DISTRO_PKGS_SPECS-ubuntu-focal has:
yes|gcc_dev|gcc-10-base,gcc,gcc-10,g++,g++-10,cpp,cpp-10|exe>dev,dev,doc,nls
which is wrong should be:
yes|gcc_dev|gcc-10-base,gcc-10,g++-10,cpp-10|exe>dev,dev,doc,nls

but there is also 2 * missing from gcc_dev_FIXUPHACK
which I will correct

**Comment by dimkr** [comment]
> so gcc-10 is a valid focal option............

It's a valid option, but not the default. `gcc` points to `gcc-9` because that's the default.

The /usr/bin/gcc symlink comes from the `gcc` package, which depends on `gcc-9` and not on `gcc-10`.
