### ISSUE TITLE
sfs-load fails with kernel-kit-output-5.10.x-x86  build 74

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#2529]
![Screenshot-error](https://user-images.githubusercontent.com/5926865/135442999-458af6f2-dd0c-4e51-953d-2632e49f021d.png)

kernel-kit-output-5.4.x-x86 build 74 seems to work ok..........

**Comment by dimkr** [comment]
![32](https://user-images.githubusercontent.com/1471149/135524801-c467d57a-d5fe-4482-9004-e9df4210675c.png)

Had to copy it to sda first, because sfs_load doesn't allow it to be in /tmp, and aufs protects against attempts to add aufs branches using directories under the aufs mount point:

![overlap](https://user-images.githubusercontent.com/1471149/135525074-8a166fec-1e6b-4a06-8efb-c971833d0a63.png)

Without the output of `dmesg`, it's hard to tell why sfs_load failed for you.

**Comment by peabee** [comment]
Maybe a bad download........not sure but
re-downloaded - checked md5s carefully - problem has "gone away".......
Sorry for any wasted effort!
