### ISSUE TITLE
Add yambar support to ptheme

### ISSUE THREAD

**Issue by dimkr** [puppylinux-woof-CE/woof-CE#2730]
If each theme has a matching yambar configuration file and ptheme just replaces it, this shouldn't be hard to do.

**Comment by 01micko** [comment]
Yes we have to `sed` the top/bottom orientation to the yambar config.

**Comment by dimkr** [comment]
> Yes we have to `sed` the top/bottom orientation to the yambar config.

I think it's better to have a configuration file for each theme.

For example, Dark Gray works better with a thin and minimalistic tray, while 412 and 431 work better with a more traditional configuration. In addition, the colors are different and it's not easy to `sed` them, unless you put a unique marker (in a comment) near each field that you want to replace.

**Comment by 01micko** [comment]
> I think it's better to have a configuration file for each theme.

True. 

One problem though, but I suppose can be overcame easily enough, in `slacko` I include multimedia stuff and that's why I committed  c1b71c2 that will run the appropriate media player if a DVD or CD is detected. I know `vanilla dpup` is more minimal so a few different `yambar` configurations will be needed, depending upon what is installed in the distro.

**Comment by dimkr** [comment]
For now I think it's OK to stick with whatever works for most users, even if this means less room for customization for more minimal builds. We have placeholders for missing applications (#2181) anyway.
