### ISSUE TITLE
Indicate the kernel source subversion if modified

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#2849]
Regarding the issue appeared in the forum with the wl wireless driver, I can confirm it too.
Same error with another out of tree driver (facetimehd.ko)
However, both modules load and work fine with "modprobe --force <module>"

**Comment by mavrothal** [comment]
In vanilladpup kernel subversion is kept at “0” although the source and build kernel subversion is changing.
As a result is not clear when an out of tree module must be rebuild.
The subversion change should be indicated either in the kernel per se or at least in the kernel sfs name. Something like 5.10.0-96.

**Comment by dimkr** [comment]
`cat /proc/version`

https://github.com/puppylinux-woof-CE/woof-CE/pull/2184

**Comment by mavrothal** [comment]
There are many ways to find kernel version is you start digging!
The point is when the kernel version and the kernel kit sfs are changed, in a  puppy "update" to be evident so the users will not start scratching their heads.

**Comment by dimkr** [comment]
This one should be fixed by #2867.

Tested by adding the kernel sources SFS from an older 5.10.x, `apt install broadcom-sta-dkms` and `modprobe wl`. The built module should keep working even when the kernel is updated, because there's no strict version checking anymore, and the module is at the right path (/lib/modules/5.10.0/updates/dkms/wl.ko).

**Comment by dimkr** [comment]
Fixe
