### ISSUE TITLE
slacko64 can't use the current labwc petbuild

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#3070]
This issue is because slackware-15.0 doesn't 'officially' (as in isn't in the repos) support wlroots and friends. Sure there are slackbuilds but that would be very messy.

I could (and have) concoct a mammoth `labwc-all` petbuild with all the goodies I need to produce a good functional distro.

**Comment by dimkr** [comment]
labwc is problematic because it always uses wlroots master, and not the latest release. The only way to support labwc until it stabilizes is to build wlroots too (if its dependencies are satisfied, they change often) and link statically.

**Comment by 01micko** [comment]
https://github.com/labwc/labwc/blob/cbed8acf010b9064e1379f81b3e64a22bfa08260/subprojects/wlroots.wrap#L3

**Comment by dimkr** [comment]
It's not perfect, sometimes you run into issues. For example, I tried to backport wlroots master (post-0.15.x) to bullseye64, but it needs some libraries (libwayland-*) to be updated, but static linking is impossible because wlroots depends on other libraries, which are dynamically linked against an older version of the problematic libraries. wlroots.wrap will work only if the host is new enough to build the latest wlroots, where you don't have a problem in first place.

**Comment by 01micko** [comment]
My proposal is pretty much slacko specific. I thinks it's doable .. and I just had my https://github.com/labwc/labwc/pull/314 merged :smile_cat: 

`<ot>` you wanna do Hebrew? (only six lines) `</ot>`

**Comment by dimkr** [comment]
> <ot> you wanna do Hebrew? (only six lines) </ot>

Sure, why not :)
