### ISSUE TITLE
busybox petbuild - /usr/sbin/javaiffind: line 18: vercmp: not found

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3080]
LxPupSc32

Having changed to the busybox petbuild now get:
```
/usr/sbin/javaiffind: line 18: vercmp: not found
/usr/sbin/javaiffind: line 21: vercmp: not found
```

javaiffind come from rootfs-skeleton..... so vercmp should be included??

**Comment by peabee** [comment]
In slacko_8.2.2-179
vercmp comes from
aaa_pup_c-1|aaa_pup_c|1||BuildingBlock|348||aaa_pup_c-1.pet|+cairo|basic pup apps|puppy|||

What is that?? and where does it come from?? and why is vercmp no longer provided by busybox??

**Comment by peabee** [comment]
Well aaa_pup_c seems to be ya-petbuild with a very strange set of random utilities in it......... but why??

And they seem to duplicate items already in rootfs-skeleton so are not needed???!!!

**Comment by dimkr** [comment]
> Well aaa_pup_c seems to be ya-petbuild with a very strange set of random utilities in it......... but why??

What's so strange about these "utilities"? Every Puppy has them.

> And they seem to duplicate items already in rootfs-skeleton so are not needed???!!!

I'll answer with a question: why use old prebuilt binaries? How do you ensure these binaries don't contain malware? What are you going to do the day you find a bug and must replace these binaries?

**Comment by peabee** [comment]
They are a strange mixture because vercmp is a standard Linux utility which can be (?) provided by busybox whereas the other 3 are Puppy specific binaries replacing binaries in rootfs-skeleton

The meaningless petbuild name should be something more descriptive like "rootfs-binaries". Is the aaa_ significant??

Specious argument about malware. Going back to source doesn't help - the source may contain the malware!! We don't do any security analysis of any of the components used to build Pups other than maybe a small degree of peer review of the source. And anyway its a free operating system which users use at their own peril.

**Comment by dimkr** [comment]
> They are a strange mixture because vercmp is a standard Linux utility which can be (?) provided by busybox whereas the other 3 are Puppy specific binaries replacing binaries in rootfs-skeleton

It's not a standard utility, it's a Puppy utility, and all busybox packages that have it are built with a busybox patch (!) that adds it.

> The meaningless petbuild name should be something more descriptive like "rootfs-binaries". Is the aaa_ significant??

The aaa_ is in the spirit of Slackware's aaa_base, aaa_libraries, etc'. I think it's a good name, considering what this package does.

> Specious argument about malware. Going back to source doesn't help - the source may contain the malware!! We don't do any security analysis of any of the components used to build Pups other than maybe a small degree of peer review of the source. And anyway its a free operating system which users use at their own peril.

If you can build the source code (= reproducibility) and find malware or a bug in the source code, at least, you can fix the problem and improve things over time. If you keep using some old magic binary, you're stuck with it: even if it turns out to be malicious, you can't replace it. Without reproducibility, Puppy will be forever stuck with issues that can't be solved, and legacy components that can't be replaced.

If you look closely, you'll see that the aaa_pup_c petbuild supports building against GTK+ 2 or GTK+ 3, while the old prebuilt binaries use GTK+ 2. If you don't want to use this petbuild and stick to the old binaries - go ahead and do that, but:
1) As I said, you're stuck with this binary as-is.
2) You'll have to include GTK+ 2 and its dependencies forever, but the clock is ticking: I wouldn't be surprised if Debian and Ubuntu stop packaging GTK+ 2 if few applications need it, and many of them (for example, asunder) are unmaintained for many years.
3) X is already on its way out of major distros, but if you want to stick with GTK+ 2, some things in your builds won't work under Wayland or run slowly (under Xwayland) and you'll have to include Xwayland in your builds forever, alongside GTK+ 2 and its dependencies.

You can resist change as much as you want to, but one day you'll just hit a wall.
