### ISSUE TITLE
pmusic - no executable permissions

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3462]
Executable permissions not set on files in:
rootfs-packages/pmusic/usr/local/pmusic

**Comment by zigbert** [comment]
@peabee 
Thank you for the feedback!

I used gitpod for the huge pMusic commit.
My local files is set executable, so there have been some converting during my Gitpod session.  
I checked gitpod now, and couldn't find any way to change file permissions...
Neither am I able to set permissions inside the github web interface...

It is of course lack of Github skills 

Can anyone point me to the knowledge.
How do I change permissions of a file in WoofCE

Thank you!

**Comment by dimkr** [comment]
`git update-index --chmod=+x ./path/to/file`

**Comment by zigbert** [comment]
I have struggled too long with the git commands in my running Slacko 7. - That's why I ended up with gitpod...

Can someone help me to change the permissions to executable of all files in

/usr/local/pmusic/
/usr/local/pmusic/frontends/
/usr/local/pmusic/plugins/

and the unique files

/usr/local/pmusic/themes/Gtk/themerc
/usr/local/pmusic/themes/Nad5/themerc
/usr/local/pmusic/themes/.NowPlaying/themerc

Thank you!
