### ISSUE TITLE
Error while installation from PPM in jammy64. Possibly petget error.

### ISSUE THREAD

**Issue by lakshayrohila** [puppylinux-woof-CE/woof-CE#3639]
I tried building jammy64 with current defaults and installed some programs using it. Don't know how many it successfully installed, but installing few it broke the system. I tried installing `apt` once for getting the same results and the next time `nano`. The common thing here, as I saw it, is `/bin/`. The executables of both programs are put in `/bin` and using `ls /bin/` after that listed only that program (atleast for `nano`; I think after installing `apt` even `ls` was not even found). **A PPM bug maybe?**

I was reading [this](https://github.com/puppylinux-woof-CE/woof-CE/discussions/3305) discussion some other day, and hence I see why there might be a bug:-
> Nobody here is working towards improving PPM, and it's essentially unmaintained for years.

**So, what might be the future of PPM in next releases?** I think it might be good to uninstall it. **But, how?** And which package manager to use instead of it? I tried building with `pkg` but it took forever to even update its repos without showing any movement, as if it was hanged; maybe due to  some bad settings used in builds? And what about `apt`? Could that be added as well (I'd actually like if we could)?

Actual question:-
1. What's the error (see https://github.com/puppylinux-woof-CE/woof-CE/issues/3639#issuecomment-1323985937) and how to resolve it?

Additional questions are (if this `petget` issue will never be handled):-
1. Should `PPM` be removed?
2. Should `pkg` be added?
3. Should `apt` be added?

**Comment by lakshayrohila** [comment]
`pkg ru` seems to work fine now after I tried it once again. Just took nearly 10-20secs. Still getting an error, which seems to say:-
```
Checking pkgs
/usr/local/petget/0setup: line 337: support/findpkgs: No such file or directory
Error 2: line 7853, Code error!
```

**Comment by lakshayrohila** [comment]
This error seems to be related to `petget`. Renaming the error.

**Comment by dimkr** [comment]
You can't just install apt through PPM to get apt support, it requires more than that. And PPM is so bad at installing packages with deep dependency trees I wouldn't be surprised if this breaks your system.

> And what about apt?

It's possible to add apt to jammy64, it's supported and works well as long as `USR_SYMLINKS=yes`.

However, bdrv.sh (which adds apt support) has [this protection](https://github.com/puppylinux-woof-CE/woof-CE/blob/38df028cc1bb5a2c762c537fd8f3e535c15e92c6/woof-code/support/bdrv.sh#L7) against builds that contain both Ubuntu and .pet packages. I added this in order to prevent woof-CE users from doing something like using a .pet package that has a .deb equivalent: if apt doesn't know that library x is installed (because it came from a .pet package apt doesn't care about), apt will try to install it when the user installs a package that depends on it.

I'll open a PR that adds a `BUILD_BDRV=yes/no` toggle in _00build.conf and removes this restriction - woof-CE users will need to be careful not to do things that conflict with apt.

**Comment by lakshayrohila** [comment]
> You can't just install apt through PPM to get apt support, it requires more than that. And PPM is so bad at installing packages with deep dependency trees I wouldn't be surprised if this breaks your system.
> 
> > And what about apt?
> 
> It's possible to add apt to jammy64, it's supported and works well as long as `USR_SYMLINKS=yes`.
> 
> However, bdrv.sh (which adds apt support) has [this protection](https://github.com/puppylinux-woof-CE/woof-CE/blob/38df028cc1bb5a2c762c537fd8f3e535c15e92c6/woof-code/support/bdrv.sh#L7) against builds that contain both Ubuntu and .pet packages. I added this in order to prevent woof-CE users from doing something like using a .pet package that has a .deb equivalent: if apt doesn't know that library x is installed (because it came from a .pet package apt doesn't care about), apt will try to install it when the user installs a package that depends on it.
> 
> I'll open a PR that adds a `BUILD_BDRV=yes/no` toggle in _00build.conf and removes this restriction - woof-CE users will need to be careful not to do things that conflict with apt.

Great work, thanks! Maybe it would be needed to write that in documentation, maybe with some examples of that what will actually conflict with `apt`.

Also had an idea- why not write an application that first searches for applications found in pet repos, if one found then install that one (`.pet` one); otherwise rely on distro dependent package manager (`slapt`, `apt`, etc.)? We could add this with name `pkg` (if `pkg` is as bad as `ppm` is; otherwise with a new name), maybe a new version of it?

Maybe this is a big project, and needs to be carefully written; but will that be possible?

**Comment by dimkr** [comment]
It's possible, but I don't think this is really needed. If the person who creates the .pet package repo for jammy64 doesn't create .pet packages for packages available in the Ubuntu repos and doesn't do ugly stuff like creating a single package that contains dependency libraries (that are normally available as a separate package), then this kind of conflict between PPM and apt shouldn't happen. Also, a "meta package manager" that calls either `apt install` or `pkg install` would be slow and inconsistent.

**Comment by lakshayrohila** [comment]
(Closed the issue as I think your PR is great).

But still PPM would be needed to be updated to install .pet packages only, right (the user may not know that PPM is not for ubuntu packages)?

**Comment by dimkr** [comment]
Since https://github.com/puppylinux-woof-CE/woof-CE/pull/3325, PPM doesn't provide the option to install Ubuntu packages if the bdrv SFS (= where apt is) is loaded, because when PPM installs a .deb package, apt doesn't know about this. In addition, it's super easy to break your system by installing an Ubuntu package with dependencies, due to various issues in PPM.
