### ISSUE TITLE
/var/spool/cups has wrong ownership

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3872]
As reported by @Marv....
Both S15Pup64 and S15Pup64 +2 built on Github
/var/spool/cups has ownership root:7 whereas it should be root:lp

![Screenshot](https://user-images.githubusercontent.com/5926865/215252878-fa1b2c9c-0fc8-4d81-bcbc-8ba5745ca09b.png)

Locally built +1 had the correct ownership

**Comment by dimkr** [comment]
Is this +1 or +2?

https://github.com/peabee/woof-CE/releases/tag/s15pup64-22.12-140123

![lp](https://user-images.githubusercontent.com/1471149/215256955-53c2673d-9f9e-4222-bef6-c753d9da28f9.png)

EDIT: this is from +2:

![2](https://user-images.githubusercontent.com/1471149/215257485-8f87096c-3d2e-474a-9abe-ff0a737aa708.png)

**Comment by peabee** [comment]
Yes - that release is +2 ..................

sha512:
2f1d065f739f19c7f198de5761f238783a03a693865f20b04999d534e23c12fcc5fad11b978d3b9cacc2ee4c85b6e2f95177cb013b8316c2e6095d676e4c4aaa

**Comment by peabee** [comment]
![Screenshot](https://user-images.githubusercontent.com/5926865/215259664-478d6bd4-2b30-4754-ae52-64bb897b1021.png)

**Comment by peabee** [comment]
I'll go back to @Marv for clarification as although it is root:7 in the puppy.sfs it is root:lp in the running system:
![Screenshot](https://user-images.githubusercontent.com/5926865/215261692-ef64b0ff-2c58-4bfe-b7ab-7e4d49c0e36b.png)

**Comment by dimkr** [comment]
Checking, the problem could be the Slackware post-installation script of CUPS that runs during 2createpackages. Group IDs are different between Ubuntu and Slackware, so if the script calls `chown root:lp ./var/spool/cups`, ownership will change to 0:7 even if Slackware assigns a different GID to `lp`. This is a classic woof-CE problem: it has always been sensitive to the host/target distro differences. (And you can't build a half-broken s15pup, then use it to run a "clean" build of s15pup from s15pup to get rid of this incompatibility.)

EDIT: looks like `lp` is 7 in Slackware too. The problem seems to be Puppy<>Slackware incompatibility, not Slackware<>Ubuntu incompatibility. It's woof-code/rootfs-skeleton/etc/group that needs to change to match Slackware. I had similar problems in dpup, so I created woof-code/rootfs-skeleton/etc/group.debian, where all group IDs match Debian.

EDIT 2: yes, `cupsd` changes ownership to `root:lp` at runtime, so the GID 7 vs. 102 difference between Slackware and Puppy doesn't break CUPS.

**Comment by peabee** [comment]
Thanks - that certainly explains what is happening - for some reason for @Marv cupsd mustn't have run to make the change - maybe he can work out why
