### ISSUE TITLE
Add LTS Kernel 6.1?

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3939]
Now that Kernel 6.1 has been declared LTS and is fully supported by AUFS it should be added to the kernel-kit builds....

I guess the question is which config should be used?

**Comment by dimkr** [comment]
I'm no longer maintaining kernels with aufs. I'm using 5.10.x and 6.1.x from https://github.com/puppylinux-woof-CE/woof-CE/actions/workflows/dpup-kernel.yml.

**Comment by peabee** [comment]
>           - kernel-kit-config: 5.15.x-x86_64
>             image: debian:bullseye-slim

what is the significance of "image" please?

**Comment by dimkr** [comment]
It's the container used to build the kernel. If you build the kernel inside an Ubuntu 22.04 container, use this kernel in a Slackware-based Puppy and a user tries to install out-of-tree drivers like NVIDIA drivers, it can fail due to mismatch between the GCC version used to build the kernel and the GCC in devx. Choose wisely.

**Comment by peabee** [comment]
Same as 5.15???

**Comment by dimkr** [comment]
Up to you, but for the sake of safety, I'd use `debian:bookworm-slim`, because Debian 12 will use 6.1.x, making it less likely to hit compiler bugs.
