### ISSUE TITLE
Dpup kernel 6.1.27 security advisory

### ISSUE THREAD

**Issue by radky2** [puppylinux-woof-CE/woof-CE#4108]
@dimkr

Is the following linux kernel security advisory of any consequence for 6.1.27 as implemented in dpup ?

https://www.debian.org/security/2023/dsa-5448

https://security-tracker.debian.org/tracker/DSA-5448-1

Thanks

**Comment by dimkr** [comment]
https://github.com/puppylinux-woof-CE/woof-CE/actions/workflows/dpup-kernel.yml automatically rebuilds the Debian kernel every two weeks, so no manual intervention is needed to get all Debian security patches in dpup.

This vulnerability was fixed in

```
[2023-07-05][ Accepted linux-signed-amd64 6.1.37+1 (source) into stable-security ](https://tracker.debian.org/news/1441935/accepted-linux-signed-amd64-61371-source-into-stable-security/)(Debian FTP Masters)
```

If you're in rush to apply this security update, I triggered https://github.com/puppylinux-woof-CE/woof-CE/actions/runs/5478468940 (so you don't have to for the next kernel build a week from now).

**Comment by radky2** [comment]
Thanks for the quick response !
