### ISSUE TITLE
kernel-kit fdrv construction issue

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#4144]
Something is wrong with fdrv firmware downloading...........

see: https://github.com/puppylinux-woof-CE/woof-CE/actions/runs/6257825226

```
Pausing here to add extra firmware.
building firmware for fdrv
+ read TAG URL
++ curl -H 'Accept: application/vnd.github+json' https://api.github.com/repos/thesofproject/sof-bin/releases
++ jq -r '.[0].tag_name + " " + .[0].assets[0].browser_download_url'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 84374    0 84374    0     0   127k      0 --:--:-- --:--:-- --:--:--  126k
+ test -n v2023.09-rc1
+ test v2023.09-rc1 '!=' null
+ test -n https://github.com/thesofproject/sof-bin/releases/download/v2023.09-rc1/sof-bin-v2023.09-rc1.tar.gz
+ test https://github.com/thesofproject/sof-bin/releases/download/v2023.09-rc1/sof-bin-v2023.09-rc1.tar.gz '!=' null
+ BASE=sof-bin-v2023.09-rc1.tar.gz
+ '[' -e sof-bin-v2023.09-rc1.tar.gz ']'
+ curl -fLo sof-bin-v2023.09-rc1.tar.gz https://github.com/thesofproject/sof-bin/releases/download/v2023.09-rc1/sof-bin-v2023.09-rc1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0 4824k    0 10473    0     0  19986      0  0:04:07 --:--:--  0:04:07 19986
100 4824k  100 4824k    0     0  8304k      0 --:--:-- --:--:-- --:--:-- 83.9M
+ DIR=sof-bin-v2023.09-rc1
+ rm -rf sof-bin-v2023.09-rc1
+ tar -xf sof-bin-v2023.09-rc1.tar.gz
+ cd sof-bin-v2023.09-rc1
+ mkdir -p /__w/woof-CE/woof-CE/kernel-kit/zfirmware_workdir/lib/firmware/intel
+ cp -r sof-v2023.09-rc1 /__w/woof-CE/woof-CE/kernel-kit/zfirmware_workdir/lib/firmware/intel/sof-v2023.09-rc1
cp: cannot stat 'sof-v2023.09-rc1': No such file or directory
............
WARNING: Extracting firmware from the kernel.org git repo has failed.
While your kernel is built, your firmware is incomplete.
Error: Process completed with exit code 1.
```

**Comment by peabee** [comment]
Looks like this recent pre-release:
https://github.com/thesofproject/sof-bin/releases/tag/v2023.09-rc1
is causing problems....
Any ideas @dimkr @01micko ?

It doesn't cause problems for 4.19 , 5.4 or 6.1(64).......

**Comment by MinTerra** [comment]
They renamed the folders
then causing get_sof.sh error while copying sof folder

![scr1](https://github.com/puppylinux-woof-CE/woof-CE/assets/135217304/266f0cdc-9898-495c-a3b4-65a6fc99f470)

**Comment by peabee** [comment]
Thanks @MinTerra 
Seems to be a permanent change from:
https://github.com/thesofproject/sof-bin/commit/877ac4739cdf3ca086d4be31d870ed9e1900a395

Suspect the code in:
https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/kernel-kit/get_sof.sh
needs to be changed to be compatible..........

**Comment by peabee** [comment]
Slackware does not have jq so get_sof.sh will never work on a Slackware system @dimkr

**Comment by dimkr** [comment]
> Slackware does not have jq so get_sof.sh will never work on a Slackware system @dimkr

kernel-kit.yml doesn't run on Slackware, so this is not problem for the periodic builds. Having one "canonical" build environment where kernel-kit works reliably was my main motivation when I automated kernel builds: 99% of people who complain about kernel-kit failures have a broken build environment with old or missing dependencies. Those who want to run kernel-kit locally instead of using the prebuilt kernels will need to install jq somehow, I don't see a better solution to extract fields from a JSON object in a shell script.

(The dpup kernels don't include fdrv built using kernel-kit, because fdrv is constructed from Debian packages, so feel free to re-implement get_sof.sh without jq. Good luck 😄 )

**Comment by peabee** [comment]
Maybe a check to see if jq is present and abort get_sof.sh if it isn't?

Are you OK for me to add this?

**Comment by dimkr** [comment]
> Maybe a check to see if jq is present

Adding some dependencies check before kernel-kit/build.sh does anything sounds like a better solution.

People are complaining that kernel-kit is broken when the real problem is missing dependencies, so fixing this only for jq sounds wrong to me.

And, get_sof.sh runs late in the build process, we don't want users to complain that they wait for hours only to find out that jq is missing.

**Comment by peabee** [comment]
Maybe both checks? Can jq be optional? Are there dire consequences if get_sof.sh doesn't run? Just soem missing firmware?

**Comment by dimkr** [comment]
You can skip get_sof.sh if you really want to, but audio won't work on many computers 🤷🏿
