### ISSUE TITLE
/etc/ssl/certs different for 32-bit builds (no symlinks)

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#4158]
In 32-bit builds (e.g. S15Ppup32 & VoidPup32),
/etc/ssl/certs has a single file - ca-certificates.crt in the puppy.sfs

whereas for 64-bit builds there are c. 300 symlinks in /etc/ssl/certs

Why this difference?? Where are these links created for 64-bit builds?

**Comment by dimkr** [comment]
AFAIK the only file that matters is /etc/ssl/certs/ca-certificates.crt - that's the CA bundle. If this one doesn't exist, all TLS certificate validation will fail. It's created from the individual certificates in /etc/ssl/certs by update-ca-certificates.

**Comment by dimkr** [comment]
https://github.com/puppylinux-woof-CE/woof-CE/blob/40f18008d47088068a8fa7a6a33e85101548ab4a/woof-code/packages-templates/ca-certificates/FIXUPHACK#L2

Maybe this line should be:

```
if [ "$WOOF_HOSTARCH" = "$WOOF_TARGETARCH" ] || [ "$WOOF_HOSTARCH" = "x86_64" -a "$WOOF_TARGETARCH" = "x86" ]; then
```

Otherwise, pinstall-cross.sh is used (and I wouldn't be too surprised if this script is broken) **and update-ca-certificates doesn't run**.

**Comment by peabee** [comment]
Doing a test build now. Thanks.
