### ISSUE TITLE
Ubuntu is moving system binaries from bin to usr/bin

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#4244]
Starting with 24.04
Presumably because 24.04 is heading to being a usrmerge distro.....
So far affected:
bash
udev

With the changes the bash & udev package/templates are no longer correct

**Comment by dimkr** [comment]
Also grep, sed and many other packages (inherited directly from Debian):

```
grep (3.11-4) unstable; urgency=low
[...]
  * Move files to /usr for DEP17 (Closes: #1059755)
[...]
```

```
sed (4.9-2) unstable; urgency=medium
[...]
  * Patch from Helmut Grohne to move sed to /usr/bin.  closes: #1059821.
[...]
```

(these two changes can break autoconf in a non-usrmerge sytsem and cause build failures in some packages)

The only practical solution is to build with `USR_SYMLINKS=yes` and finally align with Ubuntu: the old layout worked although Ubuntu went usrmerge-only only because Debian supported non-usrmerge until 12, but Ubuntu is slowly receiving the post-12 packages that assume usrmerge.

**Comment by peabee** [comment]
I would think that 99% of grep and sed uses would be path agnostic.
However searching for bin/grep in woof-code does show a couple of uses of "grep with path attached" although its not clear why. e.g. /woof-code/packages-templates/geany_FIXUPHACK
There are no occurrences of bin/sed.
All the petbuilds currently build OK.
I suspect that this may be the finish of the UPup32 series.....

**Comment by dimkr** [comment]
> I would think that 99% of grep and sed uses would be path agnostic.

739cb62 was needed because this assumption is wrong. Some build systems assume /bin/grep, etc'.  You'll see this once you start building more things from source instead of relying on .pet packages built in some older Puppy.
