### ISSUE TITLE
Standardize Icon Theme

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#539]
Puppy has a default icon theme, with is ROX specific. That icon theme is very limited and small in size, which is good.

- /usr/local/apps/ROX-Filer/ROX/MIME

I'm looking at that folder in woof, there are already a few icons. Uhmm...

Now, that prevents choice in the system level. Other file managers are unable to use ROX themes, which is bad.

However ROX can also use the standard icon theme hicolor. Just by changing one setting and now ROX is using true standards.

All icons should be moved/copied to /usr/share/icons/hicolor/48x48/mimetypes. ROX will work the same.

- /usr/share/icons/hicolor/48x48/mimetypes

From now on, other icons can be added, ALL file managers will be benefited by this.

**Comment by 01micko** [comment]
These icons shouldn't even be there at all. They should be part of the rox
package. A rox package could then have a pinstall.sh to symlink that
directory to /usr/share/icons/hicolor/48x48/mimetypes.

**Comment by jamesbond3142** [comment]
Ummm, no. 

hicolor is not a "standard" icon theme. In most cases icons should *not* be put into /usr/share/icons/hicolor; only those that are absolutely essential, or only application specific icons. "hicolor" is in fact a "fallback" icon theme, which will be used if there is no icon theme being used *OR* if icons cannot be found from the currently-used icon theme.

If you want to do it properly, then there should be a /usr/share/icons/ROX which is a symlink to where keeps its mimetype-icons; then set icon theme to "ROX". This should work on all conforming GTK applications. This way, next time you want to have a new icon, just create a new icon theme (e.g. /usr/share/icons/tango or something) and change the default icon theme to that - and ALL apps will automatically changes their icons (I lied - rox won't - but then rox is special. Either way, there is a configuration item in Rox to change the icon theme it uses too). 

cheers!


On Wed, 06 May 2015 15:59:17 -0700
jlst <notifications@github.com> wrote:

> Puppy has a default icon theme, with is ROX specific. That icon theme is very limited and small in size, which is good.
> 
> - /usr/local/apps/ROX-Filer/ROX/MIME
> 
> I'm looking at that folder in woof, there are already a few icons. Uhmm...
> 
> Now, that prevents choice in the system level. Other file managers are unable to use ROX themes, which is bad.
> 
> However ROX can also use the standard icon theme hicolor. Just by changing one setting and now ROX is using true standards.
> 
> All icons should be moved/copied to /usr/share/icons/hicolor/48x48/mimetypes. ROX will work the same.
> 
> - /usr/share/icons/hicolor/48x48/mimetypes
> 
> From now on, other icons can be added, ALL file managers will be benefited by this.
> 
> 
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/puppylinux-woof-CE/woof-CE/issues/539


-- 
James B <jamesbond3142@gmail.com>

**Comment by technosaurus** [comment]
If you are going to remove them frome woof-ce, rather than making them part of some rox package, you may as well split them out into a no-arch package and put them in /usr/share/icons/hicolor/*/mimetypes/*  Then have rox depend on it with an appropriate symlink.

Since these are in fact the icons that we would want themes to fall back to, we should also do something similar for:
 `mini-icons` to 16x16
 `midi-icons` to 48x48
 `pixmaps/puppy` to scalable
 In the process it would be nice if we could add appropriate links where possible to accommodate the [icon naming spec](http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html)
Not that it matters but /usr/share/pixmaps _should_ be xpm images, not a mix of pngs too - the pngs should go to hicolor/WxH/apps (xpm is still part of the icon theme spec so it is ok to put the mini-icons in hicolor/16x16 because they take up way less space than an equivalent png on a squashfs, but they _are_ deprecated)
