### ISSUE TITLE
Update mimetypes

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#540]
Puppy uses defaults, has already many file associations in woof. Which that means that is outdated.

It's based on two files:

- /usr/share/mime/packages/puppy.xml

This file contains mime types like 2fs, 3fs, 4fs, initrd.gz, and other strange filetypes but are essential for mounting images and administration.

However that file is not in woof but in a separte package. That is a bug.

- /usr/share/mime/packages/freedesktop.org.xml

This contains outdated standard mimetypes, which can be updated, MIME types are essential in a system, they define a system.

This again, is an essential file, it belongs to woof.

By adding these two files and add/update/fix MIME associations in /root/Choices/MIME-types , ROX will continue to work as expected.

A lot of work is to be done with an alternative file manager like PCManFM.

**Comment by 01micko** [comment]
It's not a bug per se, but I agree that specialised puppy mime-types should be in woof.

**Comment by technosaurus** [comment]
the package manager is crap anyhow.  During its rewrite, package installation should trigger an scan of .desktop files for supported MIME-Types and offer to make the Exec= the handler or override existing handlers if they already exist.

In the mean time /root/Choices/MIME-types is not where this stuff should be anyhow.
Since anything in Woof-CE should be "system-wide", everything here should be in:
`/etc/xdg/rox.sourceforge.net/MIME-types/`

For package install scripts, the entire contents of "Choices" should be moved to `$XDG_CONFIG_HOME/rox.sourceforge.net/`
(for puppy that is /root/.config/rox.sourceforge.net/)

`/root/Choices` is an outdated directory from rox-1.x days and current versions of ROX silently copy it all to the proper place anyhow... lots of wasted save file space for no good reason
