### ISSUE TITLE
ROX should not be hardwired

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#541]
In Puppy many default programs are actually scripts, which are overwritten everytime a user chooses another program as default for a specific action.

defaulthtmlviewer
defaultimageviewer
defaultwordprocessor

defaultfilmanager or defaultfm.... damn it's not there. It's a bug.

ROX is also hardwired in some scripts. To avoid being diligent and change the code, rox can be used insted of defaultfilemanager.

- /usr/local/bin/rox 

Is a symlink to the actual rox, could also be a symlink to another program.

A little script can handle this situation.

For example, one can do this:
defaults fm rox
defaults fm pcmanfm

**Comment by jlst** [comment]
As a side note, ROX is for experts.

ROX shows a lot different colors, one can tell if a script has the executable flag. Recent modified files are in bold.

Besides that, the average user, specially those who come from Windows, only want to copy & paste, cut & paste

- CTRL-C CTRL-P 

Such a basic feature is not ROX, which is enough drive away or enrage many people. I have witness that.

**Comment by mavrothal** [comment]
Hi jlst,
regarding the series of issues you reported (#539-#545) it would appear that they relate to puppy packages added during build rather that a core puppy-base that rootfs-skeleton holds in  woof-CE. To that extend many of these issues should be handled by the package install scripts rather than woof code.
Regarding ROX-filer is indeed heavily integrated into the puppy-code and it takes a lot of effort to remove it. You may want to look at the woof-next branch and see if you would like to work there for the next puppy-building system.
Regarding, the current puppy-building woof-CE branch (ie testing) would be great if you could provide   are tested to work in minimal and standard puppy builds, while alert pet/package developers to modify/include install scripts for non-standard packages with the changes you see fit.
Thanks for talking the effort.

**Comment by technosaurus** [comment]
Puppy has integrated Rox's in-house XDG implementations instead of using the xdg spec.
This pull request makes rox more interoperable with standardized file managers
  https://github.com/rox-desktop/rox-filer/pull/3

**Comment by mavrothal** [comment]
If this is never pulled (looks ROX is unmaintained the last couple of years) it means that we should maintain our own ROX-Filer fork and distro specific binaries. Right?
Or maybe modify the rox petbuild to get the sources from https://github.com/dtomas/rox-filer/archive/master.tar.gz (unless fatdog's source is changed already)

**Comment by technosaurus** [comment]
@mavrothal - the dtomas repo definitely looks more active and it appears to incorporate many code cleanups.  At this point, the offical repo is all but dead.
