### ISSUE TITLE
Expand petget capabilities

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#547]
Petget is so slow that I had to write a lightweight replacement for it.

I do check the filelist for the tar --strip option, but I also use the same filelist to determine if system updates are needed.

This is easy to understand and expand

	while read FILEx; do	
		case $FILEx in
			*/usr/share/mime/packages/?*) 		 HASMIME=1 ;;
			*/usr/share/applications/?*.desktop) HASDESKTOP=1 ;;
			*/usr/share/icons/hicolor/?*) 		 HASICONS=1 ;;
			*/usr/share/fonts/default/?*) 		 HASFONTS=1 ;;
			*/usr/share/man/?*)					 HASMANUAL=1 ;;
		esac
	done <<< "$filelist"
	

That way I can also process a directory full of packages to install. I also "merge" all install scripts into one. The woof style. Then there is a final script and some variables tell me what to update.

if [ ! "$IGNORE_POSTINSTALL" ] ; then #can be set anytime

	if [ "$PINSTALL" ] ; then
		echo -e "\n========= NOW RUNNING INSTALL SCRIPT(s) ============\n"
		${FORCELOCATION}/pinstall.final
	fi
	rm -f ${FORCELOCATION}/pinstall.final
	

	echo -e "\n========= POST-INSTALL ACTIONS ============\n"
	
	if [ $HASDESKTOP -eq 1 ]; then
		echo "--- Updating menus ---"
		fixmenus ; jwm -reload &>/dev/null || jwm -restart
	fi
	
	if [ $HASMIME -eq 1 ]; then
		echo "--- Updating MIME database ---"
		update-mime-database /usr/share/mime
	fi
	
	if [ $HASICONS -eq 1 ]; then
		echo "--- Updating HICOLOR icon cache ---"
		gtk-update-icon-cache -i -f /usr/share/icons/hicolor 
	fi
	
	if [ $HASFONTS -eq 1 ]; then
		echo "--- Updating FONTCONFIG cache ---"
		fc-cache -r /usr/share/fonts/default
	fi
	
	if [ $HASMANUAL -eq 1 ]; then
		echo "--- Updating MAN database ---"
		mandb -q
	fi
	
fi

**Comment by mavrothal** [comment]
I would recommend to make a pet and put it in the forum so people can test at various settings and see how it goes.
PPM is also used during puppy building in woof so it may have some extra stuff. If an alternative package manager works as well PPM scripts could be moved to devx and your PPMv3 can go mainline.
So, give us a pet to replace PPM ;)

**Comment by technosaurus** [comment]
@wdlkmpx is on the right track here.  petget is currently just a glorified tar wrapper.   The non-graphical parts of PPM should be moved to petget.
@mavrothal - perhaps a .pet is not the best way to test something that may replace petget (what happens when it a user uninstalls it) ... better to post it as a script

**Comment by mavrothal** [comment]
> perhaps a .pet is not the best way to test something that may replace petget (what happens when it a user uninstalls it) ... better to post it as a script

Should go back on whatever was before. 
If the pinstall script wipes out all PPM related scripts the puninstall should just reinstate it.  
But if a single script can do all of PPM functions, a script is fine.
Alternatively the new PPM/petget could install in /usr instead of /usr/local and get priority over the old one.

If someone redesigns PPM I think should be in 2 steps. First build a solid CLI app that can do all things PPM does, ie be a package manager and a puppy builder at the same time and be able to handle 5-6 different kind of packages and their (cross-referenced) dependencies. 
When happy with it go for the GUI.

**Comment by wdlkmpx** [comment]
Well, my script is very small, but I can certainly edit the petget scripts, but I get lost when it comes gtkdialog dialogs

This is how my script looks like right now, there is no security, it just to install loads of files as quickly as possible

http://pastebin.com/YnhAEBH0
