### ISSUE TITLE
What do do about rootfs-packages?

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#590]
@zigbert has some very nice work in there. The problem is that @joewing has been doing a lot of work on JWM the past couple of months and broken backwards compatibility. I know ziggy will be back soon (late fall?) to address these issues. 

Of course some builders want the old 'look and feel' of puppy. That's fine but I prefer the newer designs.

So what is the solution to keep everyone happy?

In this instance, @zigbert package depends on the binary `switch2` which is handy for switching gtk themes on the CLI, however I think we make `switch2` a pet package and let the builder decide if she/he wants it. If, in `3builddistro` we detect that `switch2` is indeed installed then we copy in the `rootfs-packages` else we proceed with the old way of popping  the gui for choice of wallpaper, jwm-them, gtk-theme etc.

If the builder has switch2 then we can offer a choice of which ziggy theme to use (just CLI I think for now). I made a nice 'buntu' theme (see the forum - but I do need to update the gtk-theme).

**Comment by mavrothal** [comment]
If the issue is just what is now in rootfs-packages I would say move it to a pet. However the idea of rooffs packages is to be hosting the no-arch and most of the common pets to facilitate maintenance and stop pet update hunting. For example sfs_load is a standard in puppy as is many other bash/gtkdialog apps. However, no pet maintainer besides zigbert came forward so far, so I would think that we can forget about it.

**Comment by zigbert** [comment]
I don't think rootfs packages should be deleted. There is a major difference between the 2 apps in it (atm) and other noarch apps like pFind. pTheme and jwm_config is completely bound to a running Woof-CE system while pFind will work in other Puppy (and alien) environments. 

So why not store them in rootfs-skeleton? - because they require JWM - that some builds don't rely on... Atm, Rox and GTK is hardcoded, but not the window manager (if I got it right).

pTheme will work without JWM, but is not yet prepared for other window managers. It might be a good idea to do so, and then replace gtk-chtheme by switch2 and pTheme. pTheme includes a separate gui-module for setting gtk theme - /usr/sbin/ptheme_gtk. If we do this, it could probably be ok to move pTheme to rootfs-skeleton.

But, it could also be the other way around - moving the apps in rootfs-skeleton that relies on external/optional backends to rootfs-packages. Bcrypt, Xdelta, ...

**Comment by dimkr** [comment]
What is the purpose of pTheme? Does it solve some real problem?

**Comment by mrfricks** [comment]
if the packages are to be kept,  they need to have more traditional/sane defaults.  right click on desktop should bring up a menu and the top tray really shouldn't be active as it covers all the icons, and just mirrors the better looking bottom tray.

at the moment i end up just deleting the contents of rootfs-packages to save myself work. i believe as it stands users would find the defaults confusing as well

**Comment by dimkr** [comment]
I second that - I deleted rootfs-packages in Librepup, because of the default settings (two panels, duplicate functionality between the panel icons and the desktop icons).

**Comment by mrfricks** [comment]
also builders new to woofCE probably won't realise why their newly built pup has the big top tray and missing right click menu.. i know i didn't for a while

**Comment by mavrothal** [comment]
I tink we are discussing 2 different things. One is pTheme itself which is currently in rootfs-packages and could be modified if problematic. This can be dome by zigbert according to feed back or anybody else that may have specific changes corrections.
Then is the rootfs-packages folder "idea" as maintenance site for no-arch and common puppy pets used in all puppies. As I said the idea did not "fly" so I would suggest to eliminate this option. 
Do we agree on that?

Regarding the specifics (pTheme) I think has some distinct features and is touch friendly in contrast to all other themes. Could eliminate or "optionalise" some features but I personally like it ;)

**Comment by dimkr** [comment]
> I think has some distinct features and is touch friendly in contrast to all other themes.

The real question IMHO, is, do we /need/ that touch friendliness? Puppy isn't very touch-friendly anyway (because it uses applications like Geany and Sylpheed).

**Comment by 01micko** [comment]
Read the opening post. 

While it does somewhat miss the point as @mavrothal explained it does offer food for thought. 

I will tell you now, it is a royal pain in the arse updating Pmusic, Pburn, pfind, pfilesearch, sfs_load, grub4dos, frisbee, whatever usual puppy app that resides in *noarch.

Then you have to make sure everyone is on the same page. 

At the end of the day, each app in `rootfs-packages` can be optional, with reasonable sane defaults. Ptheme is quite good. the problem with it is that Joe (as said) really started pushing JWM and it isn't capable of keeping up without fairly constant support. I know I'm a bit tired of the '95 look and feel!

As for touch, well the future is now. Sylpheed and such don't matter when there is apps such as easy-stroke that offer pinch to zoom and neat scrolling (tested in fatdog64 on an iconia-tab). Possibilities folks!

**Comment by zigbert** [comment]
This is a bit off-topic compared to the first post, but let me give a quick background-knowledge of jwm_config and ptheme. When some of you say you don't like these, I can't think otherwise than this is lack of knowledge. I can't see any drawbacks using them, - but what should be the default values/settings is something total different. But different opinions are easy to handle for ptheme (explained later in this comment).

jwm_config:
- A gui to set jwm configuration.
- An improved version of jwmconfig2. Simplified gui and extended options.
- Intergated and same outfit as wizardwizard, the default 'control panel' in Puppy.
- I hear that jwm is moving forward and jwm_config is outdated. That happens to the old jwmconfig2 as well. Code needs to be maintained wherever they come from.

ptheme:
- Join all themable modules in Puppy (gtk, jwm, rox, ...). NB! This includes appearance of trays, desktop-icons-templates etc. Not only colors and graphics.
- Either set a global theme (all themable modules) or dig deeper into module by module.
- Clean up the Desktop menu by removing menuitems for themable modules like icon_switcher, gtk-theme-switcher, etc.
- One click/command switch from mouse to touchscreen interface.
- One click/command to give the Puppy desktop a total new look and feel. That's not important - but it's still cool.

ptheme -p global_theme
will activate whatever valid theme (ptheme can build and save these global themes in gui). I have built some themes and Mick has done an ubuntu theme, and If you want a Puppy_Classic theme, we simply put it together, and you get the good old Puppy look in one click/command. What about asking during woof-build what global theme to use. I have not tested this, but I can't imagine it would be troublesome.

As Mick said, I can't see the reason for not offering Touch-support when we are that close. I can't see any reason for not pushing the Puppy desktop further.

**Comment by 01micko** [comment]
I want to add frisbee to the mix in `rootfs-packages`. I have made a super simple gui that pops up with checkboxes. It just loops through and adds whatever is there to the gui; there is no need of a fancy gui as it is one off. I should really add sfs_load too, and have its checkbox set to 'true' by default; the others can be false.

Maybe I'll do that after the merge, but for now (when my freaking elictricity gets reconnected - works in my street in progress). I'll add the gui to 3builddistro(-Z) as it is super simple.

**Comment by 01micko** [comment]
Ok, here we go. I'm building from `fdrv` (which is in sync) and I have put in the gui +sfs_load, +frisbee, adjusting the pinstall in frisbee (what a whopper!) because clearly most of it was to fix residue from old frisbee installs. `sfs_load` has the <default> tag set true. I'll just post the code:

```
for d in $(ls rootfs-packages)
do  
       LIST="sfs_load|pfilesearch|pfind"
       echo "$d" | egrep -q "$LIST" && def=true || def=false 
       CBOXES="$CBOXES""<hbox space-expand=\"true\" space-fill=\"true\">
		<checkbox>
			<label>$d</label>
			<default>$def</default>
			<variable>$d</variable>
		</checkbox>
	</hbox>"
done
CHOICE=/tmp/choice$$	
export GUIC="<window title=\"Choose extra packages\">
	<vbox>
		<hbox>
			<text>
				<label>Here you can choose what extra packages to install. These are maintained as part of woof</label>
			</text>
		</hbox>
		$CBOXES
		<hbox><button ok></button></hbox>
	</vbox>
</window>"
gtkdialog -p GUIC -c > $CHOICE
. $CHOICE
if [ "$EXIT" = "OK" ];then
	while read line
	do 
		if echo $line|grep -q "true" ;then
			echo "copying ${line%%=*}"
			cp -a rootfs-packages/${line%%=*}/* sandbox3/rootfs-complete/
			cat sandbox3/rootfs-complete/pinstall.sh >> sandbox3/pinstall.sh
		else
			continue
		fi
	done < $CHOICE
fi
rm $CHOICE

```

..and what it looks like. Sure ther can be more dialog added later.

![3bd-gui](https://cloud.githubusercontent.com/assets/1019119/10298732/66fe3cae-6c25-11e5-8869-859521af3e6f.png)

**Comment by dimkr** [comment]
(Don't forget to merge my fix for sfs_load - need to use name -r | cut -f 1 -d - instead of uname -r)

**Comment by 01micko** [comment]
Got it, thanks

**Comment by 01micko** [comment]
BTW, that code will works if sfs_load and others aren't present in rootfs-packages; that's why I put in pfind and friend - just in case. What ever can be added to the egrep test anyways. I think the gtkdialog gui can go to testing, because it works fine.. posting from my build now.. but of course there are bugs!

Here's a new one to me .. need this for firefox to run at each boot.. (maybe other stuff too)
```
dbus-uuidgen > "/etc/machine-id"
```
And boy.. firefox really sux with all these freaking ads on the speed dial page :disappointed:

**Comment by dimkr** [comment]
Are you sure about that? Ubuntu places it under /var/lib/dbus/machine-id, at least on some versions.

**Comment by 01micko** [comment]
It's probably not starting in the init.d script. I'll poke around.

Hmm.. this is in /etc/init.d/dbus-machine-id-gen `dbus-uuidgen > /var/lib64/dbus/machine-id`

Just that don't work for firefox. Probably something missing.

**Comment by dimkr** [comment]
Slackware's dbus and the old dbus PET could be configured differently.

**Comment by 01micko** [comment]
Um it's 64 bit, I'm using slackware's

**Comment by dimkr** [comment]
http://unix.stackexchange.com/questions/84777/how-dbus-calculates-machine-id, maybe you should add a symlink (/etc/machine-id -> /var/lib/dbus/machine-id). Also, /var/lib is not /var/lib64 on x86_64 on other distros.

**Comment by 01micko** [comment]
Hmm.. the init.d script comes from Barry.. see the dbus template.

Slackware's dbus rc.messagebus goes to /etc/rc.d .. it *should* work, but isn't.

**Comment by 01micko** [comment]
Ok, I've made a separate template called 'dbus_slack'. I'll see if that works. In my running system right now I think I moved it there manually. It's been running 12 months!

**Comment by 01micko** [comment]
Yep, that worked.
