### ISSUE TITLE
Speed up petget

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#702]
I would like to make it faster 'cause I can't use it.

So far I've just been looking at one script, I can't help but rewriting everything while understanding this code, which of course is a waste of time. But that is another discussion and the next year I will be looking for any job I can find, so I'll might end up losing my skillzz and my ability to communicate and express my thoughts

So, I would like to know what specific code needs to be sped up

**Comment by mavrothal** [comment]
Petget does not have any major bottlenecks speed wise. In my machine takes about a second real cpu time which feels even less since you must acknowledge a couple of windows during the process. So getting it down to half a second (if possible) may not be really noticeable.
Not sure if besides what you already tackled, there are other puppy scripts processing long lists.
The woof scripts 2createpackage and 3builddistro-Z, may (did not look carefully)

**Comment by wdlkmpx** [comment]
I think I mean the PPM, I guess it has to do with dependency checking

**Comment by wdlkmpx** [comment]
I also see that arch linux stuff is outdated everywhere. Although I
don't know if it's possible to get a working arch pup now that are
systemd dependencies everywhere

tar.gz is not a valid arch linux package

puppy.xml can be updated with these mimetypes

	  <mime-type type="application/x-arch-package">
		<comment>Arch Linux Package</comment>
		<glob pattern="*.pkg.tar.xz"/>
		<glob pattern="*.pkg.tar.gz"/>
	  </mime-type>

**Comment by mavrothal** [comment]
Yes, dependency checking can be improved. Specially the cascading part. Similar code is also present in  installed_size_preview.sh
