### ISSUE TITLE
huge_extras should be merged with original scripts

### ISSUE THREAD

**Issue by wdlkmpx** [puppylinux-woof-CE/woof-CE#731]
Or something like that.

It took me a while to realize that there is a special init for 'huge kernels'. There is even a special rc.sysinit.

As you can see here, a huge kernel can work with the original init with just a few tweaks:
http://murga-linux.com/puppy/viewtopic.php?p=883321

3builddistro could generate a ZCONFIG file with something like this:

	PUPDESKFLG=0
	DEVTMPFSFLG=1
	HUGEKERNEL=1

That could go in initrd.gz/ZCONFIG

init can source the file and do something
	
	#precaution
	PUPDESKFLG=0
	DEVTMPFSFLG=0
	HUGEKERNEL=0
	#config written by 3builddistro
	. /ZCONFIG
	if [ $PUPDESKFLG -eq 1 ] ; then
		...
	fi

	if [ $DEVTMPFSFLG -eq 1 ] ; then
		...
	fi
	
	if [ $HUGEKERNEL -eq 1 ] ; then
		...
	fi

The very same file will be copied to the layered filesystem before switching root:

cp -a /ZCONFIG /pup_new/etc/rc.d

And finally the other scripts will use that info accordingly:
	
	#precaution
	PUPDESKFLG=0
	DEVTMPFSFLG=0
	HUGEKERNEL=0
	#config written by 3builddistro
	. /etc/rc.d/ZCONFIG
	if [ $DEVTMPFSFLG -eq 1 ] ; then
		...
	fi
	
	if [ $HUGEKERNEL -eq 1 ] ; then
		...
	fi

Something very easy to do.. and will make updating 
scripts and stuff directly from woof-ce extremely easy..

**Comment by wdlkmpx** [comment]
I noticed slacko has this
DISTRO_KERNEL_PET="Huge_Kernel"

So if this standard, then

huge_extras/rc.sysinit

can be /etc/rc.d/rc.sysinit_huge

/etc/rc.d/rc.sysinit

	. /etc/DISTRO_SPECS
	if [ "$DISTRO_KERNEL_PET" = "Huge_Kernel" ] ; then
		exec /etc/rc.d/rc.sysinit_huge
	fi

--

Also huge_extras/init has this:

	cp -a /DISTRO_SPECS /pup_new/etc

That line should also be present in the normal init, below this line

	cp -af /tmp/* /pup_new/initrd/tmp/ #keep any log files.

**Comment by wdlkmpx** [comment]
Actually the differences between rc.sysinit and huge_estras/rc.sysinit is so minimal that it makes sense to make it one script


3builddistro has this line, it only affets the beginning of a line

	sed -i -e 's%^DEVTMPFSFLG=.*%DEVTMPFSFLG=2%' rootfs-complete/etc/rc.d/rc.sysinit

So something like this makes sense:

	DEVTMPFSFLG=0 #this line is modified by 3builddistro
	if [ "$DISTRO_KERNEL_PET" = "Huge_Kernel" ] ; then
		DEVTMPFSFLG=1 #this line will remain untouched
	fi

And 2 or 3 other small changes and it's done... a complete rc.sysinit.

**Comment by mavrothal** [comment]
Theoretically woof should build every puppy from 4.x onwards. So the 3-Z version was developed in order to accommodate the new approach without affecting old ones and without a predefined picture of how it would evolve (and still evolving). 
A major headache in having one script is that we must make sure that no  5.5-and-back puppy is broken with any new changes. If you want to go ahead and check that no puppy is affected after the merge, please do. However given the slow building process and the fact that none in the wild is build old puppies, it was discussed at some point that after this cycle, old scripts will go to a "legacy" branch and master/testing will build only 6+ puppies. 
As you can see though, the current  cycle is still open, people keep adding stuff to testing and everything remains in limbo. I think is up to the puppy builders (Mick, Igu, Phil, Peebee)  to decide if/how/when to proceed with the "legacy" branch.

**Comment by wdlkmpx** [comment]
Well, the way I see it is that really old and obsolete hardware works with kernel 3.14.55, it would often crash on first boot with slacko, but it works fine with precise puppy 5.7.1, I think it has to do with some programs, even 1stbootwelcome or something like that, I don't have any of those apps running by default in precise puppy, except retrovol.

Many people stick to old puppies, I do.. the only reason is that I have been compiling and gathering stuff for this version since 2013),  it runs the latest woof-ce code in initrd.gz and in the main sfs file, even a reasonable recent kernel taken from slacko 6.3.0 and now mounts stuff it didn't mount before.

From mainboards 2002-2003 onwards (the ones I tested) there is no problem, graphic cards from 1998 onwards.. no problems. 

This is my current rc.sysinit working for legacy kernels and huge_kernels, perhaps you might want to test a bit?

http://murga-linux.com/puppy/viewtopic.php?mode=attach&id=94180

**Comment by wdlkmpx** [comment]
I think the huge stuff should become the standard and the legacy code can be safely deleted..
