### ISSUE TITLE
Re gh-pages branch

### ISSUE THREAD

**Issue by 01micko** [puppylinux-woof-CE/woof-CE#754]
This now defunct _but_ that doesn't mean it can't serve a purpose.

What about a jekyll blog? Served up by blog.puppylinuxDOTcom? (possibly a direct link but if not a re-direct).

Since Barry has bowed out, Ladislav Bognar needs somewhere to get his info from for distrowatch.

Thoughts?

**Comment by mavrothal** [comment]
Sounds good (as long as you do not expect me to write anything :smiley_cat: )
**You** (the owner of the blog)  can also have invited pieces on various subject _a la_ BK's

**Comment by 01micko** [comment]
> Sounds good (as long as you do not expect me to write anything :smiley_cat: )
You (the owner of the blog) can also have invited pieces on various subject a la BK's

Anyone with commit rights can write what they like. All others are subject to a pull request.

Just was thinking.. I'm not even sure if jekyll is needed. Markdown are flat files and I reckon the format we have over at the other repo is excellent. As long as we could make an engine to retrieve those then I think jekyll is overkill. Like I said _me ... thinking!_ :laughing: 

In saying (th**u**nking) that, we could do that at the other repo anyway!

**Comment by jamesbond3142** [comment]
Content-wise: A blog that hosts piece of thought from various puppy community members - devs, maintainers, contributors, artists, advanced users, new users, etc would be good for variety and to keep the interest high. _Assuming_ we can attract those people to write in the first place :smile: 

I think we should be able to pull raw content from github. If those contents are in markdown then we can process it just like we do it in the other side. In theory (if github doesn't restrict it) we should be able to have an automated summary page, with links to actual post.

Then all blog posts would be just regular markdown content, perhaps following a special naming convention (by date, by topics, or something like that) so that the "blog engine" can pull out the appropriate content in appropriate order. No server-side processing necessary, all done client-side.

**Comment by 01micko** [comment]
> I think we should be able to pull raw content from github. If those contents are in markdown then we can process it just like we do it in the other side. In theory (if github doesn't restrict it) we should be able to have an automated summary page, with links to actual post.

> Then all blog posts would be just regular markdown content, perhaps following a special naming convention (by date, by topics, or something like that) so that the "blog engine" can pull out the appropriate content in appropriate order. No server-side processing necessary, all done client-side.

You explained my thoughts better than I could! :smiley_cat:

**Comment by jamesbond3142** [comment]
:smile:

I just tested, we _are_ able to pull raw content from github using its API. So yes, we can do it - at least from the technical side. How we can sustain and keep the blog running is another things ... but we're optimistic people, aren't we, mavrothal? :jack_o_lantern:

**Comment by mavrothal** [comment]
> but we're optimistic people, aren't we, mavrothal?

There are those that they think we are, and those that think. :smiling_imp:

**Comment by jamesbond3142** [comment]
:innocent: :grinning: 
Well, for whatever it is worth, if everyone here like the idea, I'll see what I can do. I'll post you a link when I have something to show.

**Comment by mavrothal** [comment]
Go ahead but as Mick hinted before (I think), why have the blog here and not in the puppylinux-woof-CE.github.io repo? Maybe add a link the banner too (risking phone compliance). 
Gh-pages could become a site for indeed the woof-CE project rather than puppy in general.

**Comment by 01micko** [comment]
> (risking phone compliance). 

Part of my thought was the "News" should point to a blog instead of puppylinux.org/news

**Comment by jamesbond3142** [comment]
I was thinking along the same way. I initially thought having "news" integrated into puppylinux.com, but if puppylinux.org/news is alive then it seems quite a bit of waste to have duplicate effort writing the same stuff (and eventually, one of them will end up neglected - not good!). A blog would be good since it has a bigger scope than just "news" (it can contain trifles, op-ed, etc too). 

I could implement this "blog" thing in puppylinux.com and pull contents from ether here, or puppylinux-woof-CE.github.io, or both - as long as the structure to pull from is clear. I tend to agree that gh-pages in this repo should become a specific site for woof-ce related new/site/blog/whatever. But I'll let our master steward make the call :smiling_imp: :innocent:

**Comment by jamesbond3142** [comment]
On further thinking, since I read in the other repo that "in_progress" stuff is quite useless, why not use this gh_pages as what "in_progress" would have been? This gh_pages could serve as the transit for for reviewers to do their work, before pushing (or pulling it) from puppylinux-woof-CE.github.io for publishing. Just a thought. I'm not sure how complex / tedious the actual process would become.

**Comment by 01micko** [comment]
> I was thinking along the same way. I initially thought having "news" integrated into puppylinux.com, but if puppylinux.org/news is alive then it seems quite a bit of waste to have duplicate effort writing the same stuff (and eventually, one of them will end up neglected - not good!). A blog would be good since it has a bigger scope than just "news" (it can contain trifles, op-ed, etc too).

> I could implement this "blog" thing in puppylinux.com and pull contents from ether here, or puppylinux-woof-CE.github.io, or both - as long as the structure to pull from is clear. I tend to agree that gh-pages in this repo should become a specific site for woof-ce related new/site/blog/whatever. But I'll let our master steward make the call :smiling_imp: :innocent:

Well 'master steward' sits better than BD. ([see bottom of post](http://www.murga-linux.com/puppy/viewtopic.php?p=884188#884188)).

Consider it "called".

**Comment by mavrothal** [comment]
>  This gh_pages could serve as the transit for for reviewers to do their work

OK. If no objections (in your sleep ;) I'll copy the content of puppylinux-woof-CE.github.io/master into woof-CE/gh-pages and try to set it as an upstream for puppylinux-woof-CE.github.io. Then `git pull upstream` `git merge upstream` should do it. Let's hope that is doable

**Comment by mavrothal** [comment]
Well, I did it but I'm not at all sure about it... 
Because of the github naming scheme the gh-page is shown in http://pupylinux.com/woof-CE !
So pupylinux.com/ and pupylinux.com/woof-CE is the same!!!.
We should probably redirect this to an xyz domain name but then if we pull into master the redirection will be pulled too. I created a `.gitattributes` file in master, with this line: `CNAME merge=ours` to block this but I'm not sure if it will work in github. 
Mick what was the domain to redirect to?

If this does not work we could leave it as such and just make sure that  we never generate a woof-CE folder. Though I think that sooner or latter will generate confusion just the same.

Plan C is just to delete gh-pages altogether (because even with the old content it does appear under puppylinux.com/woof-CE/).
Thoughts?

PS: Till we set that do not commit anything to puppylinux-woof-CE.github.io/master

**Comment by mavrothal** [comment]
Here is what I did and works.
In my local clone of the puppylinux-woof-CE.github.io I added in .git/config
```
[remote "upstream"]
	url = https://github.com/puppylinux-woof-CE/woof-CE.git
	fetch = +refs/heads/gh-pages:refs/remotes/upstream/gh-pages
```
Then just 
```
git fetch upstream
git merge upstream/gh-pages
```
did the job.

So we  *could* redirect gh-pages to some zyx domain for viewing of the changes and when happy the  'master steward' will merge them to the puppylinux-woof-CE.github.io so they'll appear in puppylinux.com
In this scheme the woof-CE repo will handle everything pull-wise.

What do you think?

**Comment by 01micko** [comment]
puppylinux.eezy.xyz is now live.

It is a simple redirection - no need for the CNAME file.

**Comment by mavrothal** [comment]
Without the CNAME file, it still redirects to http://puppylinux.com/woof-CE/ . The idea is to try to avoid this. I would add the CNAME. Should not overwrite the original in the merges

**Comment by 01micko** [comment]
Just trying to figure out.. 

Anyway CNAME needs `puppylinux.eezy.xyz`. You want to commit while I figure out the A record? Won't go live until DNS propagates (up to 24 hrs, but usually only a few).

**Comment by mavrothal** [comment]
Done in 90f70fa

**Comment by 01micko** [comment]
Ok, done at my end too.

**Comment by 01micko** [comment]
I suppose I need to rewrite my [post](http://www.murga-linux.com/puppy/viewtopic.php?p=884188#884188) but I'll let the dust settle and get comfortable with the workflow.

So... I need to add 

> ```
 [remote "upstream"]
    url = https://github.com/puppylinux-woof-CE/woof-CE.git
    fetch = +refs/heads/gh-pages:refs/remotes/upstream/gh-pages
   ```

in my `puppylinux-woof-CE.github.io/.git/config` I gather.

I suppose this really does make `in_progress` branch redundant and probably more confusing having it than not ... then again it could serve as a backup; about its only useful purpose. Perhaps in that case should be renamed to `backup`?

**Comment by 01micko** [comment]
Hmm .. bugger

```
# git fetch upstream
warning: no common commits
remote: Counting objects: 243, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 243 (delta 0), reused 0 (delta 0), pack-reused 239
Receiving objects: 100% (243/243), 1.00 MiB | 246.00 KiB/s, done.
Resolving deltas: 100% (106/106), done.
From https://github.com/puppylinux-woof-CE/woof-CE
 * [new branch]      gh-pages   -> upstream/gh-pages
# git merge upstream/gh-pages
Auto-merging history.html
CONFLICT (add/add): Merge conflict in history.html
Auto-merging CNAME
CONFLICT (add/add): Merge conflict in CNAME
Automatic merge failed; fix conflicts and then commit the result.
```

No big deal but the CNAME one is a worry. I don't know why the history one would conflict :confused:

**Comment by mavrothal** [comment]
> Ok, done at my end too.

OK. Now http://puppylinux.eezy.xyz works
However somehow  http://puppylinux.com/woof-CE/ also works :angry: :confused: 
Have to find out what we are missing

>  I don't know why the history one would conflict
Reset master to its last clean state and repeat as such
```
git reset --hard <last good hash>
git fetch upstream 
Try git merge --no-ff --no-commit upstream/gh-pages
git diff
```
and see what may be the conflict and solve it changing the *gh-pages* repo sowithh merge cleanly the first time. If necessary remove CNAME at first. After that should be OK. (I hope)

**Comment by 01micko** [comment]
Too late I already fixed manually.

**Comment by 01micko** [comment]
I think this setup is way too messy! The more complex the larger the scope for error. I don't think it is worth the effort.

**Comment by mavrothal** [comment]
I'm afraid I would agree
Also may  not be easy to "silence"  http://puppylinux.com/woof-CE/  
According to github redirect [page](https://help.github.com/articles/custom-domain-redirects-for-github-pages-sites/) orgname.github.io/projectname automatically redirects to org.example.com/projectname

**Comment by 01micko** [comment]
Ok, so we delete `gh-pages`? Then there is cause to keep `in_progress`, however, we use that as a playground 9for the blog and other ideas) and committers can go straight to `master`. I can test via a host if necessary; easy enough to clone the pull requesters repo directly on my slackware box.

**Comment by mavrothal** [comment]
Yes. 
I think is already too much effort for very little gain.
Besides worse case scenario the page goes down few minutes.

But should we ask for pull requests in master or in in_progress?
I think in-progress though it will always take an extra step to publish

**Comment by 01micko** [comment]
I think master.

I meant before that we use in_progress for ideas, like the blog and other tests.

**Comment by 01micko** [comment]
Ok, I've deleted puppylinux.eezy.xyz

**Comment by 01micko** [comment]
`gh-pages` is now deleted.

**Comment by mavrothal** [comment]
Idea!
We delete gh-pages.
We remove CNAME from puppylinux-woof-CE.github.io
You fork puppylinux-woof-CE.github.io in YOUR account and set it as upstream normally
You publish to puppylinux.com from your repo.

So puppylinux-woof-CE.github.io should show under github.io domain for testing etc and you just merge upstream when comfortable with the changes.
Besides is your domain

**Comment by mavrothal** [comment]
Ah, we also delete the in_progress.

**Comment by mavrothal** [comment]
Hm... May want to make sure that will be published from https://github.com/01micko/puppylinux-woof-CE.github.io or should be https://github.com/01micko/01micko.github.io or it needs a gh-pages.

**Comment by 01micko** [comment]
Will that work though? 

I am not the organisation! 

[github.com/01micko/puppylinux-woof-CE.github.io](https://github.com/01micko/puppylinux-woof-CE.github.io)

No, this will be another mess. Deleting fork.

**Comment by mavrothal** [comment]
what a mess!
Maybe you make a puppylinux-websites organisation?...

**Comment by 01micko** [comment]
No its ok. The website is live. We have the code. It's working. I don't mind the simple approach - I have better things to do!

I can accept pulls to master. Anything over my head I'll just test. I'll likely not accept any js  until james gives it the thumbs up .. but I can't see a queue of devs lining up to commit code! :smile_cat:
