### ISSUE TITLE
new first boot mutiple sound card wizard behaviour

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#770]
the new mscw popup that occurs on first run isn't working properly.
on my desktop sound is usually picked up straight away with no need to run mscw.
with the new popup i'm forced to repick an already working soundcard and when i do sound no longer works!
i then have to run mscw again manually and pick it a second time to get sound.

also the delayed popup, even if it was working is a bit odd. would probably be better as an option on the welcome1stboot graphic... or even just a quick gxmessage making users aware of mscw in the menu.

**Comment by wdlkmpx** [comment]
The new mscw does not show a first boot dlg. If it does it's because
this file does not exist: /var/lib/mscw/ce

But it does some stuff as delayedrun executes it. Another thing to
take into account is the new entries in alsa-base.conf.

It would be nice to see the logs of the 1st boot, 2nd boot, 3rd boot.

	Multiple-Sound-Card-Wizard report

I remember I posted a pet pkg in the forum a few days ago while trying
to resolve BuddhaDog's sound problem.

**Comment by mrfricks** [comment]
i'll check for that file in the next build. i guess this is occuring as i'm using on old mscw tahr.pet so i'll remove that and see
cheers wdlkmpx

**Comment by wdlkmpx** [comment]
Well, the tahrpup you built for me a while ago did not come with the
new mscw, I guess this is because it's properly added in
Z-3builddistro.....  just make a pet of the current mscw dir and
upload it to the repo, that way there's no mistaking

Or upload this pet, although it contains new stuff that needs to be
tested properly
http://murga-linux.com/puppy/viewtopic.php?mode=attach&id=97110
