### ISSUE TITLE
Reorganize PPM .package directory structure

### ISSUE THREAD

**Issue by rizalmartin** [puppylinux-woof-CE/woof-CE#827]
I made a overhaul in PPM which implement organized  .package directory structure, improved automatic download  andf  easier management of repos.

http://www.murga-linux.com/puppy/viewtopic.php?p=914058#

**Comment by mavrothal** [comment]
No ti me to check, but
In puppy many scripts (outside PPM) have hard-coded paths, including the the path for the position of package info files. Quicksetup is just an example. These will break. 
PPM scripts are also used for woof building. Change of paths should consider their use there.
If you want to go through the exercise of reorganising an invisible folder (...) you may want move things where most distros have them nice and visble, in /var

**Comment by wdlkmpx** [comment]
They say the most important part of a distro is ... the package manager. 

One script that is copied from woof to the new iso is 0setup. That script has been revised recently and now the changes are visible in the testing branch.

A perfect example of a simple, powerful and versatile package manager is pacman from Arch Linux, using it i got some ideas of what the ppm can be. I already forgot most of them since i'm using puppy exclusively. I'll take a look at your code and i'll attach a tarball with the current /usr/share/petget dir so you can adapt your code to that base.. i might add some suggestions, but that is not guaranteed..
