### ISSUE TITLE
The use of git makes puppy development more difficult!

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#878]
Sounds strange doesn't it?
But if you see what is happening, people just remove comments from scripts, remove the history from the top of the scripts and replace all these with a git log that reads "update", "change", "edit" " "tweak" or other useless log entries. To make things worse, commits mix 2, 3, 4... unrelated changes together or few lines of a functional changes and dozens of "beautifying" changes, making harder to see what is going on and figure why.
The result for a new comer (and the seasoned one after few months) is that the only way to be able to understand and contribute is to figure out from the code itself what is going on and why, further increasing the contribution barrier. Thus the title.
Is you intend to keep it that way you may want to reintroduce the log at the header of the scripts/files and mark the lines with the relevant functional changes with that log entry.

**Comment by wdlkmpx** [comment]
the walls of text some scripts used to have really are of no use, unless you have a fork of woofce with relevant changes.

by reading the scripts i realized the log at the beginning has many things that are (long) gone, what i did is delete/relocate comments and keep only the in place comments. i think it's better to read something and discover the details the comments.

of course it is good to add comments of what a new change is about, a general description at the beginning of how the script works. several scripts have this. although i admit i haven't added detailed  descriptions lately, it's just that sometimes my brain is not able to properly articulate descriptions, most of the time actually.

some scripts i edited and removed some comments have been reduced by 200-500 lines, delayedrun is about 80 lines, rc.update has 290 lines with relocated code into functions to make it easier to understand, they should be easier to read.

i used to add long comments to my commits, but i grew tired of it, but i'll try to improve things adding more detailed descriptions at the beginning.

people should read the scripts, the log at the beginning is misleading

**Comment by mavrothal** [comment]
>i used to add long comments to my commits, but i grew tired of it, but i'll try to improve things adding more detailed descriptions at the beginning.

I think that would be good (for all of us to do). 
There are ~800 commit messages that read "Update \<this\>". Not why, what is the problem fixed, the feature added, anything. 
Next person will go through the same trouble as you now (and the rest of us before). Read the code and try to figure out what the heck is going on. Instead (if commit messages where [kosher](http://chris.beams.io/posts/git-commit/)) could type "blame" and see how, when and why every line of code is [the way it is](https://github.com/sugarlabs/sugar/blame/master/src/jarabe/main.py). Could see for example that this line is from puppy 6, that line only for tahr the next one a work around for a bug in a specific version of grep etc, instead of rediscovering America.

**Comment by wdlkmpx** [comment]
i admit that i'm applying the ideas that were for my w repo. it was part of my unholy agenda since the beginning. it's also true that i'm beginning to commit critical changes along with miscellaneous edits, that is because i'm basically exhausted and being a tester of changes (70% of time testing, 30% coding), at least the changes are tested up to some extent...

the idea i had was to restart puppy where the current code is considered the beginning.. in fact i have scripts that can replace some puppy scripts, but they use yad, others are not finished like my version of new2dir, but almost all of them are finished at least for me.

the latest changes in rc.sysinit are cosmetic as well as functional specially for a full install:  no /tmp/bootsysinit.log... relocate code; critical error - readonly filesystem... relocate code 

so the time next i read a script i'll make sure to write my thoughts..

for example, how rc.sysinit is triggered

/sbin/init executes busybox init or minit
busybox init is controlled by /etc/inittab and rc.sysinit is specified as ::sysinit:, also read /etc/inittab.README...

**Comment by wdlkmpx** [comment]
i still try to understand how a huge, convoluted, and misleading log can lead to a better understanding, i certainly find it to be one of the most annoying things about puppy most of the same comments were at the beginning and in the target code, duplicated.

instead of dividing the script into sections and comments explaining each section, the is a log that only serves to confuse me about what stuff is there or not.

ever since i used precise as my derivative, i needed to compile and update some essential apps, instead of downgrading woof. basically that's the main source of problems in the puppy world, and that's why i have a hard time reading nonsense on the forums.

**Comment by wdlkmpx** [comment]
the problems that may arise by changing/redefining code are directly fixed in woof, and pet pkgs affected are  put into the rootfs-packages dir,  mscw and sfs_load were moved to rootfs-skeleton because they are an integral part of the system, having mscw been rewritten completely and sfs_load adapted for the new init, extrasfs code removed from bootmanager, etc.

keeping the project as it is leaves no room for true development that goes beyong simple changes.

that's why important woofce forks should be merged into the project itself, applying rules. there should be no fear about delays and broken code, it will all be fixed eventually. current devs can help, although i'm not sure how. but maybe getting the same hardware can be of help.

**Comment by wdlkmpx** [comment]
there is also the branches, i think there are too many.

master, testing and legacy should be enough, and another temporary branch where some stuff happens, but everyone should try to push there to make it relevant and important and force fixes before it fades into obscurity... like all the other branches basically. and when a branch has failed, but there is hope, it should be merged into testing (with alternative filenames) for future updates and a possible permanent deletion.

i get the update commit titles are not that informative, although some commits have proper descriptions. i can make my future commits include more info..

**Comment by mavrothal** [comment]
Please do not take personally any of the comments. All of us have done some (or a lot) of this. 
I also by no means suggest that things should not be changed, little or a lot.
All I'm suggesting is that changes should be adequately documented/explained/justified, to facilitate understanding, collaboration and future development. (It is said that code documentation  also helps developers to think through usage and implementation, particularly when it comes to new things)
If these are through the git log fine. If not, should  at least be reported in the scripts comments or "usage". That's all I'm suggesting.
It is true that  the git-woof, 1-2 punch, presents a steep entry barrier for the new comer (as suggested in the forum repetitively) so I would think that the more helpful and appealing we make it the better it is for everyone.
Then again, if none of the above happens, heck, you can still commit as before 😉

**Comment by wdlkmpx** [comment]
You're totally right about documentation, i'll try to add as many explanatory comments as i can.

well regarding collaboration, maybe it will happen in the future when someone sees a better codebase, but from what i can tell, woof or woofce, as a universal base project does not exist anymore.

people have different views. I think i've been in the middle, keeping the basic and faulty puppy structure but adding as many changes as possible.

I think there should be the /doc dir where random stuff is written by someone inspired. There should be a somewhat generic changelog to inform about the major/visible changes. As someone who has been reading and editing thousands of code lines, i think i can add lines to that file, i'll create the file soon.

And maybe the git page should also show weekly or monthly test builds of the current code. That way everyone visiting the page can install something that is up to date and can  contribute fixes inmediately.

**Comment by mavrothal** [comment]
> And maybe the git page should also show weekly or monthly test builds of the current code. That way everyone visiting the page can install something that is up to date and can contribute fixes inmediately.

That would be ideal but as you know woof-based puppy building can not be done by a single command without further developer intervention and would be unreasonable to expect current developers to be able to devote this kind of time in such a consistent rate. 

Maybe we need to develop a "build script" and/or a config file that 0-,1-,2-,3- woof scripts can interrogate as needed and have truly unattended builds.
It would also be important for the various "z-hack" pets  to move into woof so the still needed "dev-magic" be taken into account.
Of course all these may really alienate puppy builders 👅  😺

**Comment by peabee** [comment]
+1 for unattended build script.....although does the gui version do this? and does that just need bringing into line with the current 0-1-2-3?

z-hacks are usually just a way of modifiying the distro packages to conform to puppy requirements or idiosyncracies. They probably should go into package-templates for just that distro, but these are somehow more difficult to understand than making a quick pet!!

**Comment by wdlkmpx** [comment]
We have to admit that git makes development really hard.. almost impossible for puppy users ... well at least for those who don't know how to use git and/or don't want to build isos.

I personally can't find a better way to contribute to a project... i comment on pull requests, issues, commits, i know what's going on all the time. I know how to work in a separate branch rebasing my work on top of upstream and finally open a pull request. The only possible issue with github is that activity may flood your email inbox in case you're watching a project with that option activated. I disable it and now i have to keep visiting github to know what's going on.

A dedicated venue to discuss even the most trivial and depressing of things (i.e. instructing peabee to upload stuff to a pet repo) might be needed, but without disturbances from unknown beings..

I said it many times, i can merge changes on request, people can provide a diff or a modified file, well as long as that file was not based on outdated code..

Contributors with commit access who don't know much about shell scripting should be accepted as long as they know how to git and provide a service by merging stuff from someone (or somewhere) who don't know how to/don't want to use git or github or contribute directly to the project.

Just a thought..
