### ISSUE TITLE
Modify xorgwizard automatic: Load fbdev driver by default in UEFI mode.

### ISSUE THREAD

**Issue by rizalmartin** [puppylinux-woof-CE/woof-CE#897]
If no appropriate video card or xorg drivers found when booting puppy in UEFI mode. Load fbdev driver instead.

**Comment by wdlkmpx** [comment]
Well, the old xorg wizards had 2700+ lines combined. One was the retro xorg wizard with support for the xvesa x server and older xorgs (xorgwizard). the other one was the precise xorg wizard (xorgwizard-cli), and the only one that was used by then the modern puppies. Both had code to 'detect' the xorg driver and give you options.

The new xorgwizard with 600 lines includes xorgwizard-cli and xorgwizard-automatic in the same file. 

Xorg wizard automatic never detected the video driver. It had hacks to ensure a working touchpad. I'm not sure if there was something else, it's been months since i last looked at the original version of the script.

Things have been changing here and everywhere else.

The point is, xorg decides by itself what video driver to use.. unless you explicitly specify one in xorg.conf.

I use the same hard drive (with a big puppy, pfix=nocopy) in several pcs, and it always boots to desktop, which is good as my old hardware fails randomly. but it won't die, i wonder why, why

**Comment by wdlkmpx** [comment]
These are xorgwizard-cli screenshots..

http://murga-linux.com/puppy/viewtopic.php?t=108017&start=314

To trigger it on first boot or when there is no xorg.conf, add see
DISTRO_XORG_AUTO='yes' in /etc/DISTRO_SPECS

I noticed the initrd.gz distro_specs is copied to /initrd instead, so
i have add this line to /usr/bin/xwin

[ -f /initrd/DISTRO_SPECS ] && . /initrd/DISTRO_SPECS

or add this file to a sfs file:
/var/local/xwin_no_xorg_auto_flag

--

http://www.murga-linux.com/puppy/viewtopic.php?t=108492&sid=7eb2c1c1b91aba8acb243b0cb5a71dd6

I read someone was walking about 'pfix=xorgwizard' boot param. Never
seen it on puppy. It's in fatdog. I guess that param must force
xorgwizard for the current session no matter what. Easy to implement
with or without initrd. The full install will also recognize a few
boot params that traditionally only worked in the initrd.

**Comment by wdlkmpx** [comment]
a part of the comment is hidden, i paste it here again

http://www.murga-linux.com/puppy/viewtopic.php?t=108492&sid=7eb2c1c1b91aba8acb243b0cb5a71dd6

 I read someone was walking about 'pfix=xorgwizard' boot param. Never seen it in puppy. It's in fatdog. I guess that param must force  xorgwizard for the current session no matter what. Easy to implement with or without initrd. The full install will also recognize a few boot params that traditionally only worked in the initrd.

**Comment by rizalmartin** [comment]
I tested this scenario in virtualbox UEFI mode using x-slacko slim. It fails to run VESA because of missing 10H interrupt luckily that puplet includes xorg template configuration for UEFI so I just load it and it works.

How about this. In case that VESA failed to run but running in UEFI automatically load xorg fbdev configuration and start X.

**Comment by wdlkmpx** [comment]
Well, I really don't know if you're testing slacko 700b2, it has all the new code, and there are many other changes for the next release. I explained how to trigger xorgwizard in my first comment.

i think everything has be tested in the official releases as the other releases are based on the stablished code, that currently is changing. and i understand many people don't want to use rox, myself included.

By the way, for your x-slacko you said you were using the xfce multimedia apps, these apps are quite inferior to the generic apps, such as mplayer, mpv, deadbeef. 

mpv and deadbeef are by far the best choices for video/audio.. see suckless.org

http://suckless.org/rocks

**Comment by wdlkmpx** [comment]
3 years later.. I think this issue was fixed in 2016.

By default xorg tests several drivers until it finds a working one ... otherwise it will not start, you can see what it's doing in the xorg log.
