### ISSUE TITLE
_00build.conf  EXTRA_COMMANDS  

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#920]
at the end of _00build.conf i'm trying to use the EXTRA_COMMANDS option to remove a file but can't get  it to work. 
```
EXTRA_COMMANDS="rm /usr/share/X11/xorg.conf.d/10-amdgpu.conf"
```
what am i doing wrong?

**Comment by wdlkmpx** [comment]
you have to use relative paths:

usr/share/etc
./usr/share/etc

by using /usr you're telling the script file in the running system

EXTRA_COMMANDS="rm usr/share/X11/xorg.conf.d/10-amdgpu.conf
ln -sv target.so.0 usr/lib/libzz.so.1
etc
etc
etc"

**Comment by wdlkmpx** [comment]
take a look at my config file:
https://github.com/puppylinux-woof-CE/woof-CE/blob/rationalise/woof-distro/x86/debian/stretch/_00build.conf

you can add your config file too for everyone to reproduce your build easily, at least all the basic stuff.

**Comment by mrfricks** [comment]
thanks wdlkmpx, working now.   _00build.conf is really convenient , speeds up the process no end!

a separate issue but i'll ask here whilst i've got your attention.. how do i get puppy to use the /etc/X11/xorg.conf.udev?

**Comment by wdlkmpx** [comment]
It's used automatically when a touchscreen is detected.

there is an issue with the 'up key' when the evdev driver is being used... . so that's when decided to activate the evdev (udev) stuff only when a touchscreen is detected..

to fix this, see commit: https://github.com/puppylinux-woof-CE/woof-CE/commit/59cb9f442f6a68359cbd84b83583466761b9bc6e

you might want to repackage or update jwmconfig3-151025.pet replacing those files and update Packages-puppy-noarch-official..

xenialpup and tahrpup must use the xorg_base_new template. i can do it for you, if you have any updates open a pull request or send me the files. i'll update all the debian based compat distros at once, and then i'll delete xorg_base

**Comment by peabee** [comment]
> and then i'll delete xorg_base

Errrr - I'm still using xorg_base.......

**Comment by wdlkmpx** [comment]
I edited the xenial pup build recipes to fix "important issues". Clone  or pull again to build a xenialpup.. test it and report any issues you find.. or even provide a download a link to add it to the README file.

Things you might want to know:
1) A new version of xorg might break stuff for some old hardware..
2) A new kernel version might break stuff for some old hardware...

You can control (2) but not (1), i can provide a pet pkg with a xorg 1.11.4 from ubuntu precise that will make the x86 xenialpup a semi retro version.. will show a cli menu on first boot.

For the old xorg to work, it is important the xorg evdev (udev) stuff is not enabled. Fortunately it only is enabled when a touchscreen is detected, which means it will work fine.

**Comment by wdlkmpx** [comment]
I mean, it's the "alternative" xorg pkg, it will reside in /opt/xorg_alt until you use xorgwizard-cli to make it replace the current xorg. it's not possible to compile drivers for the old xorg version (it already comes with most drivers.. literally), however if you add the correct development files, it might work.

**Comment by 01micko** [comment]
This issue is ancient and irrelevant in the context of 2020. Closing
