### ISSUE TITLE
Switchable Physical Address Extension in kernel

### ISSUE THREAD

**Issue by rizalmartin** [puppylinux-woof-CE/woof-CE#932]
I suggest that the kernel can switch PAE and NON-PAE by specifying boot parameters such as

`pae=off|on`

This will create a single puppy linux distro instead off two different distros, one with pae and other is non-pae

**Comment by wdlkmpx** [comment]
It looks like that's not possible. A kernel is pae or non-pae.

I read some old laptops CPU (Pentium M, Celeron M) support PAE but it's not enabled (pae flag in /proc/cpuinfo). Adding ```forcepae``` makes the kernel assume the CPU actually supports PAE and continue.. that's what I read.

**Comment by wdlkmpx** [comment]
What could be done is this... compile the kernel twice [a new config option such as i686_pae_and_nonpae=yes] and include both kernels in the "huge" kernel tarball... and create a special boot menu to be selected by 3builddistro when such a case is detected (both kernels go to ISO).

This is just one of the many ideas i had, such as options to include devx, kernel sources, adrv, ydrv, fdrv in the iso (only the properly named *drv sfs's are recognized by the init script), specially for virtual machines (VirtualBox) and that should be the way to go.. for you to have everything needed to continue on your own, instead of searching for stuff that may be not available. The iso will be much bigger (always enough to fin in a cd), and the amount of ram needed will not change, but there will be  people who have nothing else to do complaining about the ISO size, so this change is basically for me... i'll implement it when I have some time.
