### ISSUE TITLE
On-the-fly save session on first boot

### ISSUE THREAD

**Issue by rizalmartin** [puppylinux-woof-CE/woof-CE#951]
If the user wants to save session immediately on first boot just let the user create a savefile and save session immediately and update pupstate without rebooting

**Comment by gyrog** [comment]
It's not just an update of the pupstate, the aufs stack also needs to be rearranged.
I don't think rearranging the aufs from pupmode=5 to pupmode=12 (or 13) is possible in the running system.

**Comment by wdlkmpx** [comment]
There is an alternative: start with an empty pupsave. It triggers PUPMODE 5 code only in rc.update to fix issues.

Commit https://github.com/puppylinux-woof-CE/woof-CE/commit/9e5adb033774b3383fd377bec41ec006f575e80c allows this.

**Comment by gyrog** [comment]
I  just tested booting directly into pupmode=12 using a savefolder, (very easy to create).
Simply, when init finds no savefile or savefolder and it's not pfix=ram, and it's on a Linux partition, it creates a savefolder and proceeds as pupmode=12.
It appeared to mess some rc.sysinit processing, but it booted fine to the desktop, with the first boot screen.
On shutdown, there was no bootconfig, just a normal pupmode=12 shutdown.
So it should be quite possible for savefolders.
The question with savefiles would be how big to create it, and which filesystem to create.

For interest, here is my patch aginst init in testing:`--- /mnt/sdb2/work/git/woof-CE/initrd-progs/0initrd/init	2017-01-30 01:52:35.226028564 +1000
+++ init_no5	2017-01-30 02:55:06.290984348 +1000
@@ -1231,6 +1231,12 @@
    PUPMODE=12
    ONE_PART="$(echo -n "$PUPSAVE" | cut -f 1 -d ',')"
    [ "$ONE_PART" != "$SAVEPART" ] && { SAVEPART="$ONE_PART"; ensure_save_mounted; }
+  elif [ "$ONE_FS_IS_LINUX" = "yes" -a "$SAVEPART" ]; then
+   mkdir "${SAVE_MP}${PSUBDIR}/${DISTRO_FILE_PREFIX}save"
+   if [ $? -eq 0 ];then
+    PUPMODE=12
+    PUPSAVE="$SAVEPART,$SAVE_FS,${PSUBDIR}/${DISTRO_FILE_PREFIX}save"
+   fi
   fi
  fi
 fi
`

**Comment by gyrog** [comment]
@wdlkmpx,
I ran the test again with pfix=rdsh, and I confirm that the /tmp/rc_update_force_pm5 file was created.
I don't know if the rc.update code was triggered.

**Comment by wdlkmpx** [comment]
Well commit edits the initrd init and the rootfs-skeleton rc.update... rc_update_force_pm5 is for after switch. If you boot to desktop you'll see a message /tmp/bootsysinit.log 

after 'switch_root /pup_new /sbin/init' the control is handed over /sbin/init, which in turn executes busybox init or minit (never tested the latter). The busybox init reads /etc/inittab, then executes /etc/rc.d/rc.sysinit which in turn executes rc.update.

To make init handle the whole situation... this can be the solution:

	[ "$EMPTY_PUPSAVE" ] && chroot /pup_new /etc/rc.d/rc.update 5
	  #- fix for empty pupsaves (missing /initrd/DISTRO_SPECS)
	  if [ ! -f "$SAVE_LAYER/initrd/DISTRO_SPECS" ] ; then
		EMPTY_PUPSAVE=yes
		PCLEAN=""
	  fi

then at the end before switching root:

	[ "$EMPTY_PUPSAVE" ] && chroot /pup_new /etc/rc.d/rc.update 5

haven't tested this, but that's what comes to mind..

**Comment by wdlkmpx** [comment]
I think this is ok for savefolders (with a pfix, I suggest pfix=autosave ). To make it work with savefiles we have to add the real mke2fs to the initrd, as the busybox version can only create ext2 fs

**Comment by wdlkmpx** [comment]
Or maybe something like this: autosave=folder autosave=file:ext4:2048

**Comment by gyrog** [comment]
I ran my test again and lo there is an "rc.update: Empty pupsave? Simulating PUPMODE=5 ..." line in /tmp/bootsysinit.log. So that whole mechanism works.
I no problem with the updating stuff being left to rc.update.
Hmmm...it would be nice if all save layer processing could be moved to rc.sysinit.

For me, the attraction of doing something like this is so that complete noobs are not faced with shutdownconfig. After many years, I can still remember my adverse reaction to it, on my very first puppy shutdown. So I'm not enthused about implementing something that has to be enabled by a boot parameter.

**Comment by gyrog** [comment]
Of course it's probably easier to implement automatic save layer creation at first shutdown.

**Comment by wdlkmpx** [comment]
Well, it's possible to create a pupsave automatically (savefolder if pdrv has a linux fs), the problem is that people will complain.. unless they know the pfix=ram param or something. It's hard to tell how people will react but 

It's possible to simplify the first shutdown process by adding a new button, something like "Quick save", then the script could just show another dialog for savefiles (size), and everything else could be automatic..

**Comment by gyrog** [comment]
Some people who are used to puppy will complain, complete noobs won't thank anyone if they are like me on my first puppy shutdown, I was surprised and mystified by a Linux that produced shutdownconfig. I had never installed any OS that did such a thing.
And the question that threw me most was the size question. I had no appreciation of what I was being asked, why I was being asked, or what the significance of my decisions might be.
So I'm not a fan of a "Quick save" that asks me what size this unknown thing should be.
When we first started testing savefolder, my first hack of shutdownconfig was to silently create a savefolder in the same directory as the puppy...sfs. I liked that.

**Comment by wdlkmpx** [comment]
shutdownconfig is certainly awkward. People use it to boot from vfat, ntfs partitions (usb), in that case is handy. People who want encrypt the savefile also have to go through shutdownconfig. So running that script anytime before shutting down makes sense, it's probably a good idea to make it just another wizard, configurable anytime before shutting down (in that case then it will not show up when shutting down).

We have to consult probedisk --extended-usb to determine the PDEV1 boot media. If boot from cd: full shutdowconfig, boot from HD or USB with non linux fs 'quick save' (select savefile size) + wizard. Boot from HD or USB with linux fs quick save (only 1 click -> savefolder) + wizard.

When booting from flash media with pupsave, it might be a good idea to set PUPMODE 13 by default. . (probedisk $PDRV | grep usbflash && PUPMODE=13)

Puppy is highly atypical for someone coming from Windows, I don't remember how I learned about Puppy, but the first encounter with rox was a nightmare.	In fact if i want to sell old hardware with Puppy installed, it would be a failed business.

**Comment by wdlkmpx** [comment]
If people knew that by creating a simple directory with a specific name (see ${DISTRO_FILE_PREFIX} in distro_specs in a linux fs partition, their work will be saved from the first boot.

So I guess that covers the basic concern without the need to resort to boot parameters.  For the rest, booting from a non linux partition.. there are more steps to follow of course, that's the penalty.

So... do you agree...?

**Comment by wdlkmpx** [comment]
Another idea I have... if booting from linux partition on Hard Disk, automatically create savefolder, so starting in PUPMODE 12. But what if the user wants to create an encrypted file... then probably create it on-the-fly and copy the savefolder contents to there.  I'm full of doubts..

For me since the beginning puppy was a distro for power users, even though i still use puppy exclusively, the fact that I had to learn all of this in order to use Puppy probably means that everybody else has gone through it...

**Comment by wdlkmpx** [comment]
How about a special name for savefolders... hard-coded in init. Something like 'pupsave', if no pupsave is specified, then script looks for 'pupsave' and ${DISTRO_FILE_PREFIX}save*. That way is easy to document it and explain it to everyone... or maybe automatically create the savefolder after booting from a linux partition...

**Comment by gyrog** [comment]
To keep it simple,
1) There is a shutdownconfig like utility that can be run at any time to produce /tmp/shutdownconfig_results.
So those who know, can fiddle with their save layer configurtion to their hearts content.
This might be combined with savefile resizing utility.
2) In rc.shutdown, during first shutdown, in the absence of a /tmp/shutdownconfig_results file, create a default save layer and use that, without asking anything.
Based on PUPSFS, PSAVEMARK and PSAVEPART from PUPSTATE, establish the save partition.
If that is a linux partition, create a save folder.
If it is a writable non-linux partition, create a default savefile, eg 128MiB, ext3.
3) On subsequent shutdowns, if /tmp/shutdownconfig_results exists, create a new save layer according to this spec, and copy the current save layer to it.

**Comment by wdlkmpx** [comment]
That sounds reasonable. This should also cover prefix=ram: avoid loading/creating savefiles. Something like that.

I won't be that hard to implement it, but maybe we have to communicate this. a poll or something, as all the feedback i recieve is from people suggesting to keep puppy exactly as it was before..

**Comment by gyrog** [comment]
Sometimes I wonder why we bother to try to push the envelope!
Actually, I do know why I try to push the envelope, and it's all to do with finding out if the things I can imagine, are possible.

There's just one other thing regarding creating a new save layer on shutdown.
The simple way, the multiple save layers could be just left to be sorted out by the current multiple save layer code in init.
Or the more complicated way, the new save layer could have some tag in it's name so that init can recognise it and delete the old one and rename the new one.

**Comment by 01micko** [comment]
> Sometimes I wonder why we bother to try to push the envelope!
> Actually, I do know why I try to push the envelope, and it's all to do with finding out if the things I can imagine, are possible.

Keep going I say. :1st_place_medal:

**Comment by gyrog** [comment]
This issue is a bit old now, but one of my reasons for playing with a save layer based on an sfs file, is that it could be used as an automatic save mechanism on non linux partitions.
As with a savefolder, all we need to know is where to write it.
Again, it should be ok to have an automatic save mechanism as a starting point, and then provide a utility, for those who know, to modify the save mechanism to their hearts content.

**Comment by gyrog** [comment]
Strange..., just re-reading this issue,
My new 'init' used to do this automatically, and could easily do it again,
It does a tar of the pup_rw in ram during shutdown and restores it to ram again in 'init'.
Works on all file systems, provides persistence but Puppy still runs compeletely in ram.
Great for el-cheapo slow usb sticks.
