### ISSUE TITLE
Loading SFSs fro subfolders fails in PUPMODE=13

### ISSUE THREAD

**Issue by mavrothal** [puppylinux-woof-CE/woof-CE#967]
Reported by sinobar in http://www.murga-linux.com/puppy/viewtopic.php?p=944924#944924
Is because sfs_load is called in the rc.sysinit before the /mnt/home link is set.
Possible solution in http://www.murga-linux.com/puppy/viewtopic.php?p=944963#944963

**Comment by woodenshoe-wi** [comment]
I had the same problem in tahr64-6.0.6  
I had to load the devx every time I rebooted.

I run PUPMODE=13 frugal install into subfolder on USB stick.

I tried your patch and now the devx loads automatically. 👍 

Can't post on the form because I locked myself out two weeks ago trying to change my email address. ☹️

**Comment by gyrog** [comment]
From my perspective, this is a bug in rc.sysinit, for which mavrothal has provided a possible solution, which will hopefully be found to work, and be included in woof-ce.
It seems I was wrong in my assumption that because the rc-sysinit<->sfs_load tested fine in pupmode=12, it would be fine for pupmode=13.

The old way of having both "Boot Manager/init" and "sfs_load" handling extra-sfs's also had it's problems,  i.e. when the number of extra sfs's exceeded the limit in "init", things got a little messy.

Not having to integrate with the "Boot Manager/init" combination, should also give sfs_load the possability of even more flexability.

I certainly do not see bringing back support for extra-sfs's in "init" as a forward move.

**Comment by mavrothal** [comment]
Given that it took 7 months for the issue to be reported, I think better commit that wait for testing...
