### ISSUE TITLE
Optionally show bootsplash

### ISSUE THREAD

**Issue by rizalmartin** [puppylinux-woof-CE/woof-CE#981]
Optionally show bootsplash upon booting then goto commandline if there is an error on booting. The user can enable or disable bootsplash

**Comment by wdlkmpx** [comment]
The boot splash is usually out of the user control.. why? Because it's part of the bootloader menu, as far as I know puppy uses an old syslinux version to boot puppy and it's the appropriate one as newer versions don't show the boot splash. Nothing is lost by not showing the picture of a dog... tbh.

A few months I ago i added a grub4dos boot menu that shows a dark blue background, using an updated fork of grub4dos (2016). It works flawlessly even in p4 based (netburst) cpus/pcs... which means it's ok. I have some parts for even older hardware, but I need a mainboard and a power supply... which unless you're a collector of antiquities, it doesn't make sense to get.. unless found in a trash can...

**Comment by wdlkmpx** [comment]
This can happen if the splash image is actually controlled by the kernel.

Looking at the tinycore sources i found some patches for the kernel one of them is the boot logo

This is an interesting article:
http://www.articleworld.org/index.php/How_to_change_the_Linux_penguin_boot_logo
