### ISSUE TITLE
double shebang in xdg-open script

### ISSUE THREAD

**Issue by pemasu** [puppylinux-woof-CE/woof-CE#990]
/rootfs-skeleton/usr/local/bin/xdg-open has double shebang in the script.

A couple of suggestions for additions: 

http://murga-linux.com/puppy/viewtopic.php?p=949500#949500

http://www.murga-linux.com/puppy/viewtopic.php?p=874793#874793

**Comment by 01micko** [comment]
I like @jamesbond3142 idea for fixing the anchor bug in links.

I'm not sure about drunkjedi's 'transmission' addition because some people may prefer another torrent program and indeed there is certainly no guarantee that transmission will be there, especially since the gtk2 version stopped development some years ago and will surely suffer bitrot in some not too distant future.

With support of other file managers in woof perhaps xdg-open deserves a full rewrite.
