### ISSUE TITLE
boot command line arguments psubdir and/or psubok broken

### ISSUE THREAD

**Issue by erikpopp** [puppylinux-woof-CE/woof-CE#992]
I have a grub2 multiboot flash drive that - among other things - boots Puppy Linux (frugal install).
The directory structure is:
/boot
/boot/grub/...
/boot/puppy-linux/...
/boot/cd-images/...
I used the boot arguments "psubdir" and "subok" to tell Puppy where to find its files. I stored my save file in /boot/puppy-linux
It worked just fine in Puppy Tahr 6.0.2, and if I recall correctly, it worked fine for at least one version before that.
Recently, though, after accidentally wiping my flash drive, I decided to install Puppy Tahr 6.0.5 using the same setup. So I downloaded the ISO, extracted the relevant files, and tried booting. I could boot into Puppy, but when I tried to make a save file, the save file maker didn't let me create one in /boot/puppy-linux. I eventually created a save file in the root of the flash drive, then moved it to /boot/puppy-linux Then, when I tried to use the new savefile, Puppy couldn't find it.
In case it helps, I used heavy encryption.
I tested two of my other grub2 configs (Super Grub2 Disk ISO and Kubuntu 16.04 ISO), and they worked.
My grub2 config for Puppy is:

[code]
uuid="UUID_OF_FLASH_DRIVE_PARTITION"
search --no-floppy --fs-uuid --set=root "$uuid"

menuentry 'Puppy Linux' {
  set os_dir="boot/puppy-linux"
  set os_name="Puppy Linux"

	echo "grub2: booting \"$os_name\""
  echo "grub2: loading linux kernel ($root)/$os_dir/vmlinuz"
  linux ("$root")/"$os_dir"/vmlinuz root=UUID="$uuid" acpi="force" psubok=TRUE psubdir="$os_dir"
  echo "grub2: loading initial RAM disk ($root)/$os_dir/initrd.gz"
  initrd ("$root")/"$os_dir"/initrd.gz
  echo "grub2: attempting to boot $os_name..."
}

---OTHER ENTRIES----
[/code]

Am I doing something wrong, or are psubdir and/or psubok now broken?

**Comment by wdlkmpx** [comment]
psubok is not boot param.

psubdir works fine, i always use it. you must be doing something wrong.

and unless you're using a full install, i suggest not to use 'root=UUID='... kernel param.

maybe the UUID is wrong... type blkid and write the correct UUID (not to be confused with PARTUUID)...

**Comment by wdlkmpx** [comment]
oh and by the way, as far as I know  the 'root=UUID=...' param actually requires the PARTUUID="" string (full blkid). 

so this is situation:
you're probably providing the wrong uuid to 'root=UUID=...', but the correct UUID for everything else..

**Comment by erikpopp** [comment]
Thanks for taking the time to help me out.

I tried booting Puppy in VirtualBox a few times - this time when I was much more awake - and I found the following:
- I'm quite sure that the UUID I passed to the Linux kernel is the same one I'm using in the rest of GRUB2's config. I specified it once at the top of grub.cfg in the variable $uuid, and then referenced that variable in each place that I needed it.
- removing psubok had no effect
  > I learned of that parameter from Puppy Boot Parameters (http://puppylinux.org/wikka/BootParametersPuppy)
- I could load the save file I had created before, but couldn't save changes to it
  > In fact, I couldn't write anything to the drive it was on
  > The drive that Puppy has access to in VirtualBox is a flash drive that VirtualBox presents as an attached hard drive
- I tried booting Puppy on bare metal, and found that my problem with saving went away. The only issue left was that when I installed LibreOffice, it saved it as a .sfs file to the flash drive's root instead of the folder specified in psubdir (/boot/puppy-linux).
  > I moved the LibreOffice .sfs to /boot/puppy-linux, and when I booted Puppy again, I could run LibreOffice without first loading the .sfs. The output of mount doesn't show anything with LibreOffice or ".sfs" in it, so I'm a bit confused as to whether I even need to keep that .sfs file around.
  > Do you know how to make VirtualBox play nice with Puppy?
- I'm not sure how to find my partition's PartUUID. The flash drive has an MBR partition table. Do MBR partitions even have PartUUIDs?
- Thus far, the kernel boot argument root=UUID=stuff seems to be working just fine. Is this a fragile enough setup that I still should change it?


Happily hacking,

wallaby

**Comment by wdlkmpx** [comment]
I booted puppy in Virtual Box (windows) a few times but using the ISO image, so I had no issues. i didn't do much with it.. nothing basically. I didn't save session.

Well puppy does not require root=UUID=stuff because the init script makes decisions and knows what to do.. however root=UUID=stuff is used in a full install as there's no initrd (or initramfs).

In puppyinstaller there's this:
root=PARTUUID=${DESTPART_PARTUUID}

the PARTUUID part was from one of the docs i read.. apparently it was a bit old, because it said the kernel only supported PARTUUID or something

However reading this:
https://wiki.archlinux.org/index.php/kernel_parameters

i see both are supported, random examples:
linux /boot/vmlinuz-linux root=UUID=978e3e81-8048-4ae1-8a06-aa727458e8ff quiet splash
"Boot using default options"   "root=PARTUUID=978e3e81-8048-4ae1-8a06-aa727458e8ff rw quiet splash"

To get the PARTUUID, type blkid device

blkid /dev/sda3 
/dev/sda3: UUID="aea7d6c7-e1d2-466f-beb4-6d0d6171eade" TYPE="ext4" PARTUUID="e1d6243f-03"

**Comment by erikpopp** [comment]
I tried using blkid from within Puppy, both on bare metal and in VirtualBox. Sure enough, it didn't show a partUUID for my flash drive's partitions. partUUID's must be a GPT thing. I tried booting Puppy in VirtualBox a couple more times, and I even recreated the .vmdk that tells VirtualBox to use the flash drive as a virtual hard drive. After a couple of boots, VirtualBox thought that the .vmdk file didn't exist. It now does the same for the original .vmdk file I created awhile ago. I think that this is a VirtualBox bug, not a Puppy bug.

Thanks again for your time.


Happily hacking,

wallaby

**Comment by wdlkmpx** [comment]
you're welcome. i myself will be testing puppy in virtualbox a bit more since that will the only way. but you're really using an old tahrpup, things have changed a bit since then. I think phil released newer tahrpup versions with all the changes that happened in woofce, but i see he hasn't posted updates to the tahrpup thread.. the whole puppy stuff has been sooo informal since the beginning... that i couldn't care less..

Looking in the ibiblio repos, i found the latest tahrpup and xenialpup versions:
http://distro.ibiblio.org/puppylinux/test/tahrpup/
http://distro.ibiblio.org/puppylinux/test/xenialpup/

When I have some time i'll be posting links to isos in the github wiki page, they will probably contain stuff i'm comfortable with and random bugs unless they're fixed directly in the git repo.. it's really easy to build puppy isos, what's hard is to make the configs work with the right stuff..
